"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import { logAudit } from "@/lib/audit";
import { validateGraph } from "@/lib/graph/invariants";
import type { CefrLevel, CompetencyEdge, CompetencyNode, EdgeType, Strand } from "@/lib/graph/types";
import { vocabularyDifficultyFromFrequency } from "@/lib/content/vocabulary-frequency";

const roles = ["platform_admin"] as const;
const uuid = z.string().uuid();
const skillSchema = z.object({ id: uuid.optional(), key: z.string().trim().regex(/^[a-z0-9_]+$/).max(100), labelFr: z.string().trim().min(2).max(200), category: z.string().trim().min(2).max(100), descriptionFr: z.string().trim().max(1000).optional() });
export async function saveSkill(input: unknown) { await requireRole([...roles]); const p=skillSchema.safeParse(input); if(!p.success) throw new Error("Compétence invalide."); const db=await createClient(); const row={key:p.data.key,label_fr:p.data.labelFr,category:p.data.category,description_fr:p.data.descriptionFr||null,active:true}; const result=p.data.id?await db.from("skills").update(row).eq("id",p.data.id):await db.from("skills").insert(row); if(result.error) throw new Error(result.error.message); await logAudit("catalog.skill_saved",{targetType:"skill",targetId:p.data.id,metadata:{key:p.data.key}}); revalidatePath("/admin/skills"); return {ok:true}; }
export async function deactivateSkill(input: unknown) { await requireRole([...roles]); const p=uuid.safeParse(input); if(!p.success) throw new Error("Identifiant invalide."); const db=await createClient(); const {error}=await db.from("skills").update({active:false}).eq("id",p.data); if(error) throw new Error(error.message); await logAudit("catalog.skill_deactivated",{targetType:"skill",targetId:p.data}); revalidatePath("/admin/skills"); return {ok:true}; }

const vocabSchema=z.object({id:uuid.optional(),lemma:z.string().trim().min(1).max(100),displayWord:z.string().trim().min(1).max(100),definitionFr:z.string().trim().max(1000).optional(),exampleFr:z.string().trim().max(1000).optional(),frequencyPerMillion:z.number().nonnegative().optional()});
export async function saveVocabulary(input:unknown){await requireRole([...roles]);const p=vocabSchema.safeParse(input);if(!p.success)throw new Error("Vocabulaire invalide.");const db=await createClient();const row={lemma:p.data.lemma.toLowerCase(),display_word:p.data.displayWord,definition_fr:p.data.definitionFr||null,example_fr:p.data.exampleFr||null,frequency_per_million:p.data.frequencyPerMillion??null,frequency_source:p.data.frequencyPerMillion==null?null:"manual",difficulty:p.data.frequencyPerMillion==null?null:vocabularyDifficultyFromFrequency(p.data.frequencyPerMillion),active:true};const result=p.data.id?await db.from("vocabulary_items").update(row).eq("id",p.data.id):await db.from("vocabulary_items").insert(row);if(result.error)throw new Error(result.error.message);await logAudit("catalog.vocabulary_saved",{targetType:"vocabulary_item",targetId:p.data.id,metadata:{lemma:row.lemma}});revalidatePath("/admin/vocabulary");return{ok:true};}

const nodeSchema=z.object({id:uuid,key:z.string(),labelFr:z.string().trim().min(2).max(200),descriptionFr:z.string().trim().max(2000).optional(),reviewStatus:z.enum(["draft","auto_approved","needs_human_review","human_approved","rejected","retired"])});
export async function saveCompetencyNode(input:unknown){await requireRole([...roles]);const p=nodeSchema.safeParse(input);if(!p.success)throw new Error("Nœud invalide.");const db=await createClient();const {error}=await db.from("competency_nodes").update({label_fr:p.data.labelFr,description_fr:p.data.descriptionFr||null,review_status:p.data.reviewStatus,updated_at:new Date().toISOString()}).eq("id",p.data.id);if(error)throw new Error(error.message);await logAudit("graph.node_saved",{targetType:"competency_node",targetId:p.data.id});revalidatePath("/admin/concepts");return{ok:true};}

async function graphRows(){const db=await createClient();const [{data:nodes,error:ne},{data:edges,error:ee}]=await Promise.all([db.from("competency_nodes").select("id,key,strand,label_fr,description_fr,atomicity_level,native_grade_min,native_grade_max,cefr_min,cefr_max"),db.from("competency_edges").select("source_node_id,target_node_id,edge_type,strength")]);if(ne||ee)throw new Error(ne?.message??ee?.message);return{db,nodes:(nodes??[]).map(n=>({id:n.id as string,key:n.key as string,strand:n.strand as Strand,labelFr:n.label_fr as string,descriptionFr:n.description_fr as string|undefined,atomicityLevel:n.atomicity_level as number,nativeGradeMin:n.native_grade_min as number|null,nativeGradeMax:n.native_grade_max as number|null,cefrMin:n.cefr_min as CefrLevel|null,cefrMax:n.cefr_max as CefrLevel|null})) satisfies CompetencyNode[],edges:(edges??[]).map(e=>({sourceNodeId:e.source_node_id as string,targetNodeId:e.target_node_id as string,edgeType:e.edge_type as EdgeType,strength:Number(e.strength)})) satisfies CompetencyEdge[]};}
const edgeSchema=z.object({sourceNodeId:uuid,targetNodeId:uuid,edgeType:z.enum(["prerequisite","encompasses","misconception_related","contrastive_transfer","same_family","remediates"]),strength:z.number().min(0).max(1).default(1)}).refine(v=>v.sourceNodeId!==v.targetNodeId,"Les nœuds doivent être différents");
export async function createCompetencyEdge(input:unknown){await requireRole([...roles]);const p=edgeSchema.safeParse(input);if(!p.success)throw new Error("Lien invalide.");const graph=await graphRows();const proposed={sourceNodeId:p.data.sourceNodeId,targetNodeId:p.data.targetNodeId,edgeType:p.data.edgeType,strength:p.data.strength};const validation=validateGraph(graph.nodes,[...graph.edges,proposed]);if(!validation.ok)throw new Error(validation.violations.filter(v=>v.severity==="error").map(v=>v.message).join(" · "));const {data,error}=await graph.db.from("competency_edges").insert({source_node_id:p.data.sourceNodeId,target_node_id:p.data.targetNodeId,edge_type:p.data.edgeType,strength:p.data.strength,generation_type:"human",review_status:"human_approved"}).select("id").single();if(error||!data)throw new Error(error?.message??"Lien non créé.");await logAudit("graph.edge_created",{targetType:"competency_edge",targetId:data.id as string,metadata:{warnings:validation.violations.filter(v=>v.severity==="warning")}});revalidatePath("/admin/concepts");return{ok:true,warnings:validation.violations.filter(v=>v.severity==="warning")};}

const misconceptionSchema=z.object({id:uuid,labelFr:z.string().trim().min(2).max(200),descriptionFr:z.string().trim().max(1000).optional(),nodeId:uuid.optional(),active:z.boolean()});
export async function saveMisconception(input:unknown){await requireRole([...roles]);const p=misconceptionSchema.safeParse(input);if(!p.success)throw new Error("Erreur-type invalide.");const db=await createClient();const {error}=await db.from("misconceptions").update({label_fr:p.data.labelFr,description_fr:p.data.descriptionFr||null,primary_node_id:p.data.nodeId||null,active:p.data.active}).eq("id",p.data.id);if(error)throw new Error(error.message);await logAudit("graph.misconception_saved",{targetType:"misconception",targetId:p.data.id});revalidatePath("/admin/concepts");return{ok:true};}
