import { notFound } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { PageHeader } from "@/components/page";
import { requireRole } from "@/lib/auth";
import { paragraphsFromText } from "@/lib/content/text-format";
import { getAdminReviewDetail } from "@/lib/db/reviews";
import { agreementLabel, questionOutcomeLabel, reviewDecisionLabel, reviewWorkflowLabel, statusLabel } from "@/lib/presentation/french-labels";
import { ISSUE_TAG_LABELS, REVIEW_CRITERIA } from "@/lib/review/types";
import { difficultyBandLabel } from "@/lib/scoring/band";
import { createClient } from "@/lib/supabase/server";
import { ReviewAdminNav } from "../review-nav";
import { EditorialActions } from "./editorial-actions";

type ReviewRow={id:string;naturalness_score:number|null;pedagogical_quality_score:number|null;engagement_score:number|null;difficulty_match_score:number|null;vocabulary_score:number|null;grammar_score:number|null;question_quality_score:number|null;cultural_age_score:number|null;overall_decision:string|null;general_comment:string|null;duration_seconds:number|null;passage_review_issue_tags:Array<{issue_tag:string}>;question_reviews:Array<{question_index:number;outcome:string;comment:string|null}>};
type AssignmentRow={id:string;status:string;reviewer_profile_id:string;submitted_at:string|null;profiles:{display_name:string|null}|null;passage_reviews:ReviewRow|null};
const scoreColumns={naturalness:"naturalness_score",pedagogical_quality:"pedagogical_quality_score",engagement:"engagement_score",difficulty_match:"difficulty_match_score",vocabulary:"vocabulary_score",grammar:"grammar_score",question_quality:"question_quality_score",cultural_age:"cultural_age_score"} as const;

export default async function AdminReviewDetailPage({params}:{params:Promise<{versionId:string}>}){
  await requireRole(["platform_admin"]);const {versionId}=await params;const db=await createClient();const [detail,{data:reviewerRows}]=await Promise.all([getAdminReviewDetail(versionId,db),db.from("content_reviewer_profiles").select("profile_id,profiles!content_reviewer_profiles_profile_id_fkey(display_name)").eq("active",true)]);if(!detail)notFound();
  const version=detail.version as unknown as {id:string;candidate_id:string;version_number:number;workflow_status:string;agreement_classification:string|null;average_score:number|string|null;rating_spread:number|null;payload:{generated:{title:string;body:string;questions:Array<{questionText:string;correctAnswer?:string;choices?:string[]}>};input:{topic:string;targetReadingBand:string;textType:string;targetSkills:string[]}}};
  const assignments=detail.assignments as unknown as AssignmentRow[];
  return <><PageHeader title={version.payload.generated.title} description={`${difficultyBandLabel(version.payload.input.targetReadingBand)} · ${version.payload.input.topic} · version de révision ${version.version_number}`}/><ReviewAdminNav/><section className="mb-8 flex flex-wrap gap-2"><Badge>{reviewWorkflowLabel(version.workflow_status)}</Badge>{version.agreement_classification&&<Badge variant={version.agreement_classification==="high_disagreement"?"default":"secondary"}>{agreementLabel(version.agreement_classification)}</Badge>}<Badge variant="outline">Score moyen {version.average_score==null?"—":Number(version.average_score).toFixed(2)}</Badge><Badge variant="outline">Écart {version.rating_spread??"—"}</Badge></section>
    <div className="grid gap-9 xl:grid-cols-[minmax(0,1fr)_360px]"><main><article className="border-y border-border py-6 text-sm leading-7">{paragraphsFromText(version.payload.generated.body).map((p,i)=><p className="mb-4" key={`${i}-${p.slice(0, 20)}`}>{p}</p>)}</article><h2 className="mt-9 text-lg font-semibold">Comparaison des évaluations</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr><th className="border-b border-border py-3 pr-4">Critère</th>{assignments.map(a=><th className="border-b border-border px-3 py-3" key={a.id}>{a.profiles?.display_name??"Évaluateur"}<span className="block text-xs font-normal text-muted-foreground">{statusLabel(a.status)}</span></th>)}</tr></thead><tbody>{REVIEW_CRITERIA.map(([key,label])=><tr key={key}><th className="border-b border-border py-3 pr-4 font-normal">{label}</th>{assignments.map(a=><td className="border-b border-border px-3 py-3 text-lg font-semibold" key={a.id}>{a.passage_reviews?.[scoreColumns[key]]??"—"}</td>)}</tr>)}<tr><th className="border-b border-border py-3 pr-4">Décision</th>{assignments.map(a=><td className="border-b border-border px-3 py-3" key={a.id}>{a.passage_reviews?.overall_decision?reviewDecisionLabel(a.passage_reviews.overall_decision):"—"}</td>)}</tr></tbody></table></div>
      <div className="mt-8 grid gap-5 lg:grid-cols-3">{assignments.map(a=>{const review=a.passage_reviews;return <section key={a.id} className="border-t-2 border-primary pt-4"><h3 className="font-medium">{a.profiles?.display_name??"Évaluateur"}</h3><p className="mt-2 text-sm text-muted-foreground">{review?.general_comment||"Aucun commentaire général."}</p>{review?.passage_review_issue_tags.length?<div className="mt-3 flex flex-wrap gap-1">{review.passage_review_issue_tags.map(tag=><Badge key={tag.issue_tag} variant="outline">{ISSUE_TAG_LABELS[tag.issue_tag as keyof typeof ISSUE_TAG_LABELS]??"Autre problème"}</Badge>)}</div>:null}<div className="mt-4 space-y-3">{review?.question_reviews.map(q=><div key={q.question_index} className="text-xs"><p className="font-medium">Question {q.question_index+1} · {questionOutcomeLabel(q.outcome)}</p>{q.comment&&<p className="mt-1 text-muted-foreground">{q.comment}</p>}</div>)}</div></section>})}</div></main><aside><EditorialActions versionId={version.id} candidateId={version.candidate_id} workflowStatus={version.workflow_status} payload={version.payload as unknown as Record<string,unknown>} reviewers={((reviewerRows??[]) as unknown as Array<{profile_id:string;profiles:{display_name:string|null}}>).map(row=>({id:row.profile_id,name:row.profiles.display_name??"Évaluateur"}))} assignments={assignments.map(row=>({id:row.id,status:row.status,reviewerId:row.reviewer_profile_id,name:row.profiles?.display_name??"Évaluateur"}))}/></aside></div>
  </>;
}
