import{createHash}from"node:crypto";
export type ServingState="eligible_provisional"|"empirically_validated"|"trusted_reusable"|"withdrawn"|"retired";
export type ServingPolicy={exposureCap:number;cohortPercent:number;minimumPromotionExposures:number;minimumCompletionRate:number;maximumIssueRate:number;killSwitch:boolean};
export type ServingRecord={contentVersionId:string;state:ServingState;exposureCount:number;policy:ServingPolicy;immutablePayloadChecksum:string};
const bucket=(studentId:string,contentVersionId:string)=>parseInt(createHash("sha256").update(`${studentId}:${contentVersionId}`).digest("hex").slice(0,8),16)%100;
export function canStartServingSession(record:ServingRecord,studentId:string){if(record.policy.killSwitch)return{allowed:false as const,reason:"kill_switch"};if(record.state==="withdrawn"||record.state==="retired")return{allowed:false as const,reason:"not_serving"};if(record.state==="eligible_provisional"){if(record.exposureCount>=record.policy.exposureCap)return{allowed:false as const,reason:"exposure_cap"};if(bucket(studentId,record.contentVersionId)>=record.policy.cohortPercent)return{allowed:false as const,reason:"outside_cohort"};}return{allowed:true as const,reason:"eligible",sessionBinding:{contentVersionId:record.contentVersionId,payloadChecksum:record.immutablePayloadChecksum,stateAtStart:record.state}};}
export function currentSessionContent(binding:{contentVersionId:string;payloadChecksum:string},record:ServingRecord){if(binding.contentVersionId!==record.contentVersionId||binding.payloadChecksum!==record.immutablePayloadChecksum)throw new Error("Serving version changed during session");return{continue:true,contentVersionId:binding.contentVersionId,payloadChecksum:binding.payloadChecksum};}
export function promotionDecision(input:{record:ServingRecord;completedExposures:number;completionRate:number;issueRate:number;explicitApproval?:{approvedBy:string;reason:string}}){if(input.record.state!=="eligible_provisional"&&input.record.state!=="empirically_validated")return{promote:false,reason:"invalid_state"};if(input.explicitApproval)return{promote:true,nextState:"trusted_reusable"as const,reason:"explicit_approval",approval:input.explicitApproval};const p=input.record.policy;if(input.completedExposures<p.minimumPromotionExposures)return{promote:false,reason:"insufficient_evidence"};if(input.completionRate<p.minimumCompletionRate)return{promote:false,reason:"completion_rate_below_policy"};if(input.issueRate>p.maximumIssueRate)return{promote:false,reason:"issue_rate_above_policy"};return{promote:true,nextState:"empirically_validated"as const,reason:"evidence_thresholds_met"};}
export function withdrawServing(record:ServingRecord,reason:string){if(!reason.trim())throw new Error("Withdrawal reason required");return{...record,state:"withdrawn"as const,withdrawal:{reason,preventsNewSessions:true,preservesExistingSessions:true,preservesEvidence:true}};}
