/** Fixed main diagnostic UI copy. Dynamic counters and child components have separate capture boundaries. */
export const DIAGNOSTIC_COPY = {
  "startTitle": "Ton point de départ",
  "loadingDescription": "Quelques questions pour découvrir ce que tu sais déjà et préparer la suite.",
  "loading": "Chargement de ton diagnostic…",
  "checkTitle": "Vérifions ce que tu sais",
  "resultsTitle": "Tes acquis et tes prochaines étapes",
  "teachingDescription": "Une explication, puis quelques essais pour apprendre à ton rythme.",
  "checkDescription": "Réponds sans aide. Cette nouvelle question permettra de préciser ton bilan.",
  "resultsDescription": "Tu peux commencer à apprendre. Nous vérifierons les points encore incertains au fil de tes activités.",
  "assessmentDescription": "Environ 35 minutes, avec des pauses quand tu veux. Les questions s’adaptent à tes réponses.",
  "reviewNotice": "Nous vérifions encore les questions et les activités de ce parcours. Tu peux apprendre dès maintenant ; ton bilan pourra être ajusté.",
  "skippedNotice": "Question passée. Ce point reste à vérifier.",
  "writingSavedNotice": "Ton texte est enregistré. Ce point reste à vérifier.",
  "answerSavedNotice": "Ta réponse est enregistrée et ton bilan a été mis à jour.",
  "practiceSavedNotice": "Ton entraînement est enregistré. Une nouvelle vérification permettra de voir ce que tu sais faire sans aide.",
  "connectionError": "La connexion a été interrompue. Ta réponse est conservée ; réessaie.",
  "loadingError": "Impossible de charger ton diagnostic. Recharge la page pour réessayer.",
  "pause": "Faire une pause",
  "progressSaved": "Ta progression est enregistrée",
  "ready": "Prêt à commencer ?",
  "pauseHelp": "Prends ton temps. Tu peux quitter cette page et revenir plus tard.",
  "resume": "Reprendre",
  "begin": "Commencer",
  "newCheck": "Une nouvelle vérification",
  "revisionHelp": "Ta première version est enregistrée. Relis ton texte et améliore ce qui te semble nécessaire. Tu peux aussi le garder tel quel.",
  "firstDraftHelp": "Écris d’abord ta première version. Tu pourras ensuite la relire et la modifier.",
  "chooseAnswer": "Choisis ta réponse",
  "yourAnswer": "Ta réponse",
  "supportQuestion": "Quel passage justifie ta réponse ?",
  "saving": "Enregistrement…",
  "saveFirstDraft": "Enregistrer ma première version",
  "sendRevision": "Envoyer ma version relue",
  "validate": "Valider",
  "skip": "Passer cette question",
  "dontKnow": "Je ne sais pas",
  "preparing": "Préparation de la prochaine question…",
  "provisionalHelp": "Ce premier bilan est provisoire. « Pas encore vérifié » ne veut pas dire que tu ne sais pas le faire.",
  "coverageHelp": "Les questions disponibles ne couvrent pas encore tous les points de ce bilan. Les points indiqués « Questions à venir » n’ont pas été évalués et ne sont pas considérés comme des difficultés.",
  "firstActivities": "Pour commencer",
  "verifyDescription": "Vérifier ce point avec une nouvelle question.",
  "learnDescription": "Découvrir l’explication, puis s’entraîner.",
  "consolidateDescription": "Consolider cet acquis.",
  "verifyPoint": "Vérifier ce point",
  "startActivity": "Commencer cette activité",
  "deferredHelp": "Tu as déjà donné assez de réponses aujourd’hui sur certains points. Nous les vérifierons un autre jour pour confirmer tes acquis.",
  "activitiesUnavailable": "Ton bilan est enregistré. Tes activités personnalisées ne sont pas encore disponibles.",
  "optionalTitle": "Tu peux aussi commencer une leçon",
  "optionalHelp": "Ces points restent à vérifier. Tu peux découvrir une explication et t’entraîner dès maintenant.",
  "openLesson": "Ouvrir cette leçon",
  "viewPathway": "Voir mon parcours",
  "reviewAnswers": "Revoir mes réponses au diagnostic",
  "detailsTitle": "Ton bilan détaillé",
  "unverifiedPoint": "Point à vérifier",
  "questionsComing": "Questions à venir",
  "status": {
    "mastered": "Bien acquis",
    "missing": "À travailler",
    "fragile": "À consolider",
    "uncertain": "À confirmer",
    "unknown": "Pas encore vérifié"
  },
  "mode": {
    "recognition": "Reconnaître",
    "production": "Écrire la réponse",
    "interpretation": "Comprendre",
    "independent_production": "Utiliser dans un texte personnel"
  }
} as const;
