import{describe,expect,it}from"vitest";import{PrereqGraph}from"@/lib/graph/traversal";import type{HistoricalEstimate}from"./lifecycle";import{buildJaggedProfile,determineAssessmentRequirement,diagnosticDimensionPatch,diagnosticSummaries,mergeDimensionEvidence,rankProbeCandidates,remediationRoots,shouldStopDiagnostic,staleEstimate}from"./lifecycle";
const estimates:HistoricalEstimate[]=[{nodeId:"spell",strand:"orthographe_lexicale",masteryProbability:.2,uncertainty:.3,evidenceCount:4,lastEvidenceAt:"2026-01-01",writtenScore:.2},{nodeId:"tense",strand:"conjugaison",masteryProbability:.92,uncertainty:.2,evidenceCount:8,lastEvidenceAt:"2026-01-01",receptiveScore:.95,productiveScore:.88}];
describe("diagnostic lifecycle",()=>{
it("requires initial assessment with no prior completion",()=>expect(determineAssessmentRequirement({now:"2026-07-11",estimates})).toMatchObject({required:true,kind:"initial",reason:"no_prior_assessment"}));
it("targets stale evidence on re-entry without resetting history",()=>{const r=determineAssessmentRequirement({now:"2026-07-11",lastCompletedAt:"2026-01-10",estimates,inactivityDays:60});expect(r).toMatchObject({required:true,kind:"reentry",reason:"inactivity"});expect(r.targetNodeIds).toEqual(["spell","tense"]);const stale=staleEstimate(estimates[1],"2026-07-11");expect(stale.masteryProbability).toBeLessThan(.92);expect(stale.evidenceCount).toBe(8);expect(estimates[1].masteryProbability).toBe(.92);});
it("preserves a jagged spelling/conjugation profile",()=>{const p=buildJaggedProfile(estimates);expect(p.strands.orthographe_lexicale.mastery).toBe(.2);expect(p.strands.conjugaison.mastery).toBe(.92);expect(p.dimensions.productive).toBe(.88);});
it("updates only evidence-compatible dimensions",()=>{expect(diagnosticDimensionPatch("reading",.8)).toEqual({receptiveScore:.8});expect(diagnosticDimensionPatch("writing",.4)).toEqual({productiveScore:.4,writtenScore:.4});expect(diagnosticDimensionPatch("grammar_analysis",.6)).toEqual({receptiveScore:.6,writtenScore:.6});});
it("uses the canonical evidence meaning for constructed reading responses",()=>{expect(diagnosticDimensionPatch("writing",.7,{sectionKey:"reading_comprehension",expectation:"controlled_production"})).toEqual({receptiveScore:.7,writtenScore:.7});expect(diagnosticDimensionPatch("writing",.7,{sectionKey:"spelling",expectation:"controlled_production"})).toEqual({productiveScore:.7,writtenScore:.7});});
it("accumulates dimension evidence instead of overwriting it with the latest answer",()=>{expect(mergeDimensionEvidence({receptiveScore:.8},{receptiveScore:0},3)).toEqual({receptiveScore:.6});});
it("ranks deterministically by information and coverage",()=>{const candidates=[{nodeId:"b",strand:"conjugaison" as const,modality:"reading" as const,uncertainty:.8,prerequisiteCount:3,targeted:true,asked:0},{nodeId:"a",strand:"orthographe_lexicale" as const,modality:"writing" as const,uncertainty:.8,prerequisiteCount:3,targeted:true,asked:0}];expect(rankProbeCandidates(candidates,{conjugaison:2})[0].nodeId).toBe("a");expect(rankProbeCandidates(candidates,{conjugaison:2})).toEqual(rankProbeCandidates(candidates,{conjugaison:2}));});
it("uses coverage-aware stopping rules",()=>{expect(shouldStopDiagnostic({probeCount:10,meanUncertainty:.3,coveredStrands:["conjugaison"],requiredStrands:["conjugaison"],nextInformationGain:.1})).toEqual({stop:true,reason:"resolved"});expect(shouldStopDiagnostic({probeCount:10,meanUncertainty:.3,coveredStrands:[],requiredStrands:["conjugaison"],nextInformationGain:.1}).stop).toBe(false);});
it("finds the smallest prerequisite repair roots and audience summaries",()=>{const graph=new PrereqGraph(["root","mid","target"],[{sourceNodeId:"root",targetNodeId:"mid",edgeType:"prerequisite"},{sourceNodeId:"mid",targetNodeId:"target",edgeType:"prerequisite"}]);expect(remediationRoots(graph,["root","mid","target"])).toEqual(["root"]);const summaries=diagnosticSummaries(buildJaggedProfile(estimates),["root"]);expect(summaries.studentFr).toContain("points forts");expect(summaries.system.remediationNodeIds).toEqual(["root"]);});
});
