import type{Modality,Strand}from"@/lib/graph/types";import type{PrereqGraph}from"@/lib/graph/traversal";import type{DiagnosticEvidenceExpectation}from"./item-bank";import type{DiagnosticSectionKey}from"./protocol";
export type AssessmentKind="initial"|"reentry"|"calibration";
export type HistoricalEstimate={nodeId:string;strand:Strand;masteryProbability:number;uncertainty:number;evidenceCount:number;lastEvidenceAt?:string;receptiveScore?:number|null;productiveScore?:number|null;writtenScore?:number|null;oralScore?:number|null;decayRate?:number};
export type AssessmentRequirement={required:boolean;kind:AssessmentKind;reason:"no_prior_assessment"|"inactivity"|"high_uncertainty"|"manual_calibration"|"current";targetNodeIds:string[]};
export function determineAssessmentRequirement(input:{now:string;lastCompletedAt?:string;estimates:HistoricalEstimate[];inactivityDays?:number;uncertaintyThreshold?:number}):AssessmentRequirement{const inactivityDays=input.inactivityDays??60,threshold=input.uncertaintyThreshold??.65;if(!input.lastCompletedAt)return{required:true,kind:"initial",reason:"no_prior_assessment",targetNodeIds:input.estimates.map(e=>e.nodeId).sort()};const staleBefore=Date.parse(input.now)-inactivityDays*86400000;const stale=input.estimates.filter(e=>!e.lastEvidenceAt||Date.parse(e.lastEvidenceAt)<staleBefore).map(e=>e.nodeId);if(Date.parse(input.lastCompletedAt)<staleBefore)return{required:true,kind:"reentry",reason:"inactivity",targetNodeIds:[...new Set(stale)].sort()};const uncertain=input.estimates.filter(e=>e.uncertainty>=threshold).map(e=>e.nodeId);if(uncertain.length)return{required:true,kind:"reentry",reason:"high_uncertainty",targetNodeIds:uncertain.sort()};return{required:false,kind:"calibration",reason:"current",targetNodeIds:[]};}
export function staleEstimate(estimate:HistoricalEstimate,now:string):HistoricalEstimate{if(!estimate.lastEvidenceAt)return{...estimate};const days=Math.max(0,(Date.parse(now)-Date.parse(estimate.lastEvidenceAt))/86400000),retention=Math.exp(-days*(estimate.decayRate??.05));return{...estimate,masteryProbability:Number((.1+(estimate.masteryProbability-.1)*retention).toFixed(4)),uncertainty:Number(Math.min(1,estimate.uncertainty+(1-retention)*.5).toFixed(4))};}
export type DimensionPatch={receptiveScore?:number;productiveScore?:number;writtenScore?:number;oralScore?:number};
export function diagnosticDimensionPatch(modality:Modality,score:number,evidence?:{sectionKey:DiagnosticSectionKey;expectation:DiagnosticEvidenceExpectation}):DimensionPatch{const bounded=Math.max(0,Math.min(1,score));if(evidence?.sectionKey==="reading_comprehension")return modality==="writing"?{receptiveScore:bounded,writtenScore:bounded}:{receptiveScore:bounded};if(evidence?.expectation==="receptive"){if(modality==="listening")return{receptiveScore:bounded,oralScore:bounded};return modality==="reading"?{receptiveScore:bounded}:{receptiveScore:bounded,writtenScore:bounded};}if(modality==="reading")return{receptiveScore:bounded};if(modality==="listening")return{receptiveScore:bounded,oralScore:bounded};if(modality==="writing"||modality==="dictee")return{productiveScore:bounded,writtenScore:bounded};if(modality==="grammar_analysis")return{receptiveScore:bounded,writtenScore:bounded};return{productiveScore:bounded,oralScore:bounded};}
export function mergeDimensionEvidence(previous:DimensionPatch,observation:DimensionPatch,previousEvidenceCount:number):DimensionPatch{const weight=Math.max(0,previousEvidenceCount);const out:DimensionPatch={...previous};for(const [key,value] of Object.entries(observation) as Array<[keyof DimensionPatch,number]>){const prior=previous[key];out[key]=typeof prior==="number"?Number(((prior*weight+value)/(weight+1)).toFixed(4)):value;}return out;}
export type ProbeCandidate={nodeId:string;strand:Strand;modality:Modality;uncertainty:number;prerequisiteCount:number;targeted:boolean;asked:number};
export function rankProbeCandidates(candidates:ProbeCandidate[],coverage:Partial<Record<Strand,number>>):ProbeCandidate[]{return[...candidates].sort((a,b)=>{const score=(x:ProbeCandidate)=>x.uncertainty*(1+Math.log1p(x.prerequisiteCount))*(x.targeted?1.5:1)*(1+1/(1+(coverage[x.strand]??0)))/(1+x.asked*.5);const d=score(b)-score(a);return d||a.nodeId.localeCompare(b.nodeId);});}
export function shouldStopDiagnostic(input:{probeCount:number;meanUncertainty:number;coveredStrands:Strand[];requiredStrands:Strand[];nextInformationGain:number;minProbes?:number;maxProbes?:number;uncertaintyTarget?:number;minimumInformationGain?:number}):{stop:boolean;reason:"max_probes"|"resolved"|"low_information_gain"|"continue"}{if(input.probeCount>=(input.maxProbes??30))return{stop:true,reason:"max_probes"};const covered=input.requiredStrands.every(s=>input.coveredStrands.includes(s));if(input.probeCount>=(input.minProbes??8)&&covered&&input.meanUncertainty<=(input.uncertaintyTarget??.4))return{stop:true,reason:"resolved"};if(input.probeCount>=(input.minProbes??8)&&covered&&input.nextInformationGain<(input.minimumInformationGain??.05))return{stop:true,reason:"low_information_gain"};return{stop:false,reason:"continue"};}
export function buildJaggedProfile(estimates:HistoricalEstimate[]){const strands={}as Record<string,{mastery:number;uncertainty:number;nodes:number}>;for(const e of estimates){const s=strands[e.strand]??{mastery:0,uncertainty:0,nodes:0};s.mastery+=e.masteryProbability;s.uncertainty+=e.uncertainty;s.nodes++;strands[e.strand]=s;}for(const s of Object.values(strands)){s.mastery=Number((s.mastery/s.nodes).toFixed(4));s.uncertainty=Number((s.uncertainty/s.nodes).toFixed(4));}return{strands,dimensions:{receptive:average(estimates.map(e=>e.receptiveScore)),productive:average(estimates.map(e=>e.productiveScore)),written:average(estimates.map(e=>e.writtenScore)),oral:average(estimates.map(e=>e.oralScore))}};}
const average=(values:Array<number|null|undefined>)=>{const known=values.filter((v):v is number=>typeof v==="number");return known.length?Number((known.reduce((a,b)=>a+b,0)/known.length).toFixed(4)):null;};
export function remediationRoots(graph:Pick<PrereqGraph,"directPrerequisites">,missingNodeIds:string[]):string[]{const missing=new Set(missingNodeIds);return missingNodeIds.filter(id=>graph.directPrerequisites(id).every(p=>!missing.has(p))).sort();}
export function diagnosticSummaries(profile:ReturnType<typeof buildJaggedProfile>,remediationNodeIds:string[]){const strongest=Object.entries(profile.strands).sort((a,b)=>b[1].mastery-a[1].mastery)[0]?.[0];const weakest=Object.entries(profile.strands).sort((a,b)=>a[1].mastery-b[1].mastery)[0]?.[0];return{studentFr:`Ton profil montre des points forts en ${strongest??"français"} et une prochaine étape en ${weakest??"fondations"}.`,parentFr:`Le profil conserve les écarts entre domaines; ${remediationNodeIds.length} fondation(s) prioritaire(s) sont proposées.`,teacherFr:`Profil multidimensionnel: force ${strongest??"non déterminée"}, besoin ${weakest??"non déterminé"}; remédiations ${remediationNodeIds.join(", ")||"aucune"}.`,system:{strongestStrand:strongest,weakestStrand:weakest,remediationNodeIds,profile}};}
