export const SAMPLE_THRESHOLDS={passage:30,question:50,diagnostic:50,quiz:50,distractor:100,edge:100,retrieval:50,retention:30}as const;export type MetricStatus="insufficient_evidence"|"active";
const mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;const status=(n:number,min:number):MetricStatus=>n>=min?"active":"insufficient_evidence";
export function successCalibration(rows:Array<{predicted:number;observed:number;learnerMode:string;contentType:string}>){const groups=new Map<string,typeof rows>();for(const r of rows){const k=`${r.learnerMode}:${r.contentType}`,g=groups.get(k)??[];g.push(r);groups.set(k,g);}return[...groups].map(([key,g])=>{const predicted=mean(g.map(r=>r.predicted)),observed=mean(g.map(r=>r.observed)),drift=observed-predicted,s=status(g.length,SAMPLE_THRESHOLDS.passage);return{key,n:g.length,status:s,predicted,observed,drift,flag:s==="active"&&(observed<.75||observed>.85||Math.abs(drift)>.08)?"success_zone_drift":null};});}
export function questionQuality(rows:Array<{correct:boolean;ability:number;selectedDistractor?:string}>){const s=status(rows.length,SAMPLE_THRESHOLDS.question),low=rows.filter(r=>r.ability<.5),high=rows.filter(r=>r.ability>=.5),p=mean(rows.map(r=>r.correct?1:0)),discrimination=mean(high.map(r=>r.correct?1:0))-mean(low.map(r=>r.correct?1:0));return{n:rows.length,status:s,pValue:p,discrimination,flag:s==="active"&&(p<.2||p>.95||discrimination<.1)?"bad_question":null,distractors:Object.fromEntries([...new Set(rows.flatMap(r=>r.selectedDistractor?[r.selectedDistractor]:[]))].map(id=>[id,{lowAbilityRate:low.filter(r=>r.selectedDistractor===id).length/Math.max(1,low.length),highAbilityRate:high.filter(r=>r.selectedDistractor===id).length/Math.max(1,high.length)}]))};}
export function edgePredictiveLift(rows:Array<{prerequisiteMastered:boolean;targetSuccess:boolean}>){const mastered=rows.filter(r=>r.prerequisiteMastered),missing=rows.filter(r=>!r.prerequisiteMastered),lift=mean(mastered.map(r=>r.targetSuccess?1:0))-mean(missing.map(r=>r.targetSuccess?1:0)),s=status(rows.length,SAMPLE_THRESHOLDS.edge);return{n:rows.length,status:s,lift,flag:s==="active"&&lift<.05?"no_predictive_lift":null};}
export function diagnosticCalibration(rows:Array<{estimate:number;laterUnaidedScore:number;runType:"initial"|"reentry";strand:string;learnerMode:string}>){const error=mean(rows.map(r=>Math.abs(r.estimate-r.laterUnaidedScore))),s=status(rows.length,SAMPLE_THRESHOLDS.diagnostic);return{n:rows.length,status:s,meanAbsoluteError:error,flag:s==="active"&&error>.15?"diagnostic_miscalibration":null,groups:[...new Set(rows.map(r=>`${r.runType}:${r.strand}:${r.learnerMode}`))]};}
export function quizCalibration(rows:Array<{before:number;after:number;laterUnaided:number;promptFamily:string}>){const s=status(rows.length,SAMPLE_THRESHOLDS.quiz),updateError=mean(rows.map(r=>Math.abs(r.after-r.laterUnaided))),families=new Set(rows.map(r=>r.promptFamily)).size;return{n:rows.length,status:s,updateError,promptFamilies:families,flag:s==="active"&&(updateError>.15||families<2)?"quiz_update_miscalibration":null};}
export function boundedDifficultyProposal(current:number,observedSuccess:number,target=.8){const raw=current+(observedSuccess-target)*.5,adjustment=Math.max(-.1,Math.min(.1,raw-current));return{current,proposed:Number((current+adjustment).toFixed(4)),adjustment:Number(adjustment.toFixed(4)),requiresReview:true,mutatesPublishedRecord:false};}
export function adaptiveProbeAudit(rows:Array<{informationGain:number;stopped:boolean;uncertaintyAtStop:number;stoppingReason:string}>){const s=status(rows.length,SAMPLE_THRESHOLDS.diagnostic),lowGainContinued=rows.filter(r=>r.informationGain<.05&&!r.stopped).length,prematureStops=rows.filter(r=>r.stopped&&r.uncertaintyAtStop>.65).length;return{n:rows.length,status:s,meanInformationGain:mean(rows.map(r=>r.informationGain)),lowGainContinued,prematureStops,flag:s==="active"&&(lowGainContinued/rows.length>.1||prematureStops/rows.length>.1)?"probe_stopping_anomaly":null,reasons:[...new Set(rows.map(r=>r.stoppingReason))]};}
export function forgettingRateProposal(currentDecay:number,rows:Array<{inactiveDays:number;retained:boolean}>){const long=rows.filter(r=>r.inactiveDays>=30),observedLoss=1-mean(long.map(r=>r.retained?1:0)),raw=currentDecay+(observedLoss-.3)*.05,adjustment=Math.max(-.01,Math.min(.01,raw-currentDecay));return{currentDecay,proposedDecay:Number(Math.max(0,Math.min(.2,currentDecay+adjustment)).toFixed(4)),sampleSize:rows.length,preservesHistoricalEvidence:true,requiresReview:true};}
export function operationalAnomalies(rows:Array<{abandoned:boolean;latencyMs:number}>){const s=status(rows.length,SAMPLE_THRESHOLDS.passage),abandonment=mean(rows.map(r=>r.abandoned?1:0)),latencies=rows.map(r=>r.latencyMs).sort((a,b)=>a-b),p95=latencies[Math.max(0,Math.ceil(latencies.length*.95)-1)]??0;return{status:s,abandonment,p95LatencyMs:p95,flags:s==="active"?[...(abandonment>.25?["abandonment_anomaly"]:[]),...(p95>120000?["latency_anomaly"]:[])]:[]};}
export function comparativeEffect(rows:Array<{channel:"direct"|"indirect";retained:boolean}>){const direct=rows.filter(r=>r.channel==="direct"),indirect=rows.filter(r=>r.channel==="indirect"),s=status(Math.min(direct.length,indirect.length),SAMPLE_THRESHOLDS.retrieval);return{status:s,directRetention:mean(direct.map(r=>r.retained?1:0)),indirectRetention:mean(indirect.map(r=>r.retained?1:0))};}
export function retentionReport(rows:Array<{courseCompleted:boolean;laterMastery:number;conjugationReceptive:number;conjugationProductive:number}>){const s=status(rows.length,SAMPLE_THRESHOLDS.retention);return{status:s,completionRate:mean(rows.map(r=>r.courseCompleted?1:0)),laterMastery:mean(rows.map(r=>r.laterMastery)),conjugationTransfer:mean(rows.map(r=>r.conjugationProductive-r.conjugationReceptive)),semantics:{completion:"durable_achievement",mastery:"later_retention_state"}};}
export function reviewEvents(metrics:Array<{metricKey:string;flag:string|null;status:MetricStatus;evidence:unknown}>){return metrics.filter(m=>m.status==="active"&&m.flag).map(m=>({eventType:"empirical_anomaly",reason:m.flag!,metricKey:m.metricKey,evidence:m.evidence,explainable:true}));}
