import AxeBuilder from"@axe-core/playwright";import{expect,test}from"@playwright/test";
const publicRoutes=["/","/about","/schools","/parents","/privacy","/terms","/login","/signup","/join","/reset-password"];
for(const route of publicRoutes)test(`public route ${route} renders`,async({page})=>{const response=await page.goto(route);expect(response?.status()).toBeLessThan(400);await expect(page.locator("body")).toBeVisible();});
test("password recovery is actionable",async({page})=>{await page.goto("/reset-password");await expect(page.getByRole("button",{name:"Envoyer le lien"})).toBeEnabled();});
test("login accepts a username and exposes an accessible password toggle",async({page})=>{await page.goto("/login");await expect(page.getByLabel("E-mail ou nom d’utilisateur")).toBeVisible();const password=page.getByLabel("Mot de passe",{exact:true});await expect(password).toHaveAttribute("type","password");await page.getByRole("button",{name:"Afficher le mot de passe"}).click();await expect(password).toHaveAttribute("type","text");await page.getByRole("button",{name:"Masquer le mot de passe"}).click();await expect(password).toHaveAttribute("type","password");});
test("new and confirmed passwords can be shown independently",async({page})=>{await page.goto("/set-password");const password=page.getByLabel("Nouveau mot de passe",{exact:true});const confirmation=page.getByLabel("Confirmer le mot de passe",{exact:true});await expect(password).toHaveAttribute("type","password");await expect(confirmation).toHaveAttribute("type","password");await page.getByRole("button",{name:"Afficher le mot de passe"}).first().click();await expect(password).toHaveAttribute("type","text");await expect(confirmation).toHaveAttribute("type","password");});
test("mobile public navigation remains available",async({page})=>{await page.setViewportSize({width:375,height:760});await page.goto("/");await page.getByText("Menu",{exact:true}).click();await expect(page.getByRole("navigation",{name:"Navigation mobile"}).getByRole("link",{name:"Confidentialité"})).toBeVisible();});
for(const route of ["/","/login","/reset-password"])test(`critical accessibility ${route}`,async({page})=>{await page.goto(route);const result=await new AxeBuilder({page}).withTags(["wcag2a","wcag2aa"]).analyze();expect(result.violations.filter(v=>["critical","serious"].includes(v.impact??""))).toEqual([]);});
test("service worker never caches authenticated navigations",async({page,context})=>{await page.goto("/");await page.evaluate(()=>navigator.serviceWorker?.ready);await page.goto("/login");const urls=await page.evaluate(async()=>{const result:string[]=[];for(const key of await caches.keys())for(const request of await (await caches.open(key)).keys())result.push(new URL(request.url).pathname);return result;});expect(urls).not.toContain("/login");expect(urls).not.toContain("/student");await context.clearCookies();});
