import{bktUpdateWeighted,masteryUncertainty}from"@/lib/scoring/bkt";import{diagnosticDimensionPatch}from"@/lib/diagnostic/lifecycle";import type{Modality}from"@/lib/graph/types";
export type QuizPurpose="retrieval"|"course_evidence"|"calibration";export type QuizPlacement="lesson_interval"|"module_boundary"|"ongoing"|"remediation_reassessment";
export type QuizCandidate={itemId:string;nodeId:string;promptFamily:string;modality:Modality;purposes:QuizPurpose[];misconceptionIds:string[];lastSeenAt?:string;attempts:number};
export type QuizPolicy={maximumItems:number;minimumMinutesBetween:number;maximumQuizzesPerDay:number;lessonIntervalSteps:number;minimumPromptFamiliesForMastery:number};export const DEFAULT_QUIZ_POLICY:QuizPolicy={maximumItems:5,minimumMinutesBetween:45,maximumQuizzesPerDay:3,lessonIntervalSteps:3,minimumPromptFamiliesForMastery:2};
export function quizIsDue(input:{placement:QuizPlacement;completedSteps:number;quizzesToday:number;lastQuizAt?:string;now:string},policy=DEFAULT_QUIZ_POLICY){if(input.quizzesToday>=policy.maximumQuizzesPerDay)return false;if(input.lastQuizAt&&Date.parse(input.now)-Date.parse(input.lastQuizAt)<policy.minimumMinutesBetween*60000)return false;return input.placement!=="lesson_interval"||input.completedSteps>0&&input.completedSteps%policy.lessonIntervalSteps===0;}
export function assembleQuiz(candidates:QuizCandidate[],requiredPurposes:QuizPurpose[],now:string,policy=DEFAULT_QUIZ_POLICY){const seenFamilies=new Set<string>();return[...candidates].filter(c=>requiredPurposes.some(p=>c.purposes.includes(p))).sort((a,b)=>{const age=(x:QuizCandidate)=>x.lastSeenAt?Date.parse(now)-Date.parse(x.lastSeenAt):Number.MAX_SAFE_INTEGER;return age(b)-age(a)||a.attempts-b.attempts||a.itemId.localeCompare(b.itemId);}).filter(c=>{if(seenFamilies.has(c.promptFamily))return false;seenFamilies.add(c.promptFamily);return true;}).slice(0,policy.maximumItems);}
export function recalibrateFromQuiz(input:{mastery:number;evidenceCount:number;modality:Modality;score:number;distinctPromptFamilies:number},policy=DEFAULT_QUIZ_POLICY){const weight=input.distinctPromptFamilies>=policy.minimumPromptFamiliesForMastery?1:.45,mastery=bktUpdateWeighted(input.mastery,input.score>=.75,weight),evidenceCount=input.evidenceCount+1;return{mastery,uncertainty:masteryUncertainty(mastery,evidenceCount),evidenceCount,dimensionPatch:diagnosticDimensionPatch(input.modality,input.score),transferDemonstrated:input.distinctPromptFamilies>=policy.minimumPromptFamiliesForMastery};}
export function persistentGap(input:{nodeId:string;recentScores:number[];minimumAttempts?:number;gapThreshold?:number}){const minimum=input.minimumAttempts??3;if(input.recentScores.length<minimum)return null;const recent=input.recentScores.slice(-minimum),average=recent.reduce((a,b)=>a+b,0)/recent.length;if(average>=(input.gapThreshold??.6))return null;return{nodeId:input.nodeId,average,action:"insert_smallest_remediation"as const,reassessAfterSuccessfulEvidence:2};}
export function selectSmallestRemediation(candidates:Array<{packageVersionId:string;repairsNodeIds:string[];requiredNodeCount:number}>,missingNodeIds:string[]){const missing=new Set(missingNodeIds);return[...candidates].filter(c=>c.repairsNodeIds.some(id=>missing.has(id))).sort((a,b)=>a.requiredNodeCount-b.requiredNodeCount||b.repairsNodeIds.filter(id=>missing.has(id)).length-a.repairsNodeIds.filter(id=>missing.has(id)).length||a.packageVersionId.localeCompare(b.packageVersionId))[0]??null;}
