"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { assignReviewVersions } from "@/lib/actions/reviews";
import { textTypeLabel } from "@/lib/presentation/french-labels";
import { difficultyBandLabel } from "@/lib/scoring/band";

type Version={id:string;title:string;topic:string;band:string;interest:string;textType:string;assigned:string[]};
type Reviewer={profile_id:string;active:boolean;profiles:{display_name:string|null}};
export function AssignmentManager({versions,reviewers,currentAdminId}:{versions:Version[];reviewers:Reviewer[];currentAdminId:string}){
  const orderedReviewers=useMemo(()=>[...reviewers].sort((a,b)=>a.profile_id===currentAdminId?-1:b.profile_id===currentAdminId?1:0),[reviewers,currentAdminId]);
  const router=useRouter();const pilotIds=useMemo(()=>versions.slice(0,60).map(v=>v.id),[versions]);const[selected,setSelected]=useState<string[]>(pilotIds);const[selectedReviewers,setSelectedReviewers]=useState<string[]>(orderedReviewers.slice(0,3).map(r=>r.profile_id));const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  const workloads=new Map(reviewers.map(reviewer=>[reviewer.profile_id,versions.filter(version=>version.assigned.includes(reviewer.profile_id)).length]));
  async function assign(){if(!window.confirm(`Attribuer ${selected.length} passage(s) aux ${selectedReviewers.length} évaluateurs sélectionnés ?`))return;setBusy(true);setMessage("");try{const result=await assignReviewVersions({versionIds:selected,reviewerIds:selectedReviewers});setMessage(`${result.created} attribution(s) créée(s).`);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Attribution impossible.");}finally{setBusy(false);}}
  return <div className="grid gap-9 lg:grid-cols-[300px_minmax(0,1fr)]"><aside><h2 className="text-lg font-semibold">Évaluateurs actifs</h2><p className="mt-1 text-sm text-muted-foreground">Votre compte est inclus par défaut avec deux autres évaluateurs.</p><div className="mt-4 space-y-2">{orderedReviewers.map(reviewer=><label key={reviewer.profile_id} className="flex items-center justify-between gap-3 rounded-md border border-border px-3 py-3"><span className="flex items-center gap-3"><input type="checkbox" className="size-4 accent-primary" checked={selectedReviewers.includes(reviewer.profile_id)} onChange={event=>setSelectedReviewers(value=>event.target.checked?[...value,reviewer.profile_id]:value.filter(id=>id!==reviewer.profile_id))}/><span className="text-sm">{reviewer.profiles.display_name??"Évaluateur"}</span>{reviewer.profile_id===currentAdminId&&<Badge variant="secondary">Vous</Badge>}</span><Badge variant="outline">{workloads.get(reviewer.profile_id)??0}</Badge></label>)}</div>{reviewers.length<3&&<p className="mt-4 border-l-2 border-primary pl-3 text-sm text-muted-foreground">Ajoutez encore {3-reviewers.length} évaluateur(s) dans l’écran Évaluateurs pour lancer le pilote à trois.</p>}<Button className="mt-5 w-full" disabled={busy||selected.length===0||selectedReviewers.length<2||selectedReviewers.length>3} onClick={()=>void assign()}>{busy?"Attribution…":"Auto-attribuer équitablement"}</Button>{message&&<p role="status" className="mt-3 text-sm text-muted-foreground">{message}</p>}</aside><section><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">Passages disponibles</h2><p className="mt-1 text-sm text-muted-foreground">{selected.length} sélectionné(s) sur {versions.length}. La sélection initiale prend les 60 passages les plus récents.</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setSelected(pilotIds)}>Sélectionner les 60</Button><Button size="sm" variant="ghost" onClick={()=>setSelected([])}>Effacer</Button></div></div><div className="mt-4 max-h-[68vh] divide-y divide-border overflow-y-auto border-y border-border">{versions.map(version=><label key={version.id} className="flex cursor-pointer items-start gap-3 py-4"><input type="checkbox" className="mt-1 size-4 shrink-0 accent-primary" checked={selected.includes(version.id)} onChange={event=>setSelected(value=>event.target.checked?[...value,version.id]:value.filter(id=>id!==version.id))}/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{version.title}</span><span className="mt-1 block text-xs text-muted-foreground">{difficultyBandLabel(version.band)} · {version.topic} · {textTypeLabel(version.textType)}</span></span><Badge variant={version.assigned.length?"secondary":"outline"}>{version.assigned.length} attrib.</Badge></label>)}</div></section></div>;
}
