export type AgreementCorrectionDraft={key:string;construction:"adjacent"|"separated"|"inverted"|"coordinated";template:string;correct:string;wrong:string};
/** Distinct sentence corrections, separate from recognition and completion banks. */
const groups:Record<AgreementCorrectionDraft["construction"],readonly [string,string,string][]>={
 adjacent:[
 ["Le plongeur ___ son masque.","vérifie","vérifient"],
 ["Les cyclistes ___ le village.","traversent","traverse"],
 ["La fleuriste ___ les bouquets.","prépare","préparent"],
 ["Les serveurs ___ les tables.","nettoient","nettoie"],
 ["Le renard ___ le poulailler.","contourne","contournent"],
 ["Les canards ___ dans le canal.","nagent","nage"],
 ["La potière ___ un vase.","fabrique","fabriquent"],
 ["Les skieurs ___ leurs skis.","portent","porte"],
 ["Le marchand ___ ses paniers.","installe","installent"],
 ["Les infirmières ___ les chambres.","aèrent","aère"],
 ["La tortue ___ la salade.","mange","mangent"],
 ["Les moutons ___ dans le champ.","broutent","broute"],
 ["Le pilote ___ la piste.","observe","observent"],
 ["Les choristes ___ une mélodie.","chantent","chante"],
 ],
 separated:[
 ["Le toit des cabanes ___ sous la pluie.","brille","brillent"],
 ["Les fenêtres du château ___ sur le parc.","donnent","donne"],
 ["La poignée des portes ___ dans sa main.","glisse","glissent"],
 ["Les boutons du manteau ___ au soleil.","brillent","brille"],
 ["Le parfum des fleurs ___ la terrasse.","embaume","embaument"],
 ["Les habitants du quartier ___ une fête.","organisent","organise"],
 ["La couleur des rideaux ___ avec le temps.","change","changent"],
 ["Les biscuits de la boîte ___ les enfants.","attirent","attire"],
 ["Le bruit des moteurs ___ les oiseaux.","effraie","effraient"],
 ["Les plumes du perroquet ___ le sol.","jonchent","jonche"],
 ["La couverture des livres ___ la poussière.","retient","retiennent"],
 ["Les marches de l’escalier ___ sous les pas.","craquent","craque"],
 ["Le chef des équipes ___ le départ.","annonce","annoncent"],
 ["Les racines du chêne ___ la terre.","soulèvent","soulève"],
 ],
 inverted:[
 ["Sous les feuilles ___ un escargot.","rampe","rampent"],
 ["À l’entrée du tunnel ___ des chauves-souris.","volent","vole"],
 ["Au milieu des fleurs ___ une abeille.","bourdonne","bourdonnent"],
 ["Devant le musée ___ des visiteurs.","attendent","attend"],
 ["Dans les salles ___ un air de musique.","résonne","résonnent"],
 ["Au bord du chemin ___ des coquelicots.","poussent","pousse"],
 ["Au sommet des collines ___ un moulin.","tourne","tournent"],
 ["Derrière la ferme ___ des vaches.","broutent","broute"],
 ["Entre les branches ___ un écureuil.","bondit","bondissent"],
 ["Sur le toit ___ des gouttes.","tombent","tombe"],
 ["Près des rochers ___ une barque.","flotte","flottent"],
 ["Dans le lointain ___ des montagnes.","apparaissent","apparaît"],
 ["Sous les couvertures ___ un chaton.","dort","dorment"],
 ["Dans la cheminée ___ des bûches.","crépitent","crépite"],
 ],
 coordinated:[
 ["La mère et son fils ___ des crêpes.","cuisinent","cuisine"],
 ["Le pêcheur et son ami ___ leurs filets.","rangent","range"],
 ["La pluie et le gel ___ la chaussée.","abîment","abîme"],
 ["Le lapin et le cochon d’Inde ___ une carotte.","grignotent","grignote"],
 ["La directrice et le professeur ___ les familles.","accueillent","accueille"],
 ["Le crayon et la règle ___ sur le bureau.","restent","reste"],
 ["La danseuse et son partenaire ___ une figure.","exécutent","exécute"],
 ["Le bus et le camion ___ au feu rouge.","patientent","patiente"],
 ["Le berger et son chien ___ le troupeau.","surveillent","surveille"],
 ["La rose et la tulipe ___ le jardin.","embellissent","embellit"],
 ["Le mécanicien et son apprentie ___ le capot.","soulèvent","soulève"],
 ["La chemise et le pantalon ___ sur le fil.","sèchent","sèche"],
 ["Le héron et la cigogne ___ près du marais.","marchent","marche"],
 ["La clarinette et la flûte ___ la mélodie.","jouent","joue"],
 ],
};
export const AGREEMENT_CORRECTION_DRAFTS:readonly AgreementCorrectionDraft[]=Object.entries(groups).flatMap(([construction,rows])=>rows.map(([template,correct,wrong],index)=>({key:`${construction}-${index+1}`,construction:construction as AgreementCorrectionDraft["construction"],template,correct,wrong})));
