import type {TargetTeachingContent} from './teaching-content';
type Case = {key:string; sentences:[string,string,string]; thesis:number; answer:string; distractors:[string,string,string]};
const cases:Case[]=[
 {key:'manga-club',sentences:['Certains pensent que lire un manga doit rester une activité solitaire.','Je défends au contraire la création d’un club de lecture de mangas.','Discuter des choix des personnages permettrait de découvrir des interprétations différentes.'],thesis:1,answer:'Créer un club de lecture de mangas.',distractors:['Lire les mangas uniquement seul.','Les personnages peuvent être interprétés différemment.','Remplacer tous les romans par des mangas.']},
 {key:'quiet-room',sentences:['Une salle calme devrait rester accessible pendant la pause.','Les élèves qui souhaitent lire y trouveraient un endroit sans bruit.','La pièce près du bureau pourrait convenir.'],thesis:0,answer:'Garder une salle calme accessible pendant la pause.',distractors:['Choisir obligatoirement la pièce près du bureau.','Certains élèves souhaitent lire sans bruit.','Interdire toute conversation dans le collège.']},
 {key:'repair',sentences:['Jeter un objet dès la première panne coûte cher.','Apprendre quelques réparations permet aussi de limiter les déchets.','C’est pourquoi je propose des ateliers de réparation au collège.'],thesis:2,answer:'Organiser des ateliers de réparation au collège.',distractors:['Une panne peut entraîner une dépense.','Les réparations peuvent limiter les déchets.','Interdire l’achat de tout objet neuf.']},
 {key:'uniform',sentences:['On affirme parfois qu’un uniforme rendrait tous les élèves égaux.','Je ne suis pas favorable à cette obligation.','Les différences de moyens resteraient visibles dans les sacs et les chaussures.'],thesis:1,answer:'Ne pas rendre l’uniforme obligatoire.',distractors:['L’uniforme rend tous les élèves égaux.','Les sacs peuvent montrer des différences de moyens.','Interdire les sacs et les chaussures différents.']},
 {key:'garden',sentences:['Il vaut mieux commencer notre potager par une petite surface.','Un grand terrain demanderait un entretien que notre groupe ne peut pas encore assurer.','Nous pourrions l’agrandir après une première saison réussie.'],thesis:0,answer:'Commencer le potager sur une petite surface.',distractors:['Un grand terrain demande beaucoup d’entretien.','Agrandir immédiatement le potager.','Renoncer définitivement au potager.']},
 {key:'phone',sentences:['Pendant une discussion, les notifications détournent notre attention.','Même une consultation rapide peut faire perdre le fil d’une idée.','Je recommande donc de laisser les téléphones de côté pendant les débats du club.'],thesis:2,answer:'Mettre les téléphones de côté pendant les débats du club.',distractors:['Une notification peut distraire.','Supprimer définitivement les téléphones.','Consulter son téléphone pendant chaque débat.']},
 {key:'tournament',sentences:['Le tournoi plaît beaucoup, mais son organisation occupe déjà toutes nos pauses.','Il ne faudrait pas ajouter une nouvelle compétition ce mois-ci.','Nous aurions ainsi le temps de terminer celle qui est commencée.'],thesis:1,answer:'Ne pas ajouter de compétition ce mois-ci.',distractors:['Le tournoi est apprécié.','Terminer la compétition déjà commencée prend du temps.','Ne plus jamais organiser de tournoi.']},
 {key:'library',sentences:['La bibliothèque devrait prêter aussi des livres audio.','Ils permettraient de découvrir des histoires pendant un trajet.','Ce service compléterait les livres imprimés sans les remplacer.'],thesis:0,answer:'Ajouter le prêt de livres audio à la bibliothèque.',distractors:['On peut écouter une histoire pendant un trajet.','Retirer tous les livres imprimés.','Autoriser seulement les livres imprimés.']},
];
export const ARGUMENT_THESIS_DRAFTS=cases.map(c=>({key:c.key,nodeKey:'identifier_these_argument',genre:'argumentative' as const,passage:c.sentences.join(' '),question:'Quelle idée l’auteur défend-il dans ce texte ?',answer:c.answer,distractors:c.distractors,support:c.sentences[c.thesis],otherSpans:c.sentences.filter((_,i)=>i!==c.thesis),reason:'Distinguer la thèse défendue des raisons, détails et opinions rapportées, sans demander si le lecteur est d’accord.'}));
const guided=[
 {text:'Un trajet à vélo permet de bouger. Je propose donc une journée où les élèves qui le souhaitent viennent à vélo. Cela doit rester facultatif.',answer:'Organiser une journée facultative pour venir à vélo.',others:['Obliger chacun à venir à vélo.','Faire du vélo permet de bouger.','Interdire tous les autres transports.'],support:'Je propose donc une journée où les élèves qui le souhaitent viennent à vélo.'},
 {text:'Certains veulent supprimer la récréation pour gagner du temps. Je m’oppose à cette proposition. Une pause permet de revenir plus attentif en classe.',answer:'Conserver la récréation.',others:['Supprimer la récréation.','Une pause peut aider à être attentif.','Supprimer les cours après la pause.'],support:'Je m’oppose à cette proposition.'},
 {text:'Les dessins terminés restent souvent dans les cahiers. Une exposition permettrait de les partager avec les familles. Organisons donc une exposition à la fin du trimestre.',answer:'Organiser une exposition à la fin du trimestre.',others:['Les dessins restent parfois dans les cahiers.','Inviter les familles chaque jour.','Ne plus dessiner dans les cahiers.'],support:'Organisons donc une exposition à la fin du trimestre.'},
];
export const ARGUMENT_THESIS_TEACHING:readonly TargetTeachingContent[]=[{
 id:'french-v3-teaching:argument-thesis',nodeKey:'identifier_these_argument',facetKey:'identifier_these_argument::text_type:argumentative',mode:'interpretation',status:'draft_requires_review',titleFr:'Trouver l’idée défendue dans un texte',learnerQuestionFr:'Quelle idée l’auteur veut-il nous faire accepter ?',
 steps:[{exampleFr:'Je propose un coin d’échange de jeux. Cela permettrait d’essayer un jeu sans l’acheter.',explanationFr:'L’auteur veut faire accepter une proposition : créer un coin d’échange de jeux. Cette idée défendue s’appelle la thèse. Essayer un jeu sans l’acheter est une raison donnée pour la soutenir.'},{exampleFr:'On propose parfois de vendre les jeux. Je préfère les échanger.',explanationFr:'L’auteur rapporte d’abord une autre proposition, puis donne sa position. La première idée mentionnée n’est donc pas toujours celle qu’il défend.'}],
 practice:guided.flatMap((g,i)=>[{id:`thesis-guided-${i}-answer`,promptFr:`${g.text}\n\nQuelle idée l’auteur défend-il ?`,choices:[g.answer,...g.others],answerFr:g.answer,hintFr:'Demande-toi ce que l’auteur veut faire accepter, et distingue cette idée de la raison donnée.',explanationFr:`L’idée défendue est : ${g.answer} Le texte l’exprime ainsi : « ${g.support} »`},{id:`thesis-guided-${i}-support`,promptFr:`${g.text}\n\nRecopie la phrase qui exprime cette position.`,answerFr:g.support,hintFr:'Cherche la proposition ou la prise de position, pas seulement son avantage.',explanationFr:`La phrase est : « ${g.support} »`}]),
 takeawayFr:'Cherche l’idée que l’auteur défend. Distingue-la de ses raisons et des opinions qu’il rapporte. Elle peut apparaître au début, au milieu ou à la fin.',boundaryFr:'Identifier une thèse ne signifie pas être d’accord avec elle, vérifier ses affirmations ou juger ses arguments. Une raison peut être vraie sans être l’idée principale défendue.',materialExposure:{sentences:[...guided.flatMap(g=>[g.text,g.support]),'Je propose un coin d’échange de jeux. Cela permettrait d’essayer un jeu sans l’acheter.','On propose parfois de vendre les jeux. Je préfère les échanger.']}
}];
