import type {TargetTeachingContent} from './teaching-content';
type Row={key:string;sentences:[string,string,string];reason:number;question:string;answer:string;distractors:[string,string,string]};
const rows:Row[]=[
 {key:'subtitles',sentences:['Les vidéos du journal scolaire devraient avoir des sous-titres.','Ils permettraient de comprendre les paroles même sans le son.','La prochaine vidéo présente le club de théâtre.'],reason:1,question:'Pourquoi l’auteur souhaite-t-il des sous-titres ?',answer:'Pour comprendre les paroles même sans le son.',distractors:['Pour présenter le club de théâtre.','Parce que toutes les vidéos sont déjà sous-titrées.','Pour supprimer les paroles des vidéos.']},
 {key:'water',sentences:['Une gourde peut être remplie plusieurs fois au cours de la journée.','Cela évite d’utiliser une nouvelle bouteille jetable à chaque fois.','Je propose donc d’installer une fontaine à eau dans la cour.'],reason:1,question:'Quelle raison soutient la proposition d’installer une fontaine ?',answer:'Réduire l’utilisation de bouteilles jetables.',distractors:['Installer la fontaine dans la cour.','Rendre les gourdes jetables.','Empêcher les élèves de boire plusieurs fois.']},
 {key:'team',sentences:['Gardons des équipes de taille limitée pour le projet.','Dans une petite équipe, chacun peut plus facilement prendre la parole.','Les groupes seront annoncés lundi.'],reason:1,question:'Pourquoi l’auteur défend-il des équipes de taille limitée ?',answer:'Pour faciliter la prise de parole de chacun.',distractors:['Parce que les groupes seront annoncés lundi.','Pour que personne ne parle.','Parce que les grandes équipes sont interdites.']},
 {key:'shelter',sentences:['Un espace libre se trouve à côté du portail.','Un abri protégerait les vélos de la pluie pendant les cours.','Construire un abri à vélos me semble donc utile.'],reason:1,question:'Quel avantage soutient la construction de l’abri ?',answer:'Protéger les vélos de la pluie pendant les cours.',distractors:['Construire un abri à vélos.','Empêcher toute pluie dans la cour.','Permettre de rouler dans les salles de classe.']},
 {key:'late-meeting',sentences:['La réunion est actuellement prévue à dix-sept heures.','Je demande qu’elle commence plus tôt, car le dernier bus part à cette heure-là.','Le sujet sera le voyage de classe.'],reason:1,question:'Pourquoi l’auteur demande-t-il d’avancer la réunion ?',answer:'Le dernier bus part à l’heure prévue pour la réunion.',distractors:['La réunion concerne le voyage de classe.','L’auteur veut changer le sujet de la réunion.','Tous les bus sont supprimés.']},
 {key:'costume',sentences:['Acheter des costumes neufs coûterait trop cher à notre troupe.','Réutilisons plutôt les vêtements disponibles pour le spectacle.','La représentation aura lieu dans le gymnase.'],reason:0,question:'Quelle raison justifie la réutilisation des vêtements ?',answer:'Le coût trop élevé de costumes neufs.',distractors:['Le spectacle aura lieu dans le gymnase.','La troupe ne donnera aucune représentation.','Les vêtements disponibles sont tous neufs.']},
 {key:'shade',sentences:['Plantons des arbres près des bancs.','Ils donneraient de l’ombre aux personnes assises en été.','Certains préféreraient seulement repeindre les bancs.'],reason:1,question:'Quel argument l’auteur donne-t-il pour planter des arbres ?',answer:'Les arbres apporteraient de l’ombre en été.',distractors:['Certaines personnes veulent repeindre les bancs.','Les arbres sont déjà plantés.','Les bancs ne servent à personne.']},
 {key:'anonymous',sentences:['La prochaine consultation porte sur les activités du foyer.','Une boîte à idées anonyme permettrait aux élèves de participer sans donner leur nom.','Je recommande d’en installer une près de l’accueil.'],reason:1,question:'Pourquoi l’auteur recommande-t-il une boîte à idées anonyme ?',answer:'Pour permettre de proposer des idées sans donner son nom.',distractors:['Parce que l’accueil va fermer.','Pour afficher le nom de chaque élève.','Pour empêcher les élèves de faire des propositions.']},
];
export const ARGUMENT_REASON_DRAFTS=rows.map(r=>({...r,nodeKey:'identifier_raison_argument',genre:'argumentative' as const,passage:r.sentences.join(' '),support:r.sentences[r.reason],otherSpans:r.sentences.filter((_,i)=>i!==r.reason),reason:'Identifier la raison donnée pour soutenir une proposition, en conservant la différence entre raison, proposition et détail de contexte.'}));
const guides=[
 {text:'Créons un panneau pour les annonces des clubs. Les élèves pourraient ainsi retrouver les horaires au même endroit. Le panneau serait bleu.',question:'Pourquoi créer ce panneau ?',answer:'Pour retrouver les horaires au même endroit.',others:['Parce que le panneau serait bleu.','Pour supprimer les clubs.','Parce que les horaires ne changent jamais.'],support:'Les élèves pourraient ainsi retrouver les horaires au même endroit.'},
 {text:'Les élèves ont parfois du mal à porter seuls les grandes maquettes. Je propose de les transporter à deux pour éviter de les laisser tomber. L’exposition ouvre vendredi.',question:'Pourquoi transporter les maquettes à deux ?',answer:'Pour éviter de les laisser tomber.',others:['Parce que l’exposition ouvre vendredi.','Pour rendre les maquettes plus grandes.','Pour annuler l’exposition.'],support:'Je propose de les transporter à deux pour éviter de les laisser tomber.'},
 {text:'Certains veulent jeter les feuilles utilisées d’un seul côté. Je préfère les garder comme brouillon : leur face vide peut encore servir. Une boîte est disponible près du tableau.',question:'Quelle raison soutient l’utilisation de ces feuilles comme brouillon ?',answer:'La face vide des feuilles peut encore servir.',others:['Certaines personnes veulent jeter les feuilles.','Une boîte se trouve près du tableau.','Les deux faces sont déjà remplies.'],support:'Je préfère les garder comme brouillon : leur face vide peut encore servir.'},
];
export const ARGUMENT_REASON_TEACHING:readonly TargetTeachingContent[]=[{
 id:'french-v3-teaching:argument-reason',nodeKey:'identifier_raison_argument',facetKey:'identifier_raison_argument::text_type:argumentative',mode:'interpretation',status:'draft_requires_review',titleFr:'Trouver la raison qui soutient une idée',learnerQuestionFr:'Pourquoi l’auteur défend-il cette idée ?',
 steps:[{exampleFr:'Prêtons des parapluies à l’accueil. Les élèves pourraient rentrer au sec en cas de pluie.',explanationFr:'Prêter des parapluies est la proposition défendue. Rentrer au sec est la raison donnée pour la soutenir. Une raison qui soutient une idée s’appelle un argument.'},{exampleFr:'Le stand est près de la porte. Prêtons des parapluies, car cela aiderait les élèves surpris par la pluie.',explanationFr:'Car introduit ici la raison. La place du stand est un détail, pas une raison de prêter des parapluies. Une raison peut aussi être exprimée sans car ou parce que : il faut lire le lien entre les idées.'}],
 practice:guides.flatMap((g,i)=>[{id:`reason-guided-${i}-answer`,promptFr:`${g.text}\n\n${g.question}`,choices:[g.answer,...g.others],answerFr:g.answer,hintFr:'Cherche ce qui explique pourquoi la proposition serait utile ou souhaitable.',explanationFr:`La raison donnée est : ${g.answer} Le texte dit : « ${g.support} »`},{id:`reason-guided-${i}-support`,promptFr:`${g.text}\n\nRecopie la phrase contenant cette raison.`,answerFr:g.support,hintFr:'La phrase peut contenir la proposition et sa raison, ou seulement la raison.',explanationFr:`La phrase contenant la raison est : « ${g.support} »`}]),
 takeawayFr:'Repère la proposition défendue, puis demande pourquoi l’auteur la soutient. Choisis une raison réellement donnée dans le texte, pas un détail ou une raison que tu inventes.',boundaryFr:'Repérer un argument ne prouve pas qu’il est vrai ou convaincant. Juger sa solidité est une autre compétence. Une même phrase peut contenir à la fois une proposition et sa raison.',materialExposure:{sentences:[...guides.flatMap(g=>[g.text,g.support]),'Prêtons des parapluies à l’accueil. Les élèves pourraient rentrer au sec en cas de pluie.','Le stand est près de la porte. Prêtons des parapluies, car cela aiderait les élèves surpris par la pluie.']}
}];
