/** New sentences for the approved canonical-sentence evidence, awaiting review. */
export const CANONICAL_SENTENCE_EXAMPLES: readonly [string,string,string][] = [
 ["La musicienne", "accorde", "sa guitare"],
 ["Le jardinier", "arrose", "les tomates"],
 ["Les élèves", "préparent", "une affiche"],
 ["Mon frère", "répare", "son vélo"],
 ["La dessinatrice", "termine", "son manga"],
 ["Les joueurs", "rangent", "les ballons"],
 ["Notre voisine", "ouvre", "la fenêtre"],
 ["Le cuisinier", "découpe", "les légumes"],
 ["Les visiteurs", "admirent", "la peinture"],
 ["La libraire", "conseille", "un roman"],
 ["Ma cousine", "photographie", "le paysage"],
 ["Les danseurs", "répètent", "leur chorégraphie"],
 ["Le mécanicien", "vérifie", "le moteur"],
 ["La vétérinaire", "examine", "le chat"],
 ["Les campeurs", "installent", "leur tente"],
 ["Le facteur", "distribue", "les lettres"],
];
export const CANONICAL_SENTENCE_PRODUCTION: readonly [string,string,string][] = [
 ["La nageuse", "ajuste", "ses lunettes"],
 ["Les touristes", "consultent", "le plan"],
 ["Le boulanger", "pétrit", "la pâte"],
 ["Mon oncle", "nettoie", "la terrasse"],
 ["Les chercheurs", "observent", "les étoiles"],
 ["La couturière", "choisit", "le tissu"],
 ["Le capitaine", "dirige", "le bateau"],
 ["Les enfants", "construisent", "une cabane"],
 ["La journaliste", "interroge", "le témoin"],
 ["Le peintre", "mélange", "les couleurs"],
 ["Les bénévoles", "collectent", "les vêtements"],
 ["Ma sœur", "écoute", "la radio"],
 ["Le pâtissier", "décore", "le gâteau"],
 ["Les techniciens", "testent", "le microphone"],
 ["La voyageuse", "prépare", "sa valise"],
 ["Le sculpteur", "taille", "la pierre"],
];
