import type {TargetTeachingContent} from './teaching-content';
type Practice={before:string;support:string;after:string;question:string;answer:string;others:string[]};
const practice:Record<string,Practice[]>={
 informational:[
  {before:'Le club prépare sa séance de jeudi.',support:'Le ballon prévu pour la séance ne garde plus son air. Un autre ballon est disponible dans le placard.',after:'Le responsable sort ce second ballon.',question:'Pourquoi le responsable change-t-il probablement de ballon ?',answer:'Le premier ballon ne peut plus rester gonflé.',others:['Le placard doit être jeté.','Le club a annulé toutes ses séances.','Le premier ballon est déjà parfaitement gonflé.']},
  {before:'La mairie annonce une modification du concert.',support:'La salle initiale compte cinquante sièges. Quatre-vingts personnes ont réservé leur place.',after:'Le concert se tiendra dans une salle plus grande.',question:'Pourquoi le concert change-t-il de salle ?',answer:'La première salle ne possède pas assez de sièges pour les personnes inscrites.',others:['Il n’y a aucune réservation.','Les musiciens ne veulent plus jouer.','La première salle est trop grande pour le public.']},
  {before:'La fiche décrit la distribution des repas.',support:'Un carton contient les menus sans viande. Les autres cartons contiennent tous des menus avec viande.',after:'Le premier carton est placé sur une table séparée.',question:'Pourquoi ce carton est-il probablement séparé des autres ?',answer:'Il faut pouvoir distinguer les deux types de menus.',others:['Les menus sont tous identiques.','Personne ne doit recevoir de repas.','Tous les cartons sont vides.']},
 ],
 argumentative:[
  {before:'Affichons le programme du festival aussi sur papier.',support:'Certains habitants n’ont pas accès au site internet. Ils découvrent les activités seulement après leur fin.',after:'Une affiche à la bibliothèque pourrait leur être utile.',question:'Pourquoi l’auteur souhaite-t-il une version papier ?',answer:'Il veut informer les personnes qui ne peuvent pas consulter le site.',others:['Il veut supprimer toutes les activités du festival.','Il souhaite annoncer les activités uniquement après leur fin.','Il pense que tous les habitants consultent déjà le site.']},
  {before:'Proposons un second groupe pour l’atelier photo.',support:'Le premier groupe est complet. Huit élèves attendent encore de pouvoir participer.',after:'Un autre créneau le vendredi serait possible.',question:'Pourquoi l’auteur propose-t-il un second groupe ?',answer:'Il souhaite accueillir les élèves qui n’ont pas encore de place.',others:['Il veut vider le premier groupe.','Il affirme que personne ne s’intéresse à la photo.','Il souhaite supprimer le créneau disponible.']},
  {before:'Déplaçons le panneau des résultats un peu plus bas.',support:'Les plus jeunes élèves doivent demander à un adulte de lire les lignes du haut. Les autres élèves peuvent les lire seuls.',after:'Tout le monde devrait pouvoir consulter ce panneau facilement.',question:'Pourquoi l’auteur veut-il déplacer le panneau ?',answer:'Il veut que les plus jeunes puissent lire les résultats sans aide.',others:['Il veut cacher les résultats aux plus jeunes.','Il souhaite supprimer les lignes du haut.','Il pense que le panneau est déjà trop bas.']},
 ],
};
const intros:Record<string,{title:string;example:string;explanation:string}>={
 informational:{title:'Trouver pourquoi une situation change dans un document',example:'Le projecteur ne s’allume plus. La présentation se poursuit avec des affiches.',explanation:'Le texte ne dit pas « on utilise des affiches parce que le projecteur est en panne ». Pourtant, les deux phrases permettent de faire ce lien : les affiches remplacent le projecteur qui ne fonctionne plus.'},
 argumentative:{title:'Retrouver la raison derrière une proposition',example:'Ouvrons une seconde file. Des visiteurs attendent depuis longtemps devant le guichet unique.',explanation:'La personne propose une seconde file. La phrase voisine décrit une attente longue. Tu peux en déduire son motif : elle souhaite réduire cette attente. Tu n’as pas besoin d’être d’accord avec la solution pour comprendre sa raison.'},
};
export const CAUSAL_READING_GENRES_TEACHING:readonly TargetTeachingContent[]=Object.entries(practice).map(([genre,rows])=>{
 const intro=intros[genre];
 const steps=[
  {exampleFr:intro.example,explanationFr:intro.explanation},
  {exampleFr:'Que se passe-t-il ? Quel indice proche permet d’expliquer pourquoi ?',explanationFr:'Commence par le fait ou la proposition à expliquer. Cherche ensuite un indice dans les phrases voisines. Quand tu relies ces indices pour trouver une cause qui n’est pas écrite directement, tu fais une inférence causale.'},
  {exampleFr:'La sonnerie retentit. Un livre tombe. Ces deux phrases ne disent pas qui a fait tomber le livre.',explanationFr:'Un événement qui arrive avant un autre n’en est pas forcément la cause. Choisis l’explication la mieux soutenue par le passage. N’ajoute pas une personne, une intention ou un fait que le texte ne permet pas de déduire.'},
 ];
 return {id:`french-v3-teaching:causal-reading-genres:${genre}`,nodeKey:'inferer_cause_locale',facetKey:`inferer_cause_locale::text_type:${genre}`,mode:'interpretation',status:'draft_requires_review',titleFr:intro.title,learnerQuestionFr:'Comment trouver une raison que le texte ne dit pas directement ?',steps,takeawayFr:'Repère ce qu’il faut expliquer, relie les indices proches et montre le passage qui soutient ta réponse.',boundaryFr:'Une explication plausible dans la vie ne suffit pas : elle doit être soutenue par ce texte. Comprendre la raison d’une proposition ne prouve pas que cette proposition fonctionnera.',practice:rows.flatMap((row,index)=>{
  const passage=[row.before,row.support,row.after].join(' ');
  return [
   {id:`causal-${genre}-${index}-reason`,promptFr:`${passage}\n\n${row.question}`,choices:[row.answer,...row.others],answerFr:row.answer,hintFr:'Relie la situation décrite dans le passage au changement ou à la proposition.',explanationFr:`Les indices sont : « ${row.support} » Ils soutiennent cette explication : ${row.answer}`},
   {id:`causal-${genre}-${index}-support`,promptFr:`${passage}\n\nQuel extrait donne les indices qui permettent de trouver cette raison ?`,choices:[row.before,row.support,row.after],answerFr:row.support,hintFr:'La phrase qui annonce le changement ne suffit pas. Cherche les détails qui expliquent pourquoi il a lieu.',explanationFr:`« ${row.support} » apporte les indices utiles. Les autres extraits présentent la situation ou la solution sans fournir ces mêmes indices.`},
  ];
 }),materialExposure:{sentences:[...steps.map(step=>step.exampleFr),...rows.map(row=>[row.before,row.support,row.after].join(' '))]}};
});
