/** Original fictional notices and opinions. Causes are inferred from nearby
 * clues, not external knowledge. Drafts require pedagogical review. */
type Row=readonly [key:string,before:string,support:string,after:string,question:string,answer:string,distractors:readonly string[]];
const informational:readonly Row[]=[
 ['atelier','Le centre propose un atelier de dessin mercredi.','La salle peut accueillir douze personnes. Douze inscriptions ont déjà été confirmées.','Les nouvelles demandes sont placées sur une liste d’attente.','Pourquoi les nouvelles demandes sont-elles mises en attente ?','Toutes les places de la salle sont déjà prises.',['Le matériel de dessin a disparu.','L’atelier a changé de jour.','Aucune personne ne s’est inscrite.']],
 ['retour-livres','La bibliothèque publie son bilan du lundi.','La boîte de retour était remplie jusqu’à l’ouverture. Aucun livre ne pouvait plus y entrer.','Une affiche demandait de rapporter les livres au comptoir.','Pourquoi fallait-il rendre les livres au comptoir ?','La boîte de retour ne pouvait plus recevoir de livres.',['Les livres devaient tous être réparés.','La bibliothèque ne prêtait plus de livres.','Le comptoir était fermé au public.']],
 ['projection','Le programme prévoit un film dans la cour.','Des rafales soulèvent l’écran installé dehors. Dans la salle, un autre écran est déjà fixé au mur.','La projection aura finalement lieu dans la salle.','Quelle est la cause la plus probable de ce changement de lieu ?','Le vent rend l’écran extérieur difficile à utiliser.',['Le film dure trop longtemps.','La cour est trop éloignée de la salle.','Le public a déjà vu le film.']],
 ['arrosage','Le rapport décrit l’entretien des bacs du jardin.','Ce matin, la terre est humide dans tous les bacs. De l’eau reste visible à leur surface.','L’arrosage prévu à midi est annulé.','Pourquoi l’arrosage est-il probablement annulé ?','Les bacs contiennent déjà assez d’eau.',['Les bacs ont été retirés du jardin.','Il n’y a plus de plantes dans les bacs.','Les jardiniers veulent déplacer toutes les plantes.']],
 ['pont','Le bulletin présente les accès au parc.','Une planche du petit pont est cassée. Un passage intact longe le ruisseau quelques mètres plus loin.','Des barrières ferment le pont et des flèches indiquent le passage voisin.','Pourquoi le parcours des visiteurs a-t-il été modifié ?','Le pont abîmé ne permet plus un passage sûr.',['Le ruisseau a complètement disparu.','Le parc ferme pour toute l’année.','Le passage voisin vient d’être interdit.']],
 ['impression','Le journal du collège doit être distribué vendredi.','La machine du secrétariat n’imprime plus aucune page. Celle de la bibliothèque fonctionne encore.','Les exemplaires seront imprimés à la bibliothèque.','Pourquoi l’impression a-t-elle été déplacée ?','La machine habituelle ne fonctionne plus.',['Les articles parlent uniquement de livres.','La distribution est annulée.','Le journal ne contient aucune page.']],
 ['bus','Le panneau annonce un changement pour la ligne 4.','La rue des Lilas est entièrement occupée par un chantier. Aucun véhicule ne peut la traverser.','Le bus dessert provisoirement l’arrêt de la rue voisine.','Pourquoi le bus utilise-t-il un autre arrêt ?','Il ne peut plus passer par la rue habituelle.',['Les voyageurs ont tous changé de quartier.','Le bus circule désormais sans passagers.','L’arrêt voisin sera supprimé définitivement.']],
 ['exposition','L’exposition de dessins reste ouverte jusqu’à samedi.','Des visiteurs font la queue devant une seule table d’accueil. Une seconde table est disponible à côté.','Une autre personne accueillera le public à cette seconde table.','Quel problème explique probablement cette nouvelle organisation ?','L’accueil à une seule table ralentit l’entrée des visiteurs.',['Les dessins ne sont pas encore terminés.','Les visiteurs refusent de voir l’exposition.','La seconde table bloque la sortie.']],
 ['entrainement','L’équipe reçoit son programme de la semaine.','Le terrain extérieur est recouvert de flaques. Le sol du gymnase est sec.','L’entraînement de ce soir est transféré au gymnase.','Pourquoi l’équipe s’entraînera-t-elle probablement au gymnase ?','Le terrain extérieur est trop mouillé pour la séance prévue.',['L’équipe ne souhaite plus s’entraîner.','Le gymnase ne possède aucun espace libre.','Les joueurs ont oublié la date de la séance.']],
 ['commande','Le magasin envoie une information sur une commande de cahiers.','Le colis reçu contient vingt cahiers au lieu des trente commandés. Les dix autres sont annoncés pour demain.','Une partie de la commande sera remise demain seulement.','Pourquoi la remise de la commande se fait-elle en deux fois ?','Tous les cahiers ne sont pas arrivés ensemble.',['Le client a demandé de supprimer dix cahiers.','Les trente cahiers sont déjà disponibles.','Le magasin a reçu uniquement des crayons.']],
 ['porte','Une note décrit l’accès à la salle de musique.','La serrure de la porte principale est bloquée. La porte latérale s’ouvre normalement.','Les élèves sont invités à entrer par le côté.','Pourquoi les élèves doivent-ils changer d’entrée ?','La porte principale ne peut pas être ouverte normalement.',['La salle de musique a été déplacée.','La porte latérale est condamnée.','Les élèves doivent attendre dehors toute la journée.']],
 ['horaires','Le musée prépare l’accueil d’un groupe mardi.','Le train du groupe arrive à dix heures. La visite était prévue à neuf heures trente.','Le début de la visite est reporté à dix heures trente.','Pourquoi la visite commence-t-elle plus tard ?','Le groupe ne peut pas être présent à l’heure initialement prévue.',['Le groupe souhaite quitter le musée avant neuf heures.','Le musée ne recevra aucun visiteur mardi.','Le trajet en train a été supprimé.']],
];
const argumentative:readonly Row[]=[
 ['mangas','Je propose d’ajouter des mangas au club de lecture.','Plusieurs élèves demandent ces livres chaque semaine. Ils repartent souvent sans emprunter les romans disponibles.','Essayons d’en acheter quelques-uns avant la prochaine rencontre.','Pourquoi l’auteur propose-t-il probablement cet achat ?','Il souhaite intéresser des élèves qui ne trouvent pas de lecture à leur goût.',['Il veut empêcher les élèves de lire des romans.','Il affirme que les romans sont tous abîmés.','Il souhaite fermer le club de lecture.']],
 ['horaires-club','Déplaçons la réunion du club au mercredi.','Le mardi, plusieurs membres ont un cours à la même heure. Le mercredi, ils sont libres.','Nous pourrions essayer ce nouvel horaire pendant un mois.','Quelle difficulté motive probablement la proposition ?','Certains membres ne peuvent pas venir à l’horaire actuel.',['Le club ne dispose plus d’aucun membre.','Le mercredi est le jour où tous ont cours.','La réunion doit durer un mois entier.']],
 ['panneaux','Ajoutons des panneaux à l’entrée du collège.','Les nouveaux élèves demandent souvent où se trouvent les salles. Certains arrivent en retard après avoir cherché leur chemin.','Un plan près du portail serait aussi utile.','Pourquoi l’auteur souhaite-t-il ces panneaux ?','Il veut aider les nouveaux élèves à trouver leur salle.',['Il veut déplacer toutes les salles.','Il souhaite allonger les trajets des élèves.','Il pense que les élèves connaissent déjà tous les lieux.']],
 ['casques','Prévoyons des casques pour les vidéos de l’atelier.','Dans la même salle, un groupe écoute une vidéo et un autre enregistre sa voix. Le son de la vidéo s’entend dans l’enregistrement.','Essayons cette solution dès la prochaine séance.','Quel problème motive probablement cette proposition ?','Le son d’une activité perturbe l’autre.',['Les vidéos ne contiennent aucun son.','La salle est toujours vide.','Les élèves veulent arrêter tout enregistrement.']],
 ['pret-materiel','Organisons un prêt de raquettes au collège.','Des élèves voudraient participer au tournoi. Plusieurs n’ont pas de raquette et ne peuvent pas en acheter une.','Chacun pourrait rendre le matériel après son match.','Pourquoi l’auteur propose-t-il de prêter du matériel ?','Il veut permettre de jouer à ceux qui n’ont pas de raquette.',['Il veut réserver le tournoi aux propriétaires de raquettes.','Il pense que personne ne veut participer.','Il veut empêcher le retour du matériel.']],
 ['salle-calme','Réservons une petite salle pour le travail silencieux.','Au foyer, des élèves discutent pendant que d’autres essaient de lire. Ces derniers relisent souvent la même ligne sans avancer.','Le foyer pourrait rester un lieu de rencontre.','Quelle difficulté explique probablement la proposition ?','Certains élèves ont du mal à lire au milieu des conversations.',['Tous les élèves souhaitent supprimer les discussions.','Aucun élève ne lit au collège.','La petite salle est déjà utilisée pour des concerts.']],
 ['echange-livres','Créons une table d’échange de livres.','Plusieurs élèves ont terminé leurs livres et cherchent de nouvelles lectures. D’autres possèdent des livres qu’ils ne lisent plus.','Nous pourrions commencer avec une table dans le hall.','Pourquoi cette table serait-elle utile selon l’auteur ?','Elle permettrait aux livres disponibles de trouver de nouveaux lecteurs.',['Elle obligerait chacun à racheter ses propres livres.','Elle empêcherait les élèves d’apporter des livres.','Elle servirait uniquement à ranger des cahiers vides.']],
 ['reserve-eau','Installons un point d’eau près du terrain.','Pendant les matchs, les joueurs doivent traverser tout le bâtiment pour remplir leur gourde. Ils manquent alors plusieurs minutes de jeu.','Un emplacement près de l’entrée du terrain conviendrait.','Quel problème motive probablement la demande ?','Le point d’eau actuel oblige les joueurs à s’absenter longtemps.',['Les joueurs ne possèdent jamais de gourde.','Le terrain ne sert plus à jouer.','Le bâtiment est trop proche du terrain.']],
 ['rotation','Faisons tourner les rôles dans le groupe vidéo.','Les mêmes élèves tiennent toujours la caméra. Les autres aimeraient essayer, mais restent chargés du rangement.','Un tableau des rôles pour chaque séance aiderait à nous organiser.','Pourquoi l’auteur souhaite-t-il une rotation ?','Il veut donner à chacun l’occasion d’essayer la caméra.',['Il veut supprimer le rôle de rangement.','Il affirme que la caméra est cassée.','Il souhaite confier la caméra toujours aux mêmes élèves.']],
 ['sous-titres','Ajoutons des sous-titres aux vidéos de présentation.','Dans le hall, le bruit couvre souvent les paroles des vidéos. Les visiteurs voient les images sans comprendre les explications.','Quelques lignes bien lisibles pourraient accompagner chaque passage.','Pourquoi l’auteur propose-t-il des sous-titres ?','Il veut rendre les explications accessibles quand on les entend mal.',['Il veut remplacer les vidéos par de la musique.','Il pense que les visiteurs ne voient aucune image.','Il souhaite rendre les paroles plus difficiles à comprendre.']],
 ['inscriptions','Ouvrons les inscriptions aussi pendant la pause de midi.','Le bureau ferme à seize heures. À cette heure-là, plusieurs élèves sont encore en cours.','Ce créneau supplémentaire pourrait être testé la semaine prochaine.','Pourquoi l’auteur demande-t-il un autre créneau ?','Certains élèves ne peuvent pas se rendre au bureau avant sa fermeture.',['Le bureau est déjà ouvert toute la nuit.','Personne ne souhaite s’inscrire.','L’auteur veut supprimer les inscriptions de midi.']],
 ['abri','Ajoutons un abri près de l’arrêt scolaire.','Les élèves y attendent dehors plusieurs minutes. Les jours de pluie, leurs sacs et leurs vêtements sont trempés avant le trajet.','Un petit toit suffirait peut-être, sans fermer tout l’espace.','Pourquoi l’auteur demande-t-il cet abri ?','Il souhaite protéger les élèves de la pluie pendant l’attente.',['Il veut empêcher le bus de s’arrêter.','Il souhaite prolonger le trajet scolaire.','Il affirme que les élèves attendent déjà dans une salle.']],
];
export const CAUSAL_READING_GENRES_DRAFTS=([['informational',informational],['argumentative',argumentative]] as const).flatMap(([genre,rows])=>rows.map(([key,before,support,after,question,answer,distractors])=>({key:`${genre}-${key}`,genre,nodeKey:'inferer_cause_locale',passage:[before,support,after].join(' '),support,otherSpans:[before,after],question,answer,distractors,reason:'Relier une situation et sa conséquence ou une proposition à son motif implicite, puis sélectionner les indices voisins qui soutiennent cette déduction.'})));
