import type {TargetTeachingContent} from './teaching-content';
interface MotivationPassage {key:string;before:string;clue:string;action:string;after:string;question:string;answer:string;distractors:string[]}
const rows:readonly MotivationPassage[]=[
 {key:'manga-spoiler',before:'Le club de lecture se réunit le mardi dans une petite salle dont les murs portent des affiches.',clue:'Amir vient de commencer le manga que Zoé a terminé.',action:'Quand les autres abordent la dernière page, Zoé propose de parler des dessins.',after:'Les livres sont posés au milieu de la table.',question:'Pourquoi Zoé change-t-elle probablement de sujet ?',answer:'Pour éviter de révéler la fin à Amir.',distractors:['Pour convaincre Amir d’abandonner sa lecture.','Pour montrer qu’elle n’a pas lu la dernière page.','Pour obtenir une nouvelle date de réunion.']},
 {key:'cold-friend',before:'Le groupe attend le car devant le musée.',clue:'Lina tremble et frotte ses bras nus.',action:'Yanis sort son gilet de son sac et le pose sur les épaules de Lina.',after:'Le car arrive cinq minutes plus tard et le groupe se rassemble près de la porte.',question:'Pourquoi Yanis donne-t-il probablement son gilet à Lina ?',answer:'Pour l’aider à se réchauffer.',distractors:['Pour demander à Lina de transporter son sac.','Pour lui signaler que le car est déjà reparti.','Pour récupérer un vêtement que Lina lui a prêté.']},
 {key:'slower-runner',before:'Les élèves courent sur une piste.',clue:'Derrière lui, Noé voit son camarade s’arrêter en tenant sa cheville.',action:'Il quitte sa place en tête et revient vers son camarade.',after:'Le professeur se trouve près de la ligne d’arrivée, à côté du banc et des bouteilles d’eau.',question:'Pourquoi Noé revient-il probablement en arrière ?',answer:'Pour aider son camarade qui semble blessé.',distractors:['Pour conserver à tout prix sa place en tête.','Pour empêcher son camarade de gagner malgré une course normale.','Pour rejoindre le professeur à la ligne d’arrivée.']},
 {key:'birthday-box',before:'Le salon est éclairé par une petite lampe posée sur une table près de la porte du couloir.',clue:'Demain, c’est l’anniversaire de son frère ; Maëlle termine d’emballer une boîte.',action:'Lorsqu’elle entend son frère entrer, elle glisse la boîte sous un coussin.',after:'Son frère s’assoit près de la fenêtre et pose son cahier sur une chaise à côté de lui.',question:'Pourquoi Maëlle cache-t-elle probablement la boîte ?',answer:'Pour garder le cadeau secret jusqu’à l’anniversaire.',distractors:['Pour demander à son frère de finir l’emballage.','Pour lui montrer immédiatement le contenu de la boîte.','Pour éviter que la lumière de la fenêtre abîme la boîte.']},
 {key:'reading-light',before:'Le grand-père de Sami ouvre une lettre.',clue:'Il rapproche la page de ses yeux et dit que les petites lettres sont difficiles à voir dans ce coin sombre.',action:'Sami apporte une lampe et l’oriente vers la page.',after:'La lettre tient sur une seule feuille.',question:'Pourquoi Sami déplace-t-il probablement la lampe ?',answer:'Pour aider son grand-père à lire la lettre.',distractors:['Pour empêcher son grand-père de lire le contenu.','Pour lui demander de lire plus loin de la lampe.','Pour chercher une seconde feuille dont parle le texte.']},
 {key:'robot-battery',before:'Le club présente ses robots après le déjeuner dans la grande salle qui se trouve au rez-de-chaussée.',clue:'Sur l’écran du robot de Léa, la batterie indique 2 %.',action:'Avant la démonstration, Léa branche le robot et attend que le niveau remonte.',after:'Les visiteurs arrivent par la porte du fond.',question:'Pourquoi Léa branche-t-elle probablement son robot ?',answer:'Pour éviter qu’il manque d’énergie pendant la démonstration.',distractors:['Pour lancer la démonstration sans attendre la recharge.','Pour ranger définitivement le robot avant la présentation.','Pour obtenir plus de place près de la porte du fond.']},
 {key:'new-student',before:'La pause du midi commence.',clue:'La nouvelle élève reste seule avec son plateau et regarde les tables occupées.',action:'Nora écarte son sac d’une chaise libre et fait signe à la nouvelle élève.',after:'Un pichet d’eau se trouve sur la table.',question:'Pourquoi Nora dégage-t-elle probablement la chaise ?',answer:'Pour inviter la nouvelle élève à s’asseoir avec elle.',distractors:['Pour réserver la chaise à son sac.','Pour demander à la nouvelle élève de quitter la salle.','Pour obtenir le plateau de la nouvelle élève.']},
 {key:'quiet-player',before:'Une équipe joue un match amical dans la cour, sur le terrain situé entre le gymnase et le bâtiment principal.',clue:'Depuis le début, Léo reste libre sur le côté et n’a reçu aucune passe.',action:'Bien placé pour tirer, Adam se tourne et envoie le ballon vers Léo.',after:'Le ballon roule sur le sol sec, puis rebondit près de la ligne blanche tracée au bord du terrain.',question:'Pourquoi Adam fait-il probablement cette passe ?',answer:'Pour permettre à Léo de participer au jeu.',distractors:['Pour tenir Léo à l’écart du ballon.','Pour garder seul toutes les occasions de tirer.','Pour interrompre le match et quitter le terrain.']},
];
export const MOTIVATION_DRAFTS=rows.map(r=>({...r,genre:'narrative' as const,nodeKey:'inferer_motivation_personnage',passage:[r.before,r.clue,r.action,r.after].join(' '),support:r.clue,otherSpans:[r.before,r.after],reason:'Relier un indice de situation à une action pour inférer une motivation plausible, puis sélectionner l’indice de situation qui étaye cette interprétation.'}));
const guided:readonly MotivationPassage[]=[
 {key:'wet-paint',before:'Le groupe prépare une exposition.',clue:'Une affiche vient d’être peinte et sa surface brille encore.',action:'Mina tend le bras devant Jules qui s’apprête à poser son sac dessus.',after:'Trois autres affiches sont fixées au mur.',question:'Pourquoi Mina arrête-t-elle probablement le geste de Jules ?',answer:'Pour éviter que le sac abîme la peinture encore fraîche.',distractors:['Pour demander à Jules de peindre le mur.','Pour cacher les trois autres affiches.','Pour empêcher Jules de porter un sac.']},
 {key:'low-voice',before:'Deux amis entrent dans une chambre.',clue:'Le petit frère de Chloé dort dans son lit.',action:'Chloé approche un doigt de ses lèvres et parle tout bas.',after:'Un livre est posé sur une étagère.',question:'Pourquoi Chloé parle-t-elle probablement tout bas ?',answer:'Pour ne pas réveiller son petit frère.',distractors:['Pour éviter de lire le livre.','Pour demander un nouveau lit.','Pour empêcher son ami d’entrer dans la chambre.']},
 {key:'forgotten-lunch',before:'La sortie scolaire dure toute la journée.',clue:'Pendant le pique-nique, Ali ouvre son sac vide et baisse les yeux vers les sandwichs des autres.',action:'Inès coupe son sandwich en deux et lui en tend une moitié.',after:'Le groupe est installé près d’un arbre.',question:'Pourquoi Inès partage-t-elle probablement son sandwich ?',answer:'Pour donner à manger à Ali, qui semble ne pas avoir de repas.',distractors:['Pour faire partir Ali loin du groupe.','Pour mesurer la hauteur de l’arbre.','Pour demander à Ali de porter tous les sacs.']},
];
export const MOTIVATION_TEACHING:readonly TargetTeachingContent[]=[{
 id:'french-v3-teaching:reading:inferer_motivation_personnage:narrative',nodeKey:'inferer_motivation_personnage',facetKey:'inferer_motivation_personnage::text_type:narrative',mode:'interpretation',status:'draft_requires_review',titleFr:'Comprendre pourquoi un personnage agit',learnerQuestionFr:'Quand le texte ne dit pas « elle veut… », comment trouver une raison plausible à son geste ?',
 steps:[
  {exampleFr:'Tom tend la main vers une tasse fumante. Sa sœur éloigne la tasse de ses doigts.',explanationFr:'La tasse est fumante et Tom va la toucher. Le geste de sa sœur laisse penser qu’elle veut lui éviter de se brûler. Le texte ne nomme pas directement cette intention : nous la déduisons des indices. C’est une inférence.'},
  {exampleFr:'Indice : une tasse fumante. Action : la sœur éloigne la tasse.',explanationFr:'Relie la situation à l’action. La motivation est la raison qui pousse le personnage à agir. Ici, protéger Tom explique les deux indices ensemble.'},
  {exampleFr:'« Sa sœur déteste toutes les boissons chaudes. »',explanationFr:'Cette idée pourrait exister dans une autre histoire, mais rien ici ne la soutient. Choisis une raison que les mots du texte rendent plausible, sans inventer une habitude ou un souvenir du personnage.'},
 ],
 takeawayFr:'Repère ce qui se passe juste avant le geste, puis le geste lui-même. Cherche la raison qui les relie et retrouve les mots qui soutiennent ton interprétation.',
 boundaryFr:'Une motivation déduite reste une interprétation, pas une lecture certaine des pensées. Certains récits autorisent plusieurs interprétations ; ces exercices demandent la mieux soutenue parmi les réponses proposées.',
 practice:guided.flatMap((r,index)=>{const passage=[r.before,r.clue,r.action,r.after].join(' '),support=r.clue;return [
 {id:`guided:motivation:${index+1}:answer`,promptFr:`${passage}\n\n${r.question}`,choices:[r.answer,...r.distractors],answerFr:r.answer,hintFr:'Relie le problème ou la situation au geste du personnage.',explanationFr:`${r.answer} Les indices sont : ${support}`},
 {id:`guided:motivation:${index+1}:support`,promptFr:`${passage}\n\nQuel passage soutient cette interprétation : ${r.answer}`,choices:[support,r.before,r.after],answerFr:support,hintFr:'Choisis l’indice de situation qui explique le geste demandé.',explanationFr:'Cet indice de situation, relié au geste décrit dans la question, soutient l’interprétation. Les autres phrases donnent seulement le décor.'},
 ];}),
 materialExposure:{sentences:['Tom tend la main vers une tasse fumante. Sa sœur éloigne la tasse de ses doigts.',...guided.map(r=>[r.before,r.clue,r.action,r.after].join(' '))]},
}];
