import type {Person,Gender} from '@/lib/linguistic/conjugation';
import {PRESENT_APPLICATION_CONTEXTS} from './present-application-contexts';
export type CompoundApplicationCase={verb:string;person:Person;gender:Gender;sentence:string;auxiliaryUse?:'transitive'|'intransitive';genderSpecified?:boolean};
const special:Record<string,readonly [Person,Gender,string,('transitive'|'intransitive')?][]>= {
 aller:[['1s','m','Je ___ au cinéma municipal.'],['2s','f','Tu ___ au cours de poterie.'],['3s','f','Ma cousine ___ à la bibliothèque.'],['1p','m','Nous ___ au tournoi.'],['2p','f','Vous ___ au jardin partagé.'],['3p','f','Les voisines ___ à la kermesse.'],['1s','f','Je ___ au centre sportif.'],['2s','m','Tu ___ au magasin de musique.'],['3s','m','Le gardien ___ au bureau.'],['1p','f','Nous ___ au château.'],['2p','m','Vous ___ au port de pêche.'],['3p','m','Les garçons ___ au marché couvert.']],
 venir:[['1s','m','Je ___ apporter une affiche.'],['2s','f','Tu ___ rendre le livre emprunté.'],['3s','f','La directrice ___ saluer le groupe.'],['1p','m','Nous ___ aider au déménagement.'],['2p','f','Vous ___ préparer la fête.'],['3p','f','Les joueuses ___ essayer le terrain.'],['1s','f','Je ___ chercher une invitation.'],['2s','m','Tu ___ installer le projecteur.'],['3s','m','Le voisin ___ arroser les plantes.'],['1p','f','Nous ___ répéter la chanson.'],['2p','m','Vous ___ ranger les décors.'],['3p','m','Les cousins ___ partager le repas.']],
 partir:[['1s','m','Je ___ pour Bruxelles hier.'],['2s','f','Tu ___ après la remise des prix.'],['3s','f','La voyageuse ___ sans sa valise.'],['1p','m','Nous ___ avant le coucher du soleil.'],['2p','f','Vous ___ au signal du professeur.'],['3p','f','Les visiteuses ___ par le grand escalier.'],['1s','f','Je ___ avec une carte du quartier.'],['2s','m','Tu ___ après le dernier rappel.'],['3s','m','Le navire ___ vers le large.'],['1p','f','Nous ___ du centre du village.'],['2p','m','Vous ___ avant l’orage.'],['3p','m','Les cyclistes ___ en direction du pont.']],
 sortir:[['1s','m','Je ___ la nappe du tiroir.','transitive'],['2s','f','Tu ___ du laboratoire.','intransitive'],['3s','f','La chatte ___ de son panier.','intransitive'],['1p','m','Nous ___ admirer la lune.','intransitive'],['2p','f','Vous ___ les gâteaux du four.','transitive'],['3p','f','Les danseuses ___ de la scène.','intransitive'],['1s','f','Je ___ le parasol du garage.','transitive'],['2s','m','Tu ___ par la porte de service.','intransitive'],['3s','m','Le renard ___ du terrier.','intransitive'],['1p','f','Nous ___ après le générique.','intransitive'],['2p','m','Vous ___ les couvertures du placard.','transitive'],['3p','m','Les acteurs ___ des coulisses.','intransitive']],
};
const otherVerbs=new Set(['être','avoir','faire','prendre','dire','voir','pouvoir','vouloir','savoir','devoir']);
export const COMPOUND_APPLICATION_CONTEXTS:readonly CompoundApplicationCase[]=[
 ...PRESENT_APPLICATION_CONTEXTS.filter(([verb])=>otherVerbs.has(verb)).map(([verb,person,sentence])=>({verb,person,sentence,gender:'m' as const})),
 ...Object.entries(special).flatMap(([verb,rows])=>rows.map(([person,gender,sentence,auxiliaryUse])=>({verb,person,gender,sentence,genderSpecified:true,...(auxiliaryUse?{auxiliaryUse}:{})}))),
];
