import type {TargetTeachingContent} from './teaching-content';
type Row={key:string;sentences:[string,string,string];objection:number;question:string;answer:string;distractors:[string,string,string]};
const rows:Row[]=[
 {key:'manga-club',sentences:['Je propose un club manga après les cours pour échanger nos lectures.','Plusieurs élèves craignent toutefois de manquer leur bus si le club finit trop tard.','Nous pourrions terminer avant le départ des bus.'],objection:1,question:'Quelle difficulté les élèves opposent-ils au projet de club ?',answer:'Ils risquent de manquer leur bus.',distractors:['Ils pourraient échanger leurs lectures.','Le club pourrait terminer plus tôt.','Tous les élèves détestent les mangas.']},
 {key:'courtyard',sentences:['Des élèves craignent que des tables de ping-pong réduisent la place pour courir.','Je souhaite pourtant en installer dans la cour pour varier les activités.','Le conseil des élèves en parlera jeudi.'],objection:0,question:'Quelle raison va contre l’installation des tables ?',answer:'Il resterait moins de place pour courir.',distractors:['Les activités seraient plus variées.','Le conseil se réunira jeudi.','Les tables seraient trop chères.']},
 {key:'online-paper',sentences:['Publions le journal du collège uniquement en ligne pour économiser du papier.','La prochaine édition parlera des associations du quartier.','Certains élèves n’ont cependant pas accès à Internet chez eux.'],objection:2,question:'Quelle objection peut-on opposer à un journal uniquement en ligne d’après le texte ?',answer:'Certains élèves n’ont pas Internet à la maison.',distractors:['On économiserait du papier.','Le journal parlera du quartier.','Personne ne sait lire au collège.']},
 {key:'pets',sentences:['Accueillons un lapin dans la classe pour apprendre à nous en occuper.','Qui le nourrira pendant les vacances, demandent plusieurs parents.','Un planning pourrait répartir cette tâche entre des familles volontaires.'],objection:1,question:'Quel problème les parents soulèvent-ils contre ce projet ?',answer:'Il faut prévoir qui nourrira le lapin pendant les vacances.',distractors:['Les élèves apprendraient à s’occuper du lapin.','Des familles volontaires pourraient se partager la tâche.','Le lapin ne mange jamais pendant les vacances.']},
 {key:'uniform',sentences:['Une tenue commune éviterait les comparaisons entre les vêtements des élèves.','Je suis donc favorable à cette tenue au collège.','Des familles font remarquer qu’il faudrait acheter de nouveaux vêtements alors que les anciens conviennent encore.'],objection:2,question:'Quelle raison les familles donnent-elles contre la tenue commune ?',answer:'Elle obligerait à acheter des vêtements alors que les anciens conviennent.',distractors:['Elle éviterait les comparaisons entre vêtements.','L’auteur y est favorable.','Les élèves ne possèdent aucun vêtement.']},
 {key:'garden',sentences:['Installer un potager me paraît souhaitable pour observer la croissance des plantes.','Mais cela demande un arrosage régulier, souligne la gardienne.','Nous pourrions organiser des tours d’arrosage.'],objection:1,question:'Quelle contrainte la gardienne oppose-t-elle au projet ?',answer:'Le potager aurait besoin d’un arrosage régulier.',distractors:['Les élèves observeraient la croissance des plantes.','On pourrait organiser des tours d’arrosage.','Les plantes poussent sans eau.']},
 {key:'music',sentences:['Diffusons de la musique dans le foyer pour le rendre plus accueillant.','Même à faible volume, elle pourrait gêner ceux qui souhaitent y lire au calme.','Le foyer ouvre à midi.'],objection:1,question:'Quelle raison s’oppose à la diffusion de musique dans ce texte ?',answer:'Elle pourrait déranger les élèves qui veulent lire au calme.',distractors:['Elle rendrait le foyer plus accueillant.','Le foyer ouvre à midi.','Le foyer est toujours fermé.']},
 {key:'trip',sentences:['Le trajet en train coûterait davantage que le trajet en car, rappelle le trésorier.','Je défends néanmoins le train pour notre sortie, car nous pourrions marcher plus facilement pendant le voyage.','Le départ est prévu en avril.'],objection:0,question:'Quelle objection le trésorier donne-t-il au choix du train ?',answer:'Le train coûterait plus cher que le car.',distractors:['On pourrait marcher plus facilement pendant le voyage.','Le départ est prévu en avril.','Le voyage en train serait gratuit.']},
];
export const COUNTERARGUMENT_DRAFTS=rows.map(r=>({...r,nodeKey:'reconnaitre_contre_argument',genre:'argumentative' as const,passage:r.sentences.join(' '),support:r.sentences[r.objection],otherSpans:r.sentences.filter((_,i)=>i!==r.objection),reason:'Repérer une raison qui s’oppose à la proposition défendue, distincte de sa justification, d’un détail et d’une réponse à l’objection.'}));
const guides=[
 {text:'Ouvrons la bibliothèque pendant la récréation pour permettre aux élèves de lire. Une surveillante rappelle qu’il faut alors une personne pour accueillir les lecteurs. Des adultes volontaires pourraient se relayer.',question:'Quel obstacle la surveillante signale-t-elle ?',answer:'Il faut une personne pour accueillir les lecteurs.',others:['Les élèves pourraient lire pendant la récréation.','Des volontaires pourraient se relayer.','La bibliothèque ne contient aucun livre.'],support:'Une surveillante rappelle qu’il faut alors une personne pour accueillir les lecteurs.'},
 {text:'Les affiches risquent de se décoller sous la pluie, fait remarquer Sam. Je propose tout de même de les placer dehors pour que les passants voient notre exposition. Nous pourrions les protéger avec une couverture transparente.',question:'Quelle raison Sam donne-t-il contre les affiches dehors ?',answer:'La pluie risque de les faire se décoller.',others:['Les passants verraient l’exposition.','Une couverture pourrait protéger les affiches.','L’exposition a été annulée.'],support:'Les affiches risquent de se décoller sous la pluie, fait remarquer Sam.'},
 {text:'Je souhaite ajouter un dessert au repas de fête pour offrir plus de choix. Le repas aura lieu samedi. Comment payer ces portions supplémentaires avec notre budget limité, demande Lila.',question:'Quelle objection Lila formule-t-elle ?',answer:'Le budget limité pose un problème pour payer les portions supplémentaires.',others:['Un dessert offrirait plus de choix.','Le repas aura lieu samedi.','Personne ne veut de dessert.'],support:'Comment payer ces portions supplémentaires avec notre budget limité, demande Lila.'},
];
export const COUNTERARGUMENT_TEACHING:readonly TargetTeachingContent[]=[{
 id:'french-v3-teaching:counterargument',nodeKey:'reconnaitre_contre_argument',facetKey:'reconnaitre_contre_argument::text_type:argumentative',mode:'interpretation',status:'draft_requires_review',titleFr:'Repérer une objection à une idée',learnerQuestionFr:'Quelle raison pourrait faire hésiter à accepter cette proposition ?',
 steps:[{exampleFr:'Organisons un tournoi dimanche pour réunir les classes. Mais certains élèves travaillent avec leur famille ce jour-là.',explanationFr:'Réunir les classes est une raison pour le tournoi. Le travail de certains élèves le dimanche est une raison contre ce choix de jour : ils ne pourraient pas participer. Une raison qui s’oppose à une idée est un contre-argument, ou une objection.'},{exampleFr:'Comment transporter les décors, demande Noé. Je propose quand même de jouer la pièce dans le parc. Nous pourrions emprunter une camionnette.',explanationFr:'Le transport des décors est la difficulté opposée au projet. Emprunter une camionnette est une réponse à cette difficulté. L’objection peut arriver avant la proposition ou prendre la forme d’une question : ne cherche pas seulement le mot mais.'}],
 practice:guides.flatMap((g,i)=>[{id:`counterargument-guided-${i}-answer`,promptFr:`${g.text}\n\n${g.question}`,choices:[g.answer,...g.others],answerFr:g.answer,hintFr:'Repère le projet, puis cherche une difficulté donnée contre ce projet.',explanationFr:`L’objection est : ${g.answer} Le texte dit : « ${g.support} »`},{id:`counterargument-guided-${i}-support`,promptFr:`${g.text}\n\nRecopie la phrase qui exprime cette objection.`,answerFr:g.support,hintFr:'Choisis la difficulté, pas l’avantage du projet ni la solution proposée.',explanationFr:`La phrase qui exprime l’objection est : « ${g.support} »`}]),
 takeawayFr:'Repère l’idée défendue, puis une raison donnée contre elle. Distingue cette objection de la réponse qu’on lui apporte.',boundaryFr:'Une objection ne signifie pas que le projet est impossible ou que l’auteur l’abandonne. Repérer cette raison ne suffit pas à prouver qu’elle est vraie ou convaincante.',materialExposure:{sentences:[...guides.flatMap(g=>[g.text,g.support]),'Organisons un tournoi dimanche pour réunir les classes. Mais certains élèves travaillent avec leur famille ce jour-là.','Comment transporter les décors, demande Noé. Je propose quand même de jouer la pièce dans le parc. Nous pourrions emprunter une camionnette.']}
}];
