/** Original recognition questions with supplied analysis. Selecting an explanation
 * does not establish that the learner can independently write one. */
const cases:Array<[string,string,string,[string,string,string],boolean]>=[
 ["bateau","Le bateau quitte le port.","Dans « Le bateau », bateau est masculin singulier; le déterminant Le s’accorde avec ce nom.",["Dans « Le bateau », Le s’accorde avec quitte, qui est un verbe.","Dans « Le bateau », bateau est au pluriel parce que le bateau se déplace.","Dans « Le bateau », Le ne détermine aucun nom."],false],
 ["fleur","Cette fleur pousse près du mur.","Dans « Cette fleur », fleur est féminin singulier; cette est une forme féminine singulière du déterminant.",["Cette s’accorde avec mur, le dernier nom de la phrase.","Cette est au pluriel parce que la phrase contient deux noms.","Fleur est masculin parce que le mur est masculin."],false],
 ["cahiers","Mes cahiers restent sur la table.","Dans « Mes cahiers », mes marque le pluriel du nom cahiers; cette forme ne distingue pas le masculin du féminin.",["Mes est au pluriel parce que plusieurs personnes possèdent les cahiers.","Mes s’accorde avec table et doit donc être au singulier.","Mes montre à lui seul que cahiers est un nom féminin."],false],
 ["valise","Une petite valise attend dans l’entrée.","Une s’accorde avec le nom valise, féminin singulier, même si petite les sépare.",["Une s’accorde seulement avec petite parce que c’est le mot suivant.","Une s’accorde avec entrée parce que c’est le dernier nom.","Petite empêche tout accord entre une et valise."],false],
 ["arbres","Ces arbres perdent leurs feuilles.","Dans « Ces arbres », ces marque le pluriel du nom arbres sans distinguer son genre.",["Ces s’accorde avec le verbe perdent.","Ces prouve à lui seul que arbres est féminin.","Ces est singulier parce que chaque arbre est considéré séparément."],false],
 ["leur-voiture","Les voisins lavent leur voiture.","Dans « leur voiture », voiture est singulier; leur reste singulier même si les propriétaires sont plusieurs.",["Leur doit prendre s parce que les voisins sont plusieurs.","Leur s’accorde avec lavent, qui est au pluriel.","Voiture est au pluriel parce qu’elle appartient aux voisins."],false],
 ["leurs-voitures","Les voisins lavent leurs voitures.","Dans « leurs voitures », leurs porte un s parce que le nom voitures est au pluriel.",["Le s de leurs dépend seulement du nombre de voisins.","Leurs s’accorde avec le verbe lavent et non avec un nom.","Leurs est toujours singulier même devant plusieurs noms d’objets."],false],
 ["chaque","Chaque élève reçoit une feuille.","Dans « Chaque élève », chaque accompagne le nom élève au singulier : on considère les élèves un par un.",["Chaque impose toujours le pluriel à élève.","Chaque s’accorde avec feuille, placé plus loin.","Chaque est un pronom qui remplace élève dans cette phrase."],false],
 ["plusieurs","Plusieurs pages manquent au dossier.","Plusieurs indique ici le pluriel du nom pages qu’il détermine.",["Plusieurs s’accorde avec dossier, au singulier.","Plusieurs indique seulement que le verbe manque une lettre.","Pages est singulier parce qu’il n’y a qu’un dossier."],false],
 ["musee","Un musée ouvre ses portes.","Dans « Un musée », musée est masculin singulier; un s’accorde avec ce nom malgré sa finale écrite en ée.",["Musée est féminin parce qu’il se termine par ée.","Un s’accorde avec portes et devrait donc être pluriel.","Un est le verbe de ce groupe de mots."],false],
 ["des-filles","Des filles installent la scène.","Dans « Des filles », des marque le pluriel du nom filles; des ne distingue pas à lui seul le genre du nom.",["Des est singulier parce que scène est singulier.","Des indique nécessairement un nom masculin.","Des s’accorde avec installent plutôt qu’avec filles."],false],
 ["ma-maison","Ma maison se trouve près de la gare.","Ma s’accorde avec maison, féminin singulier, et non avec le genre de la personne qui parle.",["Ma signifie obligatoirement que la personne qui parle est une femme.","Ma s’accorde avec gare parce que ce nom vient en dernier.","Ma est au pluriel parce que la phrase parle de deux bâtiments."],false],
 ["sans-nom","Elle sourit.","Il n’y a pas de groupe déterminant-nom ici : Elle est un pronom et sourit est un verbe.",["Elle est un déterminant qui s’accorde avec sourit.","Sourit est un nom déterminé par Elle.","Elle est un nom et sourit est son déterminant."],true],
 ["la-pronom","Je la regarde.","La remplace ici quelqu’un ou quelque chose; c’est un pronom devant le verbe, pas un déterminant devant un nom.",["La détermine le nom regarde et s’accorde avec lui.","La est un déterminant qui s’accorde avec Je.","Regarde est un nom féminin parce qu’il est précédé de la."],true],
 ["les-pronom","Tu les invites.","Les est ici un pronom placé devant le verbe invites; il ne forme pas un groupe déterminant-nom.",["Les s’accorde avec le nom invites.","Tu est le nom déterminé par les.","Les est toujours un déterminant, quel que soit le mot qui suit."],true],
 ["leur-pronom","Nous leur parlons.","Leur est ici un pronom : nous parlons à ces personnes. Aucun nom n’est déterminé par leur dans cette phrase.",["Leur détermine le nom parlons.","Leur doit prendre s parce que nous est au pluriel.","Leur s’accorde avec le nom Nous."],true],
];
export const DETERMINER_AGREEMENT_DRAFTS=cases.map(([key,sentence,answer,distractors,negative])=>({key,sentence,nodeKey:"construction_accord_determinant_nom" as const,prompt:`${sentence}\n\nQuelle analyse de l’accord déterminant-nom est correcte ?`,answer,distractors,negative,reason:answer}));
