/** Identification with an explicit grammatical explanation in each choice.
 * These are review candidates, not evidence of unaided written explanation. */
export type DirectObjectDraft = {
 key: string;
 nodeKey: "identifier_complement_direct";
 prompt: string;
 answer: string;
 distractors: [string, string, string];
 reason: string;
};
const cases: Array<[string, string, string, [string,string,string], string]> = [
 ["manga", "Lina lit un manga.", "« un manga » est le COD : c’est ce que Lina lit.", ["« Lina » est le COD : c’est la personne qui lit.", "« lit » est le COD : ce mot indique l’action.", "Il n’y a pas de COD : la phrase contient seulement un sujet et un verbe."], "Lire quelque chose : un manga complète directement lit; Lina est le sujet."],
 ["person", "Le médecin examine le joueur.", "« le joueur » est le COD : c’est la personne que le médecin examine.", ["« Le médecin » est le COD : c’est la personne qui examine.", "« le joueur » est un complément indirect : il désigne une personne.", "Il n’y a pas de COD : examiner ne peut pas avoir de complément."], "Un complément direct peut désigner une personne; examiner quelqu’un ne demande pas de préposition."],
 ["time", "Chaque matin, Nour prépare son sac.", "« son sac » est le COD : c’est ce que Nour prépare.", ["« Chaque matin » est le COD : ce groupe précise quand Nour prépare son sac.", "« Nour » est le COD : ce nom désigne la personne qui prépare.", "« son sac » est le sujet : c’est le dernier nom de la phrase."], "Chaque matin indique le moment; son sac complète le verbe préparer."],
 ["recipient", "Sami prête sa règle à Inès.", "« sa règle » est le COD : c’est ce que Sami prête.", ["« à Inès » est le COD : c’est la personne à qui Sami prête quelque chose.", "« Sami » est le COD : c’est la personne qui prête.", "« sa règle à Inès » est un seul COD : les deux groupes ont le même rôle."], "Prêter quelque chose à quelqu’un : sa règle est direct, à Inès indique la destinataire."],
 ["place", "Dans la cour, les élèves ramassent les feuilles.", "« les feuilles » est le COD : c’est ce que les élèves ramassent.", ["« Dans la cour » est le COD : ce groupe indique où l’action se déroule.", "« les élèves » est le COD : ce sont les personnes qui ramassent.", "Il n’y a pas de COD : la phrase commence par un lieu."], "La présence d’un lieu en début de phrase ne change pas le rôle de les feuilles."],
 ["negative", "Nous ne regardons pas cette émission.", "« cette émission » est le COD : c’est ce que nous ne regardons pas.", ["« pas » est le COD : il suit le verbe.", "« Nous » est le COD : ce pronom désigne les spectateurs.", "Il n’y a pas de COD : la négation supprime les compléments."], "La négation ne supprime pas la construction regarder quelque chose."],
 ["question", "Quel dessin préfères-tu ?", "« Quel dessin » est le COD : c’est ce que tu préfères.", ["« tu » est le COD : ce pronom est placé après le verbe.", "« Quel dessin » est le sujet : il est placé avant le verbe.", "Il n’y a pas de COD : une question ne peut pas en contenir."], "Le COD interrogatif peut précéder le verbe; tu reste le sujet de préfères."],
 ["noun-group", "Le vent secoue les branches du vieux chêne.", "« les branches du vieux chêne » est le COD : c’est tout le groupe qui désigne ce que le vent secoue.", ["« du vieux chêne » est seul le COD : c’est le dernier groupe de la phrase.", "« Le vent » est le COD : c’est ce qui provoque le mouvement.", "Il n’y a pas de COD : le sujet n’est pas une personne."], "Du vieux chêne complète branches; le COD comprend le groupe nominal entier."],
 ["listen", "Les enfants écoutent leur grand-mère.", "« leur grand-mère » est le COD : c’est la personne que les enfants écoutent.", ["« leur grand-mère » est indirect : tout complément de personne est indirect.", "« Les enfants » est le COD : ce groupe désigne ceux qui écoutent.", "Il n’y a pas de COD : écouter ne peut avoir qu’un complément de lieu."], "Écouter quelqu’un se construit directement, contrairement à parler à quelqu’un."],
 ["quantity", "La boulangère vend trois croissants.", "« trois croissants » est le COD : c’est ce que la boulangère vend.", ["« trois » est seul le COD : un nombre suffit à désigner le complément entier.", "« La boulangère » est le COD : elle réalise la vente.", "Il n’y a pas de COD : un groupe contenant un nombre ne peut pas être COD."], "Le déterminant numéral appartient au groupe nominal trois croissants, complément de vend."],
 ["coordinated", "Malik range ses crayons et sa gomme.", "« ses crayons et sa gomme » est le COD : les deux groupes désignent ce que Malik range.", ["« sa gomme » est seul le COD : seul le dernier groupe peut compléter le verbe.", "« Malik » est le COD : c’est la personne qui range.", "Il n’y a pas de COD : la présence de et empêche un complément direct."], "Deux groupes coordonnés peuvent ensemble remplir la fonction de complément direct."],
 ["perfect", "Vous avez terminé le puzzle.", "« le puzzle » est le COD : c’est ce que vous avez terminé.", ["« terminé » est le COD : il suit avez.", "« Vous » est le COD : ce pronom désigne les personnes qui ont terminé.", "Il n’y a pas de COD : un verbe au passé composé n’en possède pas."], "Avez terminé est le verbe au passé composé; le puzzle complète terminer."],
 ["indirect-only", "Zoé téléphone à son cousin.", "Il n’y a pas de COD : « à son cousin » complète téléphone avec la préposition à.", ["« son cousin » est le COD : il suffit de retirer la préposition à.", "« Zoé » est le COD : c’est la personne qui téléphone.", "« à son cousin » est le COD : tout groupe après un verbe est direct."], "Téléphoner à quelqu’un est une construction indirecte; on ne retire pas à pour changer sa fonction."],
 ["sleep", "Le bébé dort dans sa chambre.", "Il n’y a pas de COD : « dans sa chambre » indique le lieu où le bébé dort.", ["« sa chambre » est le COD : ce nom vient après le verbe.", "« Le bébé » est le COD : c’est la personne qui dort.", "« dans sa chambre » est le COD : tout complément de lieu est direct."], "Dort est ici employé sans complément d’objet; le groupe prépositionnel indique le lieu."],
 ["attribute", "Cette musicienne est célèbre.", "Il n’y a pas de COD : « célèbre » décrit le sujet après le verbe être.", ["« célèbre » est le COD : tout mot après est est un complément d’objet.", "« Cette musicienne » est le COD : ce groupe désigne une personne.", "« est » est le COD : il relie le sujet à sa description."], "Célèbre est un attribut du sujet, et non un objet de être."],
 ["provenance", "Le car arrive de Bruxelles.", "Il n’y a pas de COD : « de Bruxelles » indique la provenance du car.", ["« Bruxelles » est le COD : le nom se trouve après le verbe.", "« Le car » est le COD : c’est ce qui se déplace.", "« de Bruxelles » est le COD : tous les lieux sont des objets du verbe."], "La provenance n’est pas un complément d’objet direct; arrive n’en a pas dans cette phrase."],
];
export const DIRECT_OBJECT_DRAFTS: readonly DirectObjectDraft[] = cases.map(([key,sentence,answer,distractors,reason])=>({
 key,nodeKey:"identifier_complement_direct",prompt:`${sentence}\n\nQuelle analyse du complément d’objet direct (COD) est correcte ?`,answer,distractors,reason,
}));
