import type {TargetTeachingContent} from "./teaching-content";
const cases=[
 {sentence:"Le réparateur démonte la roue avant.",answer:"la roue avant",others:["Le réparateur","avant","Aucun COD"],hint:"Le réparateur démonte quelque chose. Quel groupe désigne cette chose, avec sa précision ?",explanation:"La roue avant est le COD de démonte. Avant précise quelle roue; il fait partie du groupe complet. Le réparateur est le sujet."},
 {sentence:"Aïcha accompagne ses deux frères.",answer:"ses deux frères",others:["Aïcha","deux","Aucun COD"],hint:"On accompagne quelqu’un. Le fait que ce soit une personne ne rend pas le complément indirect.",explanation:"Ses deux frères complète directement accompagne. Ce groupe désigne des personnes, mais aucune préposition ne le relie au verbe."},
 {sentence:"Ce soir, le cuisinier apporte la soupe aux invités.",answer:"la soupe",others:["Ce soir","aux invités","le cuisinier"],hint:"Distingue ce qu’il apporte, les personnes à qui il l’apporte et le moment.",explanation:"La soupe est ce qu’il apporte : c’est le COD. Aux invités indique les destinataires; ce soir indique le moment. Le cuisinier est le sujet."},
 {sentence:"Quels livres emprunte la journaliste ?",answer:"Quels livres",others:["la journaliste","emprunte","Aucun COD"],hint:"La journaliste emprunte quelque chose. La question porte sur cette chose.",explanation:"Quels livres est le COD de emprunte, même devant le verbe. La journaliste est le sujet, placé ici après le verbe."},
 {sentence:"Le chat ne touche pas les bottes de sa maîtresse.",answer:"les bottes de sa maîtresse",others:["sa maîtresse","Le chat","Aucun COD"],hint:"La négation ne change pas ce que complète toucher. Garde tout le groupe qui désigne les objets.",explanation:"Les bottes de sa maîtresse est le COD complet. De sa maîtresse précise bottes; il ne rend pas tout le groupe indirect. Ne…pas nie l’action sans supprimer le COD."},
 {sentence:"La capitaine répond à son entraîneuse.",answer:"Aucun COD",others:["à son entraîneuse","La capitaine","son entraîneuse"],hint:"La construction est répondre à quelqu’un. Ne retire pas à pour analyser le groupe.",explanation:"À son entraîneuse est un complément indirect de répond. La capitaine est le sujet. Cette phrase n’a donc pas de COD."},
 {sentence:"Le tissu semble doux.",answer:"Aucun COD",others:["doux","Le tissu","semble"],hint:"Doux décrit-il un objet sur lequel on agit, ou une propriété du tissu ?",explanation:"Doux décrit le sujet Le tissu après semble : c’est un attribut du sujet. Ce n’est pas un objet du verbe, même si l’adjectif suit le verbe."},
 {sentence:"Les randonneuses marchent près du lac.",answer:"Aucun COD",others:["près du lac","Les randonneuses","du lac"],hint:"Près du lac situe l’action. Il ne désigne pas ce que les randonneuses marchent.",explanation:"Près du lac indique le lieu. Les randonneuses est le sujet. Marchent n’a pas de complément d’objet direct dans cette phrase."},
];
const lesson:TargetTeachingContent={
 id:"french-v3-teaching:identifier_complement_direct",nodeKey:"identifier_complement_direct",mode:"recognition",status:"draft_requires_review",
 titleFr:"Trouver ce qui complète directement le verbe",learnerQuestionFr:"Dans « Nora photographie un pont », quel groupe dit ce qu’elle photographie ?",
 steps:[
  {exampleFr:"Nora photographie un pont. Nora photographie son amie.",explanationFr:"Un pont et son amie disent ce que Nora photographie ou qui elle photographie. Ils complètent le verbe sans préposition comme à ou de : on les appelle compléments d’objet directs, ou COD. Un COD peut désigner une chose ou une personne. Nora est le sujet : c’est elle qui photographie."},
  {exampleFr:"Nora offre une photo à sa tante.",explanationFr:"Une photo désigne ce que Nora offre : c’est le COD. À sa tante indique à qui elle l’offre : ce complément est relié au verbe par à, il est indirect. Cherche le lien de chaque groupe avec le verbe, plutôt que de choisir tous les mots placés après lui."},
  {exampleFr:"Quelle photo Nora choisit-elle ? Nora choisit la photo du vieux phare.",explanationFr:"Quelle photo est le COD dans la question, même devant le verbe. Dans la réponse, le COD complet est la photo du vieux phare. Du vieux phare précise photo à l’intérieur du groupe : le lien du groupe entier avec choisit reste direct."},
  {exampleFr:"Nora est contente. Nora sourit sur le balcon.",explanationFr:"Contente décrit Nora après est : c’est un attribut du sujet, pas un COD. Sur le balcon indique un lieu dans la deuxième phrase. Ces phrases n’ont pas de COD. La question qui ou quoi après un verbe peut aider, mais elle ne suffit pas : vérifie toujours la construction et le rôle du groupe."},
 ],
 takeawayFr:"Repère le verbe et son sujet. Cherche ce qui complète ce verbe directement, sans confondre l’objet avec le sujet, un lieu ou une description du sujet. Un COD peut venir avant le verbe; garde ses précisions si on demande le groupe complet. Il peut aussi n’y avoir aucun COD.",
 boundaryFr:"Nous travaillons ici des COD constitués de groupes nominaux dans des phrases courtes. Les pronoms COD, les propositions qui remplissent cette fonction et l’accord du participe passé demandent d’autres activités. Repérer un COD ne prouve pas encore que tu sais le remplacer par le, la, l’ ou les.",
 practice:cases.map((item,index)=>({id:`direct-object-guide-${index+1}`,promptFr:`${item.sentence}\n\nQuel est le COD complet ? S’il n’y en a pas, choisis « Aucun COD ».`,choices:[item.answer,...item.others],answerFr:item.answer,hintFr:item.hint,explanationFr:item.explanation})),
};
export const DIRECT_OBJECT_TEACHING:readonly TargetTeachingContent[]=[{...lesson,materialExposure:{sentences:[...lesson.steps.flatMap(step=>step.exampleFr.split(/(?<=[.!?])\s+/)),...cases.map(item=>item.sentence)]}}];
