import type {TargetTeachingContent} from "./teaching-content";
type Passage={text:string;question:string;answer:string;others:string[];support:string;otherSpans:string[]};
const narratives:readonly Passage[]=[
 {text:"Zoé apporte des biscuits à la répétition. Elle pose la boîte sur le piano fermé. Ensuite, elle rejoint le groupe près de la scène.",question:"Où Zoé pose-t-elle la boîte ?",answer:"Sur le piano fermé.",others:["Près de la scène.","Dans un placard.","Sur une chaise."],support:"Elle pose la boîte sur le piano fermé.",otherSpans:["Zoé apporte des biscuits à la répétition.","Ensuite, elle rejoint le groupe près de la scène."]},
 {text:"Le matin, Yacine cherche ses lunettes dans sa chambre. Sa petite sœur les retrouve derrière un coussin du canapé. Yacine les prend et sort rejoindre son père.",question:"Qui retrouve les lunettes ?",answer:"La petite sœur de Yacine.",others:["Yacine.","Le père de Yacine.","Un voisin."],support:"Sa petite sœur les retrouve derrière un coussin du canapé.",otherSpans:["Le matin, Yacine cherche ses lunettes dans sa chambre.","Yacine les prend et sort rejoindre son père."]},
 {text:"Le club prépare un jeu de piste. Hugo cache quatre enveloppes dans le jardin. Il garde la dernière carte dans sa poche pour expliquer les règles.",question:"Combien d’enveloppes Hugo cache-t-il ?",answer:"Quatre enveloppes.",others:["Une enveloppe.","Trois enveloppes.","Cinq enveloppes."],support:"Hugo cache quatre enveloppes dans le jardin.",otherSpans:["Le club prépare un jeu de piste.","Il garde la dernière carte dans sa poche pour expliquer les règles."]},
];
const argumentativePassages:readonly Passage[]=[
 {text:"Un atelier de réparation aiderait à prolonger la vie de nos objets. Je propose de l’organiser le premier vendredi de chaque mois. Les participants pourraient apprendre à réparer une petite panne avant de remplacer leur appareil.",question:"Quand l’atelier est-il proposé ?",answer:"Le premier vendredi de chaque mois.",others:["Tous les vendredis.","Le dernier lundi de chaque mois.","Une fois par an."],support:"Je propose de l’organiser le premier vendredi de chaque mois.",otherSpans:["Un atelier de réparation aiderait à prolonger la vie de nos objets.","Les participants pourraient apprendre à réparer une petite panne avant de remplacer leur appareil."]},
 {text:"Les élèves devraient pouvoir exposer leurs créations pour partager leurs idées. Le hall du deuxième étage pourrait accueillir les dessins. Cet endroit permettrait de les voir en passant d’un cours à l’autre.",question:"Quel endroit est proposé pour les dessins ?",answer:"Le hall du deuxième étage.",others:["La salle de sport.","Le hall du rez-de-chaussée.","La cour derrière le bâtiment."],support:"Le hall du deuxième étage pourrait accueillir les dessins.",otherSpans:["Les élèves devraient pouvoir exposer leurs créations pour partager leurs idées.","Cet endroit permettrait de les voir en passant d’un cours à l’autre."]},
 {text:"Créer un potager permettrait de mieux comprendre la croissance des plantes. Nous demandons cinq grandes jardinières pour commencer. Un petit espace bien entretenu serait plus facile à suivre qu’un vaste terrain laissé à l’abandon.",question:"Combien de jardinières sont demandées ?",answer:"Cinq grandes jardinières.",others:["Deux grandes jardinières.","Quatre grandes jardinières.","Dix grandes jardinières."],support:"Nous demandons cinq grandes jardinières pour commencer.",otherSpans:["Créer un potager permettrait de mieux comprendre la croissance des plantes.","Un petit espace bien entretenu serait plus facile à suivre qu’un vaste terrain laissé à l’abandon."]},
];
function practice(genre:string,passages:readonly Passage[]):TargetTeachingContent['practice']{
 return passages.flatMap((p,index)=>[
 {id:`explicit-${genre}-guide-${index+1}-answer`,promptFr:`${p.text}\n\n${p.question}`,choices:[p.answer,...p.others],answerFr:p.answer,hintFr:"Repère ce que demande le mot où, qui, quand ou combien, puis retrouve l’information correspondante dans le texte.",explanationFr:`Le texte dit : « ${p.support} » La réponse est donc : ${p.answer}`},
 {id:`explicit-${genre}-guide-${index+1}-support`,promptFr:`${p.text}\n\nQuelle phrase du texte permet de répondre à la question : « ${p.question} » ?`,choices:[p.support,...p.otherSpans],answerFr:p.support,hintFr:"Choisis la phrase qui contient précisément l’information demandée, pas seulement une phrase sur le même sujet.",explanationFr:`« ${p.support} » contient l’information demandée. Les autres phrases donnent des éléments différents.`},
 ]);
}
const lessons:TargetTeachingContent[]=[
 {id:"french-v3-teaching:explicit-reading:narrative",nodeKey:"localiser_information_explicite",facetKey:"localiser_information_explicite::text_type:narrative",mode:"interpretation",status:"draft_requires_review",titleFr:"Retrouver une information dans un récit",learnerQuestionFr:"Comment retrouver où un personnage a posé son sac ?",
 steps:[
 {exampleFr:"Inaya entre dans l’atelier. Elle pose son sac sous la table rouge. Puis elle prend un pinceau.",explanationFr:"La question Où Inaya pose-t-elle son sac ? demande un lieu. La deuxième phrase donne ce lieu directement : sous la table rouge. Une information écrite directement dans le texte est une information explicite."},
 {exampleFr:"Elle pose son sac sous la table rouge.",explanationFr:"Reviens à cette phrase pour vérifier ta réponse. Sous la table rouge répond à où. Dire dans l’atelier est moins précis, même si l’atelier est mentionné ailleurs."},
 {exampleFr:"Puis elle prend un pinceau.",explanationFr:"Cette phrase explique ce qui arrive ensuite. Elle ne dit pas où est posé le sac. Deux phrases peuvent parler du même personnage sans répondre à la même question."},
 ],takeawayFr:"Lis exactement la question. Cherche la personne, le lieu, le moment ou la quantité demandée, puis retrouve la phrase qui le dit. Réponds sans ajouter de détail inventé.",boundaryFr:"Cette leçon travaille ce que le récit dit directement. Si une cause ou une intention n’est pas écrite, il faut parfois faire une déduction : c’est une autre opération. Une information absente ne peut pas être retrouvée en choisissant au hasard.",practice:practice("narrative",narratives)},
 {id:"french-v3-teaching:explicit-reading:argumentative",nodeKey:"localiser_information_explicite",facetKey:"localiser_information_explicite::text_type:argumentative",mode:"interpretation",status:"draft_requires_review",titleFr:"Retrouver un détail dans un texte qui défend une idée",learnerQuestionFr:"Dans une proposition pour le collège, comment retrouver exactement ce qui est demandé ?",
 steps:[
 {exampleFr:"Installer des bancs rendrait l’attente plus agréable. Je propose deux bancs près du préau. Les élèves pourraient s’y asseoir à l’abri de la pluie.",explanationFr:"L’auteur défend une proposition : c’est un texte argumentatif. Si on demande Combien de bancs sont proposés ?, la réponse est écrite directement dans la deuxième phrase : deux. Il n’est pas nécessaire de donner son avis sur la proposition."},
 {exampleFr:"Je propose deux bancs près du préau.",explanationFr:"Cette phrase contient plusieurs détails explicites : deux répond à combien, et près du préau répond à où. Sélectionne le détail que la question demande."},
 {exampleFr:"Les élèves pourraient s’y asseoir à l’abri de la pluie.",explanationFr:"Cette phrase donne un avantage attendu. Elle ne change pas la quantité annoncée et ne prouve pas que les bancs sont déjà installés. Garde la différence entre une proposition et un fait accompli."},
 ],takeawayFr:"Même dans un texte qui défend une idée, une question peut demander un simple détail. Retrouve la phrase qui donne ce détail, sans remplacer la réponse par ton opinion ou une supposition.",boundaryFr:"Retrouver un détail ne suffit pas à identifier toute la thèse, à juger la solidité des arguments ou à vérifier leurs affirmations dans le monde réel. Ici, on relève ce que le texte affirme ou propose.",practice:practice("argumentative",argumentativePassages)},
];
export const EXPLICIT_READING_TEACHING:readonly TargetTeachingContent[]=lessons.map((lesson,index)=>({...lesson,materialExposure:{sentences:[...lesson.steps.map(s=>s.exampleFr),...[narratives,argumentativePassages][index].flatMap(p=>[p.text,p.support,...p.otherSpans])]}}));
