/** Original fictional short texts. Questions ask for stated facts, not inference. */
const narrative:readonly [string,string,string,string,string,string,readonly string[]][]=[
 ["manga-return","Nora entre à la bibliothèque avec deux mangas dans son sac.","Elle dépose les livres dans la boîte bleue près de la porte.","Puis elle rejoint son amie au rayon des romans.","Où Nora dépose-t-elle les livres ?","Dans la boîte bleue près de la porte.",["Sur une table au rayon des romans.","Dans le sac de son amie.","Derrière le comptoir de la bibliothèque."]],
 ["bus-departure","Adam arrive au terminus avant son frère.","Leur bus part à huit heures quinze.","Pendant qu’il attend, Adam achète une bouteille d’eau.","À quelle heure le bus part-il ?","À huit heures quinze.",["À huit heures.","À huit heures trente.","À neuf heures quinze."]],
 ["cake-delivery","Le gâteau est enfin prêt pour la fête.","Maya confie la boîte à son cousin Idriss.","Elle ferme ensuite les fenêtres de la cuisine et prend ses clés.","À qui Maya confie-t-elle la boîte ?","À son cousin Idriss.",["À sa sœur.","À un voisin.","À la personne qui a préparé le gâteau."]],
 ["lost-glove","Après la répétition, Éli cherche son gant rouge.","Il le retrouve sous le banc du vestiaire.","Il range le gant dans sa poche et court rejoindre les autres dehors.","Où Éli retrouve-t-il son gant ?","Sous le banc du vestiaire.",["Dans sa poche.","Dehors près de la porte.","Sur une chaise de la salle de répétition."]],
 ["garden-seeds","Samira ouvre le petit sachet offert par sa tante.","Elle plante six graines dans un pot en terre.","Elle arrose le pot, puis le pose sur le rebord de la fenêtre.","Combien de graines Samira plante-t-elle ?","Six graines.",["Trois graines.","Cinq graines.","Dix graines."]],
 ["repair-bike","Le vélo de Tom fait un bruit étrange.","Sa voisine resserre une vis près de la roue arrière.","Tom essaie ensuite le vélo dans l’allée et lui dit merci.","Que resserre la voisine ?","Une vis près de la roue arrière.",["Une vis sur le guidon.","La selle du vélo.","Le bouchon d’une roue."]],
 ["draw-prize","Les dessins du concours sont exposés dans le couloir.","Le jury remet à Lina un carnet à couverture verte.","Elle montre son prix à ses camarades avant de retourner en classe.","Quel prix Lina reçoit-elle ?","Un carnet à couverture verte.",["Une boîte de crayons.","Un livre de dessin.","Une affiche pour sa classe."]],
 ["rain-shelter","La pluie surprend Amine au retour du marché.","Il s’abrite sous l’auvent de la boulangerie.","Quand les gouttes deviennent moins fortes, il reprend son chemin avec ses achats.","Où Amine s’abrite-t-il ?","Sous l’auvent de la boulangerie.",["Dans une voiture.","Sous un arbre du marché.","À l’intérieur de son immeuble."]],
];
const argumentative:typeof narrative=[
 ["library-hours","La bibliothèque devrait ouvrir un peu plus tard pour les élèves qui terminent leurs cours après seize heures.","Je propose une fermeture à dix-huit heures le mercredi.","Cette ouverture supplémentaire laisserait davantage de temps pour emprunter un livre.","Quel jour la fermeture à dix-huit heures est-elle proposée ?","Le mercredi.",["Le lundi.","Le vendredi.","Le samedi."]],
 ["water-taps","Installer des points d’eau dans la cour permettrait aux élèves de remplir leurs gourdes.","Notre groupe demande deux robinets près du gymnase.","Ce changement pourrait réduire le nombre de bouteilles jetées après le sport.","Combien de robinets le groupe demande-t-il ?","Deux robinets.",["Un robinet.","Trois robinets.","Quatre robinets."]],
 ["quiet-room","Un lieu calme serait utile aux élèves qui veulent lire pendant la pause.","Je propose d’utiliser la petite salle à côté du bureau des surveillants.","On pourrait y limiter les conversations pour que chacun puisse se concentrer.","Quelle salle est proposée ?","La petite salle à côté du bureau des surveillants.",["La salle à côté du gymnase.","La salle des professeurs.","La grande salle au-dessus de la cantine."]],
 ["games-loan","Le prêt de jeux de société rendrait les pauses pluvieuses plus agréables.","Le conseil des élèves pourrait gérer les emprunts.","Les élèves apprendraient ainsi à partager le matériel et à le rendre en bon état.","Qui pourrait gérer les emprunts ?","Le conseil des élèves.",["Les parents uniquement.","Le club de théâtre.","Les commerçants du quartier."]],
 ["tree-yard","La cour manque d’ombre pendant les journées chaudes.","Nous proposons de planter trois arbres le long du mur sud.","Des arbres rendraient cet espace plus agréable sans empêcher les jeux au centre de la cour.","Où les arbres seraient-ils plantés ?","Le long du mur sud.",["Au centre de la cour.","Devant la porte du gymnase.","Dans la rue derrière l’école."]],
 ["manga-club","Un club de manga peut donner envie de lire et d’échanger des avis.","Les rencontres pourraient avoir lieu une fois par mois.","Chaque participant présenterait un livre afin de faire découvrir des histoires variées.","À quelle fréquence les rencontres sont-elles proposées ?","Une fois par mois.",["Tous les jours.","Deux fois par semaine.","Une fois par an."]],
 ["bike-space","Les vélos rangés devant l’entrée gênent parfois le passage.","Je propose de déplacer les supports derrière le bâtiment principal.","Cette solution laisserait l’entrée libre tout en conservant une place pour les cyclistes.","Où faudrait-il déplacer les supports ?","Derrière le bâtiment principal.",["Devant l’entrée.","Au milieu du terrain de sport.","Dans le hall du bâtiment."]],
 ["reuse-paper","Nous devrions réutiliser les feuilles imprimées sur une seule face pour les brouillons.","Une boîte de collecte pourrait être installée dans chaque salle de classe.","Ce geste simple éviterait de prendre une feuille neuve pour chaque essai.","Où une boîte de collecte serait-elle installée ?","Dans chaque salle de classe.",["Uniquement à la bibliothèque.","Dans la cour.","Chez chaque élève."]],
];
export const EXPLICIT_READING_DRAFTS=([['narrative',narrative],['argumentative',argumentative]] as const).flatMap(([genre,rows])=>rows.map(([key,before,support,after,question,answer,distractors])=>({key,genre,nodeKey:"localiser_information_explicite",passage:[before,support,after].join(' '),support,otherSpans:[before,after],question,answer,distractors,reason:"Retrouver une information directement énoncée et sélectionner la phrase qui la contient, sans déduire une cause ou une intention."})));
