import type {TargetTeachingContent} from './teaching-content';
type Pair={key:string;title:string;example:string;explain:string;method:string;boundary:string;cases:readonly [string,string,string][]};
const pairs:readonly Pair[]=[
 {key:'a_a',title:'a ou à',example:'Nora a un vélo. Nora va à la piscine.',explain:'Dans la première phrase, a est une forme du verbe avoir : Nora avait un vélo reste possible. Dans la seconde, à relie va au lieu. Va avait la piscine ne fonctionne pas.',method:'Essaie avait à la place du mot. Si la phrase reste construite correctement, choisis a. Sinon, examine le lien introduit par à.',boundary:'Ce test change le temps de la phrase. Il sert à repérer avoir, pas à conserver exactement le même moment.',cases:[['Le groupe ___ terminé son affiche.','a','Avait terminé est possible : a est ici le verbe avoir.'],['Tu pars ___ vélo.','à','Pars avait vélo ne fonctionne pas. À introduit la manière de se déplacer.'],['Cette veste ___ une poche intérieure.','a','Cette veste avait une poche intérieure est une phrase correctement construite.'],['Le cours commence ___ dix heures.','à','À introduit une heure ; ce n’est pas le verbe avoir.']]},
 {key:'et_est',title:'et ou est',example:'Le chat est calme. Le chat et le chien dorment.',explain:'Est est une forme du verbe être : le chat était calme. Et relie ici deux noms : le chat et le chien.',method:'Essaie était pour repérer le verbe être. Si le mot relie deux éléments, et peut convenir : les deux éléments restent présents.',boundary:'Ne choisis pas seulement au son. Était ne remplace pas une liaison entre deux mots.',cases:[['La porte ___ lourde.','est','La porte était lourde garde une construction correcte.'],['Nous prenons du papier ___ de la colle.','et','Et relie les deux fournitures.'],['Mon frère ___ arrivé tôt.','est','Était arrivé est possible : est aide ici à former le passé composé.'],['Le tissu est doux ___ léger.','et','Et relie les deux qualités doux et léger.']]},
 {key:'son_sont',title:'son ou sont',example:'Lina cherche son sac. Les sacs sont prêts.',explain:'Son accompagne le nom sac et indique à qui il est associé. Sont est le verbe être avec un sujet au pluriel : les sacs étaient prêts.',method:'Essaie étaient pour repérer sont. Devant un nom, essaie mon ou ton pour reconnaître son.',boundary:'Son peut précéder un nom féminin commençant par une voyelle, comme son amie. Le genre du propriétaire ne décide pas de cette forme.',cases:[['Les lumières ___ éteintes.','sont','Les lumières étaient éteintes est possible.'],['Amir retrouve ___ manteau.','son','Son accompagne manteau ; mon manteau est aussi un groupe possible.'],['Ces chemins ___ glissants.','sont','Sont est le verbe être avec ces chemins.'],['Elle attend ___ amie.','son','Devant amie, on emploie son. Cela ne signifie pas que l’amie est un garçon.']]},
 {key:'on_ont',title:'on ou ont',example:'On ferme la fenêtre. Les voisins ont froid.',explain:'On occupe la place du sujet, comme il dans il ferme. Ont est une forme d’avoir : les voisins avaient froid.',method:'Essaie avaient pour reconnaître ont. Si le mot est le sujet d’un verbe à la troisième personne du singulier, on peut convenir.',boundary:'On peut désigner plusieurs personnes, mais le verbe qui le suit se conjugue au singulier.',cases:[['___ écoute la consigne.','On','On est le sujet de écoute.'],['Les joueurs ___ gagné.','ont','Les joueurs avaient gagné est possible.'],['Ce soir, ___ cuisine ensemble.','on','On est le sujet de cuisine, même si plusieurs personnes participent.'],['Ces oiseaux ___ un long bec.','ont','Avaient un long bec est possible : il s’agit d’avoir.']]},
 {key:'ce_se',title:'ce ou se',example:'Ce garçon se prépare.',explain:'Ce accompagne le nom garçon et le désigne. Se accompagne ici le verbe se préparer et renvoie au sujet qui se prépare.',method:'Regarde le rôle du mot. Ce peut accompagner un nom. Se appartient à une construction verbale : je me prépare, il se prépare.',boundary:'Ce peut aussi être un pronom, comme dans ce sera utile. Ne transforme donc pas le repère devant un nom en règle absolue.',cases:[['___ carnet est neuf.','Ce','Ce désigne le carnet.'],['Le chien ___ couche.','se','Le verbe est se coucher : le chien se couche.'],['___ sera une belle journée.','Ce','Ce est ici un pronom, sujet de sera.'],['Les élèves ___ saluent.','se','Se accompagne saluent : les élèves se saluent les uns les autres.']]},
 {key:'ces_ses',title:'ces ou ses',example:'Regarde ces chaussures-ci. Léa range ses propres chaussures.',explain:'Ces désigne les chaussures que l’on montre. Ses relie les chaussures à Léa, comme les siennes. Le contexte doit permettre de choisir.',method:'Cherche si le texte montre des choses ou les relie à quelqu’un. Pour le singulier, ces correspond à ce, cet ou cette ; ses correspond à son ou sa.',boundary:'Sans contexte, ces chaussures et ses chaussures peuvent tous les deux être corrects. Il ne faut pas inventer l’intention du texte.',cases:[['Je montre deux affiches : regarde ___ affiches-ci.','ces','Le texte désigne les affiches montrées.'],['Mina possède deux rollers. Elle lace ___ propres rollers.','ses','Les rollers sont associés à Mina ; ce sont les siens.'],['Tu désignes trois photos : ___ photos-là sont floues.','ces','Photos-là reprend les photos désignées.'],['Ces livres appartiennent à Paul : ce sont ___ livres à lui.','ses','Le contexte indique à qui les livres appartiennent.']]},
 {key:'ou_ou',title:'ou ou où',example:'Tu préfères le thé ou le jus ? Où est la tasse ?',explain:'Ou propose un choix entre deux boissons. Où demande ici un lieu : l’endroit où se trouve la tasse.',method:'Essaie ou bien pour reconnaître le choix écrit ou. Où peut désigner un lieu ou un moment.',boundary:'Où ne concerne pas uniquement les lieux : on écrit aussi le jour où nous sommes partis.',cases:[['Veux-tu écrire ___ dessiner ?','ou','Ou bien convient : il s’agit d’un choix.'],['Voici la salle ___ nous répétons.','où','Où reprend un lieu, la salle.'],['Tu peux venir lundi ___ mardi.','ou','Le texte propose deux possibilités.'],['Je me souviens du jour ___ il a neigé.','où','Où reprend ici un moment, le jour.']]},
];
export const HOMOPHONE_TEACHING:readonly TargetTeachingContent[]=pairs.flatMap(pair=>(['recognition','production'] as const).map(mode=>({
 id:`french-v3-teaching:homophone:${pair.key}:${mode}`,nodeKey:`distinguer_homophones_${pair.key}`,mode,status:'draft_requires_review' as const,titleFr:`${mode==='recognition'?'Choisir':'Écrire'} ${pair.title}`,learnerQuestionFr:`Comment choisir entre ${pair.title} dans une phrase ?`,steps:[{exampleFr:pair.example,explanationFr:pair.explain},{exampleFr:pair.cases[0][0].replace('___',pair.cases[0][1]),explanationFr:pair.method}],practice:pair.cases.map(([sentence,answer,why],i)=>({id:`guided:homophone:${pair.key}:${mode}:${i+1}`,promptFr:`${sentence}\n${mode==='recognition'?'Choisis':'Écris'} le mot qui convient.`,...(mode==='recognition'?{choices:pair.title.split(' ou ').map(word=>answer[0]===answer[0].toUpperCase()?word[0].toUpperCase()+word.slice(1):word)}:{}),answerFr:answer,hintFr:pair.method,explanationFr:`${sentence.replace("___",answer)} ${why}`})),takeawayFr:pair.method,boundaryFr:pair.boundary,materialExposure:{words:pair.title.split(" ou ").map(word=>({lemma:word,form:word})),sentences:[pair.example,...pair.cases.flatMap(([sentence,answer])=>[sentence,sentence.replace('___',answer)])]},
})));
