import {conjugate,type Person} from '@/lib/linguistic/conjugation';
type ImperativePerson=Extract<Person,'2s'|'1p'|'2p'>;
const contexts:readonly [string,ImperativePerson,string][]=[
 ['parler','2s','___ moins fort près du dortoir.'],
 ['écouter','2s','___ le message laissé sur le répondeur.'],
 ['regarder','2s','___ la date sur le ticket.'],
 ['chercher','2s','___ ton nom dans cette liste.'],
 ['préparer','1p','___ un goûter pour les visiteurs.'],
 ['jouer','1p','___ la dernière scène une seconde fois.'],
 ['travailler','1p','___ à deux sur cette énigme.'],
 ['rester','1p','___ dans le hall pendant la pluie.'],
 ['porter','2p','___ vos badges pendant la visite.'],
 ['dessiner','2p','___ le plan de votre quartier.'],
 ['raconter','2p','___ vos découvertes à la classe.'],
 ['aider','2p','___ les nouveaux élèves à trouver la bibliothèque.'],
 ['finir','2s','___ ton puzzle avant de ranger la boîte.'],
 ['choisir','2s','___ le livre que tu veux emprunter.'],
 ['remplir','2s','___ la fiche avec ton prénom.'],
 ['ralentir','2s','___ avant le virage au bout de la piste.'],
 ['réfléchir','1p','___ à un nom pour notre équipe.'],
 ['applaudir','1p','___ les bénévoles pour leur travail.'],
 ['choisir','1p','___ ensemble le prochain jeu.'],
 ['finir','1p','___ la décoration de notre stand.'],
 ['remplir','2p','___ vos paniers avec les pommes tombées.'],
 ['réfléchir','2p','___ à la question avant de lever la main.'],
 ['ralentir','2p','___ pour laisser passer les piétons.'],
 ['applaudir','2p','___ la troupe après le dernier salut.'],
 ['manger','2s','___ ton sandwich avant la séance.'],
 ['ranger','2s','___ ces photos dans le bon album.'],
 ['changer','2s','___ la pile de cette lampe.'],
 ['bouger','2s','___ ton pion de deux cases.'],
 ['partager','1p','___ nos idées avant de voter.'],
 ['mélanger','1p','___ la farine et le sucre dans ce saladier.'],
 ['ranger','1p','___ nos instruments après le concert.'],
 ['changer','1p','___ de chemin pour éviter les travaux.'],
 ['nager','2p','___ le long du bord du bassin.'],
 ['manger','2p','___ vos fruits après la randonnée.'],
 ['partager','2p','___ les cartes entre tous les joueurs.'],
 ['bouger','2p','___ les épaules pour vous détendre.'],
 ['bouger','1p','___ cette table pour dégager le passage.'],
 ['nager','1p','___ ensemble jusqu’au ponton.'],
 ['manger','1p','___ sur la terrasse après le match.'],
 ['partager','1p','___ les frais du cadeau.'],
 ['mélanger','1p','___ les équipes pour la deuxième manche.'],
 ['ranger','1p','___ nos vélos sous cet abri.'],
 ['lancer','2s','___ la balle vers le panier vide.'],
 ['placer','2s','___ cette étiquette sous le dessin.'],
 ['effacer','2s','___ le calcul écrit dans la marge.'],
 ['avancer','2s','___ jusqu’à la porte ouverte.'],
 ['commencer','1p','___ par lire les règles du tournoi.'],
 ['avancer','1p','___ vers le prochain arrêt.'],
 ['placer','1p','___ les chaises autour de notre table.'],
 ['lancer','1p','___ notre appel à volontaires.'],
 ['tracer','2p','___ une ligne sous chaque titre.'],
 ['commencer','2p','___ vos exposés par une question.'],
 ['effacer','2p','___ les traces sur vos ardoises.'],
 ['placer','2p','___ vos sacs sur les étagères.'],
 ['effacer','1p','___ notre schéma avant le prochain cours.'],
 ['tracer','1p','___ ensemble le parcours sur la carte.'],
 ['commencer','1p','___ notre repas pendant que la soupe est chaude.'],
 ['placer','1p','___ notre panneau près de l’entrée.'],
 ['avancer','1p','___ nos pions chacun notre tour.'],
 ['lancer','1p','___ la musique pour notre échauffement.'],
];
export const IMPERATIF_FAMILY_APPLICATIONS=contexts.map(([verb,person,sentence],i)=>({
 verb,person,sentence,answer:conjugate(verb,'imperatif_present',person),
 family:i<12?'regular_er':i<24?'regular_ir':i<42?'spelling_ger':'spelling_cer',
 audience:person==='2s'?'Tu t’adresses à une personne que tu tutoies.':person==='1p'?'Tu proposes une action à faire ensemble, toi compris.':'Tu t’adresses à plusieurs personnes.',
}));
