import type {TargetTeachingContent} from './teaching-content';
type Row={key:string;passage:string;pronoun:string;sentence:string;answer:string;distractors:[string,string,string];support:string;otherSpans:[string,string]};
const rows:Row[]=[
 {key:'ticket',passage:'Pour visiter la tour, chaque personne reçoit un billet à l’accueil. Il doit être conservé jusqu’à la sortie. La visite dure vingt minutes.',pronoun:'Il',sentence:'Il doit être conservé jusqu’à la sortie.',answer:'un billet',distractors:['l’accueil','la tour','chaque personne'],support:'Pour visiter la tour, chaque personne reçoit un billet à l’accueil.',otherSpans:['Il doit être conservé jusqu’à la sortie.','La visite dure vingt minutes.']},
 {key:'map',passage:'Une carte est fournie aux visiteurs au début du parcours. Elle indique les chemins accessibles à pied. Des panneaux complètent les indications.',pronoun:'Elle',sentence:'Elle indique les chemins accessibles à pied.',answer:'une carte',distractors:['les chemins','les visiteurs','des panneaux'],support:'Une carte est fournie aux visiteurs au début du parcours.',otherSpans:['Elle indique les chemins accessibles à pied.','Des panneaux complètent les indications.']},
 {key:'headphones',passage:'Le laboratoire prête des casques aux élèves pour écouter les enregistrements. Ils doivent être rendus dans leur boîte après utilisation. Un adulte vérifie le matériel.',pronoun:'Ils',sentence:'Ils doivent être rendus dans leur boîte après utilisation.',answer:'des casques',distractors:['les élèves','les enregistrements','un adulte'],support:'Le laboratoire prête des casques aux élèves pour écouter les enregistrements.',otherSpans:['Ils doivent être rendus dans leur boîte après utilisation.','Un adulte vérifie le matériel.']},
 {key:'lamps',passage:'Des lampes sont installées près des tables dans la salle de lecture. Elles s’allument grâce au bouton situé sur leur pied. Les lecteurs peuvent choisir une place libre.',pronoun:'Elles',sentence:'Elles s’allument grâce au bouton situé sur leur pied.',answer:'des lampes',distractors:['les tables','la salle de lecture','les lecteurs'],support:'Des lampes sont installées près des tables dans la salle de lecture.',otherSpans:['Elles s’allument grâce au bouton situé sur leur pied.','Les lecteurs peuvent choisir une place libre.']},
 {key:'volunteer',passage:'Un bénévole remet un plan aux nouveaux membres de l’association. Il répond ensuite à leurs questions sur les activités. Les inscriptions ont lieu dans le hall.',pronoun:'Il',sentence:'Il répond ensuite à leurs questions sur les activités.',answer:'un bénévole',distractors:['un plan','les nouveaux membres','le hall'],support:'Un bénévole remet un plan aux nouveaux membres de l’association.',otherSpans:['Il répond ensuite à leurs questions sur les activités.','Les inscriptions ont lieu dans le hall.']},
 {key:'librarian',passage:'La bibliothécaire présente une revue aux membres du club. Elle conseille aussi les personnes qui cherchent un roman. Le prêt est limité à trois documents.',pronoun:'Elle',sentence:'Elle conseille aussi les personnes qui cherchent un roman.',answer:'la bibliothécaire',distractors:['une revue','les personnes','un roman'],support:'La bibliothécaire présente une revue aux membres du club.',otherSpans:['Elle conseille aussi les personnes qui cherchent un roman.','Le prêt est limité à trois documents.']},
 {key:'guides',passage:'Les guides distribuent des livrets aux visiteurs du château. Ils conduisent ensuite le groupe dans les salles ouvertes au public. Les livrets contiennent un plan.',pronoun:'Ils',sentence:'Ils conduisent ensuite le groupe dans les salles ouvertes au public.',answer:'les guides',distractors:['des livrets','les visiteurs','les salles'],support:'Les guides distribuent des livrets aux visiteurs du château.',otherSpans:['Ils conduisent ensuite le groupe dans les salles ouvertes au public.','Les livrets contiennent un plan.']},
 {key:'instructors',passage:'Les monitrices vérifient les cordes avant l’atelier d’escalade. Elles expliquent ensuite les consignes aux participants. Le groupe reste au sol pendant les explications.',pronoun:'Elles',sentence:'Elles expliquent ensuite les consignes aux participants.',answer:'les monitrices',distractors:['les cordes','les consignes','les participants'],support:'Les monitrices vérifient les cordes avant l’atelier d’escalade.',otherSpans:['Elles expliquent ensuite les consignes aux participants.','Le groupe reste au sol pendant les explications.']},
];
export const INFORMATIONAL_SUBJECT_REFERENCE_DRAFTS=rows.map(r=>({...r,nodeKey:'resoudre_pronom_sujet',genre:'informational' as const,question:`Dans « ${r.sentence} », qui ou que désigne « ${r.pronoun} » ?`,reason:'Résoudre la référence d’un pronom sujet dans une notice informative fictive. Le genre et le nombre aident, mais le sens du verbe permet de départager plusieurs noms compatibles.'}));
const guides=[
 {text:'Le gardien vérifie le portail avant l’ouverture. Il accueille ensuite les visiteurs.',pronoun:'Il',answer:'Le gardien',others:['le portail','les visiteurs','l’ouverture'],why:'C’est le gardien qui peut accueillir les visiteurs. Le portail est aussi masculin singulier, mais le sens de la phrase permet de choisir.'},
 {text:'Une étiquette est collée sur chaque boîte. Elle indique la date de retour.',pronoun:'Elle',answer:'Une étiquette',others:['chaque boîte','la date','le retour'],why:'C’est l’étiquette qui porte l’indication de la date, même si boîte est aussi féminin singulier.'},
 {text:'Des agents rangent les vélos dans le local. Ils accueillent ensuite les cyclistes.',pronoun:'Ils',answer:'Des agents',others:['les vélos','le local','les cyclistes'],why:'Les agents et les vélos sont au masculin pluriel. Seuls les agents peuvent accueillir les cyclistes.'},
 {text:'Les affiches sont placées près des portes. Elles présentent les horaires du festival.',pronoun:'Elles',answer:'Les affiches',others:['les portes','les horaires','le festival'],why:'Les affiches donnent les horaires. Le nom portes est plus proche de Elles, mais ce n’est pas le nom repris ici.'},
];
export const INFORMATIONAL_SUBJECT_REFERENCE_TEACHING:readonly TargetTeachingContent[]=[{
 id:'french-v3-teaching:informational-subject-reference',nodeKey:'resoudre_pronom_sujet',facetKey:'resoudre_pronom_sujet::text_type:informational',mode:'interpretation',status:'draft_requires_review',titleFr:'Comprendre qui fait l’action dans une notice',learnerQuestionFr:'Qui ou que désignent il, elle, ils et elles dans ce texte ?',
 steps:[{exampleFr:'Une borne est placée à l’entrée. Elle imprime les tickets.',explanationFr:'Elle désigne ici une borne. Ce petit mot permet de ne pas répéter le même nom. Il remplace le sujet dans la seconde phrase : c’est un pronom sujet.'},{exampleFr:'Le responsable ouvre le placard. Il distribue ensuite le matériel.',explanationFr:'Responsable et placard sont tous deux masculins et singuliers. Mais c’est le responsable qui distribue le matériel. Cherche un nom compatible avec le pronom, puis vérifie que l’action a du sens avec ce nom.'}],
 practice:guides.map((g,i)=>({id:`informational-subject-guided-${i}`,promptFr:`${g.text}\n\nQui ou que désigne « ${g.pronoun} » ?`,choices:[g.answer,...g.others],answerFr:g.answer,hintFr:'Remplace le pronom par chaque nom possible et relis l’action.',explanationFr:g.why})),
 takeawayFr:'Relie le pronom à ce dont parle le texte. Vérifie le genre, le nombre et le sens de la phrase : le nom le plus proche n’est pas toujours la bonne réponse.',boundaryFr:'Dans ces notices, le pronom reprend un nom présent dans le texte. Dans d’autres textes, il peut désigner une personne connue du contexte ou ne reprendre aucun nom, comme dans il pleut. Identifier le nom repris ne prouve pas encore que tu sais employer le pronom en écrivant.',materialExposure:{sentences:[...guides.map(g=>g.text),'Une borne est placée à l’entrée. Elle imprime les tickets.','Le responsable ouvre le placard. Il distribue ensuite le matériel.']}
}];
