/** Original short passages; definitions are supplied locally so prior vocabulary
 * knowledge is not required. Content and difficulty await the owner's review. */
type Row=readonly [key:string,word:string,before:string,support:string,after:string,answer:string,distractors:readonly string[]];
const narrative:readonly Row[]=[
 ['lucarne','lucarne','Nora cherche son chat dans le grenier.','Une lucarne, petite fenêtre dans le toit, laisse entrer la lumière.','Le chat dort près d’une vieille malle.','Une petite fenêtre dans le toit.',['Une boîte pour ranger les vêtements.','Une lampe suspendue au plafond.','Une porte au fond du grenier.']],
 ['escale','escale','Le bateau de Sami approche d’une île.','L’équipage y fait une escale, un arrêt pendant le voyage.','Sami descend acheter du pain avant le départ.','Un arrêt pendant un voyage.',['Le départ définitif du bateau.','Une réparation du moteur.','Une traversée sans arrêt.']],
 ['recroqueville','recroquevillé','Adam aperçoit un hérisson sous la haie.','L’animal est recroquevillé : il a replié son corps sur lui-même.','Adam s’éloigne pour le laisser tranquille.','Replié sur lui-même.',['Allongé de tout son long.','Caché entièrement sous terre.','En train de courir.']],
 ['baluchon','baluchon','La jeune voyageuse arrive au village.','Elle porte un baluchon, un paquet de vêtements enveloppés dans un tissu.','Elle le pose avant de demander son chemin.','Un paquet enveloppé dans un tissu.',['Une veste qu’on porte sous la pluie.','Un grand panier rempli de fruits.','Une petite tente pour dormir.']],
 ['furtif','furtif','Inès attend que sa sœur ouvre son cadeau.','Elle lui lance un regard furtif, bref et discret.','Puis elle reprend son livre sans rien dire.','Bref et discret.',['Long et insistant.','Triste et plein de larmes.','Brillant et coloré.']],
 ['clairiere','clairière','Le sentier mène Léo au milieu de la forêt.','Il atteint une clairière, un espace sans arbres entouré de bois.','Il s’y arrête pour boire.','Un espace sans arbres dans la forêt.',['Un chemin très étroit entre des rochers.','Un groupe d’arbres très serrés.','Une cabane construite dans un arbre.']],
 ['tressaillir','tressaillir','Maya lit près de la fenêtre ouverte.','Un bruit la fait tressaillir, c’est-à-dire sursauter brusquement.','Elle découvre que le vent a fermé une porte.','Sursauter brusquement.',['S’endormir peu à peu.','Parler d’une voix très basse.','Marcher sans faire de bruit.']],
 ['replique','réplique','Idriss répète une pièce avec ses amis.','Il oublie sa réplique, la phrase que son personnage doit prononcer.','Une amie lui montre la bonne ligne du texte.','La phrase que le personnage doit dire.',['Le vêtement porté sur scène.','La place réservée au public.','Le geste qui termine la pièce.']],
 ['reperer','repérer','Awa cherche son frère dans la foule.','Elle finit par le repérer, autrement dit par reconnaître où il se trouve.','Elle lève le bras pour lui faire signe.','Reconnaître où il se trouve.',['Le prévenir d’un danger.','Lui demander de revenir.','Se souvenir de son prénom.']],
 ['accalmie','accalmie','La pluie retient Zoé sous un abri.','Une accalmie arrive : le vent et la pluie se calment pour un moment.','Zoé en profite pour rejoindre la maison.','Un moment où le mauvais temps se calme.',['Un orage qui devient plus violent.','Une journée entière sans nuages.','Un abri contre le vent.']],
 ['ebreche','ébréché','Noé sort deux bols du placard.','L’un est ébréché : un petit morceau manque sur son bord.','Il choisit l’autre pour servir la soupe.','Dont un petit morceau manque sur le bord.',['Dont le fond est encore humide.','Qui est rempli jusqu’en haut.','Qui porte un dessin effacé.']],
 ['hisser','hisser','Salma prépare le décor du spectacle.','Elle doit hisser la lune en carton, c’est-à-dire la faire monter avec une corde.','Son amie attache la corde une fois la lune en place.','Faire monter avec une corde.',['Découper avec des ciseaux.','Peindre avec plusieurs couleurs.','Faire descendre au sol.']],
];
const informational:readonly Row[]=[
 ['vestige','vestige','Des fouilles ont lieu près de la rivière.','Un vestige est une trace matérielle laissée par une époque passée.','Les fragments de murs découverts seront étudiés.','Une trace matérielle du passé.',['Un objet fabriqué pour un spectacle.','Une prévision sur l’avenir.','Un outil utilisé pour creuser.']],
 ['hiberner','hiberner','Certains animaux changent de rythme en hiver.','Hiberner signifie passer l’hiver dans un état de vie très ralentie.','Leur température et leur activité diminuent alors.','Passer l’hiver avec une activité très ralentie.',['Partir vers un pays chaud.','Chercher de la nourriture toute la nuit.','Changer de couleur au printemps.']],
 ['affluent','affluent','Cette carte présente les cours d’eau de la région.','Un affluent est un cours d’eau qui se jette dans un autre.','Des flèches indiquent le sens de l’écoulement.','Un cours d’eau qui se jette dans un autre.',['Un lac fermé de tous les côtés.','Un pont construit sur une rivière.','L’endroit où un fleuve rejoint la mer.']],
 ['opaque','opaque','L’atelier compare plusieurs matériaux.','Un matériau opaque ne laisse pas passer la lumière.','On peut tester le carton avec une lampe.','Qui ne laisse pas passer la lumière.',['Qui ne laisse pas passer les sons.','Qui laisse voir nettement à travers.','Qui se casse très facilement.']],
 ['refuge','refuge','Le panneau explique les règles de la réserve.','Un refuge est un lieu où l’on peut se mettre à l’abri d’un danger.','Certaines zones sont réservées aux animaux.','Un lieu où se mettre à l’abri d’un danger.',['Un chemin réservé aux voitures.','Un endroit où acheter à manger.','Un panneau indiquant une direction.']],
 ['benevole','bénévole','L’association présente son équipe sur une affiche.','Une personne bénévole donne de son temps sans être payée pour cette activité.','Les personnes intéressées peuvent proposer leur aide.','Qui aide sans être payée pour cette activité.',['Qui reçoit un salaire pour chaque heure.','Qui apprend seule une nouvelle activité.','Qui vient obligatoirement tous les jours.']],
 ['manuscrit','manuscrit','Une vitrine expose plusieurs textes anciens.','Un manuscrit est un texte écrit à la main.','La lumière reste faible pour protéger les pages.','Un texte écrit à la main.',['Un texte imprimé en plusieurs exemplaires.','Une image sans aucune écriture.','Un texte enregistré avec un microphone.']],
 ['reservoir','réservoir','Une fiche décrit le circuit de récupération de pluie.','Le réservoir est le récipient dans lequel l’eau est conservée.','Un tuyau permet ensuite d’arroser le jardin.','Le récipient où l’eau est conservée.',['Le tuyau par lequel l’eau sort.','Le filtre qui enlève les feuilles.','Le toit sur lequel tombe la pluie.']],
 ['perimetre','périmètre','Le guide présente le plan du terrain.','Le périmètre correspond à la longueur totale de son contour.','Toutes les longueurs sont indiquées en mètres.','La longueur totale du contour.',['La surface à l’intérieur du terrain.','La distance du centre à un angle.','La hauteur de la clôture.']],
 ['durable','durable','La fiche compare plusieurs sacs.','Ici, durable signifie qui peut être utilisé longtemps sans se détériorer.','Les sacs sont soumis aux mêmes essais.','Qui peut être utilisé longtemps sans s’abîmer.',['Qui coûte toujours moins cher.','Qui doit être jeté après une utilisation.','Qui est forcément fabriqué en bois.']],
 ['archives','archives','La bibliothèque ouvre une nouvelle salle.','Les archives sont des documents conservés comme traces d’activités passées.','On peut les consulter sur rendez-vous.','Des documents conservés sur des activités passées.',['Des livres encore en cours d’écriture.','Des objets proposés à la vente.','Des formulaires qui doivent rester vides.']],
 ['amovible','amovible','La notice décrit une petite lampe.','Son support est amovible, c’est-à-dire qu’il peut être retiré.','La lampe fonctionne avec une batterie.','Qui peut être retiré.',['Qui tourne automatiquement.','Qui doit rester fixé pour toujours.','Qui s’allume dans le noir.']],
];
const argumentative:readonly Row[]=[
 ['concertation','concertation','Je souhaite que les élèves participent au choix des activités.','Organisons une concertation, un échange d’avis avant de décider.','La décision tiendrait ainsi compte de plusieurs besoins.','Un échange d’avis avant une décision.',['Un concert organisé par les élèves.','Une décision prise sans discussion.','Un concours entre plusieurs équipes.']],
 ['equitable','équitable','Chaque groupe devrait accéder au matériel de sport.','Je propose une répartition équitable, qui traite chacun de façon juste.','Les groupes qui attendent pourraient disposer d’un autre créneau.','Qui traite chacun de façon juste.',['Qui favorise toujours le plus grand groupe.','Qui distribue le matériel au hasard.','Qui réserve tout aux mêmes personnes.']],
 ['nuisance','nuisance','Je pense que les livraisons devraient avoir lieu plus tard.','Le bruit très tôt le matin est une nuisance, une gêne pour les habitants.','Changer l’horaire leur permettrait de mieux dormir.','Une gêne pour les habitants.',['Une aide apportée aux habitants.','Un horaire annoncé à l’avance.','Une obligation de travailler dehors.']],
 ['compromis','compromis','Certains veulent jouer dans la salle, d’autres veulent y lire.','Cherchons un compromis, une solution où chaque groupe accepte de céder sur un point.','Nous pourrions réserver des horaires différents à ces activités.','Une solution où chacun accepte une concession.',['Une solution imposée par un seul groupe.','Une promesse de ne jamais changer d’avis.','Une compétition pour choisir le meilleur groupe.']],
 ['accessible','accessible','Notre exposition devrait accueillir davantage de visiteurs.','Rendons-la accessible, c’est-à-dire facile à atteindre et à utiliser pour tous.','Une entrée sans marche aiderait notamment les personnes en fauteuil.','Facile à atteindre et à utiliser pour tous.',['Réservée aux visiteurs déjà inscrits.','Située le plus loin possible de l’entrée.','Ouverte uniquement aux personnes du quartier.']],
 ['ponctuel','ponctuel','Je propose une collecte de livres le mois prochain.','Ce serait un événement ponctuel, organisé une seule fois et non régulièrement.','Nous pourrions ensuite décider s’il faut le renouveler.','Organisé une seule fois, sans régularité prévue.',['Organisé tous les matins.','Qui commence toujours en retard.','Qui dure obligatoirement plusieurs années.']],
 ['pertinent','pertinent','Pour choisir un atelier, écoutons les propositions des élèves.','Un argument pertinent est un argument qui répond bien au sujet discuté.','Cela nous aiderait à comparer les idées sans nous disperser.','Qui répond bien au sujet discuté.',['Qui est plus long que tous les autres.','Qui change complètement de sujet.','Qui plaît forcément à tout le monde.']],
 ['mutualiser','mutualiser','Les clubs achètent parfois le même matériel chacun de leur côté.','Nous devrions le mutualiser, autrement dit le mettre en commun.','Un calendrier permettrait à chaque club de l’utiliser à son tour.','Mettre en commun.',['Jeter après chaque utilisation.','Réserver à un seul club.','Acheter en plusieurs exemplaires identiques.']],
 ['preserver','préserver','Le jardin accueille des oiseaux et des insectes.','Il faut préserver cet espace, c’est-à-dire le protéger des dégradations.','Installons donc des chemins pour éviter de piétiner les plantes.','Protéger des dégradations.',['Transformer entièrement.','Utiliser sans aucune limite.','Fermer définitivement aux animaux.']],
 ['autonomie','autonomie','Les élèves pourraient organiser eux-mêmes une petite exposition.','Ils gagneraient en autonomie, la capacité d’agir sans dépendre constamment d’une aide.','Un adulte resterait disponible en cas de difficulté.','La capacité d’agir sans aide constante.',['L’obligation de toujours rester seul.','Le fait de suivre chaque ordre sans réfléchir.','La capacité de faire tout plus vite que les autres.']],
 ['diversifier','diversifier','Le club de lecture propose surtout des romans.','Nous devrions diversifier nos choix, c’est-à-dire les rendre plus variés.','Des mangas et des documentaires pourraient attirer de nouveaux lecteurs.','Rendre les choix plus variés.',['Supprimer tous les choix possibles.','Choisir toujours le même type de livre.','Réduire le nombre de lecteurs.']],
 ['transitoire','transitoire','La salle habituelle est fermée pendant les travaux.','Utilisons une solution transitoire, une solution temporaire en attendant la situation définitive.','La bibliothèque pourrait nous accueillir quelques semaines.','Temporaire, en attendant la situation définitive.',['Définitive et impossible à modifier.','Décidée sans prévenir personne.','Réservée aux déplacements en voiture.']],
];
export const LOCAL_DEFINITION_READING_DRAFTS=([['narrative',narrative],['informational',informational],['argumentative',argumentative]] as const).flatMap(([genre,rows])=>rows.map(([key,word,before,support,after,answer,distractors ])=>({key:`${genre}-${key}`,genre,nodeKey:'deduire_mot_definition_locale',passage:[before,support,after].join(' '),support,otherSpans:[before,after],question:`Dans ce texte, que signifie « ${word} » ?`,answer,distractors,reason:'Utiliser une définition ou une reformulation proche du mot, puis sélectionner la phrase qui permet de justifier ce sens.'})));
