import {conjugate,PERSONS,type Person} from '@/lib/linguistic/conjugation';
import type {TargetTeachingContent} from './teaching-content';
type Row=[string,Person,string];
type Family={key:string;model:string;forms:string[];rule:string;boundary:string;guided:Row[];checks:Row[]};
export const PASSE_SIMPLE_FAMILIES:Family[]=[
 {key:'regular_er',model:'parler',forms:['parlai','parlas','parla','parlâmes','parlâtes','parlèrent'],rule:'Enlève -er et ajoute -ai, -as, -a, -âmes, -âtes ou -èrent selon le sujet. Nous et vous portent un accent circonflexe sur â.',boundary:'Je parlai raconte ici un événement au passé simple. Je parlais est une forme de l’imparfait. Les verbes être et faire ont leurs propres modèles.',guided:[
 ['regarder','1s','À cet instant, je ___ derrière la porte.'],['entrer','2s','Soudain, tu ___ dans la salle.'],['fermer','3s','Le gardien ___ ensuite le portail.'],['trouver','1p','Ce jour-là, nous ___ une lettre dans le grenier.'],['traverser','2p','Vous ___ alors la cour en silence.'],['raconter','3p','Les voyageurs ___ leur aventure ce soir-là.']],checks:[
 ['chercher','1s','Je ___ alors une issue dans le mur.'],['dessiner','1s','Ce soir-là, je ___ le chemin sur une feuille.'],['frapper','2s','Tu ___ trois fois à la porte, puis tu attendis.'],['sauter','2s','À ce signal, tu ___ par-dessus le ruisseau.'],['tomber','3s','Une pierre ___ soudain du muret.'],['montrer','3s','Lina ___ alors la trace sur le sol.'],['porter','1p','Nous ___ ensuite la caisse jusqu’au refuge.'],['aider','1p','Ce matin-là, nous ___ le voyageur à repartir.'],['rester','2p','Vous ___ quelques minutes devant le tableau, puis vous repartîtes.'],['quitter','2p','À la fin du récit, vous ___ la pièce.'],['observer','3p','Les enfants ___ un instant la cabane avant d’entrer.'],['préparer','3p','Les habitants ___ ensuite un repas pour leurs invités.']]},
 {key:'regular_ir',model:'finir',forms:['finis','finis','finit','finîmes','finîtes','finirent'],rule:'Avec les verbes du modèle finir, enlève -ir et ajoute -is, -is, -it, -îmes, -îtes ou -irent. Je et tu partagent la même forme écrite. Nous et vous portent un accent circonflexe sur î.',boundary:'Certaines formes ressemblent au présent : je finis, tu finis, il finit. Ici, le temps est demandé et le récit situe l’action dans le passé. Les formes nous finîmes et vous finîtes se distinguent de finissons et finissez.',guided:[
 ['choisir','1s','Ce jour-là, je ___ le sentier de gauche.'],['remplir','2s','Tu ___ alors ta gourde à la fontaine.'],['finir','3s','Lina ___ enfin son dessin.'],['réfléchir','1p','Nous ___ un instant, puis nous ouvrîmes la boîte.'],['ralentir','2p','Vous ___ aussitôt devant cet obstacle.'],['applaudir','3p','À la fin de la scène, les spectateurs ___.']],checks:[
 ['finir','1s','Je ___ ma lettre avant de quitter la maison.'],['rougir','1s','En entendant mon nom, je ___ brusquement.'],['choisir','2s','Tu ___ alors une clé parmi les trois.'],['grandir','2s','Dans cette ville, tu ___ entouré de tes cousins.'],['réussir','3s','Après plusieurs essais, le garçon ___ à ouvrir la serrure.'],['remplir','3s','Le cuisinier ___ ensuite le grand panier.'],['bâtir','1p','Cette année-là, nous ___ un abri près du lac.'],['nourrir','1p','Nous ___ les animaux avant de reprendre la route.'],['agir','2p','À cet instant, vous ___ sans hésiter.'],['finir','2p','Vous ___ votre récit juste avant la sonnerie.'],['obéir','3p','Les soldats ___ à cet ordre puis quittèrent la cour.'],['réfléchir','3p','Les deux amis ___ quelques instants avant de répondre.']]},
 {key:'spelling_ger',model:'manger',forms:['mangeai','mangeas','mangea','mangeâmes','mangeâtes','mangèrent'],rule:'Les terminaisons sont celles de parler. Devant a ou â, garde un e après le g pour conserver le son doux : mangeai, mangeâmes. Devant è, ce e supplémentaire n’est pas nécessaire : mangèrent.',boundary:'N’écris pas mangâmes ni mangeèrent. L’accent de nous et vous reste nécessaire même après le e ajouté : mangeâmes, mangeâtes.',guided:[
 ['ranger','1s','Je ___ ensuite les lettres dans leur boîte.'],['bouger','2s','À ce moment, tu ___ légèrement la tête.'],['changer','3s','Lina ___ alors de direction.'],['partager','1p','Nous ___ notre repas avec les voyageurs.'],['mélanger','2p','Vous ___ alors les deux couleurs.'],['nager','3p','Les enfants ___ jusqu’à la rive.']],checks:[
 ['manger','1s','Ce soir-là, je ___ une soupe près du feu.'],['plonger','1s','Je ___ alors la main dans le sac.'],['changer','2s','Tu ___ soudain de place pour mieux voir.'],['ranger','2s','Tu ___ les outils avant de fermer l’atelier.'],['bouger','3s','Une branche ___ brusquement près de la fenêtre.'],['partager','3s','Le garçon ___ son pain avec le voyageur.'],['mélanger','1p','Nous ___ les cartes avant la première partie.'],['nager','1p','Nous ___ vers le petit bateau.'],['ranger','2p','Vous ___ les couvertures dans le coffre.'],['manger','2p','Vous ___ sous le grand arbre avant le départ.'],['changer','3p','Les joueurs ___ de camp au signal.'],['partager','3p','Les voisins ___ les provisions entre les familles.']]},
 {key:'spelling_cer',model:'lancer',forms:['lançai','lanças','lança','lançâmes','lançâtes','lancèrent'],rule:'Les terminaisons sont celles de parler. Devant a ou â, remplace c par ç pour garder le son s : lançai, lançâmes. Devant è, garde c sans cédille : lancèrent.',boundary:'N’écris pas lancâmes ni lançèrent. Nous et vous gardent aussi leur accent circonflexe : lançâmes, lançâtes.',guided:[
 ['placer','1s','Je ___ alors la lampe sur la table.'],['effacer','2s','Tu ___ ensuite le trait de crayon.'],['avancer','3s','Le gardien ___ d’un pas vers la porte.'],['commencer','1p','Nous ___ enfin notre traversée.'],['tracer','2p','Vous ___ un cercle autour de la marque.'],['lancer','3p','Les enfants ___ une corde vers le bateau.']],checks:[
 ['lancer','1s','Je ___ alors un caillou dans l’eau.'],['avancer','1s','Je ___ jusqu’au bord de la clairière.'],['placer','2s','Tu ___ la clé dans la serrure, puis tu tournas.'],['commencer','2s','Tu ___ ton histoire dès que le silence revint.'],['effacer','3s','Lina ___ le message avant de sortir.'],['tracer','3s','Le voyageur ___ une flèche sur le plan.'],['placer','1p','Nous ___ les bancs autour du feu.'],['avancer','1p','Nous ___ ensemble vers le pont.'],['lancer','2p','Vous ___ vos filets près des rochers.'],['commencer','2p','Vous ___ la recherche au lever du jour.'],['effacer','3p','Les élèves ___ leurs calculs après la correction.'],['placer','3p','Les musiciens ___ leurs chaises devant la scène.']]},
];
function authoredForm(f:Family,verb:string,person:Person){
 const ending=(f.key==='regular_ir'?['is','is','it','îmes','îtes','irent']:['ai','as','a','âmes','âtes','èrent'])[PERSONS.indexOf(person)];
 let stem=verb.slice(0,-2);
 if(/^[aâ]/.test(ending)){if(f.key==='spelling_ger')stem+='e';if(f.key==='spelling_cer')stem=stem.slice(0,-1)+'ç';}
 const answer=stem+ending;if(conjugate(verb,'passe_simple',person)!==answer)throw Error(`Passé simple disagreement: ${verb}/${person}`);return answer;
}
export const PASSE_SIMPLE_FAMILY_APPLICATIONS=PASSE_SIMPLE_FAMILIES.flatMap(f=>f.checks.map(([verb,person,sentence])=>({family:f.key,verb,person,sentence,answer:authoredForm(f,verb,person)})));
export const PASSE_SIMPLE_FAMILY_TEACHING:readonly TargetTeachingContent[]=PASSE_SIMPLE_FAMILIES.map(f=>{
 f.forms.forEach((form,i)=>{if(conjugate(f.model,'passe_simple',PERSONS[i])!==form)throw Error('Authored model mismatch');});
 const steps=[
  {exampleFr:'Le vent soufflait. Soudain, Lina ferma la fenêtre.',explanationFr:'Dans une histoire écrite, certaines actions font avancer le récit. Ferma raconte ici ce que Lina fit à ce moment. Ce temps s’appelle le passé simple.'},
  {exampleFr:['je','tu','il ou elle','nous','vous','ils ou elles'].map((p,i)=>`${p} : ${f.forms[i]}`).join('\n'),explanationFr:'Repère le sujet, puis choisis la forme qui lui correspond. Le narrateur peut raconter avec je ou nous, même si beaucoup de récits parlent d’un personnage avec il ou elle.'},
  {exampleFr:`nous : ${f.forms[3]}\nvous : ${f.forms[4]}\nils ou elles : ${f.forms[5]}`,explanationFr:f.rule},
 ];
 const practice=f.guided.map(([verb,person,gap],i)=>{const answer=authoredForm(f,verb,person);return {id:`passe-simple-family:${f.key}:${i}`,promptFr:`Complète ce récit avec ${verb} au passé simple. Écris seulement le verbe : ${gap}`,answerFr:answer,hintFr:`Repère le sujet. ${f.rule}`,explanationFr:`${gap.replace('___',answer)} La forme attendue est ${answer}.`};});
 return {id:`french-v3-teaching:passe-simple:pattern:${f.key}`,nodeKey:'produire_passe_simple',facetKey:`produire_passe_simple::pattern:${f.key}`,mode:'production',status:'draft_requires_review',titleFr:`Raconter au passé simple avec les verbes comme ${f.model}`,learnerQuestionFr:`Comment écrire les verbes comme ${f.model} au passé simple ?`,steps,practice,takeawayFr:'Repère le sujet, choisis la terminaison et vérifie les accents ainsi que les changements de lettres nécessaires.',boundaryFr:`${f.boundary} Ici, le passé simple est demandé. Choisir entre les temps dans un récit se travaille séparément.`,materialExposure:{words:[...new Set([f.model,...f.guided.map(r=>r[0])])].map(lemma=>({lemma,form:lemma})),sentences:[...steps.flatMap(s=>s.exampleFr.split('\n')),...f.guided.map(([verb,person,gap])=>gap.replace('___',authoredForm(f,verb,person)))]}};
});
