import {conjugate,PERSONS} from '@/lib/linguistic/conjugation';
import type {TargetTeachingContent} from './teaching-content';
type VerbContent={verb:string;forms:readonly string[];rule:string;boundary:string;guided:readonly string[];checks:readonly string[]};
/** Original narrative contexts. Guided examples never count as independent evidence. */
export const PASSE_SIMPLE_VERBS:readonly VerbContent[]=[
 {verb:'être',forms:['fus','fus','fut','fûmes','fûtes','furent'],rule:'Apprends fus, fus, fut, fûmes, fûtes, furent. Je et tu ont la même forme. Nous et vous portent un accent circonflexe sur û.',boundary:'Il fut ne prend pas l’accent de qu’il fût, qui appartient à un autre temps et un autre mode. Ne remplace pas fus par étais quand le passé simple est demandé.',
 guided:['Ce jour-là, je ___ choisi pour guider le groupe.','Tu ___ le premier à apercevoir le refuge.','La porte ___ ouverte au lever du jour.','Nous ___ surpris par ce bruit soudain.','Vous ___ accueillis par les habitants.','Les voyageurs ___ réunis dans la grande salle.'],
 checks:['Je ___ aussitôt conduit auprès du capitaine.','Je ___ le dernier à quitter le bateau.','Tu ___ désigné pour porter le message.','Tu ___ surpris par cette réponse.','Le garçon ___ libéré avant la nuit.','La jeune fille ___ la première à comprendre le signe.','Nous ___ avertis de leur arrivée.','Nous ___ témoins de cette rencontre.','Vous ___ invités à entrer dans la cour.','Vous ___ les seuls à retrouver la trace.','Les deux amis ___ félicités pour leur courage.','Les portes ___ refermées après leur passage.']},
 {verb:'avoir',forms:['eus','eus','eut','eûmes','eûtes','eurent'],rule:'Apprends eus, eus, eut, eûmes, eûtes, eurent. Le début eu reste dans les six formes. Nous et vous ont un accent circonflexe sur û.',boundary:'Il eut n’a pas l’accent de qu’il eût. Ici, avoir est le verbe demandé, pas un auxiliaire que tu dois ajouter à un participe passé.',
 guided:['Je ___ soudain une idée pour sortir de la grotte.','Tu ___ juste le temps de fermer la grille.','La voyageuse ___ enfin une réponse.','Nous ___ la chance de trouver un abri.','Vous ___ le courage de continuer.','Les enfants ___ une grande surprise en ouvrant le coffre.'],
 checks:['Je ___ alors le sentiment d’être suivi.','Je ___ un instant de doute devant la serrure.','Tu ___ une occasion de parler au roi.','Tu ___ enfin la permission de partir.','Le gardien ___ un mouvement de recul.','La fillette ___ un sourire en découvrant le dessin.','Nous ___ quelques minutes pour préparer nos sacs.','Nous ___ une conversation avec le vieux marin.','Vous ___ l’idée de suivre la rivière.','Vous ___ une réponse avant la tombée du jour.','Les pêcheurs ___ du mal à tirer le filet.','Les visiteurs ___ la surprise de découvrir une seconde cour.']},
 {verb:'aller',forms:['allai','allas','alla','allâmes','allâtes','allèrent'],rule:'Au passé simple, aller garde all- et prend -ai, -as, -a, -âmes, -âtes, -èrent. Ces terminaisons ressemblent à celles de parler, même si aller est irrégulier au présent.',boundary:'Je allai devient j’allai devant la voyelle. Ne confonds pas allai avec allais. Il alla raconte un déplacement ; il allait est une autre forme, à l’imparfait.',
 guided:['J’___ ensuite chercher une lanterne.','Tu ___ jusqu’au pied de la tour.','Le messager ___ prévenir le village.','Nous ___ retrouver nos compagnons près du pont.','Vous ___ explorer la rive opposée.','Les soldats ___ chercher du renfort.'],
 checks:['J’___ frapper à la porte de la maison voisine.','J’___ déposer le paquet dans la remise.','Tu ___ accueillir les voyageurs à la gare.','Tu ___ vérifier le chemin derrière le moulin.','Le prince ___ demander conseil à sa sœur.','La bergère ___ chercher le troupeau.','Nous ___ examiner les traces dans la neige.','Nous ___ annoncer la nouvelle au village.','Vous ___ attendre vos amis près de la fontaine.','Vous ___ demander une carte au gardien.','Les enfants ___ observer le navire depuis la jetée.','Les habitants ___ porter des couvertures aux voyageurs.']},
 {verb:'faire',forms:['fis','fis','fit','fîmes','fîtes','firent'],rule:'Au passé simple, faire utilise fi- : fis, fis, fit, fîmes, fîtes, firent. Je et tu ont un s ; il ou elle a un t. Nous et vous portent î.',boundary:'N’écris pas fais pour un passé simple demandé. Il fit se distingue de qu’il fît : la forme au passé simple n’a pas de circonflexe à la troisième personne du singulier.',
 guided:['Je ___ un signe à mon compagnon.','Tu ___ un pas vers la fenêtre.','Le gardien ___ entrer le groupe.','Nous ___ une halte près du ruisseau.','Vous ___ le tour des remparts.','Les voyageurs ___ un feu pour se réchauffer.'],
 checks:['Je ___ une marque sur la carte.','Je ___ demi-tour en entendant le cri.','Tu ___ tomber une pièce sur le sol.','Tu ___ une promesse avant de partir.','La vieille dame ___ asseoir son invité.','Le cheval ___ un écart devant l’obstacle.','Nous ___ passer les sacs par la fenêtre.','Nous ___ une découverte derrière le mur.','Vous ___ une dernière tentative pour ouvrir la porte.','Vous ___ signe au bateau de s’approcher.','Les deux sœurs ___ un détour par le marché.','Les guides ___ traverser le pont aux visiteurs.']},

 {verb:'dire',forms:['dis','dis','dit','dîmes','dîtes','dirent'],rule:'Au singulier, je dis, tu dis et il dit s’écrivent comme au présent. Au pluriel, le passé simple change : nous dîmes, vous dîtes, ils dirent. Vérifie les accents de dîmes et dîtes.',boundary:'Vous dites est au présent ; vous dîtes est au passé simple. Pour je dis, tu dis et il dit, la forme seule ne permet pas de reconnaître le temps : il faut lire le récit. Ici, le temps est fourni.',
 guided:['Je ___ enfin mon nom au gardien.','Tu ___ quelques mots pour rassurer ton frère.','La reine ___ au messager de patienter.','Nous ___ adieu aux habitants du village.','Vous ___ la vérité au capitaine.','Les enfants ___ ensemble le mot de passe.'],
 checks:['Je ___ tout bas ce que j’avais découvert.','Je ___ au voyageur où trouver un abri.','Tu ___ merci à la personne qui nous avait aidés.','Tu ___ au guide que le passage était libre.','Le garçon ___ son secret à sa sœur.','La voyageuse ___ au revoir à ses compagnons.','Nous ___ au garde pourquoi nous étions venus.','Nous ___ quelques mots avant de reprendre la route.','Vous ___ au marin de jeter la corde.','Vous ___ à vos amis de rester près du feu.','Les témoins ___ ce qu’ils avaient vu.','Les éclaireuses ___ au groupe de les suivre.']},
 {verb:'prendre',forms:['pris','pris','prit','prîmes','prîtes','prirent'],rule:'Prendre utilise pri- au passé simple : pris, pris, prit, prîmes, prîtes, prirent. Je et tu finissent par s ; il ou elle finit par t. Nous et vous portent un accent sur î.',boundary:'Il prit est une forme du passé simple. Dans il a pris, pris accompagne a : c’est un passé composé. N’écris pas prends ou prenait quand le passé simple est demandé.',
 guided:['Je ___ la lanterne posée près de la porte.','Tu ___ le sentier qui descendait vers le lac.','La voyageuse ___ une couverture dans son sac.','Nous ___ place autour de la table.','Vous ___ la décision de rentrer avant la nuit.','Les enfants ___ chacun une pomme dans le panier.'],
 checks:['Je ___ une carte pour retrouver le chemin.','Je ___ mon courage à deux mains et frappai à la porte.','Tu ___ la corde que te tendait le marin.','Tu ___ le dernier billet pour la traversée.','Le gardien ___ les clés suspendues au mur.','La fillette ___ son frère par la main.','Nous ___ le temps de regarder les traces.','Nous ___ le bateau qui partait à l’aube.','Vous ___ un raccourci à travers les champs.','Vous ___ soin du blessé jusqu’à l’arrivée du médecin.','Les passagers ___ leurs sacs avant de descendre.','Les deux sœurs ___ la route du village voisin.']},
 {verb:'voir',forms:['vis','vis','vit','vîmes','vîtes','virent'],rule:'Pour voir, le passé simple commence par vi- : vis, vis, vit, vîmes, vîtes, virent. Je et tu finissent par s ; il ou elle finit par t. Vérifie le î de nous vîmes et vous vîtes.',boundary:'Il vit raconte ici ce qu’un personnage aperçut. Il voit est au présent et il a vu au passé composé. Vit peut aussi appartenir au verbe vivre au présent : ici, le verbe voir et le temps sont donnés.',
 guided:['Je ___ une lumière derrière les arbres.','Tu ___ le bateau apparaître au loin.','Le garçon ___ une ombre passer sous la porte.','Nous ___ enfin le sommet de la montagne.','Vous ___ le signal du gardien.','Les voyageuses ___ une tour au bord du lac.'],
 checks:['Je ___ le renard disparaître dans les buissons.','Je ___ une inscription au fond du coffre.','Tu ___ le messager entrer dans la cour.','Tu ___ une étoile filer au-dessus du camp.','La reine ___ son fils revenir du voyage.','Le marin ___ une voile à l’horizon.','Nous ___ les traces laissées dans la boue.','Nous ___ la rivière déborder devant le moulin.','Vous ___ les danseurs entrer sur la scène.','Vous ___ une fissure dans la muraille.','Les enfants ___ le cerf franchir la clôture.','Les pêcheuses ___ le phare s’allumer.']},
 {verb:'venir',forms:['vins','vins','vint','vînmes','vîntes','vinrent'],rule:'Le début change selon la personne : vins, vins, vint, vînmes, vîntes, vinrent. Nous et vous ont un î suivi de n : écris vînmes et vîntes. Ils ou elles gardent vin- dans vinrent.',boundary:'Il vint ne prend pas l’accent de qu’il vînt, qui appartient à un autre temps et un autre mode. Ne remplace pas vint par vient ou venait : ces formes sont au présent et à l’imparfait.',
 guided:['Je ___ aider mon voisin à porter son sac.','Tu ___ nous retrouver devant la mairie.','La messagère ___ annoncer la victoire.','Nous ___ saluer le capitaine avant son départ.','Vous ___ chercher vos affaires dans la grange.','Les habitants ___ accueillir les voyageurs.'],
 checks:['Je ___ apporter une lettre au château.','Je ___ demander de l’aide au forgeron.','Tu ___ me prévenir du danger.','Tu ___ partager notre repas près du feu.','Le médecin ___ soigner le blessé.','La musicienne ___ jouer dans la grande salle.','Nous ___ écouter le récit du vieux pêcheur.','Nous ___ rendre les outils empruntés.','Vous ___ assister au départ de la caravane.','Vous ___ remettre le prix à la gagnante.','Les voisins ___ réparer la barrière.','Les deux amies ___ nous tenir compagnie.']},
 {"verb": "partir", "forms": ["partis", "partis", "partit", "partîmes", "partîtes", "partirent"], "rule": "Garde part- puis ajoute -is, -is, -it, -îmes, -îtes, -irent. Le t de part- reste devant chaque terminaison.", "boundary": "Il partit est au passé simple ; il part est au présent. N’ajoute pas est : il est parti appartient au passé composé.", "guided": ["Je ___ avant le lever du soleil.", "Tu ___ chercher du bois dans la forêt.", "La caravane ___ vers le désert.", "Nous ___ sans attendre la fin de l’orage.", "Vous ___ au son de la cloche.", "Les voyageurs ___ après un dernier salut."], "checks": ["Je ___ retrouver ma sœur au village.", "Je ___ dès que le chemin fut libre.", "Tu ___ avec le premier convoi.", "Tu ___ en laissant un mot sur la table.", "Le navire ___ à la tombée du jour.", "La jeune fille ___ à la recherche de son chien.", "Nous ___ en direction de la côte.", "Nous ___ après avoir rangé le camp.", "Vous ___ juste avant la fermeture du pont.", "Vous ___ ensemble pour la capitale.", "Les cavaliers ___ au galop.", "Les deux amies ___ par le sentier du lac."]},
 {"verb": "sortir", "forms": ["sortis", "sortis", "sortit", "sortîmes", "sortîtes", "sortirent"], "rule": "Garde sort- et ajoute -is, -is, -it, -îmes, -îtes, -irent. Nous sortîmes et vous sortîtes portent î.", "boundary": "Je sors est au présent ; je sortis est au passé simple. Sortir peut signifier quitter un lieu ou retirer un objet : le choix de l’auxiliaire aux temps composés est une autre question.", "guided": ["Je ___ de la grotte avec précaution.", "Tu ___ une clé de ta poche.", "Le chat ___ de sa cachette.", "Nous ___ dans la cour au premier rayon de soleil.", "Vous ___ les couvertures du coffre.", "Les enfants ___ pour admirer la neige."], "checks": ["Je ___ mon carnet pour dessiner le paysage.", "Je ___ du théâtre par une petite porte.", "Tu ___ le pain du four.", "Tu ___ de la cabane pour appeler le guide.", "Le gardien ___ sa lampe du tiroir.", "La voyageuse ___ de la gare en courant.", "Nous ___ les sacs de la voiture.", "Nous ___ du bois près de la rivière.", "Vous ___ de la salle sans faire de bruit.", "Vous ___ la carte de son étui.", "Les souris ___ du trou dans le mur.", "Les pêcheurs ___ les filets de leur barque."]},
 {"verb": "pouvoir", "forms": ["pus", "pus", "put", "pûmes", "pûtes", "purent"], "rule": "Le passé simple utilise pu- : pus, pus, put, pûmes, pûtes, purent. Je et tu ont s ; il ou elle a t. Nous et vous prennent û.", "boundary": "Il put ne prend pas l’accent de qu’il pût. Il a pu contient un auxiliaire et un participe passé ; ici, écris seulement la forme du passé simple.", "guided": ["Je ___ enfin ouvrir la serrure.", "Tu ___ traverser avant la crue.", "La fillette ___ rejoindre sa famille.", "Nous ___ nous abriter dans une grange.", "Vous ___ lire le message grâce à la lampe.", "Les marins ___ réparer la voile."], "checks": ["Je ___ entendre un appel derrière la porte.", "Je ___ retrouver le chemin en suivant les traces.", "Tu ___ retenir la corde à temps.", "Tu ___ distinguer le phare dans la brume.", "Le cheval ___ franchir le fossé.", "La gardienne ___ arrêter la machine.", "Nous ___ atteindre la rive avant la nuit.", "Nous ___ prévenir les habitants du danger.", "Vous ___ sauver les livres de la pluie.", "Vous ___ récupérer vos bagages au dernier moment.", "Les voyageurs ___ acheter les derniers billets.", "Les deux sœurs ___ soulever le couvercle ensemble."]},
 {"verb": "vouloir", "forms": ["voulus", "voulus", "voulut", "voulûmes", "voulûtes", "voulurent"], "rule": "Le début reste voul- : voulus, voulus, voulut, voulûmes, voulûtes, voulurent. Observe le û de nous et vous.", "boundary": "Il voulut exprime ici une intention dans le récit, sans garantir que l’action a réussi. Il voulait est à l’imparfait ; le temps demandé ici est le passé simple.", "guided": ["Je ___ comprendre le sens du dessin.", "Tu ___ suivre le bruit jusqu’à sa source.", "Le prince ___ parler au gardien.", "Nous ___ tenter une dernière fois notre chance.", "Vous ___ savoir qui avait laissé ce message.", "Les enfants ___ visiter le vieux moulin."], "checks": ["Je ___ remercier la personne qui m’avait aidé.", "Je ___ examiner la boîte de plus près.", "Tu ___ courir vers le pont, mais je te retins.", "Tu ___ raconter ton aventure au village.", "La reine ___ rencontrer les voyageurs.", "Le garçon ___ ouvrir la fenêtre, mais elle était bloquée.", "Nous ___ retrouver le propriétaire du chien.", "Nous ___ offrir un repas à nos guides.", "Vous ___ emporter le coffre, mais il était trop lourd.", "Vous ___ connaître la suite de l’histoire.", "Les marins ___ attendre le retour du capitaine.", "Les voisines ___ organiser une fête pour les enfants."]},
 {"verb": "savoir", "forms": ["sus", "sus", "sut", "sûmes", "sûtes", "surent"], "rule": "Savoir change de début : sus, sus, sut, sûmes, sûtes, surent. N’utilise pas sav- dans ces formes. Nous et vous ont û.", "boundary": "Il sut peut raconter le moment où il apprit une information ou sa capacité à agir. Il savait est à l’imparfait. Ici, tu formes le temps fourni ; choisir entre les deux temps se travaille séparément.", "guided": ["Je ___ alors pourquoi la porte était fermée.", "Tu ___ trouver les mots pour le rassurer.", "La reine ___ enfin la vérité.", "Nous ___ aussitôt que le voyage était terminé.", "Vous ___ reconnaître le bon chemin.", "Les enfants ___ garder leur calme."], "checks": ["Je ___ à cet instant qui avait écrit la lettre.", "Je ___ profiter de cette occasion pour parler.", "Tu ___ résoudre l’énigme du coffre.", "Tu ___ bientôt où le groupe s’était réfugié.", "Le gardien ___ reconnaître son ancien ami.", "La jeune fille ___ convaincre le capitaine de l’écouter.", "Nous ___ enfin ce qui s’était passé au moulin.", "Nous ___ éviter le piège tendu sur la route.", "Vous ___ trouver un abri malgré l’obscurité.", "Vous ___ alors que les secours approchaient.", "Les voyageurs ___ partager leurs dernières provisions.", "Les deux frères ___ réparer le mécanisme."]},
 {"verb": "devoir", "forms": ["dus", "dus", "dut", "dûmes", "dûtes", "durent"], "rule": "Devoir utilise du- : dus, dus, dut, dûmes, dûtes, durent. Nous et vous prennent û ; il dut ne prend pas d’accent.", "boundary": "Dans il a dû partir, dû est un participe passé avec un accent. Dans il dut partir, dut est la forme du passé simple sans accent. Les phrases proposées expriment une obligation ou une nécessité.", "guided": ["Je ___ attendre le retour du passeur.", "Tu ___ abandonner ton sac pour grimper.", "La voyageuse ___ changer de route.", "Nous ___ avancer à pied dans la boue.", "Vous ___ patienter devant la grille.", "Les habitants ___ quitter leurs maisons menacées par la crue."], "checks": ["Je ___ demander une nouvelle carte au gardien.", "Je ___ m’arrêter pour reprendre mon souffle.", "Tu ___ faire demi-tour devant le mur.", "Tu ___ emprunter une lampe à ton voisin.", "Le capitaine ___ réduire la vitesse du navire.", "La fillette ___ se hisser sur une caisse pour voir.", "Nous ___ traverser la rivière sur un radeau.", "Nous ___ renoncer à entrer dans la grotte inondée.", "Vous ___ chercher un autre passage entre les rochers.", "Vous ___ porter le blessé jusqu’au refuge.", "Les pêcheurs ___ rentrer au port avant la tempête.", "Les musiciennes ___ déplacer leurs instruments à l’abri."]},
];
function form(c:VerbContent,index:number){
 const answer=c.forms[index];if(conjugate(c.verb,'passe_simple',PERSONS[index])!==answer)throw Error(`Passé simple authored answer mismatch: ${c.verb}/${PERSONS[index]}`);return answer;
}
export const PASSE_SIMPLE_VERB_APPLICATIONS=PASSE_SIMPLE_VERBS.flatMap(c=>c.checks.map((sentence,i)=>({verb:c.verb,person:PERSONS[Math.floor(i/2)],sentence,answer:form(c,Math.floor(i/2))})));
export const PASSE_SIMPLE_VERB_TEACHING:readonly TargetTeachingContent[]=PASSE_SIMPLE_VERBS.map(c=>{
 if(c.guided.length!==6||c.checks.length!==12||c.forms.length!==6)throw Error('Incomplete verb/person coverage');
 const steps=[
  {exampleFr:c.guided[0].replace('___',form(c,0)),explanationFr:'Cette phrase appartient à un récit écrit au passé. Le verbe raconte ici un fait de l’histoire. La forme demandée s’appelle le passé simple. On la rencontre surtout dans les récits écrits.'},
  {exampleFr:PERSONS.map((_,i)=>`${['je','tu','il ou elle','nous','vous','ils ou elles'][i]} : ${form(c,i)}`).join('\n'),explanationFr:c.rule},
  {exampleFr:`nous : ${form(c,3)}\nvous : ${form(c,4)}\nils ou elles : ${form(c,5)}`,explanationFr:'Commence par repérer le sujet. Vérifie ensuite la terminaison et les accents. Le narrateur peut raconter avec je ou nous ; un récit peut aussi s’adresser à un personnage ou à son lecteur avec tu ou vous.'},
 ];
 return {id:`french-v3-teaching:passe-simple:verb:${c.verb}`,nodeKey:'produire_passe_simple',facetKey:`produire_passe_simple::verb:${c.verb}`,mode:'production',status:'draft_requires_review',titleFr:`Raconter au passé simple avec ${c.verb}`,learnerQuestionFr:`Comment écrire ${c.verb} au passé simple ?`,steps,
 practice:c.guided.map((gap,i)=>({id:`passe-simple-verb:${c.verb}:${i}`,promptFr:`Complète ce récit avec ${c.verb} au passé simple. Écris seulement le verbe : ${gap}`,answerFr:form(c,i),hintFr:c.rule,explanationFr:`${gap.replace('___',form(c,i))} La forme attendue est ${form(c,i)}.`})),
 takeawayFr:'Repère le sujet, choisis la forme du passé simple et vérifie ses accents.',boundaryFr:`${c.boundary} Le temps est donné : choisir le temps approprié dans une rédaction se travaille séparément.`,
 materialExposure:{words:[{lemma:c.verb,form:c.verb}],sentences:[...steps.flatMap(s=>s.exampleFr.split('\n')),...c.guided.map((gap,i)=>gap.replace('___',form(c,i)))]}};
});
