import {conjugate,PERSONS} from '@/lib/linguistic/conjugation';
import type {TargetTeachingContent} from './teaching-content';
type VerbContent={verb:string;forms:readonly string[];rule:string;boundary:string;guided:readonly string[];checks:readonly string[]};
/** Original narrative contexts. Guided examples never count as independent evidence. */
export const PASSE_SIMPLE_VERBS:readonly VerbContent[]=[
 {verb:'être',forms:['fus','fus','fut','fûmes','fûtes','furent'],rule:'Apprends fus, fus, fut, fûmes, fûtes, furent. Je et tu ont la même forme. Nous et vous portent un accent circonflexe sur û.',boundary:'Il fut ne prend pas l’accent de qu’il fût, qui appartient à un autre temps et un autre mode. Ne remplace pas fus par étais quand le passé simple est demandé.',
 guided:['Ce jour-là, je ___ choisi pour guider le groupe.','Tu ___ le premier à apercevoir le refuge.','La porte ___ ouverte au lever du jour.','Nous ___ surpris par ce bruit soudain.','Vous ___ accueillis par les habitants.','Les voyageurs ___ réunis dans la grande salle.'],
 checks:['Je ___ aussitôt conduit auprès du capitaine.','Je ___ le dernier à quitter le bateau.','Tu ___ désigné pour porter le message.','Tu ___ surpris par cette réponse.','Le garçon ___ libéré avant la nuit.','La jeune fille ___ la première à comprendre le signe.','Nous ___ avertis de leur arrivée.','Nous ___ témoins de cette rencontre.','Vous ___ invités à entrer dans la cour.','Vous ___ les seuls à retrouver la trace.','Les deux amis ___ félicités pour leur courage.','Les portes ___ refermées après leur passage.']},
 {verb:'avoir',forms:['eus','eus','eut','eûmes','eûtes','eurent'],rule:'Apprends eus, eus, eut, eûmes, eûtes, eurent. Le début eu reste dans les six formes. Nous et vous ont un accent circonflexe sur û.',boundary:'Il eut n’a pas l’accent de qu’il eût. Ici, avoir est le verbe demandé, pas un auxiliaire que tu dois ajouter à un participe passé.',
 guided:['Je ___ soudain une idée pour sortir de la grotte.','Tu ___ juste le temps de fermer la grille.','La voyageuse ___ enfin une réponse.','Nous ___ la chance de trouver un abri.','Vous ___ le courage de continuer.','Les enfants ___ une grande surprise en ouvrant le coffre.'],
 checks:['Je ___ alors le sentiment d’être suivi.','Je ___ un instant de doute devant la serrure.','Tu ___ une occasion de parler au roi.','Tu ___ enfin la permission de partir.','Le gardien ___ un mouvement de recul.','La fillette ___ un sourire en découvrant le dessin.','Nous ___ quelques minutes pour préparer nos sacs.','Nous ___ une conversation avec le vieux marin.','Vous ___ l’idée de suivre la rivière.','Vous ___ une réponse avant la tombée du jour.','Les pêcheurs ___ du mal à tirer le filet.','Les visiteurs ___ la surprise de découvrir une seconde cour.']},
 {verb:'aller',forms:['allai','allas','alla','allâmes','allâtes','allèrent'],rule:'Au passé simple, aller garde all- et prend -ai, -as, -a, -âmes, -âtes, -èrent. Ces terminaisons ressemblent à celles de parler, même si aller est irrégulier au présent.',boundary:'Je allai devient j’allai devant la voyelle. Ne confonds pas allai avec allais. Il alla raconte un déplacement ; il allait est une autre forme, à l’imparfait.',
 guided:['J’___ ensuite chercher une lanterne.','Tu ___ jusqu’au pied de la tour.','Le messager ___ prévenir le village.','Nous ___ retrouver nos compagnons près du pont.','Vous ___ explorer la rive opposée.','Les soldats ___ chercher du renfort.'],
 checks:['J’___ frapper à la porte de la maison voisine.','J’___ déposer le paquet dans la remise.','Tu ___ accueillir les voyageurs à la gare.','Tu ___ vérifier le chemin derrière le moulin.','Le prince ___ demander conseil à sa sœur.','La bergère ___ chercher le troupeau.','Nous ___ examiner les traces dans la neige.','Nous ___ annoncer la nouvelle au village.','Vous ___ attendre vos amis près de la fontaine.','Vous ___ demander une carte au gardien.','Les enfants ___ observer le navire depuis la jetée.','Les habitants ___ porter des couvertures aux voyageurs.']},
 {verb:'faire',forms:['fis','fis','fit','fîmes','fîtes','firent'],rule:'Au passé simple, faire utilise fi- : fis, fis, fit, fîmes, fîtes, firent. Je et tu ont un s ; il ou elle a un t. Nous et vous portent î.',boundary:'N’écris pas fais pour un passé simple demandé. Il fit se distingue de qu’il fît : la forme au passé simple n’a pas de circonflexe à la troisième personne du singulier.',
 guided:['Je ___ un signe à mon compagnon.','Tu ___ un pas vers la fenêtre.','Le gardien ___ entrer le groupe.','Nous ___ une halte près du ruisseau.','Vous ___ le tour des remparts.','Les voyageurs ___ un feu pour se réchauffer.'],
 checks:['Je ___ une marque sur la carte.','Je ___ demi-tour en entendant le cri.','Tu ___ tomber une pièce sur le sol.','Tu ___ une promesse avant de partir.','La vieille dame ___ asseoir son invité.','Le cheval ___ un écart devant l’obstacle.','Nous ___ passer les sacs par la fenêtre.','Nous ___ une découverte derrière le mur.','Vous ___ une dernière tentative pour ouvrir la porte.','Vous ___ signe au bateau de s’approcher.','Les deux sœurs ___ un détour par le marché.','Les guides ___ traverser le pont aux visiteurs.']},
];
function form(c:VerbContent,index:number){
 const answer=c.forms[index];if(conjugate(c.verb,'passe_simple',PERSONS[index])!==answer)throw Error(`Passé simple authored answer mismatch: ${c.verb}/${PERSONS[index]}`);return answer;
}
export const PASSE_SIMPLE_VERB_APPLICATIONS=PASSE_SIMPLE_VERBS.flatMap(c=>c.checks.map((sentence,i)=>({verb:c.verb,person:PERSONS[Math.floor(i/2)],sentence,answer:form(c,Math.floor(i/2))})));
export const PASSE_SIMPLE_VERB_TEACHING:readonly TargetTeachingContent[]=PASSE_SIMPLE_VERBS.map(c=>{
 if(c.guided.length!==6||c.checks.length!==12||c.forms.length!==6)throw Error('Incomplete verb/person coverage');
 const steps=[
  {exampleFr:c.guided[0].replace('___',form(c,0)),explanationFr:'Cette phrase appartient à un récit écrit au passé. Le verbe raconte ici un fait de l’histoire. La forme demandée s’appelle le passé simple. On la rencontre surtout dans les récits écrits.'},
  {exampleFr:PERSONS.map((_,i)=>`${['je','tu','il ou elle','nous','vous','ils ou elles'][i]} : ${form(c,i)}`).join('\n'),explanationFr:c.rule},
  {exampleFr:`nous : ${form(c,3)}\nvous : ${form(c,4)}\nils ou elles : ${form(c,5)}`,explanationFr:'Commence par repérer le sujet. Vérifie ensuite la terminaison et les accents. Le narrateur peut raconter avec je ou nous ; un récit peut aussi s’adresser à un personnage ou à son lecteur avec tu ou vous.'},
 ];
 return {id:`french-v3-teaching:passe-simple:verb:${c.verb}`,nodeKey:'produire_passe_simple',facetKey:`produire_passe_simple::verb:${c.verb}`,mode:'production',status:'draft_requires_review',titleFr:`Raconter au passé simple avec ${c.verb}`,learnerQuestionFr:`Comment écrire ${c.verb} au passé simple ?`,steps,
 practice:c.guided.map((gap,i)=>({id:`passe-simple-verb:${c.verb}:${i}`,promptFr:`Complète ce récit avec ${c.verb} au passé simple. Écris seulement le verbe : ${gap}`,answerFr:form(c,i),hintFr:c.rule,explanationFr:`${gap.replace('___',form(c,i))} La forme attendue est ${form(c,i)}.`})),
 takeawayFr:'Repère le sujet, choisis la forme du passé simple et vérifie ses accents.',boundaryFr:`${c.boundary} Le temps est donné : choisir le temps approprié dans une rédaction se travaille séparément.`,
 materialExposure:{words:[{lemma:c.verb,form:c.verb}],sentences:[...steps.flatMap(s=>s.exampleFr.split('\n')),...c.guided.map((gap,i)=>gap.replace('___',form(c,i)))]}};
});
