import {conjugationLesson} from "@/lib/conjugation/lessons";
import type {TargetTeachingContent} from "./teaching-content";
const futureSource=conjugationLesson("reconnaitre_futur_proche","Reconnaître le futur proche");
const pastSource=conjugationLesson("reconnaitre_passe_recent","Reconnaître le passé récent");
const drafts:TargetTeachingContent[]=[
 {
  id:"french-v3-teaching:recognition:futur_proche",nodeKey:"reconnaitre_futur_proche",mode:"recognition",status:"draft_requires_review",
  titleFr:"Reconnaître le futur proche",learnerQuestionFr:"Comment reconnaître « je vais partir » dans une phrase ?",
  steps:[
   {exampleFr:futureSource.examples[0],explanationFr:"Le départ est annoncé. Vais est une forme du verbe aller au présent; partir reste à l’infinitif. Les deux verbes forment ici le futur proche."},
   {exampleFr:futureSource.pattern,explanationFr:"Cherche les deux éléments ensemble : vais, vas, va, allons, allez ou vont, puis un infinitif. Nous allons vérifier suit ce modèle."},
   {exampleFr:"Nous allons au stade. Nous allons regarder le match.",explanationFr:"Dans la première phrase, au stade indique une destination : il n’y a pas d’infinitif après allons. Dans la seconde, allons regarder annonce ce qui va se passer."},
   {exampleFr:"Demain, elle prépare le repas. Elle va préparer le repas.",explanationFr:"Une phrase peut parler de l’avenir sans employer le futur proche. Repère la construction verbale : le mot demain, à lui seul, ne donne pas le nom du temps."},
  ],
  takeawayFr:"Pour reconnaître le futur proche, cherche aller au présent suivi d’un infinitif. Vérifie la construction entière, pas seulement un mot lié à l’avenir.",
  boundaryFr:"Cette leçon porte sur la reconnaissance de la construction. Elle ne suffit pas pour conjuguer tous les verbes ni expliquer toutes les intentions exprimées dans un texte. Futur proche ne signifie pas toujours dans quelques secondes : le contexte précise le moment.",
  practice:[
   {id:"recognition-futur-guide-1",promptFr:"Tu vas réserver une place.\n\nQuel groupe forme le futur proche ?",choices:["vas réserver","réserver une place","Tu vas","une place"],answerFr:"vas réserver",hintFr:"Cherche aller au présent et l’infinitif qui le suit.",explanationFr:"Vas est aller au présent; réserver est l’infinitif. Le groupe verbal est vas réserver."},
   {id:"recognition-futur-guide-2",promptFr:"Quelle phrase contient un futur proche ?",choices:["Elles vont installer la tente.","Elles installent la tente.","Elles ont installé la tente.","Elles viennent d’installer la tente."],answerFr:"Elles vont installer la tente.",hintFr:"Repère la forme vont, puis le verbe qui suit.",explanationFr:"Vont installer associe aller au présent à un infinitif. Ont installé est un passé composé; viennent d’installer est un passé récent."},
   {id:"recognition-futur-guide-3",promptFr:"Dans quelle phrase aller forme-t-il un futur proche ?",choices:["Nous allons visiter la ferme.","Nous allons à la ferme.","Nous sommes allés à la ferme.","Nous allions à la ferme."],answerFr:"Nous allons visiter la ferme.",hintFr:"Une destination après aller ne suffit pas : cherche un infinitif.",explanationFr:"Visiter est l’infinitif qui suit allons. À la ferme est un complément de lieu dans les autres phrases."},
   {id:"recognition-futur-guide-4",promptFr:"Elle ne va pas participer au concours.\n\nQuel repère permet de reconnaître le futur proche ?",choices:["Va au présent et participer à l’infinitif.","Le mot concours.","La présence de ne et pas seulement.","Participer est conjugué au présent."],answerFr:"Va au présent et participer à l’infinitif.",hintFr:"La négation peut séparer les deux verbes sans faire disparaître la construction.",explanationFr:"Ne va pas participer contient toujours aller au présent et l’infinitif participer. La négation ne transforme pas participer en verbe conjugué."},
   {id:"recognition-futur-guide-5",promptFr:"Les quatre phrases parlent de demain. Laquelle emploie le futur proche ?",choices:["Demain, je vais ranger ma chambre.","Demain, je range ma chambre.","Demain, je rangerai ma chambre.","Demain, ma chambre sera rangée."],answerFr:"Demain, je vais ranger ma chambre.",hintFr:"Demain apparaît partout. Quelle phrase suit le modèle aller au présent + infinitif ?",explanationFr:"Vais ranger est le futur proche. Le moment annoncé ne suffit pas à distinguer les constructions."},
   {id:"recognition-futur-guide-6",promptFr:"Vous allez bientôt recevoir les invitations.\n\nQuels sont les deux verbes de la construction du futur proche ?",choices:["Allez et recevoir.","Allez et bientôt.","Recevoir et invitations.","Vous et allez."],answerFr:"Allez et recevoir.",hintFr:"Bientôt est un mot qui précise le moment, pas un verbe.",explanationFr:"Allez est aller au présent et recevoir est l’infinitif. Bientôt s’insère entre les deux sans changer cette construction."},
  ],
 },
 {
  id:"french-v3-teaching:recognition:passe_recent",nodeKey:"reconnaitre_passe_recent",mode:"recognition",status:"draft_requires_review",
  titleFr:"Reconnaître le passé récent",learnerQuestionFr:"Que repérer dans « elle vient de finir » ?",
  steps:[
   {exampleFr:pastSource.examples[0],explanationFr:"L’action de finir est présentée comme tout juste terminée. Vient est venir au présent, de relie les verbes et finir reste à l’infinitif : c’est le passé récent."},
   {exampleFr:pastSource.pattern,explanationFr:"Cherche viens, vient, venons, venez ou viennent, puis de ou d’ et un infinitif. Devant une voyelle, de devient d’ : ils viennent d’arriver."},
   {exampleFr:"Je viens de Bordeaux. Je viens de téléphoner.",explanationFr:"De Bordeaux indique une provenance, pas un verbe à l’infinitif. De téléphoner fait partie du passé récent : l’appel vient de se terminer."},
   {exampleFr:"Elle vient de peindre le banc. Elle a peint le banc.",explanationFr:"Les deux phrases parlent d’une action passée, mais elles n’utilisent pas la même construction. Vient de peindre est un passé récent; a peint est un passé composé."},
  ],
  takeawayFr:"Repère venir au présent + de ou d’ + infinitif. Un lieu après venir de ne forme pas un passé récent.",
  boundaryFr:"Cette leçon porte sur venir au présent. La forme venait de situe une action par rapport à un autre moment passé et demande un autre repère. Reconnaître la construction ne prouve pas encore que tu sais la produire ou interpréter tous ses usages.",
  practice:[
   {id:"recognition-recent-guide-1",promptFr:"Nous venons de fermer la boutique.\n\nQuel groupe forme le passé récent ?",choices:["venons de fermer","fermer la boutique","Nous venons","la boutique"],answerFr:"venons de fermer",hintFr:"Garde venir, de et l’infinitif dans le même groupe.",explanationFr:"Venons est venir au présent. Avec de et fermer à l’infinitif, il forme le passé récent."},
   {id:"recognition-recent-guide-2",promptFr:"Quelle phrase contient un passé récent ?",choices:["Ils viennent de découvrir la réponse.","Ils découvrent la réponse.","Ils ont découvert la réponse.","Ils vont découvrir la réponse."],answerFr:"Ils viennent de découvrir la réponse.",hintFr:"Cherche venir au présent, puis de et un infinitif.",explanationFr:"Viennent de découvrir indique une découverte tout juste faite. Vont découvrir annonce une découverte à venir."},
   {id:"recognition-recent-guide-3",promptFr:"Quelle phrase suit le modèle du passé récent ?",choices:["Tu viens d’ouvrir la fenêtre.","Tu viens de la bibliothèque.","Tu viens au jardin.","Tu es venu au jardin."],answerFr:"Tu viens d’ouvrir la fenêtre.",hintFr:"Ouvrir est un infinitif. Bibliothèque et jardin sont des noms de lieux.",explanationFr:"D’ est la forme de de devant ouvrir. Viens d’ouvrir contient les trois éléments du passé récent."},
   {id:"recognition-recent-guide-4",promptFr:"Vous venez de terminer votre dessin.\n\nQuelle est la forme du verbe terminer ici ?",choices:["Un infinitif après de.","Un participe passé.","Un verbe au futur simple.","Un verbe au présent avec vous."],answerFr:"Un infinitif après de.",hintFr:"Le verbe conjugué avec vous est venez.",explanationFr:"Terminer reste à l’infinitif. C’est venez qui porte les marques du présent et de la personne."},
   {id:"recognition-recent-guide-5",promptFr:"Dans quelle phrase venir indique-t-il une provenance, sans former un passé récent ?",choices:["Elle vient du village voisin.","Elle vient de poser son sac.","Elle vient d’envoyer un message.","Elle vient de prendre une photo."],answerFr:"Elle vient du village voisin.",hintFr:"Cherche un lieu après venir, sans infinitif.",explanationFr:"Du village voisin indique d’où elle vient. Les trois autres phrases contiennent venir au présent, de ou d’ et un infinitif."},
   {id:"recognition-recent-guide-6",promptFr:"Il a réparé le vélo. Il vient de réparer le vélo.\n\nQuelle différence de construction voit-on ?",choices:["A réparé est un passé composé; vient de réparer est un passé récent.","Les deux groupes sont au futur proche.","Réparé et réparer sont tous deux des infinitifs.","Vient de réparer ne contient aucun verbe conjugué."],answerFr:"A réparé est un passé composé; vient de réparer est un passé récent.",hintFr:"Compare avoir + participe passé avec venir de + infinitif.",explanationFr:"A réparé utilise un auxiliaire et un participe passé. Vient de réparer utilise venir au présent, de et un infinitif."},
  ],
 },
];
export const PERIPHRASTIC_RECOGNITION_TEACHING:readonly TargetTeachingContent[]=drafts.map(lesson=>({...lesson,materialExposure:{sentences:[...lesson.steps.map(step=>step.exampleFr),...lesson.practice.flatMap(exercise=>[exercise.promptFr,...(exercise.choices??[])]) ]}}));
