import {conjugate,type Person} from '@/lib/linguistic/conjugation';
import {conjugationSentenceGap} from './conjugation-sentence';
const contexts:readonly [string,Person,string][]=[
 ['finir','1s','Quand le bus est arrivé, je ___ mon petit déjeuner.'],
 ['choisir','2s','Avant notre départ, tu ___ le trajet.'],
 ['réussir','3s','Quand la finale a commencé, la candidate ___ toutes les épreuves précédentes.'],
 ['finir','1p','À l’arrivée du camion, nous ___ le rangement.'],
 ['choisir','2p','Quand le serveur est revenu, vous ___ le dessert.'],
 ['réussir','3p','Avant le concert, les élèves ___ leur audition.'],
 ['choisir','1s','Quand tu as appelé, je ___ un titre pour notre journal.'],
 ['réussir','2s','Avant de sortir, tu ___ la dernière énigme.'],
 ['finir','3s','Quand la lumière s’est éteinte, la classe ___ la lecture.'],
 ['choisir','1p','Avant la réunion, nous ___ les photographies.'],
 ['finir','2p','À dix-huit heures, vous ___ le montage de la maquette.'],
 ['réussir','3p','Quand leur famille est arrivée, les apprentis ___ leur première recette.'],
 ['manger','1s','Quand le film a commencé, je ___ mon sandwich.'],
 ['nager','2s','À midi, tu ___ pendant une heure.'],
 ['voyager','3s','Avant cette rencontre, la journaliste ___ au Pérou.'],
 ['manger','1p','Quand les invités sont arrivés, nous ___ le dessert.'],
 ['nager','2p','À la fermeture du bassin, vous ___ vingt longueurs.'],
 ['voyager','3p','Avant leur installation, les artistes ___ dans plusieurs pays.'],
 ['voyager','1s','Avant cet été-là, je ___ seulement en train.'],
 ['manger','2s','Quand la récréation a commencé, tu ___ ton fruit.'],
 ['nager','3s','Avant de rejoindre la plage, la nageuse ___ jusqu’à la balise.'],
 ['voyager','1p','Quand nous sommes arrivés, nous ___ toute la nuit.'],
 ['manger','2p','Quand le guide est venu, vous ___ près du port.'],
 ['nager','3p','Avant la compétition, les athlètes ___ dans ce bassin.'],
 ['commencer','1s','Quand tu as appelé, je ___ la préparation du repas.'],
 ['lancer','2s','Quand le chien a bondi, tu ___ la balle.'],
 ['avancer','3s','Au moment de la panne, le robot ___ de deux mètres.'],
 ['commencer','1p','Quand la pluie est tombée, nous ___ la visite.'],
 ['lancer','2p','Quand le match a été arrêté, vous ___ trois fois le ballon.'],
 ['avancer','3p','Quand le soleil s’est levé, les marcheurs ___ de six kilomètres.'],
 ['avancer','1s','Avant ton arrivée, je ___ les tables près du mur.'],
 ['commencer','2s','Quand le professeur est entré, tu ___ ton dessin.'],
 ['lancer','3s','À la fin de la journée, la mairie ___ la campagne.'],
 ['avancer','1p','Au moment du contrôle, nous ___ tous les cartons vers la sortie.'],
 ['commencer','2p','Quand la cloche a sonné, vous ___ la deuxième page.'],
 ['lancer','3p','Avant le tournoi, les élèves ___ un appel aux bénévoles.'],
];
export const PLUS_QUE_PARFAIT_FAMILY_APPLICATIONS=contexts.map(([verb,person,sentence])=>({verb,person,sentence:conjugationSentenceGap(sentence,conjugate(verb,'plus_que_parfait',person)),answer:conjugate(verb,'plus_que_parfait',person)}));
