import {conjugate,PERSONS,type Person} from '@/lib/linguistic/conjugation';
import {CONJUGATION_TEACHING_CASES} from './conjugation-teaching';
import {conjugationSentenceGap} from './conjugation-sentence';
import type {TargetTeachingContent} from './teaching-content';
const subjects:Record<Person,string>={'1s':'je','2s':'tu','3s':'il / elle','1p':'nous','2p':'vous','3p':'ils / elles'};
export const PLUS_QUE_PARFAIT_FAMILY_TEACHING:readonly TargetTeachingContent[]=CONJUGATION_TEACHING_CASES.filter(d=>d.key.startsWith('pattern:')).map(d=>{
 const verb=d.model,ir=d.key==='pattern:regular_ir',participle=conjugate(verb,'plus_que_parfait','1s').split(' ').slice(1).join(' ');
 const practice=d.cases.map((row,index)=>{
  const answerFr=conjugate(row.verb,'plus_que_parfait',row.person),sentence=conjugationSentenceGap(row.sentence,answerFr),pp=answerFr.split(' ').slice(1).join(' ');
  return {id:`plus-que-parfait:${d.key}:guided-${index}`,promptFr:`Complète avec ${row.verb} au plus-que-parfait. Écris le groupe verbal manquant : ${sentence}`,answerFr,hintFr:`Avec ${subjects[row.person]}, avoir à l’imparfait donne ${conjugate('avoir','imparfait',row.person)}. Ajoute le participe passé de ${row.verb} : ${pp}.`,explanationFr:`${sentence.replace('___',answerFr)} ${conjugate('avoir','imparfait',row.person)} est l’auxiliaire, le verbe qui aide à former ce temps. ${pp} est le participe passé de ${row.verb}.`};
 });
 const steps:TargetTeachingContent['steps']=[
  {exampleFr:'Quand Zoé est arrivée, nous avions déjà terminé le rangement.',explanationFr:'Deux moments sont dans le passé : le rangement était fini avant l’arrivée de Zoé. Avions terminé indique l’action accomplie en premier. Le plus-que-parfait utilise un verbe qui aide, appelé auxiliaire, et une forme du verbe de l’action, appelée participe passé.'},
  {exampleFr:`${verb} → ${participle} ; j’${conjugate('avoir','imparfait','1s')} ${participle}`,explanationFr:`Dans ces phrases, le verbe qui aide est avoir, conjugué à l’imparfait. Pour ce modèle, ${ir?'remplace -ir par -i pour former le participe passé':'remplace -er par -é, avec un accent aigu, pour former le participe passé'}.`},
  ...(d.key==='pattern:spelling_ger'?[{exampleFr:'Je mangeais. J’avais mangé. Nous avions mangé.',explanationFr:'Ne transporte pas le e de mangeais dans le participe passé. Manger devient mangé, sans e supplémentaire : le é permet déjà au g de garder le même son.'}]:d.key==='pattern:spelling_cer'?[{exampleFr:'Je lançais. J’avais lancé. Nous avions lancé.',explanationFr:'Devant le é de lancé, le c garde le son s sans cédille. N’écris pas lançé. La cédille de lançais ne se transporte pas dans le participe passé.'}]:[]),
  {exampleFr:PERSONS.map(p=>`${subjects[p]} : ${conjugate(verb,'plus_que_parfait',p)}`).join('\n'),explanationFr:'Le sujet fait changer avoir : avais, avais, avait, avions, aviez, avaient. Dans ces phrases sans complément direct placé avant le verbe, le participe passé ne change pas selon le sujet.'},
 ];
 return {id:`french-v3-teaching:plus-que-parfait:${d.key}`,nodeKey:'produire_plus_que_parfait',facetKey:`produire_plus_que_parfait::${d.key}`,mode:'production',status:'draft_requires_review',titleFr:`Écrire les verbes comme ${verb} au plus-que-parfait`,learnerQuestionFr:`Comment raconter une action déjà accomplie avant un autre moment passé avec les verbes comme ${verb} ?`,steps,practice,takeawayFr:`Écris avoir à l’imparfait avec le sujet, puis le participe passé : ${participle}.`,boundaryFr:`Le temps est donné ici : cette leçon ne vérifie pas le choix entre imparfait et plus-que-parfait. Elle traite des phrases avec avoir, sans complément direct placé avant le verbe. L’auxiliaire être, les verbes pronominaux et l’accord avec un complément placé avant demandent d’autres vérifications. ${ir?'Tous les verbes en -ir ne suivent pas finir.':'Tous les verbes en -er ne suivent pas ce modèle : aller se travaille séparément.'}`,materialExposure:{words:[...new Set([verb,'avoir','être','terminer',...d.cases.map(c=>c.verb),...(ir?[]:['aller'])])].map(lemma=>({lemma,form:lemma==='terminer'?'terminé':lemma})),sentences:[...steps.flatMap(s=>s.exampleFr.split('\n')),...practice.map(p=>p.explanationFr.split('. ')[0]+'.')]}};
});
