import type { Person } from "@/lib/linguistic/conjugation";

/** Original sentence gaps for controlled present-form application. The tense is
 * supplied; these do not assess tense choice or independent connected writing. */
export const PRESENT_APPLICATION_CONTEXTS: readonly [verb: string, person: Person, sentence: string][] = [
  ["parler", "1s", "Je ___ avec le bibliothécaire."],
  ["jouer", "2s", "Tu ___ aux échecs avec ta cousine."],
  ["aimer", "3s", "Ma sœur ___ les histoires de dragons."],
  ["donner", "1p", "Nous ___ nos anciens livres à une association."],
  ["regarder", "2p", "Vous ___ les oiseaux près du lac."],
  ["chanter", "3p", "Les enfants ___ dans la cour."],
  ["travailler", "1s", "Je ___ sur le journal du collège."],
  ["aimer", "2s", "Tu ___ résoudre des énigmes."],
  ["parler", "3s", "Le guide ___ des animaux de la forêt."],
  ["jouer", "1p", "Nous ___ une scène de théâtre."],
  ["donner", "2p", "Vous ___ un titre à votre affiche."],
  ["regarder", "3p", "Mes cousins ___ les étoiles."],
  ["finir", "1s", "Je ___ la construction de mon robot."],
  ["choisir", "2s", "Tu ___ une couleur pour la porte."],
  ["grandir", "3s", "Le jeune arbre ___ près de la fenêtre."],
  ["réussir", "1p", "Nous ___ ce défi en équipe."],
  ["finir", "2p", "Vous ___ le montage de la vidéo."],
  ["choisir", "3p", "Les joueuses ___ un nom pour leur équipe."],
  ["réussir", "1s", "Je ___ mon premier saut."],
  ["grandir", "2s", "Tu ___ entouré de tes cousins."],
  ["finir", "3s", "Le spectacle ___ avant vingt heures."],
  ["choisir", "1p", "Nous ___ un itinéraire sur la carte."],
  ["grandir", "2p", "Vous ___ dans le même quartier."],
  ["réussir", "3p", "Les équipes ___ toutes les étapes du parcours."],
  ["aller", "1s", "Je ___ chez le dentiste."],
  ["aller", "2s", "Tu ___ vers la sortie."],
  ["aller", "3s", "Le groupe ___ à la gare."],
  ["aller", "1p", "Nous ___ au club d’échecs."],
  ["aller", "2p", "Vous ___ chez vos grands-parents."],
  ["aller", "3p", "Mes voisines ___ au concert."],
  ["aller", "1s", "Je ___ à la boulangerie."],
  ["aller", "2s", "Tu ___ au cours de dessin."],
  ["aller", "3s", "Mon frère ___ à l’atelier."],
  ["aller", "1p", "Nous ___ vers la rivière."],
  ["aller", "2p", "Vous ___ à l’exposition."],
  ["aller", "3p", "Les élèves ___ au réfectoire."],
  ["faire", "1s", "Je ___ une liste de courses."],
  ["faire", "2s", "Tu ___ un nœud avec cette corde."],
  ["faire", "3s", "Sam ___ la vaisselle."],
  ["faire", "1p", "Nous ___ des recherches sur les volcans."],
  ["faire", "2p", "Vous ___ un détour par le pont."],
  ["faire", "3p", "Les jumelles ___ de la musique."],
  ["faire", "1s", "Je ___ attention aux cyclistes."],
  ["faire", "2s", "Tu ___ équipe avec Lila."],
  ["faire", "3s", "Le cuisinier ___ cuire le riz."],
  ["faire", "1p", "Nous ___ le tour du lac."],
  ["faire", "2p", "Vous ___ un croquis de la maison."],
  ["faire", "3p", "Les comédiens ___ rire le public."],
];
