import type { Person } from "@/lib/linguistic/conjugation";

/** Original sentence gaps for controlled present-form application. The tense is
 * supplied; these do not assess tense choice or independent connected writing. */
export const PRESENT_APPLICATION_CONTEXTS: readonly [verb: string, person: Person, sentence: string][] = [
  ["parler", "1s", "Je ___ avec le bibliothécaire."],
  ["jouer", "2s", "Tu ___ aux échecs avec ta cousine."],
  ["aimer", "3s", "Ma sœur ___ les histoires de dragons."],
  ["donner", "1p", "Nous ___ nos anciens livres à une association."],
  ["regarder", "2p", "Vous ___ les oiseaux près du lac."],
  ["chanter", "3p", "Les enfants ___ dans la cour."],
  ["travailler", "1s", "Je ___ sur le journal du collège."],
  ["aimer", "2s", "Tu ___ résoudre des énigmes."],
  ["parler", "3s", "Le guide ___ des animaux de la forêt."],
  ["jouer", "1p", "Nous ___ une scène de théâtre."],
  ["donner", "2p", "Vous ___ un titre à votre affiche."],
  ["regarder", "3p", "Mes cousins ___ les étoiles."],
  ["finir", "1s", "Je ___ la construction de mon robot."],
  ["choisir", "2s", "Tu ___ une couleur pour la porte."],
  ["grandir", "3s", "Le jeune arbre ___ près de la fenêtre."],
  ["réussir", "1p", "Nous ___ ce défi en équipe."],
  ["finir", "2p", "Vous ___ le montage de la vidéo."],
  ["choisir", "3p", "Les joueuses ___ un nom pour leur équipe."],
  ["réussir", "1s", "Je ___ mon premier saut."],
  ["grandir", "2s", "Tu ___ entouré de tes cousins."],
  ["finir", "3s", "Le spectacle ___ avant vingt heures."],
  ["choisir", "1p", "Nous ___ un itinéraire sur la carte."],
  ["grandir", "2p", "Vous ___ dans le même quartier."],
  ["réussir", "3p", "Les équipes ___ toutes les étapes du parcours."],
  ["aller", "1s", "Je ___ chez le dentiste."],
  ["aller", "2s", "Tu ___ vers la sortie."],
  ["aller", "3s", "Le groupe ___ à la gare."],
  ["aller", "1p", "Nous ___ au club d’échecs."],
  ["aller", "2p", "Vous ___ chez vos grands-parents."],
  ["aller", "3p", "Mes voisines ___ au concert."],
  ["aller", "1s", "Je ___ à la boulangerie."],
  ["aller", "2s", "Tu ___ au cours de dessin."],
  ["aller", "3s", "Mon frère ___ à l’atelier."],
  ["aller", "1p", "Nous ___ vers la rivière."],
  ["aller", "2p", "Vous ___ à l’exposition."],
  ["aller", "3p", "Les élèves ___ au réfectoire."],
  ["faire", "1s", "Je ___ une liste de courses."],
  ["faire", "2s", "Tu ___ un nœud avec cette corde."],
  ["faire", "3s", "Sam ___ la vaisselle."],
  ["faire", "1p", "Nous ___ des recherches sur les volcans."],
  ["faire", "2p", "Vous ___ un détour par le pont."],
  ["faire", "3p", "Les jumelles ___ de la musique."],
  ["faire", "1s", "Je ___ attention aux cyclistes."],
  ["faire", "2s", "Tu ___ équipe avec Lila."],
  ["faire", "3s", "Le cuisinier ___ cuire le riz."],
  ["faire", "1p", "Nous ___ le tour du lac."],
  ["faire", "2p", "Vous ___ un croquis de la maison."],
  ["faire", "3p", "Les comédiens ___ rire le public."],
  ["être", "1s", "Je ___ responsable du ballon."],
  ["être", "2s", "Tu ___ le premier à répondre."],
  ["être", "3s", "Le magasin ___ fermé le lundi."],
  ["être", "1p", "Nous ___ heureux de participer."],
  ["être", "2p", "Vous ___ sur la bonne piste."],
  ["être", "3p", "Les fenêtres ___ ouvertes."],
  ["être", "1s", "Je ___ à côté du piano."],
  ["être", "2s", "Tu ___ très patient avec le chiot."],
  ["être", "3s", "La lampe ___ allumée."],
  ["être", "1p", "Nous ___ membres du club de lecture."],
  ["être", "2p", "Vous ___ invités à la répétition."],
  ["être", "3p", "Les valises ___ sous le banc."],
  ["avoir", "1s", "J’___ envie de dessiner."],
  ["avoir", "2s", "Tu ___ froid sans ton manteau."],
  ["avoir", "3s", "Le vélo ___ deux pneus neufs."],
  ["avoir", "1p", "Nous ___ rendez-vous à midi."],
  ["avoir", "2p", "Vous ___ plusieurs solutions."],
  ["avoir", "3p", "Les musiciens ___ besoin de silence."],
  ["avoir", "1s", "J’___ douze cartes en main."],
  ["avoir", "2s", "Tu ___ raison de demander."],
  ["avoir", "3s", "Le bâtiment ___ trois étages."],
  ["avoir", "1p", "Nous ___ confiance en notre équipe."],
  ["avoir", "2p", "Vous ___ encore quelques minutes."],
  ["avoir", "3p", "Les tortues ___ une carapace."],
  ["prendre", "1s", "Je ___ la dernière part de tarte."],
  ["prendre", "2s", "Tu ___ soin de ces plantes."],
  ["prendre", "3s", "Le gardien ___ les clés du portail."],
  ["prendre", "1p", "Nous ___ le sentier de gauche."],
  ["prendre", "2p", "Vous ___ votre repas dehors."],
  ["prendre", "3p", "Les touristes ___ un plan de la ville."],
  ["prendre", "1s", "Je ___ une serviette propre."],
  ["prendre", "2s", "Tu ___ la parole après Inès."],
  ["prendre", "3s", "La réunion ___ fin à dix heures."],
  ["prendre", "1p", "Nous ___ place devant la scène."],
  ["prendre", "2p", "Vous ___ une décision ensemble."],
  ["prendre", "3p", "Les pompiers ___ la route du village."],
  ["venir", "1s", "Je ___ rendre ton casque."],
  ["venir", "2s", "Tu ___ me montrer ta bande dessinée."],
  ["venir", "3s", "Le facteur ___ chaque matin."],
  ["venir", "1p", "Nous ___ apporter des couvertures."],
  ["venir", "2p", "Vous ___ du quartier voisin."],
  ["venir", "3p", "Les visiteurs ___ admirer les tableaux."],
  ["venir", "1s", "Je ___ poser une question."],
  ["venir", "2s", "Tu ___ récupérer ton parapluie."],
  ["venir", "3s", "La lumière ___ de cette fenêtre."],
  ["venir", "1p", "Nous ___ soutenir les coureurs."],
  ["venir", "2p", "Vous ___ goûter notre soupe."],
  ["venir", "3p", "Les cris ___ du terrain de sport."],
  ["partir", "1s", "Je ___ pour Lyon samedi."],
  ["partir", "2s", "Tu ___ avant la fin du film."],
  ["partir", "3s", "Le bateau ___ du port."],
  ["partir", "1p", "Nous ___ explorer la forêt."],
  ["partir", "2p", "Vous ___ sans vos bagages."],
  ["partir", "3p", "Les oiseaux ___ vers le sud."],
  ["partir", "1s", "Je ___ à la recherche du chat."],
  ["partir", "2s", "Tu ___ avec une gourde pleine."],
  ["partir", "3s", "La fusée ___ dans quelques secondes."],
  ["partir", "1p", "Nous ___ du même point."],
  ["partir", "2p", "Vous ___ au lever du soleil."],
  ["partir", "3p", "Les voyageurs ___ pour la montagne."],
  ["sortir", "1s", "Je ___ les assiettes du placard."],
  ["sortir", "2s", "Tu ___ de ton atelier."],
  ["sortir", "3s", "Le lapin ___ de sa cachette."],
  ["sortir", "1p", "Nous ___ prendre l’air."],
  ["sortir", "2p", "Vous ___ vos instruments."],
  ["sortir", "3p", "Les spectateurs ___ de la salle."],
  ["sortir", "1s", "Je ___ mon carnet de croquis."],
  ["sortir", "2s", "Tu ___ par le petit portail."],
  ["sortir", "3s", "La fumée ___ de la cheminée."],
  ["sortir", "1p", "Nous ___ de chez le coiffeur."],
  ["sortir", "2p", "Vous ___ les cartons du garage."],
  ["sortir", "3p", "Les poussins ___ de leurs œufs."],
  ["dire", "1s", "Je ___ merci au chauffeur."],
  ["dire", "2s", "Tu ___ ce mot trop vite."],
  ["dire", "3s", "Le médecin ___ de se reposer."],
  ["dire", "1p", "Nous ___ au revoir à nos cousins."],
  ["dire", "2p", "Vous ___ pourquoi vous êtes absents."],
  ["dire", "3p", "Les témoins ___ ce qu’ils ont vu."],
  ["dire", "1s", "Je ___ la date à voix haute."],
  ["dire", "2s", "Tu ___ ton adresse au livreur."],
  ["dire", "3s", "Cette pancarte ___ de ralentir."],
  ["dire", "1p", "Nous ___ le nom de notre chanson préférée."],
  ["dire", "2p", "Vous ___ oui à cette proposition."],
  ["dire", "3p", "Les enfants ___ bonne nuit à leur grand-mère."],
  ["voir", "1s", "Je ___ une montgolfière au loin."],
  ["voir", "2s", "Tu ___ le phare depuis la plage."],
  ["voir", "3s", "Le chat ___ un oiseau."],
  ["voir", "1p", "Nous ___ les montagnes depuis le toit."],
  ["voir", "2p", "Vous ___ une différence entre ces photos."],
  ["voir", "3p", "Les astronomes ___ une nouvelle comète."],
  ["voir", "1s", "Je ___ mon reflet dans la vitre."],
  ["voir", "2s", "Tu ___ la fin du tunnel."],
  ["voir", "3s", "La conductrice ___ le feu rouge."],
  ["voir", "1p", "Nous ___ un arc-en-ciel."],
  ["voir", "2p", "Vous ___ le sommet à travers les nuages."],
  ["voir", "3p", "Les plongeurs ___ des poissons colorés."],
  ["pouvoir", "1s", "Je ___ porter cette boîte."],
  ["pouvoir", "2s", "Tu ___ emprunter mon stylo."],
  ["pouvoir", "3s", "Le public ___ poser des questions."],
  ["pouvoir", "1p", "Nous ___ construire un abri."],
  ["pouvoir", "2p", "Vous ___ consulter le plan."],
  ["pouvoir", "3p", "Les passagers ___ descendre ici."],
  ["pouvoir", "1s", "Je ___ traduire cette phrase."],
  ["pouvoir", "2s", "Tu ___ ouvrir ton cadeau."],
  ["pouvoir", "3s", "Cette clé ___ tourner dans la serrure."],
  ["pouvoir", "1p", "Nous ___ partager le trajet."],
  ["pouvoir", "2p", "Vous ___ éteindre la lumière."],
  ["pouvoir", "3p", "Les bénévoles ___ préparer la salle."],
  ["vouloir", "1s", "Je ___ visiter cette île."],
  ["vouloir", "2s", "Tu ___ devenir vétérinaire."],
  ["vouloir", "3s", "Le client ___ échanger son billet."],
  ["vouloir", "1p", "Nous ___ planter des arbres."],
  ["vouloir", "2p", "Vous ___ raconter votre voyage."],
  ["vouloir", "3p", "Les voisins ___ nettoyer la plage."],
  ["vouloir", "1s", "Je ___ goûter ce fruit."],
  ["vouloir", "2s", "Tu ___ photographier le coucher du soleil."],
  ["vouloir", "3s", "La chanteuse ___ remercier son public."],
  ["vouloir", "1p", "Nous ___ apprendre cette danse."],
  ["vouloir", "2p", "Vous ___ dessiner les costumes."],
  ["vouloir", "3p", "Les joueurs ___ améliorer leur défense."],
  ["savoir", "1s", "Je ___ préparer une omelette."],
  ["savoir", "2s", "Tu ___ où se cache la clé."],
  ["savoir", "3s", "Le pilote ___ lire cette carte."],
  ["savoir", "1p", "Nous ___ reconnaître ce symbole."],
  ["savoir", "2p", "Vous ___ résoudre cette énigme."],
  ["savoir", "3p", "Les enfants ___ attacher leurs lacets."],
  ["savoir", "1s", "Je ___ quand passe le bus."],
  ["savoir", "2s", "Tu ___ fabriquer un cerf-volant."],
  ["savoir", "3s", "La guide ___ répondre aux questions."],
  ["savoir", "1p", "Nous ___ pourquoi la glace fond."],
  ["savoir", "2p", "Vous ___ garder un secret."],
  ["savoir", "3p", "Les secouristes ___ pratiquer les premiers gestes."],
  ["devoir", "1s", "Je ___ nourrir les poissons."],
  ["devoir", "2s", "Tu ___ mettre un casque."],
  ["devoir", "3s", "Le livreur ___ trouver une autre entrée."],
  ["devoir", "1p", "Nous ___ économiser l’eau."],
  ["devoir", "2p", "Vous ___ signer ce formulaire."],
  ["devoir", "3p", "Les coureurs ___ franchir la ligne."],
  ["devoir", "1s", "Je ___ rappeler mon cousin."],
  ["devoir", "2s", "Tu ___ peser les ingrédients."],
  ["devoir", "3s", "La gardienne ___ fermer le musée."],
  ["devoir", "1p", "Nous ___ respecter le silence."],
  ["devoir", "2p", "Vous ___ attendre votre tour."],
  ["devoir", "3p", "Les campeurs ___ éteindre leur feu."],
];
