/** Original fictional passages. Each question distinguishes relevant information
 * from other true details. Sources and difficulty remain pending human review. */
type Row=readonly [string,string,string,string,string,string,readonly string[]];
const narrative:readonly Row[]=[
 ['manga','Aya choisit un manga pour son frère.','Elle emprunte un roman pour sa sœur.','Pour elle-même, elle prend une bande dessinée.','Quel livre Aya emprunte-t-elle pour sa sœur ?','Un roman.',['Un manga.','Une bande dessinée.','Un dictionnaire.']],
 ['departure','Le car de Sami arrive à huit heures.','Sami retrouve son cousin à huit heures trente.','Le spectacle commence à neuf heures.','À quelle heure Sami retrouve-t-il son cousin ?','À huit heures trente.',['À huit heures.','À neuf heures.','À neuf heures trente.']],
 ['delivery','Lina laisse le pain chez sa grand-mère.','Elle apporte les fleurs chez sa tante.','Puis elle range les légumes chez elle.','Où Lina apporte-t-elle les fleurs ?','Chez sa tante.',['Chez sa grand-mère.','Chez elle.','Au marché.']],
 ['team','Noé porte le sac de ballons.','Malo distribue les maillots aux joueurs.','Jules remplit les gourdes.','Qui distribue les maillots ?','Malo.',['Noé.','Jules.','Les joueurs.']],
 ['coins','Inès dépense trois euros pour son trajet.','Elle paie cinq euros pour une place de cinéma.','Il lui reste deux euros pour une boisson.','Combien Inès paie-t-elle pour la place de cinéma ?','Cinq euros.',['Trois euros.','Deux euros.','Dix euros.']],
 ['keys','Yanis trouve une clé sous le canapé.','Il la pose sur le bureau de sa mère.','Il range ensuite son téléphone dans le tiroir.','Où Yanis pose-t-il la clé ?','Sur le bureau de sa mère.',['Sous le canapé.','Dans le tiroir.','Dans sa poche.']],
 ['rehearsal','Le matin, Zoé répète sa chanson seule.','À midi, elle la chante devant son amie.','Le soir, elle la présente à sa famille.','Quand Zoé chante-t-elle devant son amie ?','À midi.',['Le matin.','Le soir.','Toute la journée.']],
 ['drawing','Nassim dessine un pont au crayon.','Il colorie la rivière avec un feutre bleu.','Il ajoute le titre au stylo noir.','Avec quoi Nassim colorie-t-il la rivière ?','Un feutre bleu.',['Un crayon.','Un stylo noir.','Un pinceau.']],
 ['rescue','Emma appelle son père pour signaler la panne.','Sa voisine vient la chercher en voiture.','Son frère récupère le vélo le lendemain.','Qui vient chercher Emma en voiture ?','Sa voisine.',['Son père.','Son frère.','Emma elle-même.']],
 ['boxes','Dina prépare quatre boîtes pour les livres.','Elle utilise deux boîtes pour les vêtements.','Une dernière boîte contient ses chaussures.','Combien de boîtes contiennent les vêtements ?','Deux.',['Quatre.','Une.','Sept.']],
 ['message','Au réveil, Léo lit un message de Sara.','Après le déjeuner, il lui répond.','Avant de dormir, il reçoit sa réponse.','Quand Léo répond-il à Sara ?','Après le déjeuner.',['Au réveil.','Avant de dormir.','Pendant la nuit.']],
 ['route','Awa traverse le parc pour aller au théâtre.','Pour rentrer, elle passe par la place du marché.','Elle rejoint ensuite son immeuble près du stade.','Par où Awa passe-t-elle pour rentrer ?','Par la place du marché.',['Par le parc.','Par le stade.','Par le théâtre.']],
];
const informational:readonly Row[]=[
 ['club','Le club de dessin se réunit le lundi.','Le club de manga se réunit le jeudi.','Les deux clubs exposent leurs travaux le samedi.','Quel jour le club de manga se réunit-il ?','Le jeudi.',['Le lundi.','Le samedi.','Le dimanche.']],
 ['fees','L’entrée de l’exposition coûte quatre euros.','La visite guidée coûte deux euros de plus.','Le catalogue est vendu six euros.','Quel est le prix du catalogue ?','Six euros.',['Quatre euros.','Deux euros.','Dix euros.']],
 ['contacts','Pour emprunter une raquette, adressez-vous à Nora.','Pour réserver un terrain, contactez Idriss.','Les objets perdus sont conservés par Lucie.','Qui faut-il contacter pour réserver un terrain ?','Idriss.',['Nora.','Lucie.','Tous les trois.']],
 ['rooms','Les inscriptions ont lieu dans la salle verte.','Les ateliers se déroulent dans la salle jaune.','Les sacs doivent rester dans la salle bleue.','Où faut-il laisser les sacs ?','Dans la salle bleue.',['Dans la salle verte.','Dans la salle jaune.','Dans le couloir.']],
 ['times','Le bâtiment ouvre à neuf heures.','Le premier atelier commence à dix heures.','Les portes ferment à dix-sept heures.','À quelle heure le premier atelier commence-t-il ?','À dix heures.',['À neuf heures.','À dix-sept heures.','À midi.']],
 ['portions','Chaque équipe reçoit huit feuilles blanches.','Chaque équipe reçoit aussi trois feuilles rouges.','Deux crayons sont fournis avec le papier.','Combien de feuilles rouges reçoit chaque équipe ?','Trois.',['Huit.','Deux.','Onze.']],
 ['equipment','Pour le dessin, apportez un crayon.','Pour le collage, apportez des ciseaux.','Pour la peinture, apportez une blouse.','Quel objet faut-il apporter pour le collage ?','Des ciseaux.',['Un crayon.','Une blouse.','Un pinceau.']],
 ['deadlines','Les inscriptions ouvrent le 3 mai.','Le paiement doit être effectué avant le 12 mai.','La liste des participants sera publiée le 18 mai.','Avant quelle date faut-il payer ?','Le 12 mai.',['Le 3 mai.','Le 18 mai.','Le 31 mai.']],
 ['library','Les romans se trouvent au premier étage.','Les bandes dessinées sont au rez-de-chaussée.','Les documentaires sont au deuxième étage.','Où se trouvent les documentaires ?','Au deuxième étage.',['Au premier étage.','Au rez-de-chaussée.','Au sous-sol.']],
 ['transport','Le bus rouge dessert la gare.','Le bus vert dessert la piscine.','Le bus bleu dessert le musée.','Quel bus dessert la piscine ?','Le bus vert.',['Le bus rouge.','Le bus bleu.','Tous les bus.']],
 ['turns','Les débutants jouent pendant quinze minutes.','Les joueurs confirmés jouent pendant vingt minutes.','Une pause de cinq minutes sépare les parties.','Combien de temps dure une partie pour les débutants ?','Quinze minutes.',['Vingt minutes.','Cinq minutes.','Trente minutes.']],
 ['collection','Les piles usagées vont dans la boîte fermée.','Le papier va dans le bac ouvert.','Les vêtements sont déposés dans les sacs.','Où faut-il déposer le papier ?','Dans le bac ouvert.',['Dans la boîte fermée.','Dans les sacs.','Sur le sol.']],
];
const argumentative:readonly Row[]=[
 ['reading','Je souhaite créer un coin lecture dans la cour.','Je propose de placer les livres sous le préau et les jeux près du terrain.','Chacun pourrait ainsi choisir son activité pendant la pause.','Où la personne propose-t-elle de placer les livres ?','Sous le préau.',['Près du terrain.','Dans les classes.','À la bibliothèque.']],
 ['music','Un concert serait une bonne occasion de réunir les familles.','Je propose une répétition le mardi et le concert le vendredi.','Nous aurions le temps de corriger les derniers détails.','Quel jour le concert est-il proposé ?','Le vendredi.',['Le mardi.','Le mercredi.','Le dimanche.']],
 ['bikes','Nous devrions améliorer l’accueil des cyclistes.','Je demande six nouveaux supports pour les vélos et deux bancs pour se reposer.','Ces équipements rendraient l’entrée plus pratique.','Combien de supports pour les vélos sont demandés ?','Six.',['Deux.','Huit.','Quatre.']],
 ['workshop','Un atelier de cuisine permettrait de partager nos recettes.','Je propose que les élèves choisissent les plats et que les adultes achètent les ingrédients.','Cette répartition donnerait un rôle à chacun.','Qui choisirait les plats selon cette proposition ?','Les élèves.',['Les adultes.','Les commerçants.','Les cuisiniers du quartier.']],
 ['cinema','Organisons une soirée cinéma accessible à tous.','Je propose un billet à trois euros pour les élèves et à cinq euros pour les adultes.','Le tarif réduit aiderait les jeunes à participer.','Quel tarif est proposé pour les élèves ?','Trois euros.',['Cinq euros.','Huit euros.','Deux euros.']],
 ['recycling','Je pense que notre école devrait mieux trier ses déchets.','Plaçons un bac à papier dans chaque classe et un bac à piles à l’accueil.','Il serait alors plus facile de trouver le bon endroit.','Où serait placé le bac à piles ?','À l’accueil.',['Dans chaque classe.','Dans la cour.','À la cantine.']],
 ['games','Un tournoi de jeux de société ferait découvrir de nouveaux jeux.','Je propose de consacrer vingt minutes aux explications et quarante minutes aux parties.','Même les débutants pourraient comprendre les règles avant de jouer.','Combien de temps serait consacré aux explications ?','Vingt minutes.',['Quarante minutes.','Soixante minutes.','Dix minutes.']],
 ['garden','Créons un jardin que les élèves pourront entretenir ensemble.','Je propose de planter les fleurs près du portail et les légumes derrière la cantine.','Deux espaces distincts faciliteraient l’organisation.','Où les légumes seraient-ils plantés ?','Derrière la cantine.',['Près du portail.','Au centre de la cour.','Devant les classes.']],
 ['exchange','Un échange de mangas serait plus utile qu’une vente.','Je propose d’apporter les livres le lundi et de choisir ceux des autres le mercredi.','Chacun pourrait découvrir une histoire sans dépenser d’argent.','Quand pourrait-on choisir les livres des autres ?','Le mercredi.',['Le lundi.','Le vendredi.','Tous les jours.']],
 ['sports','Une journée sportive devrait laisser du temps pour se reposer.','Je propose des matchs le matin et des jeux calmes après le déjeuner.','Ce programme conviendrait à des envies différentes.','Quand les jeux calmes auraient-ils lieu ?','Après le déjeuner.',['Le matin.','Avant le petit déjeuner.','Pendant les matchs.']],
 ['costumes','Nous pourrions fabriquer les costumes de la pièce nous-mêmes.','Je propose de confier la couture à Salma et la peinture des décors à Hugo.','Nous utiliserions ainsi les talents de chacun.','Quelle tâche serait confiée à Hugo ?','La peinture des décors.',['La couture des costumes.','Le choix de la pièce.','La vente des billets.']],
 ['quiet','Je souhaite que la salle d’étude reste calme sans interdire tout travail en groupe.','Je propose une zone silencieuse à gauche et une zone de discussion à droite.','Les élèves pourraient choisir l’espace adapté à leur travail.','Où serait située la zone silencieuse ?','À gauche.',['À droite.','Dans le couloir.','Dans toute la salle.']],
];
export const QUESTION_DETAIL_READING_DRAFTS=([['narrative',narrative],['informational',informational],['argumentative',argumentative]] as const).flatMap(([genre,rows])=>rows.map(([key,before,support,after,question,answer,distractors],index)=>({key:`${genre}-${key}`,genre,nodeKey:'associer_information_question',passage:(genre!=='narrative'&&index%2===0?[support,before,after]:[before,support,after]).join(' '),support,otherSpans:[before,after],question,answer,distractors,reason:'Choisir le détail qui répond exactement à la question en distinguant plusieurs personnes, moments, lieux ou quantités énoncés dans le même passage.'})));
