import type {TargetTeachingContent} from './teaching-content';
type PracticeText={sentences:readonly [string,string,string];supportIndex:number;question:string;answer:string;others:string[];hint:string;explanation:string};
const practiceTexts:Record<string,PracticeText[]>={
 narrative:[
  {sentences:['Mina prête sa règle à son voisin.','Elle donne sa gomme à sa cousine.','Elle garde son compas pour son exercice.'],supportIndex:0,question:'Quel objet Mina prête-t-elle à son voisin ?',answer:'Sa règle.',others:['Sa gomme.','Son compas.','Son cahier.'],hint:'Cherche le voisin et l’action de prêter. La cousine est une autre personne.',explanation:'La règle est prêtée au voisin. La gomme est donnée à la cousine et le compas reste avec Mina.'},
  {sentences:['Oumar achète son billet le jeudi.','Il prend le train le samedi.','Il rentre chez lui le lundi.'],supportIndex:2,question:'Quel jour Oumar rentre-t-il chez lui ?',answer:'Le lundi.',others:['Le jeudi.','Le samedi.','Le vendredi.'],hint:'Les trois jours sont vrais, mais ils correspondent à trois actions différentes.',explanation:'Lundi correspond au retour. Jeudi concerne l’achat du billet et samedi le départ en train.'},
  {sentences:['Lou prépare cinq sandwichs pour ses amis.','Elle en met trois dans son sac.','Elle laisse les deux autres dans le panier de son frère.'],supportIndex:1,question:'Combien de sandwichs Lou met-elle dans son sac ?',answer:'Trois.',others:['Cinq.','Deux.','Huit.'],hint:'La question porte sur le sac, pas sur tous les sandwichs préparés.',explanation:'Trois sandwichs vont dans le sac. Cinq est le total préparé et deux le nombre laissé dans le panier.'},
 ],
 informational:[
  {sentences:['Les billets peuvent être achetés au guichet.','Les réservations de groupe se font par téléphone.','Les objets trouvés sont remis au bureau du gardien.'],supportIndex:2,question:'Où faut-il remettre un objet trouvé ?',answer:'Au bureau du gardien.',others:['Au guichet.','Dans la salle d’attente.','À l’accueil.'],hint:'Associe le lieu à l’action « remettre un objet trouvé ».',explanation:'Le bureau du gardien concerne les objets trouvés. Le guichet sert à acheter les billets.'},
  {sentences:['Le prêt des jeux dure une semaine.','Le prêt des livres dure trois semaines.','Le prêt des films dure deux semaines.'],supportIndex:1,question:'Combien de temps peut-on garder un livre ?',answer:'Trois semaines.',others:['Une semaine.','Deux semaines.','Six semaines.'],hint:'Toutes les durées sont écrites. Laquelle est associée aux livres ?',explanation:'Les livres sont prêtés trois semaines. Les autres durées concernent les jeux et les films.'},
  {sentences:['Pour installer les tables, demandez de l’aide à Bilal.','Pour régler le son, adressez-vous à Manon.','Pour ranger les chaises, rejoignez Éva.'],supportIndex:0,question:'Qui peut aider à installer les tables ?',answer:'Bilal.',others:['Manon.','Éva.','Les trois personnes.'],hint:'La question nomme une tâche précise : installer les tables.',explanation:'Bilal est associé aux tables. Manon s’occupe du son et Éva des chaises.'},
 ],
 argumentative:[
  {sentences:['Je propose un atelier de dessin à onze heures et une exposition à quinze heures.','Cette journée permettrait aux élèves de montrer leurs créations.','Les familles pourraient rencontrer les artistes après les ateliers.'],supportIndex:0,question:'À quelle heure l’exposition est-elle proposée ?',answer:'À quinze heures.',others:['À onze heures.','À midi.','Le texte ne propose aucune heure.'],hint:'Ne confonds pas l’heure de l’atelier avec celle de l’exposition.',explanation:'Quinze heures concerne l’exposition. Onze heures concerne l’atelier. Ce sont des horaires proposés, pas des événements déjà réalisés.'},
  {sentences:['Notre club devrait proposer des activités moins coûteuses.','Je propose une entrée gratuite et un repas à quatre euros.','Les élèves pourraient venir même sans acheter de repas.'],supportIndex:1,question:'Qu’est-ce qui serait gratuit ?',answer:'L’entrée.',others:['Le repas.','L’entrée et le repas.','Aucun des deux.'],hint:'La proposition distingue le prix de l’entrée et celui du repas.',explanation:'L’entrée serait gratuite, mais le repas coûterait quatre euros. La dernière phrase explique qu’il serait possible de ne pas acheter de repas.'},
  {sentences:['Nous devrions mieux répartir les tâches du journal.','Chacun pourrait ainsi se concentrer sur son rôle.','Je propose que Rania réalise les entretiens et que Karim prenne les photos.'],supportIndex:2,question:'Quelle tâche serait confiée à Rania ?',answer:'Réaliser les entretiens.',others:['Prendre les photos.','Imprimer le journal.','Réaliser toutes les tâches.'],hint:'Les deux personnes ont des rôles différents. Relis celui de Rania.',explanation:'Rania réaliserait les entretiens. Les photos seraient confiées à Karim. Il faut lire la proposition exacte, même si une autre organisation serait possible.'},
 ],
};
const introductions:Record<string,{title:string;example:string;question:string;explanation:string;boundary:string}>={
 narrative:{title:'Choisir le détail qui répond à la question dans une histoire',example:'Tess prend son parapluie dans l’entrée. Elle range ses bottes dans le placard.',question:'Où Tess range-t-elle ses bottes ?',explanation:'Dans le placard. L’entrée est aussi un lieu de l’histoire, mais elle concerne le parapluie. Choisis le lieu lié aux bottes et à l’action de les ranger.',boundary:'On cherche ici un détail écrit dans une courte histoire. Trouver une émotion cachée ou expliquer une intention demande un autre travail.'},
 informational:{title:'Choisir le bon renseignement dans une annonce',example:'La visite commence à quatorze heures. Le goûter est servi à seize heures.',question:'À quelle heure le goûter est-il servi ?',explanation:'À seize heures. Les deux horaires sont vrais, mais quatorze heures correspond à la visite. Un renseignement exact peut donc ne pas répondre à la question.',boundary:'On lit les renseignements de cette annonce. Ne remplace pas ce qui est écrit par les horaires que tu connais ailleurs.'},
 argumentative:{title:'Lire précisément les détails d’une proposition',example:'Je propose de commencer les répétitions en juin et de jouer la pièce en juillet. Nous aurions ainsi le temps de nous préparer.',question:'Quand la pièce serait-elle jouée selon cette proposition ?',explanation:'En juillet. Juin concerne les répétitions. On peut retrouver ce détail sans être d’accord avec la proposition.',boundary:'Une proposition n’est pas un fait déjà réalisé. Ici, on cherche ce que la personne propose, sans encore juger si ses raisons sont convaincantes.'},
};
export const QUESTION_DETAIL_READING_TEACHING:readonly TargetTeachingContent[]=Object.entries(practiceTexts).map(([genre,rows])=>{
 const intro=introductions[genre];
 const steps=[
  {exampleFr:intro.example,explanationFr:`${intro.question} ${intro.explanation}`},
  {exampleFr:`${intro.question} → Je repère l’action et ce que la question demande.`,explanationFr:'« Qui » demande une personne, « où » un lieu, « quand » un moment et « combien » une quantité. Relie aussi cette indication à la bonne action. Le détail utile est une information pertinente : il répond précisément à la question.'},
  {exampleFr:'Une phrase parle du bon personnage, mais pas de l’action demandée.',explanationFr:'Cela ne suffit pas. Relis la question entière, puis la phrase choisie. Vérifie la personne, l’objet, l’action et le moment utiles. Si le texte ne donne pas la réponse, ne l’invente pas.'},
 ];
 return {id:`french-v3-teaching:question-detail-reading:${genre}`,nodeKey:'associer_information_question',facetKey:`associer_information_question::text_type:${genre}`,mode:'interpretation',status:'draft_requires_review',titleFr:intro.title,learnerQuestionFr:'Plusieurs détails sont vrais. Lequel répond exactement à la question ?',steps,takeawayFr:'Repère ce que la question demande, choisis le détail lié à la bonne action, puis retrouve la phrase qui le prouve.',boundaryFr:intro.boundary,
 practice:rows.flatMap((row,index)=>{
  const passage=row.sentences.join(' '),support=row.sentences[row.supportIndex];
  return [
   {id:`question-detail-${genre}-${index}-answer`,promptFr:`${passage}\n\n${row.question}`,choices:[row.answer,...row.others],answerFr:row.answer,hintFr:row.hint,explanationFr:row.explanation},
   {id:`question-detail-${genre}-${index}-support`,promptFr:`${passage}\n\n${row.question}\nQuelle phrase contient l’information nécessaire pour répondre ?`,choices:[...row.sentences],answerFr:support,hintFr:'Choisis une phrase qui permet de répondre à la question, pas seulement une phrase du même texte.',explanationFr:`« ${support} » permet de répondre. ${row.explanation}`},
  ];
 }),materialExposure:{sentences:[...steps.map(s=>s.exampleFr),...rows.map(r=>r.sentences.join(' '))]}};
});
