type Row={key:string;passage:string;pronoun:string;answer:string;distractors:string[];support:string;otherSpans:string[]};
const rows:Row[]=[
 {key:'manga-return',passage:'Inès emprunte un manga à la bibliothèque. Elle glisse aussi une règle dans son sac. Le lendemain, elle le rend à la bibliothécaire. La règle reste dans le sac.',pronoun:'le',answer:'le manga',distractors:['la règle','le sac','le lendemain'],support:'Inès emprunte un manga à la bibliothèque.',otherSpans:['Elle glisse aussi une règle dans son sac.','La règle reste dans le sac.']},
 {key:'poster-wall',passage:'Malik termine une affiche pour le tournoi. Son frère lui prête un marteau. Malik la fixe sur le panneau du club. Puis il rapporte le marteau à son frère.',pronoun:'la',answer:'une affiche',distractors:['un marteau','le panneau','son frère'],support:'Malik termine une affiche pour le tournoi.',otherSpans:['Son frère lui prête un marteau.','Puis il rapporte le marteau à son frère.']},
 {key:'keys-found',passage:'Nora cherche ses clés avant de partir. Sa veste est déjà sur ses épaules. Elle les retrouve sous une revue. Elle peut enfin fermer la porte.',pronoun:'les',answer:'ses clés',distractors:['sa veste','une revue','ses épaules'],support:'Nora cherche ses clés avant de partir.',otherSpans:['Sa veste est déjà sur ses épaules.','Elle peut enfin fermer la porte.']},
 {key:'coach-message',passage:'La capitaine doit prévenir son entraîneuse du retard du car. Les autres joueuses attendent près du portail. La capitaine lui envoie un message. Le car arrive peu après.',pronoun:'lui',answer:'son entraîneuse',distractors:['les autres joueuses','le car','le portail'],support:'La capitaine doit prévenir son entraîneuse du retard du car.',otherSpans:['Les autres joueuses attendent près du portail.','Le car arrive peu après.']},
 {key:'visitors-directions',passage:'Deux visiteurs demandent le chemin du musée à Yanis. Un vélo est posé contre le mur. Yanis leur indique la rue à prendre. Les visiteurs le remercient et repartent.',pronoun:'leur',answer:'deux visiteurs',distractors:['Yanis','un vélo','le musée'],support:'Deux visiteurs demandent le chemin du musée à Yanis.',otherSpans:['Un vélo est posé contre le mur.','Les visiteurs le remercient et repartent.']},
 {key:'camera-protection',passage:'Zoé sort son appareil photo sur le sentier. Des gouttes commencent à tomber sur les pierres. Elle le range aussitôt dans sa housse. Le groupe continue jusqu’au refuge.',pronoun:'le',answer:'son appareil photo',distractors:['le sentier','le groupe','sa housse'],support:'Zoé sort son appareil photo sur le sentier.',otherSpans:['Des gouttes commencent à tomber sur les pierres.','Le groupe continue jusqu’au refuge.']},
 {key:'plants-water',passage:'Adam installe trois petites plantes sur le balcon. Sa sœur apporte un arrosoir rempli. Il les arrose avant de rentrer. Le soleil disparaît derrière les immeubles.',pronoun:'les',answer:'trois petites plantes',distractors:['les immeubles','un arrosoir','sa sœur'],support:'Adam installe trois petites plantes sur le balcon.',otherSpans:['Sa sœur apporte un arrosoir rempli.','Le soleil disparaît derrière les immeubles.']},
 {key:'singer-water',passage:'Le chanteur demande un verre d’eau à la technicienne. Les danseurs répètent encore près du rideau. La technicienne lui apporte une bouteille. Il la remercie avant de monter sur scène.',pronoun:'lui',answer:'le chanteur',distractors:['les danseurs','la technicienne','le rideau'],support:'Le chanteur demande un verre d’eau à la technicienne.',otherSpans:['Les danseurs répètent encore près du rideau.','Il la remercie avant de monter sur scène.']},
];
export const OBJECT_REFERENCE_DRAFTS=rows.map(r=>({...r,nodeKey:'resoudre_pronom_objet',genre:'narrative' as const,question:`Dans ce récit, que remplace « ${r.pronoun} » ?`,reason:'Résoudre la référence du pronom complément dans un récit bref, sans inférer la capacité à produire ce pronom.'}));
