import type {TargetTeachingContent} from "./teaching-content";
const make=(nodeKey:string,content:Omit<TargetTeachingContent,"id"|"nodeKey"|"facetKey"|"mode"|"status">):TargetTeachingContent=>({id:`french-v3-teaching:reading:${nodeKey}:informational`,nodeKey,facetKey:`${nodeKey}::text_type:informational`,mode:"interpretation",status:"draft_requires_review",...content});
const lessons=[
 make("deduire_mot_definition_locale",{
 titleFr:"Trouver une définition dans le texte",learnerQuestionFr:"Et si le texte expliquait lui-même le mot que tu ne connais pas ?",
 steps:[
 {exampleFr:"Le document contient un glossaire, c’est-à-dire une liste de mots accompagnés de leur explication.",explanationFr:"Même si glossaire est nouveau pour toi, la suite donne son sens. C’est-à-dire annonce une explication. Tu peux remplacer glossaire par liste de mots expliqués pour vérifier que la phrase reste cohérente."},
 {exampleFr:"Le concours est anonyme : le jury ne connaît pas le nom des participants.",explanationFr:"Les deux-points introduisent ici une précision qui explique anonyme. Cela ne veut pas dire que personne ne participe, mais que les noms ne sont pas connus du jury."},
 {exampleFr:"Une légende accompagne la photo. Ici, ce mot désigne le petit texte qui explique l’image.",explanationFr:"Un mot peut avoir plusieurs sens. Ici indique lequel retenir : le petit texte sous une image, pas un récit merveilleux que tu connais peut-être déjà."},
 ],
 takeawayFr:"Lis juste avant et juste après le mot. Cherche une définition annoncée par c’est-à-dire, on appelle, ce mot désigne ou une précision après deux-points. Vérifie ce sens en le remplaçant dans la phrase.",
 boundaryFr:"Les deux-points n’annoncent pas toujours une définition : ils peuvent introduire une liste ou une cause. Quand le texte donne seulement des exemples, il faut en déduire le sens; c’est une autre démarche. Si aucun indice ne suffit, ne prétends pas que le texte permet de savoir.",
 practice:[
 {id:"vocab-definition-guide-1",promptFr:"Les sacs restent au vestiaire, un espace où l’on dépose vêtements et affaires avant une activité.\n\nQue désigne vestiaire ici ?",choices:["Un espace où déposer ses affaires.","Une personne qui porte les sacs.","Le nom de l’activité.","Un vêtement obligatoire."],answerFr:"Un espace où déposer ses affaires.",hintFr:"La précision après la virgule explique vestiaire.",explanationFr:"Un espace où l’on dépose vêtements et affaires définit directement le vestiaire dans ce passage."},
 {id:"vocab-definition-guide-2",promptFr:"Le règlement exige un consentement : chaque personne doit donner son accord avant d’être photographiée.\n\nQuel sens de consentement est expliqué ?",choices:["L’accord donné par la personne.","La qualité de la photographie.","Le nom de l’appareil.","L’interdiction de toute photographie."],answerFr:"L’accord donné par la personne.",hintFr:"Que doit donner chaque personne, d’après la suite ?",explanationFr:"La précision donner son accord explique consentement. Le texte permet une photo si cet accord est donné."},
 {id:"vocab-definition-guide-3",promptFr:"Une annexe termine le dossier. Ce mot désigne ici une partie ajoutée qui contient des documents complémentaires.\n\nQu’est-ce qu’une annexe dans ce dossier ?",choices:["Une partie ajoutée avec des documents complémentaires.","Le titre principal du dossier.","La personne qui lit le dossier.","La date de remise du dossier."],answerFr:"Une partie ajoutée avec des documents complémentaires.",hintFr:"Repère ce qui suit ce mot désigne ici.",explanationFr:"Le texte fournit le sens de annexe; aucun détail sur le titre ou la date n’est donné."},
 {id:"vocab-definition-guide-4",promptFr:"Le groupe prépare une rétrospective, autrement dit une présentation de ses réalisations passées. Les projets futurs seront discutés plus tard.\n\nQuel est le sens de rétrospective ici ?",choices:["Une présentation de réalisations passées.","Une liste des seuls projets futurs.","Une réunion annulée.","Une nouvelle réalisation sportive."],answerFr:"Une présentation de réalisations passées.",hintFr:"Autrement dit annonce une reformulation du mot.",explanationFr:"La définition porte sur ce qui a déjà été réalisé. La dernière phrase distingue ce travail des projets futurs."},
 ],
 }),
 make("deduire_mot_exemple_contraste",{
 titleFr:"Déduire un mot grâce aux exemples",learnerQuestionFr:"Comment comprendre un mot quand le texte montre des exemples sans donner sa définition ?",
 steps:[
 {exampleFr:"Le gardien est vigilant : il observe chaque entrée, remarque les portes ouvertes et signale aussitôt une situation inhabituelle.",explanationFr:"Le texte ne remplace pas vigilant par un autre mot. Il montre des comportements : observer, remarquer, signaler. Ils ont en commun l’attention portée à ce qui se passe. Vigilant signifie ici attentif aux risques ou aux événements."},
 {exampleFr:"La première consigne est concise : elle tient en une ligne. La seconde répète la même idée pendant deux pages.",explanationFr:"Le contraste oppose une formulation courte à une formulation longue et répétitive. Il aide à comprendre concise : exprimée en peu de mots. Cela ne veut pas dire que la consigne est absente."},
 {exampleFr:"Le menu est varié : soupe, salade, poisson et fruits. Les assiettes sont bleues.",explanationFr:"L’énumération donne l’indice utile pour varié : plusieurs sortes de plats. La couleur des assiettes ne t’aide pas à comprendre ce mot. Choisis les détails qui expliquent le sens, pas tous les détails présents."},
 ],
 takeawayFr:"Repère les actions, exemples ou oppositions autour du mot. Cherche ce qu’ils ont en commun, propose un sens puis remplace le mot pour vérifier. Appuie ton choix sur les indices du passage.",
 boundaryFr:"Un exemple seul peut être insuffisant. Ne transforme pas une hypothèse en certitude si plusieurs sens restent possibles. Le sens retenu vaut pour ce passage; le mot peut avoir d’autres emplois ailleurs.",
 practice:[
 {id:"vocab-contrast-guide-1",promptFr:"L’animatrice décrit Adam comme assidu. Il vient à toutes les séances, arrive à l’heure et manque rarement un entraînement.\n\nQue signifie assidu ici ?",choices:["Présent de façon régulière et appliquée.","Souvent absent des séances.","Toujours chargé de fermer la salle.","Plus rapide que tous les autres."],answerFr:"Présent de façon régulière et appliquée.",hintFr:"Les trois comportements concernent-ils sa vitesse ou sa présence ?",explanationFr:"Venir à toutes les séances, être ponctuel et manquer rarement illustrent une participation régulière. Rien ne compare sa vitesse à celle des autres."},
 {id:"vocab-contrast-guide-2",promptFr:"Le local est exigu : deux tables le remplissent presque entièrement et les élèves doivent se serrer pour passer. La grande salle voisine est libre.\n\nQue signifie exigu ?",choices:["Trop petit pour y être à l’aise.","Très spacieux.","Complètement vide.","Situé très loin du collège."],answerFr:"Trop petit pour y être à l’aise.",hintFr:"Qu’indiquent les tables qui remplissent la pièce et le passage difficile ?",explanationFr:"Ces indices montrent que l’espace est réduit. La grande salle voisine fournit un contraste, sans changer la taille du local."},
 {id:"vocab-contrast-guide-3",promptFr:"Le cycliste reste prudent : il ralentit près des piétons, regarde avant de tourner et vérifie ses freins. Son casque est rouge.\n\nQuel sens de prudent est soutenu par ces actions ?",choices:["Attentif à éviter les risques.","Pressé d’aller le plus vite possible.","Habillé entièrement en rouge.","Incapable de tourner."],answerFr:"Attentif à éviter les risques.",hintFr:"Cherche le point commun entre ralentir, regarder et vérifier.",explanationFr:"Les actions réduisent les risques. La couleur du casque n’explique pas à elle seule prudent."},
 {id:"vocab-contrast-guide-4",promptFr:"Les premiers badges sont uniformes : même forme, même couleur, même taille. Les nouveaux badges ont chacun un dessin différent.\n\nQue signifie uniformes pour les premiers badges ?",choices:["Tous semblables selon les caractéristiques décrites.","Tous différents les uns des autres.","Conçus uniquement pour les adultes.","Impossible à porter."],answerFr:"Tous semblables selon les caractéristiques décrites.",hintFr:"Observe la répétition de même, puis le contraste avec les nouveaux badges.",explanationFr:"La forme, la couleur et la taille communes montrent la ressemblance. Le texte ne dit rien sur l’âge des personnes qui les portent."},
 ],
 }),
];
export const READING_VOCABULARY_TEACHING:readonly TargetTeachingContent[]=lessons.map(lesson=>({...lesson,materialExposure:{sentences:[...lesson.steps.map(step=>step.exampleFr),...lesson.practice.map(exercise=>exercise.promptFr.split("\n\n")[0])]}}));
