import {READING_VOCABULARY_TEACHING} from "./reading-vocabulary-teaching";
import type {TargetTeachingContent} from "./teaching-content";
import {READING_INFORMATION_TEACHING} from "./reading-information-teaching";
const make=(nodeKey:string,content:Omit<TargetTeachingContent,"id"|"nodeKey"|"facetKey"|"mode"|"status">):TargetTeachingContent=>({
 id:`french-v3-teaching:reading:${nodeKey}:narrative`,nodeKey,facetKey:`${nodeKey}::text_type:narrative`,mode:"interpretation",status:"draft_requires_review",...content,
});
/** Guided examples deliberately differ from the diagnostic draft passages.
 * Review must still examine semantic overlap before any publication. */
export const READING_TEACHING:readonly TargetTeachingContent[]=[
 make("resoudre_pronom_sujet",{
  titleFr:"Retrouver qui fait l’action",learnerQuestionFr:"Quand je lis « il » ou « elle », de qui parle le texte ?",
  steps:[
   {exampleFr:"La chanteuse prend le micro. Elle commence une chanson.",explanationFr:"Qui commence une chanson ? La chanteuse. Le petit mot « elle » évite de répéter « la chanteuse ». Ce mot qui reprend un nom est un pronom."},
   {exampleFr:"Le cousin d’Amina arrive. Il apporte un jeu.",explanationFr:"« Il » reprend « le cousin », pas Amina. Ne choisis pas simplement le dernier nom rencontré. Remplace « il » par ton candidat : « Le cousin apporte un jeu ». La phrase garde son sens."},
   {exampleFr:"Tom ramasse les cartes. Elles sont tombées du paquet.",explanationFr:"« Elles » désigne plusieurs choses au féminin : les cartes. Un pronom peut reprendre un objet, et le nom repris n’est pas toujours celui qui faisait l’action dans la phrase précédente."},
  ],
  takeawayFr:"Relis la phrase précédente, cherche un nom qui convient à il, elle, ils ou elles, puis remplace le pronom par ce nom pour vérifier le sens.",
  boundaryFr:"Si plusieurs noms conviennent, il faut lire davantage. Ici, les petits textes permettent de trouver une seule réponse. Les mots comme « le » dans « Tom le range » ont une autre fonction, travaillée séparément.",
  practice:[
   {id:"reading-subject-guide-1",promptFr:"L’actrice entre dans la salle. Elle pose son sac sur une chaise.\n\nQui pose son sac ?",choices:["L’actrice.","La chaise.","Le sac.","La salle."],answerFr:"L’actrice.",hintFr:"Remplace « Elle » par un nom de la première phrase. Qui peut faire cette action ?",explanationFr:"« Elle pose son sac » signifie ici « L’actrice pose son sac ». Le pronom reprend l’actrice."},
   {id:"reading-subject-guide-2",promptFr:"Le voisin de Léonie frappe à la porte. Il tient un colis.\n\nQui tient un colis ?",choices:["Le voisin de Léonie.","Léonie.","Le colis.","La porte."],answerFr:"Le voisin de Léonie.",hintFr:"Le nom placé juste avant le pronom n’est pas forcément celui qu’il reprend. Cherche le groupe qui convient à « il ».",explanationFr:"« Le voisin de Léonie » désigne un voisin. C’est ce voisin qui frappe et qui tient un colis; « il » ne reprend pas Léonie."},
   {id:"reading-subject-guide-3",promptFr:"Emma rassemble les images sur la table. Elles serviront à fabriquer un collage.\n\nQu’est-ce qui servira au collage ?",choices:["Les images.","Emma.","La table.","Le collage lui-même."],answerFr:"Les images.",hintFr:"« Elles » reprend un groupe au féminin pluriel.",explanationFr:"Ce sont les images qui serviront au collage. « Elles » reprend le complément de la première phrase, pas Emma."},
   {id:"reading-subject-guide-4",promptFr:"Les voisins remercient la gardienne. Ils repartent avec leurs sacs.\n\nQui repart avec des sacs ?",choices:["Les voisins.","La gardienne.","Les sacs.","On ne peut pas le savoir."],answerFr:"Les voisins.",hintFr:"Cherche un groupe de personnes au pluriel auquel « ils » peut renvoyer.",explanationFr:"« Ils » reprend les voisins. La gardienne est une seule personne et n’est pas désignée par ce pronom masculin pluriel."},
  ],
 }),
 make("resoudre_pronom_objet",{
  titleFr:"Retrouver ce que remplace « le », « la » ou « lui »",learnerQuestionFr:"Dans « Nina le range », qu’est-ce qui est rangé ?",
  steps:[
   {exampleFr:"Nina prend un cahier. Nina le range.",explanationFr:"Nina range le cahier. « Le » reprend ce cahier : il évite de répéter son nom. Contrairement à Nina, le cahier ne fait pas l’action; il est rangé. « Le » est ici un pronom complément."},
   {exampleFr:"Alex ouvre la boîte. Alex la referme.\nAlex ramasse les crayons. Alex les range.",explanationFr:"« La » reprend la boîte. « Les » reprend les crayons. Reviens aux noms du texte pour comprendre ce qui est refermé ou rangé."},
   {exampleFr:"Nina téléphone à son oncle. Nina lui raconte sa journée.\nNina retrouve ses amis. Nina leur raconte sa journée.",explanationFr:"« Lui » reprend ici une personne à qui Nina parle : son oncle. « Leur » reprend plusieurs personnes : ses amis. Demande-toi « à qui ? », puis vérifie dans le texte."},
  ],
  takeawayFr:"Pour comprendre le petit mot, reconstruis la phrase avec le nom : Nina range le cahier; Nina raconte sa journée à son oncle.",
  boundaryFr:"Cette leçon sert à retrouver un nom dans un récit. Elle ne vérifie pas encore si tu sais choisir ou placer tous les pronoms en écrivant. Les emplois de « y » et « en » demandent aussi d’autres exemples.",
  practice:[
   {id:"reading-object-guide-1",promptFr:"Mina trouve un portefeuille sous la table. Mina le remet à l’accueil.\n\nQue remet Mina à l’accueil ?",choices:["Le portefeuille.","La table.","Mina elle-même.","L’accueil."],answerFr:"Le portefeuille.",hintFr:"Remplace « le » dans la deuxième phrase par l’objet trouvé.",explanationFr:"Mina remet le portefeuille. « Le » reprend l’objet présenté dans la première phrase."},
   {id:"reading-object-guide-2",promptFr:"Éloi reçoit une carte de sa tante. Éloi la garde dans un tiroir.\n\nQue garde Éloi dans le tiroir ?",choices:["La carte.","Sa tante.","Le tiroir.","Éloi lui-même."],answerFr:"La carte.",hintFr:"Une personne et un objet féminins sont mentionnés. Vérifie lequel a du sens dans « Éloi garde ... dans un tiroir ».",explanationFr:"« La » reprend la carte, pas la tante. Le sens de l’action permet de choisir entre ces deux noms féminins."},
   {id:"reading-object-guide-3",promptFr:"Lina offre un dessin à son grand-père. Lina lui souhaite une bonne fête.\n\nÀ qui Lina souhaite-t-elle une bonne fête ?",choices:["À son grand-père.","À Lina elle-même.","Au dessin.","On ne peut pas le savoir."],answerFr:"À son grand-père.",hintFr:"Cherche la personne à qui le dessin est offert.",explanationFr:"Lina souhaite une bonne fête à son grand-père. « Lui » reprend le destinataire humain déjà mentionné."},
   {id:"reading-object-guide-4",promptFr:"Le gardien accueille les enfants. Il leur indique le chemin du jardin.\n\nÀ qui le gardien indique-t-il le chemin ?",choices:["Aux enfants.","Au gardien lui-même.","Au jardin.","On ne peut pas le savoir."],answerFr:"Aux enfants.",hintFr:"« Leur » renvoie ici à plusieurs personnes qui reçoivent une indication.",explanationFr:"Le gardien indique le chemin aux enfants. « Leur » reprend ces destinataires; « il » désigne séparément le gardien."},
  ],
 }),
 make("inferer_chronologie_implicite",{
  titleFr:"Retrouver ce qui s’est passé avant",learnerQuestionFr:"La première phrase raconte-t-elle toujours le premier événement ?",
  steps:[
   {exampleFr:"Le groupe a écouté le morceau. Ana l’avait enregistré la veille.",explanationFr:"L’enregistrement a eu lieu avant l’écoute, même si le texte en parle après. Un récit peut revenir sur un événement plus ancien."},
   {exampleFr:"Ana avait enregistré le morceau → Le groupe l’a écouté.",explanationFr:"« Avait enregistré » situe l’enregistrement avant l’autre action passée. Ce temps s’appelle le plus-que-parfait. Ici, il nous aide à remettre les actions dans l’ordre; nous n’avons pas besoin de conjuguer nous-mêmes le verbe."},
   {exampleFr:"Hugo présente sa maquette. Le toit, déjà collé, tient bien.",explanationFr:"Au moment de la présentation, le collage est terminé : le toit est collé. Cet état donne aussi un indice sur l’ordre des événements."},
  ],
  takeawayFr:"Repère les deux événements. Cherche un temps verbal ou un résultat déjà visible qui indique lequel a eu lieu avant l’autre.",
  boundaryFr:"Ne complète pas le texte avec ce qui arrive habituellement. Si aucun indice ne permet de choisir un ordre, dis-le. Ces exercices portent sur de courts retours en arrière, pas sur tous les changements de temps d’un récit.",
  practice:[
   {id:"reading-time-guide-1",promptFr:"Le professeur a montré l’affiche. Les élèves l’avaient dessinée en atelier.\n\nQuel événement a eu lieu en premier ?",choices:["Les élèves ont dessiné l’affiche.","Le professeur a montré l’affiche.","Les deux actions ont commencé ensemble.","Le texte ne permet pas de choisir."],answerFr:"Les élèves ont dessiné l’affiche.",hintFr:"Regarde « avaient dessinée ». À quel événement ce temps renvoie-t-il ?",explanationFr:"Le dessin est antérieur à la présentation. Le plus-que-parfait permet de retrouver cet ordre malgré l’ordre des phrases."},
   {id:"reading-time-guide-2",promptFr:"Jade porte son pull. La manche, réparée par sa mère, n’a plus de trou.\n\nQuel événement a eu lieu avant cette scène ?",choices:["La mère de Jade a réparé la manche.","Jade a déchiré la manche pendant cette scène.","La mère commence à réparer pendant cette scène.","Le texte ne donne aucun indice."],answerFr:"La mère de Jade a réparé la manche.",hintFr:"Dans quel état se trouve la manche quand Jade porte le pull ?",explanationFr:"La manche est réparée et n’a plus de trou. Ce résultat est déjà présent : la réparation a donc eu lieu avant la scène décrite."},
   {id:"reading-time-guide-3",promptFr:"Bilal a tendu les clés à sa sœur. Il les avait retrouvées sous un coussin.\n\nQuel événement a eu lieu en premier ?",choices:["Bilal a retrouvé les clés.","Bilal a tendu les clés à sa sœur.","Sa sœur a caché les clés.","Le texte ne permet pas de choisir."],answerFr:"Bilal a retrouvé les clés.",hintFr:"« Avait retrouvées » indique une action plus ancienne que « a tendu ».",explanationFr:"Bilal retrouve les clés, puis les tend à sa sœur. Le texte ne dit pas que sa sœur les avait cachées."},
   {id:"reading-time-guide-4",promptFr:"Le spectacle a commencé à dix-neuf heures. Nora avait préparé les costumes dans l’après-midi.\n\nQuel événement a eu lieu en premier ?",choices:["Nora a préparé les costumes.","Le spectacle a commencé.","La préparation a commencé pendant le spectacle.","Le texte ne permet pas de choisir."],answerFr:"Nora a préparé les costumes.",hintFr:"Le temps verbal et le moment de la journée donnent deux indices qui vont dans le même sens.",explanationFr:"La préparation est déjà terminée quand le spectacle commence. « Avait préparé » et « dans l’après-midi » confirment cet ordre."},
  ],
 }),
 make("inferer_cause_locale",{
  titleFr:"Comprendre pourquoi un personnage agit",learnerQuestionFr:"Le texte ne dit pas « parce que » : comment trouver une explication ?",
  steps:[
   {exampleFr:"La soupe fume dans le bol. Zoé approche la cuillère de ses lèvres, puis souffle dessus.",explanationFr:"Pourquoi Zoé souffle-t-elle ? Elle veut probablement refroidir la soupe. Le texte ne donne pas directement cette explication, mais la vapeur et le geste vont ensemble."},
   {exampleFr:"Indice : la soupe fume. Geste à expliquer : Zoé souffle dessus. Explication probable : elle veut la refroidir.",explanationFr:"Relier un indice à une explication que le texte ne formule pas directement, c’est faire une inférence. L’indice rend notre réponse plausible. Il faut pouvoir montrer ce qui, dans le texte, soutient cette réponse."},
   {exampleFr:"Zoé regarde la pendule, puis souffle sur sa soupe.",explanationFr:"« Puis » indique un ordre. Cela ne prouve pas que la pendule explique le geste. Cherche un indice qui aide vraiment à comprendre pourquoi elle souffle, comme la chaleur de la soupe."},
  ],
  takeawayFr:"Repère le geste à expliquer. Cherche un indice précis. Choisis l’explication qui relie cet indice au geste, sans ajouter une histoire que le texte ne raconte pas.",
  boundaryFr:"Une explication peut être probable sans être certaine. Si le texte dit seulement que quelqu’un part, on ne sait pas forcément pourquoi. Cette leçon travaille des causes proches dans de courts récits, pas les intentions complexes d’un personnage dans tout un roman.",
  practice:[
   {id:"reading-cause-guide-1",promptFr:"Malik essaie de lire l’étiquette d’un pot. Les lettres sont minuscules. Il prend une loupe dans le tiroir.\n\nPourquoi prend-il probablement une loupe ?",choices:["Pour mieux voir les petites lettres.","Pour mesurer le pot.","Pour effacer l’étiquette.","Pour savoir qui a acheté le pot."],answerFr:"Pour mieux voir les petites lettres.",hintFr:"Quel détail rend la lecture difficile ?",explanationFr:"L’indice « Les lettres sont minuscules » explique le besoin de les agrandir. Le texte ne parle ni d’effacer l’étiquette ni de retrouver l’acheteur."},
   {id:"reading-cause-guide-2",promptFr:"À l’atelier, Elsa ouvre un flacon. Une odeur très forte lui pique le nez. Elle remet aussitôt le bouchon.\n\nPourquoi referme-t-elle probablement le flacon ?",choices:["Pour limiter l’odeur qui la gêne.","Pour changer la couleur du flacon.","Pour commencer à boire son contenu.","Pour cacher une étiquette déchirée."],answerFr:"Pour limiter l’odeur qui la gêne.",hintFr:"Que se passe-t-il entre l’ouverture et la fermeture du flacon ?",explanationFr:"L’odeur forte et la gêne au nez soutiennent cette explication. Il n’est pas nécessaire d’inventer ce que contient le flacon."},
   {id:"reading-cause-guide-3",promptFr:"Le soleil éclaire directement l’écran de la tablette. Les images se distinguent à peine. Yasmine s’installe à l’ombre d’un arbre.\n\nPourquoi change-t-elle probablement de place ?",choices:["Pour mieux distinguer les images à l’ombre.","Pour recharger la tablette.","Pour retrouver une amie mentionnée dans le texte.","Pour ouvrir une autre application."],answerFr:"Pour mieux distinguer les images à l’ombre.",hintFr:"Quelle difficulté apparaît juste avant le déplacement ?",explanationFr:"Les images se distinguent mal sous la lumière directe. Chercher l’ombre répond à cette difficulté; aucune batterie vide ni amie n’est mentionnée."},
   {id:"reading-cause-guide-4",promptFr:"À dix heures, Hugo ferme son carnet et sort de la pièce. Une affiche est accrochée au mur.\n\nPourquoi Hugo sort-il ?",choices:["Le texte ne donne pas assez d’indices pour le savoir.","Il a forcément faim.","L’affiche lui fait peur.","Il a certainement terminé tous ses devoirs."],answerFr:"Le texte ne donne pas assez d’indices pour le savoir.",hintFr:"Le texte donne-t-il une raison, ou seulement des actions et des détails ?",explanationFr:"L’heure, le carnet et l’affiche ne suffisent pas à choisir une cause. La faim, la peur et les devoirs terminés sont des ajouts que rien ne confirme."},
  ],
 }),
 ...READING_INFORMATION_TEACHING,...READING_VOCABULARY_TEACHING,
].map(lesson=>({...lesson,materialExposure:lesson.materialExposure??{sentences:[...lesson.steps.map(step=>step.exampleFr),...lesson.practice.map(exercise=>exercise.promptFr.split("\n\n")[0])]}}));
