/** Original fictional micro-passages. The cause is inferred from the passage,
 * not supplied in the question. Content remains subject to pedagogical review. */
export const NARRATIVE_CAUSE_DRAFTS=[
 {key:"manga-queue",passage:"À la bibliothèque, Nour prend le dernier tome de son manga préféré. Près du comptoir, cinq élèves attendent déjà avec des livres. Nour regarde l’heure et pose son manga sur une table. Elle reviendra l’emprunter après le déjeuner.",
  question:"Pourquoi Nour reporte-t-elle probablement l’emprunt du manga ?",answer:"Elle ne veut pas attendre dans la file maintenant.",
  distractors:["Elle a déjà lu ce tome.","La bibliothèque refuse les mangas.","Elle a oublié quel livre elle voulait."],
  support:"Près du comptoir, cinq élèves attendent déjà avec des livres.",otherSpans:["Nour prend le dernier tome de son manga préféré.","Elle reviendra l’emprunter après le déjeuner."],reason:"La file d’attente et le regard vers l’heure permettent d’inférer le manque de temps ; aucun règlement ou oubli n’est mentionné."},
 {key:"basket-shoelace",passage:"Le match va commencer. Sami rejoint ses coéquipiers, puis s’arrête au bord du terrain. Un long lacet traîne derrière sa chaussure droite. Il pose le ballon et s’accroupit quelques secondes avant de repartir en courant.",
  question:"Pourquoi Sami s’accroupit-il probablement ?",answer:"Il veut renouer son lacet.",
  distractors:["Il veut ramasser le ballon tombé hors du terrain.","Il cherche une pièce de monnaie.","Il veut s’asseoir pour regarder tout le match."],
  support:"Un long lacet traîne derrière sa chaussure droite.",otherSpans:["Le match va commencer.","Sami rejoint ses coéquipiers, puis s’arrête au bord du terrain."],reason:"Le lacet qui traîne explique l’arrêt et le geste ; le ballon est posé volontairement et Sami repart."},
 {key:"drawing-window",passage:"Aya dessine près d’une fenêtre ouverte. Un courant d’air fait glisser ses feuilles jusqu’au bord de la table. Elle pose sa trousse sur le tas de dessins, puis reprend ses crayons de couleur. Au mur, une horloge indique quatre heures.",
  question:"Pourquoi Aya pose-t-elle sa trousse sur les dessins ?",answer:"Elle veut empêcher les feuilles de s’envoler ou de glisser.",
  distractors:["Elle veut cacher ses dessins à quelqu’un.","Elle veut colorier la trousse.","Elle veut vérifier l’heure."],
  support:"Un courant d’air fait glisser ses feuilles jusqu’au bord de la table.",otherSpans:["Aya dessine près d’une fenêtre ouverte.","Au mur, une horloge indique quatre heures."],reason:"Le déplacement des feuilles fournit la cause précise ; la fenêtre seule est un indice moins direct."},
 {key:"dance-music",passage:"Le groupe de danse répète dans la salle. La musique s’arrête brusquement et l’écran de l’enceinte devient noir. Les danseurs restent immobiles. Inès branche alors le câble de l’enceinte sur une prise, puis attend que le voyant s’allume.",
  question:"Pourquoi Inès branche-t-elle l’enceinte ?",answer:"Elle pense que l’enceinte n’a plus assez d’énergie pour fonctionner.",
  distractors:["Elle veut changer les pas de danse.","Elle veut baisser le volume d’une musique qui joue encore.","Elle veut déplacer la prise électrique."],
  support:"La musique s’arrête brusquement et l’écran de l’enceinte devient noir.",otherSpans:["Le groupe de danse répète dans la salle.","Les danseurs restent immobiles."],reason:"L’arrêt du son et de l’écran, puis le branchement, soutiennent l’hypothèse d’alimentation sans affirmer une panne technique certaine."},
 {key:"rain-notebook",passage:"En sortant du collège, Léo ouvre son cahier pour vérifier un devoir. De grosses gouttes commencent à tomber sur les pages. Il referme aussitôt le cahier et le glisse sous sa veste. Son arrêt de bus est encore à quelques rues.",
  question:"Pourquoi Léo glisse-t-il son cahier sous sa veste ?",answer:"Il veut protéger les pages de la pluie.",
  distractors:["Il veut empêcher le bus de partir.","Il a terminé tous ses devoirs.","Il veut échanger son cahier avec un camarade."],
  support:"De grosses gouttes commencent à tomber sur les pages.",otherSpans:["Léo ouvre son cahier pour vérifier un devoir.","Son arrêt de bus est encore à quelques rues."],reason:"Les gouttes sur les pages motivent la protection ; la distance du bus situe la scène mais n’explique pas à elle seule le geste."},
 {key:"game-headphones",passage:"Mina joue sur son ordinateur dans le salon. À côté d’elle, son frère commence une visioconférence et fait signe qu’il n’entend pas son interlocuteur. Mina coupe les haut-parleurs du jeu et met son casque. La partie continue sur l’écran.",
  question:"Pourquoi Mina met-elle son casque ?",answer:"Elle veut que le son du jeu gêne moins la conversation de son frère.",
  distractors:["Elle veut arrêter définitivement la partie.","Elle veut participer à la visioconférence à la place de son frère.","Elle veut cacher l’écran de son ordinateur."],
  support:"À côté d’elle, son frère commence une visioconférence et fait signe qu’il n’entend pas son interlocuteur.",otherSpans:["Mina joue sur son ordinateur dans le salon.","La partie continue sur l’écran."],reason:"La difficulté d’écoute du frère explique la suppression du son ambiant ; la partie continue."},
 {key:"bike-route",passage:"Jules roule vers le parc. Au bout de sa rue, une barrière bloque toute la chaussée et des ouvriers creusent le sol. Il ralentit, fait demi-tour et prend la rue parallèle. Le panier de son vélo contient un goûter.",
  question:"Pourquoi Jules prend-il la rue parallèle ?",answer:"Son trajet habituel est bloqué par des travaux.",
  distractors:["Il veut acheter un nouveau vélo.","Il a perdu son goûter.","Le parc vient de fermer pour la journée."],
  support:"Au bout de sa rue, une barrière bloque toute la chaussée et des ouvriers creusent le sol.",otherSpans:["Jules roule vers le parc.","Le panier de son vélo contient un goûter."],reason:"La barrière et les travaux justifient le détour ; la fermeture du parc n’est pas indiquée."},
 {key:"cinema-seat",passage:"Salomé s’installe au cinéma. Un spectateur très grand s’assied juste devant elle et lui cache le milieu de l’écran. Elle consulte son billet, puis demande à l’agent si elle peut prendre le siège libre au bout de sa rangée. Le film n’a pas encore commencé.",
  question:"Pourquoi Salomé demande-t-elle à changer de siège ?",answer:"Elle veut mieux voir l’écran.",
  distractors:["Elle veut quitter le cinéma avant la séance.","Elle veut retrouver un objet tombé dans une autre rangée.","Elle sait que son billet correspond au siège du bout."],
  support:"Un spectateur très grand s’assied juste devant elle et lui cache le milieu de l’écran.",otherSpans:["Salomé s’installe au cinéma.","Le film n’a pas encore commencé."],reason:"La vue masquée motive la demande ; le texte ne dit pas que le billet attribue un autre siège."},
] as const;
