/** Original miniature texts. Interpret the stated message, not outside facts. */
type Row = readonly [string, string, string, readonly [string,string,string]];
const narrative: readonly Row[] = [
 ['manga','Bien que son manga soit passionnant, Salma le ferme pour rejoindre sa petite sœur qui l’attend dehors.','Salma interrompt sa lecture pour rejoindre sa sœur.',['Salma trouve son manga passionnant.','Salma préfère continuer à lire plutôt que sortir.','La sœur de Salma lui emprunte son manga.']],
 ['rain','Alors que la pluie redouble, Idriss poursuit son chemin vers le refuge dont il aperçoit enfin le toit.','Idriss continue vers le refuge malgré la pluie.',['Idriss voit le toit du refuge.','Idriss renonce à atteindre le refuge.','Idriss attend que la pluie cesse dans le refuge.']],
 ['key','La clé que Mila croyait avoir perdue réapparaît lorsqu’elle vide la poche intérieure de son manteau.','Mila retrouve sa clé dans son manteau.',['Le manteau de Mila possède une poche intérieure.','Mila perd sa clé en vidant ses poches.','Quelqu’un rapporte à Mila sa clé perdue.']],
 ['race','Yanis, qui menait la course depuis le départ, ralentit pour aider un coureur tombé près du dernier virage.','Yanis ralentit sa course pour aider un autre coureur.',['Yanis était en tête depuis le départ.','Yanis accélère pour conserver son avance.','Yanis est tombé dans le dernier virage.']],
 ['letter','En découvrant la lettre que son grand-père avait glissée dans le livre, Awa comprend pourquoi il tenait à le lui offrir.','La lettre révèle à Awa le sens du cadeau de son grand-père.',['Le grand-père d’Awa lui a offert un livre.','Awa ignore toujours pourquoi elle a reçu ce livre.','Awa décide d’écrire un livre pour son grand-père.']],
 ['stage','Même si elle tremble encore, Éva entre sur scène dès que son partenaire lui fait le signe convenu.','Éva entre sur scène malgré sa nervosité.',['Éva et son partenaire ont prévu un signe.','Éva refuse d’entrer sur scène parce qu’elle tremble.','Le partenaire d’Éva entre sur scène à sa place.']],
 ['bridge','Le pont étant fermé, les deux amis suivent un sentier qui longe la rivière jusqu’au village voisin.','Les amis prennent un autre chemin à cause du pont fermé.',['Le sentier longe une rivière.','Les amis traversent le pont pour atteindre le village.','Les amis décident de réparer le pont.']],
 ['drawing','Noam conserve le dessin froissé que son frère voulait jeter, car il lui rappelle leur première sortie ensemble.','Noam garde un dessin auquel un souvenir donne de la valeur.',['Le dessin de Noam est froissé.','Noam jette le dessin pour oublier leur sortie.','Noam garde le dessin pour gagner un concours.']],
 ['train','Au moment où le train démarre, Leïla aperçoit sur le quai sa tante qui lui fait un dernier signe de la main.','Leïla voit sa tante lui dire au revoir au départ du train.',['La tante de Leïla se trouve sur le quai.','Leïla descend du train pour retrouver sa tante.','La tante de Leïla monte dans le train avec elle.']],
 ['repair','Après plusieurs essais infructueux, Sami réussit à faire tourner la roue du petit robot qu’il avait démonté la veille.','Sami parvient enfin à faire fonctionner la roue du robot.',['Sami a démonté le robot la veille.','Sami abandonne la réparation après plusieurs essais.','Sami remplace son robot par un modèle neuf.']],
 ['promise','Puisqu’elle avait promis de revenir avant la nuit, Inès quitte ses amis alors que leur partie vient seulement de commencer.','Inès interrompt la rencontre pour tenir sa promesse de rentrer.',['La partie des amis vient de commencer.','Inès reste jouer jusqu’à la nuit malgré sa promesse.','Inès rentre parce que la partie est terminée.']],
 ['package','Le paquet que les voisins déposent devant sa porte surprend Moussa, qui ne s’attendait pas à recevoir un cadeau.','Moussa est surpris par un cadeau inattendu de ses voisins.',['Les voisins déposent un paquet devant une porte.','Moussa attendait avec impatience ce cadeau précis.','Moussa apporte un cadeau chez ses voisins.']],
];
const informational: readonly Row[] = [
 ['library','Pendant les travaux qui bloquent l’entrée principale, les lecteurs de cette bibliothèque doivent passer par la porte du jardin.','L’accès à la bibliothèque se fait provisoirement par le jardin.',['La bibliothèque possède une porte côté jardin.','La bibliothèque reste entièrement fermée pendant les travaux.','La porte du jardin est réservée aux ouvriers.']],
 ['workshop','Les inscriptions à cet atelier restent ouvertes jusqu’à vendredi, sauf si les vingt places proposées sont occupées plus tôt.','Les inscriptions ferment vendredi au plus tard, ou avant si l’atelier est complet.',['Cet atelier propose vingt places.','Les inscriptions ouvrent seulement vendredi.','Tout le monde peut s’inscrire après vendredi.']],
 ['borrow','Un outil emprunté à cette association doit être rendu propre, même lorsqu’il n’a servi que quelques minutes.','Tout outil emprunté doit être rendu propre, quelle que soit la durée d’utilisation.',['Certains outils ne servent que quelques minutes.','Seuls les outils utilisés longtemps doivent être nettoyés.','L’association interdit les emprunts de courte durée.']],
 ['bus','À partir de lundi, le bus qui desservait la place du marché s’arrêtera devant la poste en raison des travaux de voirie.','L’arrêt de ce bus est déplacé devant la poste dès lundi.',['Des travaux de voirie sont prévus.','Le bus ne circulera plus à partir de lundi.','Le bus conservera son arrêt sur la place du marché.']],
 ['exhibition','Cette exposition est accessible gratuitement aux moins de seize ans, à condition qu’ils présentent un justificatif d’âge à l’entrée.','Les moins de seize ans entrent gratuitement s’ils prouvent leur âge.',['Un justificatif peut être présenté à l’entrée.','Tous les visiteurs entrent gratuitement sans justificatif.','Les moins de seize ans ne peuvent pas visiter l’exposition.']],
 ['reservation','Toute réservation qui n’est pas confirmée dans les deux jours est annulée afin de rendre la place disponible pour une autre personne.','Une réservation non confirmée sous deux jours est annulée.',['Une place peut être proposée à une autre personne.','Une réservation reste valable sans confirmation.','Chaque réservation est annulée deux jours après sa confirmation.']],
 ['parcel','Les colis arrivés après dix-sept heures sont enregistrés le lendemain, car le comptoir de réception ferme à cette heure-là.','Les colis reçus après la fermeture sont enregistrés le lendemain.',['Le comptoir ferme à dix-sept heures.','Les colis arrivés tard sont définitivement refusés.','Tous les colis sont enregistrés dès leur arrivée.']],
 ['equipment','Le matériel de cet atelier reste sur place afin que chaque groupe puisse le retrouver, même si une activité se poursuit le lendemain.','Le matériel doit rester dans l’atelier pour être disponible aux groupes.',['Une activité peut se poursuivre le lendemain.','Chaque groupe peut emporter le matériel chez lui.','Le matériel est remplacé après chaque activité.']],
 ['menu','Le menu affiché peut changer lorsque certains ingrédients manquent, mais le prix du repas reste celui annoncé.','Le contenu du repas peut changer sans modification du prix annoncé.',['Certains ingrédients peuvent manquer.','Le prix augmente chaque fois que le menu change.','Le menu affiché ne change jamais.']],
 ['registration','Pour participer à cette sortie, les élèves doivent remettre l’autorisation signée, même s’ils ont déjà payé le transport.','Le paiement du transport ne dispense pas de remettre l’autorisation signée.',['Les élèves paient le transport pour cette sortie.','Le paiement suffit pour être autorisé à participer.','Seuls les élèves qui n’ont pas payé doivent remettre une autorisation.']],
 ['room','Lorsqu’une réunion dépasse l’horaire prévu, elle doit se poursuivre dans une autre salle si le groupe suivant arrive.','Le groupe doit libérer la salle pour les suivants, même si sa réunion continue.',['Une réunion peut dépasser l’horaire prévu.','Le groupe suivant doit toujours attendre la fin de la réunion.','Toute réunion commencée peut garder la salle sans limite.']],
 ['returns','Les livres de cette boîte sont collectés chaque matin, si bien qu’un retour effectué le soir est enregistré le jour suivant.','Un livre déposé le soir est enregistré au retour le lendemain.',['La collecte des livres a lieu le matin.','Les livres déposés le soir sont enregistrés immédiatement.','Il est interdit de déposer un livre le soir.']],
];
const argumentative: readonly Row[] = [
 ['garden','Même si un potager demande du travail, nous devrions en créer un au collège pour apprendre ensemble à faire pousser des légumes.','Le texte propose un potager scolaire malgré le travail nécessaire.',['Un potager demande du travail.','Le texte conseille de renoncer au potager à cause du travail.','Le texte affirme que le collège possède déjà un potager.']],
 ['mangas','Puisque certains élèves commencent à aimer lire grâce aux mangas, la bibliothèque devrait leur réserver davantage de place.','Le texte défend une plus grande place pour les mangas à la bibliothèque.',['Certains élèves découvrent le plaisir de lire avec les mangas.','Le texte propose de retirer les mangas de la bibliothèque.','Le texte demande de remplacer tous les livres par des mangas.']],
 ['shade','Installer une zone d’ombre serait utile dans la cour, car les élèves qui souhaitent lire dehors auraient un endroit plus agréable.','Le texte recommande un espace ombragé pour rendre la lecture dehors plus agréable.',['Des élèves souhaitent lire dehors.','Le texte conseille d’interdire la lecture dans la cour.','Le texte affirme que toute la cour est déjà à l’ombre.']],
 ['training','Plutôt que de réserver l’atelier aux élèves expérimentés, ouvrons-le aux débutants afin que chacun puisse découvrir la robotique.','Le texte propose d’accueillir les débutants à l’atelier de robotique.',['Certains élèves sont déjà expérimentés.','Le texte demande de réserver l’atelier aux plus expérimentés.','Le texte propose de supprimer l’atelier de robotique.']],
 ['noise','Bien que la musique rende la fête plus animée, il faudrait en baisser le volume pour que les voisins puissent se reposer.','Le texte demande de réduire le volume de la musique par respect pour les voisins.',['La musique rend la fête plus animée.','Le texte demande d’augmenter le volume pendant toute la nuit.','Le texte propose d’annuler toutes les fêtes du quartier.']],
 ['repairs','Avant d’acheter de nouveaux vélos, essayons de réparer ceux qui sont abîmés afin de ne pas écarter du matériel encore utilisable.','Le texte propose de tenter les réparations avant de remplacer les vélos.',['Certains vélos sont abîmés.','Le texte conseille de jeter tous les vélos abîmés.','Le texte affirme que tous les vélos sont impossibles à réparer.']],
 ['schedule','Un horaire affiché près de chaque salle éviterait des hésitations aux nouveaux élèves, qui ne connaissent pas encore les lieux.','Le texte recommande d’afficher les horaires pour aider les nouveaux élèves.',['Les nouveaux élèves connaissent encore mal les lieux.','Le texte propose de cacher les horaires aux nouveaux élèves.','Le texte affirme que tous les élèves connaissent déjà les salles.']],
 ['vote','Pour que les élèves absents puissent aussi donner leur avis, le vote devrait rester ouvert jusqu’au lendemain de la réunion.','Le texte propose de prolonger le vote pour permettre aux absents de participer.',['Certains élèves sont absents à la réunion.','Le texte propose de réserver le vote aux élèves présents.','Le texte demande de remplacer le vote par une décision imposée.']],
 ['sharing','Nous gagnerions à partager les costumes entre les clubs de théâtre, même si cela exige de s’accorder sur un calendrier.','Le texte défend le partage des costumes malgré l’organisation nécessaire.',['Partager les costumes demande un calendrier commun.','Le texte déconseille tout partage entre les clubs.','Le texte affirme que les clubs jouent tous le même spectacle.']],
 ['walk','Lorsque le trajet le permet, encourageons les déplacements à pied plutôt que d’imposer une voiture pour chaque courte sortie.','Le texte recommande la marche pour les sorties où elle est possible.',['Certaines sorties comportent un trajet court.','Le texte interdit toute utilisation de la voiture.','Le texte recommande une voiture pour chaque courte sortie.']],
 ['feedback','Les propositions devraient recevoir une réponse, même lorsqu’elles sont refusées, afin que leurs auteurs comprennent la décision.','Le texte demande une réponse expliquée même aux propositions refusées.',['Certaines propositions sont refusées.','Le texte demande d’accepter toutes les propositions.','Le texte conseille de ne jamais répondre aux propositions refusées.']],
 ['quiet','Préservons un espace calme dans la maison des jeunes pour ceux qui souhaitent travailler, sans empêcher les activités animées dans les autres salles.','Le texte propose de faire coexister un espace de travail calme et des activités animées.',['Des jeunes souhaitent travailler au calme.','Le texte demande le silence dans toutes les salles.','Le texte propose de supprimer tout espace de travail.']],
];

export const SENTENCE_MAIN_IDEA_DRAFTS = Object.entries({narrative,informational,argumentative}).flatMap(([genre,rows])=>rows.map(([key,passage,answer,distractors])=>({key:`${genre}:${key}`,nodeKey:'identifier_idee_phrase',genre:genre as 'narrative'|'informational'|'argumentative',passage,question:'Quelle proposition exprime le mieux l’idée centrale de cette phrase ?',answer,distractors})));
