export type SubjectIdentificationDraft={key:string;construction:"adjacent"|"separated"|"inverted"|"coordinated";sentence:string;verbForm:string;subject:string;distractors:[string,string,string];reason:string};
/** Original sentences for the approved subject-identification node. Construction
 * tags describe sampling coverage, not separately approved mastery targets. */
export const SUBJECT_IDENTIFICATION_DRAFTS:readonly SubjectIdentificationDraft[]=[
 {key:"camera",construction:"adjacent",sentence:"La photographe installe son appareil sur le banc près de la fontaine.",verbForm:"installe",subject:"La photographe",distractors:["son appareil","le banc","la fontaine"],reason:"La photographe est le sujet de installe; appareil est l’objet installé et les autres groupes précisent des lieux."},
 {key:"potters",construction:"adjacent",sentence:"Les potiers exposent leurs bols dans la salle près de l’entrée.",verbForm:"exposent",subject:"Les potiers",distractors:["leurs bols","la salle","l’entrée"],reason:"Les potiers commande la personne et le nombre de exposent; les bols sont les objets exposés."},
 {key:"lift",construction:"adjacent",sentence:"Cet ascenseur transporte les visiteurs vers la terrasse du restaurant.",verbForm:"transporte",subject:"Cet ascenseur",distractors:["les visiteurs","la terrasse","le restaurant"],reason:"Le sujet est Cet ascenseur, même si c’est un objet. Les visiteurs sont transportés."},
 {key:"clouds",construction:"adjacent",sentence:"Ces nuages cachent le sommet de la montagne pendant la randonnée.",verbForm:"cachent",subject:"Ces nuages",distractors:["le sommet de la montagne","la montagne","la randonnée"],reason:"Ces nuages est le sujet de cachent; le sommet de la montagne est ce qui est caché."},
 {key:"bread",construction:"separated",sentence:"L’odeur du pain attire les passants vers la boulangerie.",verbForm:"attire",subject:"L’odeur du pain",distractors:["du pain","les passants","la boulangerie"],reason:"Le groupe sujet complet est L’odeur du pain. Son noyau odeur est singulier; du pain précise cette odeur."},
 {key:"boats",construction:"separated",sentence:"Les voiles du bateau claquent au-dessus des marins près du quai.",verbForm:"claquent",subject:"Les voiles du bateau",distractors:["du bateau","des marins","du quai"],reason:"Les voiles du bateau est le groupe sujet; voiles est son noyau pluriel. Bateau ne commande pas l’accord."},
 {key:"baker",construction:"separated",sentence:"Le boulanger, derrière les présentoirs, accueille la cliente près du comptoir.",verbForm:"accueille",subject:"Le boulanger",distractors:["les présentoirs","la cliente","du comptoir"],reason:"Derrière les présentoirs précise un lieu. Le sujet de accueille reste Le boulanger."},
 {key:"dancers",construction:"separated",sentence:"Les danseuses, après la pause, rejoignent le professeur dans le studio.",verbForm:"rejoignent",subject:"Les danseuses",distractors:["la pause","le professeur","le studio"],reason:"Après la pause précise un moment. Les danseuses est le sujet; le professeur est la personne rejointe."},
 {key:"arch",construction:"inverted",sentence:"Sous les arches passent les visiteurs du château avec leur guide.",verbForm:"passent",subject:"les visiteurs du château",distractors:["les arches","du château","leur guide"],reason:"On peut rétablir : les visiteurs du château passent sous les arches. Le sujet complet vient après le verbe."},
 {key:"lantern",construction:"inverted",sentence:"Au-dessus des tables brille une lanterne près du balcon.",verbForm:"brille",subject:"une lanterne",distractors:["des tables","du balcon","Au-dessus des tables"],reason:"Une lanterne brille : le sujet singulier est après le verbe. Les tables indiquent un lieu."},
 {key:"delivery",construction:"inverted",sentence:"À quelle heure arrive le livreur de la pharmacie avec le colis ?",verbForm:"arrive",subject:"le livreur de la pharmacie",distractors:["quelle heure","de la pharmacie","le colis"],reason:"Le livreur de la pharmacie arrive à une certaine heure. Le sujet est le groupe entier, pas le colis qu’il apporte."},
 {key:"market",construction:"inverted",sentence:"Derrière la mairie attendent les marchands avec leurs paniers de fruits.",verbForm:"attendent",subject:"les marchands",distractors:["la mairie","leurs paniers de fruits","de fruits"],reason:"Les marchands attendent derrière la mairie. Leur place après le verbe ne change pas leur fonction de sujet."},
 {key:"cooks",construction:"coordinated",sentence:"Yanis et Chloé découpent les légumes sur la planche près de l’évier.",verbForm:"découpent",subject:"Yanis et Chloé",distractors:["Chloé","les légumes","la planche"],reason:"Les deux personnes forment ensemble le sujet. Choisir seulement Chloé laisserait de côté Yanis."},
 {key:"devices",construction:"coordinated",sentence:"Le portable et la tablette affichent le même message sur leur écran.",verbForm:"affichent",subject:"Le portable et la tablette",distractors:["la tablette","le même message","leur écran"],reason:"Les deux appareils distincts forment le sujet pluriel; le message est ce qui est affiché."},
 {key:"museum",construction:"coordinated",sentence:"La guide et les élèves traversent la galerie vers la sortie du musée.",verbForm:"traversent",subject:"La guide et les élèves",distractors:["les élèves","la galerie","la sortie du musée"],reason:"La guide fait partie du sujet avec les élèves. La galerie est traversée, elle n’est pas le sujet."},
 {key:"instruments",construction:"coordinated",sentence:"Le violon et la flûte accompagnent la chanteuse pendant le refrain.",verbForm:"accompagnent",subject:"Le violon et la flûte",distractors:["la flûte","la chanteuse","le refrain"],reason:"Le sujet réunit les deux instruments; la chanteuse est accompagnée et le refrain précise le moment."},
];
