import type {TargetTeachingContent} from "./teaching-content";
const cases=[
 {sentence:"Le projecteur éclaire les acteurs près du rideau.",verb:"éclaire",answer:"Le projecteur",others:["les acteurs","du rideau","près du rideau"],hint:"Quel groupe peut être remplacé par il devant éclaire ?",explanation:"Le projecteur est le sujet : il éclaire les acteurs. Un objet peut être sujet. Les acteurs reçoivent la lumière."},
 {sentence:"Les pages du carnet dépassent de la poche.",verb:"dépassent",answer:"Les pages du carnet",others:["du carnet","la poche","Les pages"],hint:"Cherche tout le groupe qui peut être remplacé par elles, avec la précision qui l’accompagne.",explanation:"Les pages du carnet forme le groupe sujet complet. Pages en est le noyau pluriel; du carnet précise de quelles pages on parle. Les pages seul ne reprend pas le groupe complet demandé."},
 {sentence:"Au bout du couloir patientent les parents avec leurs enfants.",verb:"patientent",answer:"les parents",others:["du couloir","leurs enfants","Au bout du couloir"],hint:"Remets la phrase dans l’ordre : les parents patientent au bout du couloir avec leurs enfants.",explanation:"Les parents est le sujet, même placé après patientent. Le couloir indique un lieu et avec leurs enfants ajoute une précision."},
 {sentence:"Le jardinier et sa voisine transportent les pots jusqu’au portail.",verb:"transportent",answer:"Le jardinier et sa voisine",others:["sa voisine","les pots","Le jardinier"],hint:"Et réunit ici deux personnes dans le sujet. Il faut garder les deux.",explanation:"Le jardinier et sa voisine est le sujet complet : ils transportent les pots. Chaque personne seule ne constitue qu’une partie de ce sujet."},
 {sentence:"La fresque est admirée par les passants depuis le trottoir.",verb:"est",answer:"La fresque",others:["les passants","le trottoir","par les passants"],hint:"On peut dire : elle est admirée par les passants. Quel groupe elle remplace-t-il ?",explanation:"La fresque est le sujet du verbe est. Ce sont les passants qui admirent, mais la phrase présente la fresque comme ce qui est admiré. Le sujet n’est donc pas toujours celui qui fait l’action."},
 {sentence:"La bibliothécaire classe les romans et les albums sur les étagères.",verb:"classe",answer:"La bibliothécaire",others:["les romans et les albums","les albums","les étagères"],hint:"Et peut relier des objets de l’action. Il ne transforme pas automatiquement ces mots en sujet.",explanation:"La bibliothécaire est le sujet : elle classe les livres. Les romans et les albums est le groupe qui indique ce qu’elle classe, même si deux noms y sont reliés par et."},
];
const lesson:TargetTeachingContent={
 id:"french-v3-teaching:identifier_sujet_verbe",nodeKey:"identifier_sujet_verbe",mode:"recognition",status:"draft_requires_review",
 titleFr:"Trouver le sujet complet d’un verbe",learnerQuestionFr:"Dans « Les élèves du club arrivent », qui commande la forme arrivent ?",
 steps:[
  {exampleFr:"Les élèves du club arrivent. Ils arrivent.",explanationFr:"Le groupe Les élèves du club peut être remplacé par ils. C’est le sujet du verbe arrivent : il lui donne sa personne et son nombre. Élèves est le mot principal, appelé noyau; du club précise de quels élèves on parle."},
  {exampleFr:"Devant la salle arrivent les élèves du club.",explanationFr:"Le sujet peut venir après le verbe. Remets-le mentalement devant : Les élèves du club arrivent devant la salle. Devant la salle donne un lieu; ce groupe n’est pas le sujet."},
  {exampleFr:"Le colis est ouvert par la responsable. Il est ouvert par la responsable.",explanationFr:"Le colis est le sujet de est, même si la responsable fait l’action d’ouvrir. Pour trouver le sujet, ne demande pas seulement qui fait l’action : vérifie aussi le lien grammatical avec le verbe et le remplacement par un pronom."},
 ],
 takeawayFr:"Repère le verbe demandé. Cherche le groupe qui peut devenir il, elle, ils ou elles en gardant le même lien avec ce verbe. Si on demande le sujet complet, garde ses précisions et tous les éléments reliés dans ce sujet.",
 boundaryFr:"Ces exemples utilisent des sujets constitués de noms ou de groupes nominaux. Les sujets comme je ou nous, les phrases avec plusieurs propositions et les tournures impersonnelles seront travaillés séparément. Trouver le sujet ne prouve pas encore que tu sais écrire toutes les formes du verbe.",
 practice:cases.map((item,index)=>({id:`subject-identification-guide-${index+1}`,promptFr:`${item.sentence}\n\nQuel est le groupe sujet complet du verbe « ${item.verb} » ?`,choices:[item.answer,...item.others],answerFr:item.answer,hintFr:item.hint,explanationFr:item.explanation})),
};
export const SUBJECT_TEACHING:readonly TargetTeachingContent[]=[{...lesson,materialExposure:{sentences:[...lesson.steps.map(step=>step.exampleFr),...cases.map(item=>item.sentence)]}}];
