export type TenseRecognitionDraft={key:string;nodeKey:"reconnaitre_futur_proche"|"reconnaitre_passe_recent";prompt:string;answer:string;distractors:[string,string,string];reason:string};
export const TENSE_RECOGNITION_DRAFTS:readonly TenseRecognitionDraft[]=[
 {key:"future-library",nodeKey:"reconnaitre_futur_proche",prompt:"Je vais emprunter ce roman.\n\nQuel groupe verbal forme le futur proche ?",answer:"vais emprunter",distractors:["Je vais","emprunter ce roman","ce roman"],reason:"Vais est aller au présent et emprunter est l’infinitif."},
 {key:"future-measure",nodeKey:"reconnaitre_futur_proche",prompt:"Quelle phrase emploie le futur proche ?",answer:"Tu vas mesurer la planche.",distractors:["Tu mesures la planche.","Tu as mesuré la planche.","Tu mesureras la planche."],reason:"Vas mesurer suit le modèle aller au présent + infinitif."},
 {key:"future-negative",nodeKey:"reconnaitre_futur_proche",prompt:"Quelle phrase contient un futur proche malgré la négation ?",answer:"Les voisins ne vont pas déplacer leur voiture.",distractors:["Les voisins ne déplacent pas leur voiture.","Les voisins n’ont pas déplacé leur voiture.","Les voisins ne déplaçaient pas leur voiture."],reason:"Ne vont pas déplacer conserve aller au présent et déplacer à l’infinitif."},
 {key:"future-destination",nodeKey:"reconnaitre_futur_proche",prompt:"Dans quelle phrase va forme-t-il un futur proche ?",answer:"Il va examiner le dessin.",distractors:["Il va au cours de dessin.","Il va chez sa tante.","Il va dans la cour."],reason:"Examiner est un infinitif; les autres groupes après va indiquent une destination."},
 {key:"future-adverb",nodeKey:"reconnaitre_futur_proche",prompt:"Nous allons probablement gagner cette manche.\n\nQuels verbes forment le futur proche ?",answer:"allons et gagner",distractors:["allons et probablement","gagner et manche","Nous et allons"],reason:"L’adverbe probablement s’insère entre aller au présent et l’infinitif sans changer la construction."},
 {key:"future-time",nodeKey:"reconnaitre_futur_proche",prompt:"Les quatre phrases annoncent une activité pour samedi. Laquelle emploie le futur proche ?",answer:"Samedi, elle va fabriquer un cerf-volant.",distractors:["Samedi, elle fabrique un cerf-volant.","Samedi, elle fabriquera un cerf-volant.","Samedi, un cerf-volant sera fabriqué."],reason:"Va fabriquer est un futur proche; le moment samedi ne suffit pas à nommer le temps."},
 {key:"future-name",nodeKey:"reconnaitre_futur_proche",prompt:"Le gardien va éteindre les lumières.\n\nComment appelle-t-on la construction va éteindre ?",answer:"Le futur proche.",distractors:["Le passé composé.","L’imparfait.","Le passé récent."],reason:"Va est aller au présent et éteindre est un infinitif."},
 {key:"future-no-longer",nodeKey:"reconnaitre_futur_proche",prompt:"Vous n’allez plus utiliser ce chemin.\n\nQuel groupe contient toute la construction du futur proche avec sa négation ?",answer:"n’allez plus utiliser",distractors:["Vous n’allez","utiliser ce chemin","plus utiliser ce chemin"],reason:"La négation entoure allez; utiliser complète la construction du futur proche."},
 {key:"recent-station",nodeKey:"reconnaitre_passe_recent",prompt:"Le train vient de quitter la gare.\n\nQuel groupe forme le passé récent ?",answer:"vient de quitter",distractors:["Le train vient","quitter la gare","de quitter la gare"],reason:"Vient est venir au présent, suivi de de et de l’infinitif quitter."},
 {key:"recent-find",nodeKey:"reconnaitre_passe_recent",prompt:"Quelle phrase emploie le passé récent ?",answer:"Nous venons de retrouver notre chat.",distractors:["Nous retrouvons notre chat.","Nous avons retrouvé notre chat.","Nous allons retrouver notre chat."],reason:"Venons de retrouver présente l’action comme tout juste accomplie."},
 {key:"recent-apostrophe",nodeKey:"reconnaitre_passe_recent",prompt:"Les enfants viennent d’apercevoir un hérisson.\n\nQuel groupe forme le passé récent ?",answer:"viennent d’apercevoir",distractors:["Les enfants viennent","apercevoir un hérisson","d’apercevoir un hérisson"],reason:"D’ est la forme de de devant l’infinitif apercevoir."},
 {key:"recent-provenance",nodeKey:"reconnaitre_passe_recent",prompt:"Dans quelle phrase viens de forme-t-il un passé récent ?",answer:"Je viens de réparer mon casque.",distractors:["Je viens de Lille.","Je viens de la plage.","Je viens de chez mon cousin."],reason:"Réparer est un infinitif. Lille, la plage et chez mon cousin indiquent une provenance."},
 {key:"recent-structure",nodeKey:"reconnaitre_passe_recent",prompt:"Tu viens de renverser ton verre.\n\nQuelle description correspond à la construction viens de renverser ?",answer:"Venir au présent + de + infinitif.",distractors:["Aller au présent + infinitif.","Avoir au présent + participe passé.","Venir à l’imparfait + de + infinitif."],reason:"Viens est au présent et renverser reste à l’infinitif."},
 {key:"recent-name",nodeKey:"reconnaitre_passe_recent",prompt:"Vous venez de recevoir une carte.\n\nComment appelle-t-on venez de recevoir ?",answer:"Le passé récent.",distractors:["Le futur proche.","Le passé composé.","L’imparfait."],reason:"Venez est venir au présent; de recevoir complète le passé récent."},
 {key:"recent-comparison",nodeKey:"reconnaitre_passe_recent",prompt:"Quelle phrase emploie venir au présent + de + infinitif pour présenter une action tout juste terminée ?",answer:"La joueuse vient de marquer un but.",distractors:["La joueuse a marqué un but.","La joueuse va marquer un but.","La joueuse marquait un but."],reason:"Vient de marquer est la construction demandée, distincte du passé composé a marqué."},
 {key:"recent-place",nodeKey:"reconnaitre_passe_recent",prompt:"Quelle phrase indique une provenance et ne contient pas de passé récent ?",answer:"Les colis viennent de l’entrepôt.",distractors:["Les colis viennent d’arriver.","Les colis viennent de tomber.","Les colis viennent de repartir."],reason:"De l’entrepôt est un lieu; les autres phrases contiennent de ou d’ suivi d’un infinitif."},
];
