import {expect,it} from "vitest";
import {readTextualSupport,publicTextualSupport,gradeTextualSupport} from "./textual-support";
import {assessSkills,type Skill} from "./engine";
import type {GeneratedItem} from "@/lib/ai/item-generation/schemas";
import {readFileSync} from "node:fs";
import {adaptV3ForAssessment} from "./v3-adapter";
import {createSession} from "./session";
import {bindAssessmentRelease} from "./release-binding";
import {runAssessmentCommand,publicAssessmentView,type AssessmentBundle,type AssessmentStore,type StoredSession} from "./service";
const passage="Lina serre son manteau. Le vent siffle sous la porte. Son sac est bleu.";
const item:GeneratedItem={nodeKey:"inferer_cause_locale",strand:"comprehension_ecrite",modality:"reading",learnerMode:"shared",responseType:"mcq",promptFr:`${passage}\nPourquoi Lina serre-t-elle son manteau ?`,acceptableAnswers:[],validatorType:"exact",choices:[{text:"Elle a froid.",correct:true},{text:"Elle cherche son sac.",correct:false}],validatorConfig:{textualSupport:{passageText:passage,choices:[{quoteFr:"Le vent siffle sous la porte.",correct:true},{quoteFr:"Son sac est bleu.",correct:false}]}}};
it("accepts only excerpts from the displayed passage and withholds the answer key",()=>{
 expect(readTextualSupport(item)).not.toBeNull();
 const publicChoices=publicTextualSupport("session","item",item)!;
 expect(JSON.stringify(publicChoices)).not.toContain("correct");
 const good=publicChoices.find(c=>c.text.startsWith("Le vent"))!.id;
 const bad=publicChoices.find(c=>c.id!==good)!.id;
 expect(gradeTextualSupport("session","item",item,good)).toEqual({valid:true,correct:true});
 expect(gradeTextualSupport("session","item",item,bad)).toEqual({valid:true,correct:false});
 expect(gradeTextualSupport("other-session","item",item,good).valid).toBe(false);
 expect(gradeTextualSupport("session","item",item,undefined).valid).toBe(false);
 const changed=structuredClone(item);changed.promptFr="Un autre texte.";
 expect(()=>readTextualSupport(changed)).toThrow(/differs/);
});
it("does not count answers without assessed support as evidence for a support-required skill",()=>{
 const skill:Skill={id:"reading",branch:"reading",level:0,modes:["interpretation"],prerequisites:[],evidenceRequirements:{interpretation:{minimumItems:3,minimumContexts:3,minimumOccasions:2,minimumAccuracy:.8,unaidedRequired:true,textualSupportRequired:true}}};
 const answers=Array.from({length:4},(_,i)=>({itemId:`q${i}`,skillId:skill.id,mode:"interpretation" as const,contextId:`text${i}`,occasionId:`occasion${i}`,unaided:true,correct:true,guessProbability:.25,activeSeconds:30}));
 expect(assessSkills([skill],answers)[0].status).toBe("unknown");
 expect(assessSkills([skill],answers.map(a=>({...a,textualSupportAssessed:true})))[0].status).toBe("mastered");
});
it("grades the conclusion and supporting passage together through the saved assessment command",async()=>{
 const bank=JSON.parse(readFileSync("generated/diagnostic-bank-v3-draft.json","utf8"));
 const full=adaptV3ForAssessment({bank,artifact:JSON.parse(readFileSync("generated/french-taxonomy-v3.json","utf8"))});
 const skill={...full.skills.find(s=>s.nodeKey===item.nodeKey)!,prerequisites:[]};
 const assessment={...full,skills:[skill],probes:[{id:"support-test",skillId:skill.id,mode:skill.modes[0],contextId:"passage:test",difficulty:.5,expectedSeconds:60,guessProbability:.5,textualSupportAssessed:true}]};
 const entry={...bank.items[0],itemKey:"support-test",item};
 const bundle:AssessmentBundle={assessment,bank:{...bank,items:[entry]},taxonomyId:"taxonomy",bankId:"bank"};
 const id="11111111-1111-4111-8111-111111111111";
 let stored:StoredSession={id,studentId:"student",releaseId:"release",state:{...createSession(bindAssessmentRelease(assessment,bundle)),paused:false,pendingItemId:"support-test",lastPulseAt:0}};
 const store:AssessmentStore={load:async()=>structuredClone(stored),release:async()=>bundle,save:async(_,__,revision,state)=>{if(revision!==stored.state.revision)return false;stored={...stored,state};return true;}};
 const question=publicAssessmentView(stored,bundle).question!;
 const answer=question.choices.find(c=>c.text==="Elle a froid.")!.id;
 const command={type:"answer",sessionId:id,revision:0,itemId:"support-test",answer};
 expect(await runAssessmentCommand(store,"student",command,()=>0)).toHaveProperty("error");
 expect(stored.state.observations).toHaveLength(0);
 const bad=question.supportChoices!.find(c=>c.text==="Son sac est bleu.")!.id;
 await runAssessmentCommand(store,"student",{...command,supportChoiceId:bad},()=>0);
 expect(stored.state.observations[0]).toMatchObject({correct:false,textualSupportAssessed:true});
});
