"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { createCompetencyEdge, deactivateSkill, deactivateVocabulary, saveCompetencyNode, saveMisconception, saveSkill, saveVocabulary } from "@/lib/actions/catalog";

const input="h-9 w-full rounded-md border border-input bg-background px-3 text-sm";
export function SkillManager({skills}:{skills:Array<{id:string;key:string;label_fr:string;category:string;description_fr:string|null;active:boolean}>}){const router=useRouter();const[id,setId]=useState<string|undefined>();const[key,setKey]=useState("");const[label,setLabel]=useState("");const[category,setCategory]=useState("lecture");const[error,setError]=useState("");function clear(){setId(undefined);setKey("");setLabel("");setCategory("lecture");}async function save(e:React.FormEvent){e.preventDefault();try{await saveSkill({id,key,labelFr:label,category});clear();router.refresh();}catch{setError("Enregistrement impossible.");}}return <><Card className="mb-5"><CardContent className="pt-6"><form onSubmit={save} className="grid gap-3 sm:grid-cols-4"><input aria-label="Clé" value={key} onChange={e=>setKey(e.target.value)} className={input} placeholder="cle_stable"/><input aria-label="Libellé" value={label} onChange={e=>setLabel(e.target.value)} className={input} placeholder="Libellé français"/><input aria-label="Catégorie" value={category} onChange={e=>setCategory(e.target.value)} className={input}/><div className="flex gap-2"><Button>{id?"Enregistrer":"Ajouter"}</Button>{id&&<Button type="button" variant="ghost" onClick={clear}>Annuler</Button>}</div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</form></CardContent></Card><div className="space-y-2">{skills.map(skill=><Card key={skill.id}><CardContent className="flex items-center justify-between gap-3 pt-6"><div><p className="font-medium">{skill.label_fr}</p><p className="text-xs text-muted-foreground">{skill.key} · {skill.category}{skill.active?"":" · inactive"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setId(skill.id);setKey(skill.key);setLabel(skill.label_fr);setCategory(skill.category)}}>Modifier</Button>{skill.active&&<Button size="sm" variant="destructive" onClick={()=>deactivateSkill(skill.id).then(()=>router.refresh())}>Désactiver</Button>}</div></CardContent></Card>)}</div></>}

export function VocabularyManager({items}:{items:Array<{id:string;lemma:string;display_word:string;definition_fr:string|null;difficulty:number|null;frequency_per_million:number|null;active:boolean}>}){const router=useRouter();const[id,setId]=useState<string|undefined>();const[word,setWord]=useState("");const[definition,setDefinition]=useState("");const[frequency,setFrequency]=useState(10);function clear(){setId(undefined);setWord("");setDefinition("");setFrequency(10);}async function save(e:React.FormEvent){e.preventDefault();await saveVocabulary({id,lemma:word,displayWord:word,definitionFr:definition,frequencyPerMillion:frequency});clear();router.refresh();}return <><Card className="mb-5"><CardContent className="pt-6"><form onSubmit={save} className="grid gap-3 sm:grid-cols-4"><input aria-label="Mot" value={word} onChange={e=>setWord(e.target.value)} className={input} placeholder="Mot"/><input aria-label="Définition" value={definition} onChange={e=>setDefinition(e.target.value)} className={`${input} sm:col-span-2`} placeholder="Définition"/><div className="flex gap-2"><input aria-label="Fréquence par million" type="number" min="0" step="0.1" value={frequency} onChange={e=>setFrequency(Number(e.target.value))} className={input}/><Button>{id?"Enregistrer":"Ajouter"}</Button></div>{id&&<Button type="button" variant="ghost" onClick={clear}>Annuler</Button>}</form></CardContent></Card><div className="space-y-2">{items.map(item=><Card key={item.id}><CardContent className="flex items-center justify-between gap-3 pt-6"><div><p className="font-medium">{item.display_word}</p><p className="text-xs text-muted-foreground">{item.definition_fr??"—"} · fréquence {item.frequency_per_million??"—"}/M · difficulté {item.difficulty??"—"}{item.active?"":" · inactive"}</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>{setId(item.id);setWord(item.display_word);setDefinition(item.definition_fr??"");setFrequency(item.frequency_per_million??0)}}>Modifier</Button>{item.active&&<Button size="sm" variant="destructive" onClick={()=>deactivateVocabulary(item.id).then(()=>router.refresh())}>Désactiver</Button>}</div></CardContent></Card>)}</div></>}

type Node={id:string;key:string;label_fr:string;description_fr:string|null;review_status:string}; type Edge={id:string;source_node_id:string;target_node_id:string;edge_type:string}; type Mis={id:string;label_fr:string;description_fr:string|null;primary_node_id:string|null;active:boolean};
export function GraphStudio({nodes,edges,misconceptions}:{nodes:Node[];edges:Edge[];misconceptions:Mis[]}){const router=useRouter();const [source,setSource]=useState(nodes[0]?.id??"");const [target,setTarget]=useState(nodes[1]?.id??"");const [message,setMessage]=useState("");async function addEdge(e:React.FormEvent){e.preventDefault();setMessage("");try{const r=await createCompetencyEdge({sourceNodeId:source,targetNodeId:target,edgeType:"prerequisite",strength:1});setMessage(r.warnings.length?`Lien créé avec avertissement : ${r.warnings.map(w=>w.message).join(" · ")}`:"Lien créé.");router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Lien refusé.");}}return <><Card className="mb-5"><CardContent className="pt-6"><h2 className="mb-3 font-semibold">Ajouter un prérequis</h2><form onSubmit={addEdge} className="grid gap-3 sm:grid-cols-3"><select value={source} onChange={e=>setSource(e.target.value)} className={`${input} appearance-none pr-10`}>{nodes.map(n=><option className="bg-zinc-950" key={n.id} value={n.id}>{n.label_fr}</option>)}</select><select value={target} onChange={e=>setTarget(e.target.value)} className={`${input} appearance-none pr-10`}>{nodes.map(n=><option className="bg-zinc-950" key={n.id} value={n.id}>{n.label_fr}</option>)}</select><Button>Vérifier et créer</Button></form>{message&&<p className="mt-2 text-sm text-muted-foreground">{message}</p>}<p className="mt-2 text-xs text-muted-foreground">{edges.length} liens existants. Les cycles sont refusés avant écriture.</p></CardContent></Card><h2 className="mb-3 font-semibold">Nœuds</h2><div className="mb-8 space-y-2">{nodes.map(node=><NodeEditor key={node.id} node={node} onSaved={()=>router.refresh()}/>)}</div><h2 className="mb-3 font-semibold">Erreurs-types</h2><div className="space-y-2">{misconceptions.map(m=><Card key={m.id}><CardContent className="flex flex-wrap items-center justify-between gap-3 pt-6"><div><p className="font-medium">{m.label_fr}</p><p className="text-xs text-muted-foreground">{m.description_fr??"—"}</p></div><button className="text-xs text-muted-foreground" onClick={()=>saveMisconception({id:m.id,labelFr:m.label_fr,descriptionFr:m.description_fr??undefined,nodeId:m.primary_node_id??undefined,active:!m.active}).then(()=>router.refresh())}>{m.active?"Désactiver":"Réactiver"}</button></CardContent></Card>)}</div></>}
function NodeEditor({node,onSaved}:{node:Node;onSaved:()=>void}){const [label,setLabel]=useState(node.label_fr);const [description,setDescription]=useState(node.description_fr??"");return <Card><CardContent className="grid gap-2 pt-6 sm:grid-cols-[1fr_2fr_auto]"><div><p className="text-xs text-muted-foreground">{node.key}</p><input aria-label={`Libellé ${node.key}`} className={input} value={label} onChange={e=>setLabel(e.target.value)}/></div><textarea aria-label={`Description ${node.key}`} className="rounded-md border border-input bg-background p-2 text-sm" value={description} onChange={e=>setDescription(e.target.value)}/><Button variant="outline" onClick={()=>saveCompetencyNode({id:node.id,key:node.key,labelFr:label,descriptionFr:description,reviewStatus:node.review_status}).then(onSaved)}>Enregistrer</Button></CardContent></Card>}
