import {readFileSync,writeFileSync} from "node:fs";
import {adaptV3ForAssessment} from "../src/lib/diagnostic/granular/v3-adapter";
import {auditHomophoneNovelty} from "../src/lib/diagnostic/granular/homophone-novelty-audit";
import {checksum} from "../src/lib/taxonomy/validate";
const read=(path:string)=>JSON.parse(readFileSync(path,"utf8"));
const artifact=read("generated/french-taxonomy-v3.json"),bank=read("generated/diagnostic-bank-v3-draft.json");
const assessment=adaptV3ForAssessment({artifact,bank}),rows=auditHomophoneNovelty(assessment);
const report={status:"proposal_requires_decision",taxonomyChecksum:assessment.taxonomyChecksum,affectedCompetencies:7,affectedEvidenceTargets:rows.length,rows};
const text=`# Homophone evidence: novelty feasibility review\n\nStatus: proposal requires a decision. No graph change or runtime override.\n\nApproved source: ${report.taxonomyChecksum}. Audit checksum: ${checksum(report)}.\n\n## Observed conflict\n\nThe approved graph requires at least three distinct items and novel target words for each of these fixed-pair skills. The runtime identifies novelty by the assessed word, so different question IDs or sentences do not make the same target word new. Even counting both spellings separately provides at most two distinct target words. A faithful target-word annotation therefore cannot satisfy either question pool. Recognition questions exposing both choices can exhaust the pair even sooner.\n\n| Skill | Recognition | Controlled production |\n| --- | --- | --- |\n${rows.filter(row=>row.mode==="recognition").map(row=>`| ${row.pair.join(" / ")} | Blocked under target-word novelty | Blocked under target-word novelty |`).join("\n")}\n\n## Concrete proposal for a separately versioned correction\n\nFor these seven competencies and their 14 evidence definitions only, replace the novel-target-word requirement with novel-sentence evidence. Preserve the competency IDs, prerequisite graph, recognition/production separation, minimum item counts, accuracy thresholds, contrasting-error criteria, unaided production and multiple occasions. Keep the approved v3 artifact and historical releases unchanged. A new checksum-bound decision would be needed before activating the correction.\n\nSixteen synthetic contexts per target fail allocation under the current rule and pass under the proposed sentence rule. This demonstrates feasibility, not educational validity, approval or sufficient reviewed content. Educator review must also ensure different meanings and sentence structures, not superficial rewording.\n\n## What remains unchanged now\n\nThe production adapter and release guards still enforce the approved word-novelty rule. No question, facet or content approval is created. The full-graph synthetic integration bank uses artificial unique tokens and must not be mistaken for proof that real fixed-pair homophone tasks satisfy this contract.\n`;
for(const [path,value] of [["docs/diagnostic/homophone-novelty-review.json",JSON.stringify({...report,checksum:checksum(report)},null,2)+"\n"],["docs/diagnostic/homophone-novelty-review.md",text]]){
 if(process.argv.includes("--check")){if(readFileSync(path,"utf8")!==value)throw Error(`Stale audit: ${path}`);}else writeFileSync(path,value);
}
console.log(JSON.stringify({affectedCompetencies:7,affectedEvidenceTargets:rows.length,currentPoolsReady:rows.filter(row=>row.currentPoolsReady).length,proposedPoolsReady:rows.filter(row=>row.proposedPoolsReady).length,status:report.status}));
