import {resolveTeachingScope} from "../src/lib/diagnostic/granular/teaching-scope";
import {granularBankOptions} from "./lib/granular-bank-options";
import {readFileSync,writeFileSync} from "node:fs";
import {checksum} from "../src/lib/taxonomy/validate";
import {applyQuestionPoolScope} from "../src/lib/diagnostic/granular/question-pools";
import {inspectReleaseBank} from "../src/lib/diagnostic/granular/release-bank";
import {teachingContentChecksum,validatePublishedTeaching,type ParallelReviewTeachingContent} from "../src/lib/diagnostic/granular/teaching-content";
import {validateActivityBindings} from "../src/lib/diagnostic/granular/activity-validation";
import {buildLearningCheckRegistry} from "../src/lib/diagnostic/granular/check-registry";
import {assembleDraftBank} from "../src/lib/diagnostic/granular/assemble-drafts";
import {FRENCH_DRAFT_EXPANSION_SOURCES} from "../src/lib/diagnostic/granular/draft-expansion-sources";
const read=(p:string)=>JSON.parse(readFileSync(p,"utf8"));
const prepared=read("docs/diagnostic/v3-parallel-review-candidate.json");
const {assessment:source,teachingReadiness}=prepared;
const ready=new Set<string>(teachingReadiness.filter((row:{freshCheckAvailable:boolean})=>row.freshCheckAvailable).map((row:{skillId:string})=>row.skillId));
const resolved=resolveTeachingScope(source.skills,ready);
const included=new Set(resolved.included);
const releasedReady=new Set([...ready].filter(id=>included.has(id)));
const assessment=applyQuestionPoolScope(source,{version:"french-granular-release-scope-v1",assessmentSkillIds:[...included].sort(),teachingSkillIds:[...releasedReady].sort(),limitationFr:"Ce premier bilan couvre une partie des compétences. Les autres restent à vérifier au fil du parcours."});
const artifact=read("generated/french-taxonomy-v3.json");
const {bank}=assembleDraftBank(read("generated/diagnostic-bank-v3-draft.json"),artifact.taxonomy,FRENCH_DRAFT_EXPANSION_SOURCES.map(name=>read(`generated/french-v3-${name}-expansion.json`)),granularBankOptions(process.argv.slice(2)));
const lessonIds=new Set(teachingReadiness.filter((row:{freshCheckAvailable:boolean;skillId:string})=>row.freshCheckAvailable&&releasedReady.has(row.skillId)).map((row:{lessonId:string})=>row.lessonId));
const probeIds=new Set(assessment.probes.map(probe=>probe.id));
const teachingContent:ParallelReviewTeachingContent[]=prepared.teachingContent.filter((lesson:{id:string})=>lessonIds.has(lesson.id)).map((lesson:ParallelReviewTeachingContent)=>({...lesson,assessmentExposureIds:lesson.assessmentExposureIds.filter(id=>probeIds.has(id))}));
assessment.reviewPolicy={...assessment.reviewPolicy!,teachingChecksums:Object.fromEntries(teachingContent.map(lesson=>[lesson.id,teachingContentChecksum(lesson)]))};
validatePublishedTeaching(assessment,teachingContent);
const checks=buildLearningCheckRegistry(assessment,bank,artifact.taxonomy);
const activities=[...checks.bindings,...prepared.teachingBindings.filter((binding:{contentId:string})=>lessonIds.has(binding.contentId))];
validateActivityBindings(assessment,activities);
const bankValid=inspectReleaseBank({assessment,bank,taxonomyId:"unpublished",bankId:"unpublished"});
if(!bankValid)throw Error("Scoped candidate fails approved graph/bank validation");
const missingInstructionSkillIds=[...included].filter(id=>!ready.has(id)).sort();
const content={status:"scoped_release_preparation",assessment,teachingContent,activities,bankChecksum:assessment.bankChecksum,summary:{graphTargets:assessment.skills.length,assessmentTargets:included.size,teachingTargets:releasedReady.size,questions:assessment.probes.length,missingInstructionTargets:missingInstructionSkillIds.length},missingInstructionSkillIds,blockedTeachingTargets:resolved.blocked,limitations:["Not published or activated", "Draft check bindings still require publication", "Missing prerequisite instruction must be completed", "Full graph question coverage remains incomplete"]};
const path="docs/diagnostic/v3-scoped-review-candidate.json",output=JSON.stringify({...content,checksum:checksum(content)},null,2)+"\n";
if(process.argv.includes("--check")){if(readFileSync(path,"utf8")!==output)throw Error("Stale scoped candidate");}else writeFileSync(path,output);
console.log(JSON.stringify(content.summary));
