import {conjugate,PERSONS} from "../src/lib/linguistic/conjugation";
import {readFileSync,writeFileSync} from 'node:fs';
import {FUTUR_PROCHE_APPLICATIONS} from '../src/lib/diagnostic/granular/futur-proche-production';
import {conjugationFacet} from '../src/lib/diagnostic/granular/facets';
import {runGates} from '../src/lib/ai/item-generation/pipeline';
import {checksum} from '../src/lib/taxonomy/validate';
import {validateCanonicalDiagnosticBank,type CanonicalDiagnosticBankArtifact,type CanonicalDiagnosticBankItem} from '../src/lib/diagnostic/item-bank';
import {questionMaterialKeys} from '../src/lib/diagnostic/granular/material-annotations';
import type {FacetAnnotation} from '../src/lib/diagnostic/granular/facet-adapter';
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8'));
const artifact=read('generated/french-taxonomy-v3.json'),base=read('generated/diagnostic-bank-v3-draft.json') as CanonicalDiagnosticBankArtifact;
const node=artifact.taxonomy.nodes.find((n:{key:string})=>n.key==='produire_futur_proche');
const evidence=node.evidence.find((e:{expectation:string})=>e.expectation==='controlled_production');
const items:CanonicalDiagnosticBankItem[]=[],annotations:FacetAnnotation[]=[];
for(const [i,row] of FUTUR_PROCHE_APPLICATIONS.entries()){
 const config={verb:row.verb,tense:'futur_proche',person:row.person};
 const sentences=[row.sentence,row.sentence.replace('___',row.answer)];
 const raw={nodeKey:node.key,strand:node.strand,modality:'writing',learnerMode:'shared',responseType:'short_answer',promptFr:`Complète avec ${row.verb} au futur proche : ${row.sentence}`,instructionsFr:'Écris le groupe verbal manquant.',correctAnswer:row.answer,acceptableAnswers:[],validatorType:'conjugator',difficulty:50,validatorConfig:{...config,sentenceApplication:row.sentence,finiteResponseSpace:{alternatives:PERSONS.map(person=>conjugate(row.verb,"futur_proche",person)),rationaleFr:"Le verbe et le temps sont fournis. Les six formes de personne donnent un plancher conservateur de hasard pour cette production contrôlée, pas une rédaction libre."},materialExposure:{words:[{lemma:row.verb,form:row.verb}],sentences,assessed:{sentences}}}};
 const checked=await runGates(raw,{knownNodeKeys:new Set([node.key]),knownMisconceptionKeys:new Set()});if(!checked.item||checked.gates.verdict==='rejected')throw Error(`Rejected futur proche ${i}`);
 questionMaterialKeys(checked.item);
 const itemKey=`v3-futur-proche-production:${row.verb}:${row.person}:${i}`;
 const entry:CanonicalDiagnosticBankItem={itemKey,item:checked.item,evidenceKey:evidence.key,evidenceExpectation:evidence.expectation,sectionKey:'conjugation',promptFamily:'sentence-form-application',difficultyTier:'core',reviewStatus:'needs_human_review',qcGates:{...checked.gates,gate3_ensemble:{agrees:false,agreement:0},verdict:'needs_human_review'}};
 items.push(entry);annotations.push({itemKey,itemChecksum:checksum(entry),facetKey:conjugationFacet(node.key,config)!,contextKey:`futur-proche-application:${i}`});
}
const combined={...base,items:[...base.items,...items]};delete combined.manifest;
const validation=validateCanonicalDiagnosticBank(combined,artifact.taxonomy);if(validation.issues.length)throw Error(validation.issues.join('\n'));
const content={version:'french-v3-futur-proche-production-expansion-v1',status:'draft_requires_review',parentTaxonomyChecksum:artifact.manifest.contentChecksum,sourceBankChecksum:validateCanonicalDiagnosticBank(base,artifact.taxonomy).manifest.checksum,items,annotations};
const path='generated/french-v3-futur-proche-production-expansion.json',output=JSON.stringify({...content,checksum:checksum(content)},null,2)+'\n';
if(process.argv.includes('--check')){if(readFileSync(path,'utf8')!==output)throw Error('Stale futur proche production');}else writeFileSync(path,output);
console.log(JSON.stringify({questions:items.length}));
