import{readFileSync}from"node:fs";import{config as loadEnv}from"dotenv";import{createClient}from"@supabase/supabase-js";import{stableUuid}from"../src/lib/lexicon/baseline";import type{FrenchTaxonomyV1Artifact}from"../src/lib/taxonomy/french-v1";
loadEnv({path:".env.local",quiet:true});
const artifact=JSON.parse(readFileSync(process.argv[2]??"generated/french-taxonomy-v1.json","utf8")) as FrenchTaxonomyV1Artifact;
if(!artifact.validation.valid)throw new Error("Taxonomy artifact is not valid.");
const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase service environment is required.");
const db=createClient(url,key,{auth:{persistSession:false}});const fail=(message?:string)=>{if(message)throw new Error(message);};
const releaseGate=await db.from("taxonomy_releases").select("id,status,manifest_checksum").eq("release_key",artifact.release.key).maybeSingle();fail(releaseGate.error?.message);if(releaseGate.data&&releaseGate.data.manifest_checksum!==artifact.manifest.contentChecksum)throw new Error("Existing release key has a different checksum.");if(releaseGate.data&&["published","withdrawn"].includes(releaseGate.data.status as string)){process.stdout.write(`${JSON.stringify({ok:true,unchanged:true,releaseId:releaseGate.data.id,checksum:artifact.manifest.contentChecksum})}\n`);process.exit(0);}
let ontology=await db.from("ontology_versions").select("id,checksum").eq("version",artifact.ontology.version).maybeSingle();fail(ontology.error?.message);if(ontology.data&&ontology.data.checksum!==artifact.ontology.checksum)throw new Error("Ontology version checksum mismatch.");if(!ontology.data){const r=await db.from("ontology_versions").insert({version:artifact.ontology.version,document_path:artifact.ontology.document,checksum:artifact.ontology.checksum,status:"active",approved_at:new Date().toISOString()}).select("id,checksum").single();fail(r.error?.message);ontology=r;}const ontologyId=ontology.data!.id as string;
let source=await db.from("taxonomy_sources").select("id").eq("source_key","sigma-original-taxonomy").maybeSingle();fail(source.error?.message);if(!source.data){const r=await db.from("taxonomy_sources").insert({source_key:"sigma-original-taxonomy",title:"SigmaWrite French Taxonomy",owner_name:"SigmaWrite",source_kind:"original",steward:"taxonomy-steward"}).select("id").single();fail(r.error?.message);source=r;}const sourceId=source.data!.id as string;
let sourceVersion=await db.from("taxonomy_source_versions").select("id,artifact_checksum").eq("source_id",sourceId).eq("version_label","1.0.0").maybeSingle();fail(sourceVersion.error?.message);if(sourceVersion.data&&sourceVersion.data.artifact_checksum!==artifact.sources.checksum)throw new Error("Taxonomy source checksum mismatch.");if(!sourceVersion.data){const r=await db.from("taxonomy_source_versions").insert({source_id:sourceId,version_label:"1.0.0",artifact_checksum:artifact.sources.checksum,rights_status:"importable",license_identifier:"Proprietary-SigmaWrite-v1",terms_snapshot:"Original SigmaWrite taxonomy records.",permitted_fields:["competency_nodes","competency_edges","mastery_evidence","progression_mappings","content_concepts"],attribution_template:"© SigmaWrite, French Taxonomy {release_version}.",commercial_use_allowed:true,decision_notes:"Original records approved by source register.",approved_at:new Date().toISOString()}).select("id,artifact_checksum").single();fail(r.error?.message);sourceVersion=r;}const sourceVersionId=sourceVersion.data!.id as string;
const existing=await db.from("competency_nodes").select("id,key").in("key",artifact.taxonomy.nodes.map(n=>n.key));fail(existing.error?.message);const nodeIds=new Map((existing.data??[]).map(row=>[row.key as string,row.id as string]));
for(const node of artifact.taxonomy.nodes){const id=nodeIds.get(node.key)??stableUuid("sigmawrite-taxonomy-node",node.key);nodeIds.set(node.key,id);const modalities=[...new Set(node.evidence.map(e=>e.modality).filter(m=>m!=="multimodal"))];const expectations=[...new Set(node.evidence.map(e=>e.expectation))];const row={id,key:node.key,strand:node.strand,label_fr:node.labelFr,description_fr:node.descriptionFr,atomicity_level:node.atomicityLevel,ontology_version_id:ontologyId,node_type:node.nodeType,modality_scope:modalities,expectation_scope:expectations,generation_type:"human",review_status:"human_approved",version:1};const r=await db.from("competency_nodes").upsert(row,{onConflict:"key"});fail(r.error?.message);
for(const evidence of node.evidence){const evidenceId=stableUuid("sigmawrite-mastery-evidence",`${node.key}:${evidence.key}`);const minimumDistinctItems=Math.max(2,Number(evidence.successCriteria.minimumDistinctItems??evidence.successCriteria.minimumDistinctTexts??2));const minimumOccasions=Math.max(2,Number(evidence.successCriteria.minimumOccasions??2));const er=await db.from("competency_mastery_evidence").upsert({id:evidenceId,node_id:id,evidence_key:evidence.key,observable_action_fr:evidence.actionFr,modality:evidence.modality,expectation:evidence.expectation,success_criteria:evidence.successCriteria,minimum_distinct_items:minimumDistinctItems,minimum_occasions:minimumOccasions,source_version_id:sourceVersionId,review_status:"human_approved"},{onConflict:"id"});fail(er.error?.message);}
for(const mapping of node.mappings){const expectation=node.evidence[0]?.expectation??"receptive";const mappingId=stableUuid("sigmawrite-progression-mapping",`${node.key}:${mapping.learnerMode}:${mapping.framework}:${expectation}`);const mr=await db.from("competency_progression_mappings").upsert({id:mappingId,node_id:id,learner_mode:mapping.learnerMode,framework:mapping.framework,level_min:mapping.levelMin??null,level_max:mapping.levelMax??null,expectation,mapping_status:mapping.status,confidence:mapping.status==="reviewed"?.8:.5,rationale:"French progression matrix v1.",source_version_id:sourceVersionId},{onConflict:"id"});fail(mr.error?.message);}}
for(const edge of artifact.taxonomy.edges){const sourceNodeId=nodeIds.get(edge.source),targetNodeId=nodeIds.get(edge.target);if(!sourceNodeId||!targetNodeId)throw new Error(`Dangling edge ${edge.source}->${edge.target}`);const id=stableUuid("sigmawrite-taxonomy-edge",`${edge.source}:${edge.target}:${edge.type}`);const r=await db.from("competency_edges").upsert({id,source_node_id:sourceNodeId,target_node_id:targetNodeId,edge_type:edge.type,prerequisite_class:edge.prerequisiteClass??null,rationale:edge.rationale,source_version_id:sourceVersionId,generation_type:"human",review_status:"human_approved"},{onConflict:"source_node_id,target_node_id,edge_type"});fail(r.error?.message);}
let release=await db.from("taxonomy_releases").select("id,status,manifest_checksum").eq("release_key",artifact.release.key).maybeSingle();fail(release.error?.message);if(release.data&&release.data.manifest_checksum!==artifact.manifest.contentChecksum)throw new Error("Existing release key has a different checksum.");if(!release.data){const r=await db.from("taxonomy_releases").insert({release_key:artifact.release.key,version:artifact.release.version,ontology_version_id:ontologyId,status:"validating",manifest:{coverage:artifact.coverage,components:artifact.manifest.componentChecksums,gaps:artifact.gaps},manifest_checksum:artifact.manifest.contentChecksum,validation_report:{valid:true,issues:artifact.validation.issues}}).select("id,status,manifest_checksum").single();fail(r.error?.message);release=r;}const releaseId=release.data!.id as string;
if(!["published","withdrawn"].includes(release.data!.status as string)){
  const membership=async(recordType:string,recordId:string,stableKey:string,snapshot:unknown,recordChecksum:string)=>{const r=await db.from("taxonomy_release_memberships").upsert({release_id:releaseId,record_type:recordType,record_id:recordId,stable_key:stableKey,record_version:1,record_snapshot:snapshot,record_checksum:recordChecksum},{onConflict:"release_id,record_type,record_id"});fail(r.error?.message);};
  for(const node of artifact.taxonomy.nodes){await membership("competency_node",nodeIds.get(node.key)!,node.key,node,artifact.validation.manifest.checksums.nodes);
    for(const evidence of node.evidence){await membership("mastery_evidence",stableUuid("sigmawrite-mastery-evidence",`${node.key}:${evidence.key}`),`${node.key}:${evidence.key}`,evidence,artifact.validation.manifest.checksums.nodes);}
    for(const mapping of node.mappings){const expectation=node.evidence[0]?.expectation??"receptive";await membership("progression_mapping",stableUuid("sigmawrite-progression-mapping",`${node.key}:${mapping.learnerMode}:${mapping.framework}:${expectation}`),`${node.key}:${mapping.learnerMode}:${mapping.framework}:${expectation}`,mapping,artifact.validation.manifest.checksums.nodes);}}
  for(const edge of artifact.taxonomy.edges){await membership("competency_edge",stableUuid("sigmawrite-taxonomy-edge",`${edge.source}:${edge.target}:${edge.type}`),`${edge.source}:${edge.target}:${edge.type}`,edge,artifact.validation.manifest.checksums.edges);}
  for(const concept of artifact.contentConcepts){await membership("content_concept",stableUuid("sigmawrite-content-concept",concept.key),concept.key,concept,artifact.manifest.componentChecksums.concepts);}
}
const publisher=process.env.TAXONOMY_PUBLISHER_PROFILE_ID;if(publisher&&release.data!.status!=="published"){const reviewPath=artifact.release.key==="french-taxonomy-v1"?"docs/french-taxonomy-v1-release.md":"docs/french-taxonomy-v2-release.md";const review=readFileSync(reviewPath,"utf8");if(!review.includes(`**Approved checksum:** \`${artifact.manifest.contentChecksum}\``)||!review.includes("**Decision:** approve"))throw new Error("Checksum-bound release approval is not recorded.");const r=await db.from("taxonomy_releases").update({status:"published",published_by:publisher,published_at:new Date().toISOString()}).eq("id",releaseId).eq("status","validating");fail(r.error?.message);}
process.stdout.write(`${JSON.stringify({ok:true,releaseId,checksum:artifact.manifest.contentChecksum,published:Boolean(publisher),nodes:artifact.coverage.nodes})}\n`);
