/**
 * Emits idempotent SQL to seed the past-narration slice into Postgres.
 * Source of truth is src/lib/content/slices/past-narration.ts.
 *
 *   npx tsx scripts/seed-past-narration.mts > /tmp/seed-past-narration.sql
 *
 * Nodes are human-anchored, so they are inserted as review_status='human_approved'.
 * Re-runnable: upserts nodes by key, inserts edges/misconceptions on-conflict-skip.
 */
import {
  EDGES,
  MISCONCEPTIONS,
  NODES,
} from "../src/lib/content/slices/past-narration.ts";

const q = (s: string | undefined) =>
  s === undefined ? "null" : `'${s.replace(/'/g, "''")}'`;
const b = (v: boolean | undefined) => (v ? "true" : "false");

const lines: string[] = [];
lines.push("-- Generated by scripts/seed-past-narration.mts — do not edit by hand.");
lines.push("begin;");

// Nodes
lines.push(`
insert into competency_nodes
  (key, strand, label_fr, description_fr, atomicity_level,
   native_grade_min, native_grade_max, cefr_min, cefr_max,
   requires_reading, requires_writing, requires_listening, requires_speaking,
   generation_type, review_status)
values`);
lines.push(
  NODES.map(
    (n) =>
      `  (${q(n.key)}, ${q(n.strand)}, ${q(n.labelFr)}, ${q(n.descriptionFr)}, ${n.atomicityLevel}, ` +
      `${n.nativeGradeMin}, ${n.nativeGradeMax}, ${q(n.cefrMin)}, ${q(n.cefrMax)}, ` +
      `${b(n.requiresReading)}, ${b(n.requiresWriting)}, ${b(n.requiresListening)}, ${b(n.requiresSpeaking)}, ` +
      `'human', 'human_approved')`
  ).join(",\n")
);
lines.push(`on conflict (key) do update set
  strand = excluded.strand, label_fr = excluded.label_fr,
  description_fr = excluded.description_fr, atomicity_level = excluded.atomicity_level,
  native_grade_min = excluded.native_grade_min, native_grade_max = excluded.native_grade_max,
  cefr_min = excluded.cefr_min, cefr_max = excluded.cefr_max,
  requires_reading = excluded.requires_reading, requires_writing = excluded.requires_writing,
  requires_listening = excluded.requires_listening, requires_speaking = excluded.requires_speaking,
  review_status = 'human_approved', updated_at = now();`);

// Edges (resolve keys → ids via join)
const edgeValues = EDGES.map(
  (e) => `    (${q(e.source)}, ${q(e.target)}, ${q(e.edgeType)})`
).join(",\n");
lines.push(`
insert into competency_edges (source_node_id, target_node_id, edge_type, generation_type)
select s.id, t.id, e.edge_type, 'human'
from (values
${edgeValues}
) as e(src, tgt, edge_type)
join competency_nodes s on s.key = e.src
join competency_nodes t on t.key = e.tgt
on conflict (source_node_id, target_node_id, edge_type) do nothing;`);

// Misconceptions
lines.push(`
insert into misconceptions (key, label_fr, description_fr, strand, primary_node_id, diagnostic_signature)
select m.key, m.label_fr, m.description_fr, m.strand, n.id, m.sig::jsonb
from (values`);
lines.push(
  MISCONCEPTIONS.map(
    (m) =>
      `  (${q(m.key)}, ${q(m.labelFr)}, ${q(m.descriptionFr)}, ${q(m.strand)}, ${q(m.primaryNodeKey)}, ${q(JSON.stringify(m.signature))})`
  ).join(",\n")
);
lines.push(`) as m(key, label_fr, description_fr, strand, node_key, sig)
join competency_nodes n on n.key = m.node_key
on conflict (key) do nothing;`);

lines.push("commit;");
lines.push(
  `\n-- Seeded: ${NODES.length} nodes, ${EDGES.length} edges, ${MISCONCEPTIONS.length} misconceptions.`
);

console.log(lines.join("\n"));
