/**
 * Emit idempotent SQL to seed generated items into competency_items (+ choices).
 * Reads ./generated/past-narration-items.json (produced by generate-slice-items.mts).
 *
 *   npx tsx --tsconfig ./tsconfig.json scripts/seed-generated-items.mts > /tmp/seed-items.sql
 *
 * Re-runnable: deletes prior AI-generated items for the slice's nodes, then
 * re-inserts. Choices cascade with their item. Node/misconception keys are
 * resolved to ids via joins at apply time.
 */
import { readFileSync } from "node:fs";
import { NODES } from "@/lib/content/slices/past-narration";
import type { GeneratedItem } from "@/lib/ai/item-generation/schemas";

const path = process.argv[2] ?? "./generated/past-narration-items.json";
const items = JSON.parse(readFileSync(path, "utf8")) as GeneratedItem[];

const q = (s: string | undefined | null) =>
  s == null ? "null" : `'${s.replace(/'/g, "''")}'`;
const jsonb = (o: unknown) =>
  o == null ? "null" : `'${JSON.stringify(o).replace(/'/g, "''")}'::jsonb`;
const textArr = (a: string[] | undefined) =>
  a && a.length ? `ARRAY[${a.map((x) => q(x)).join(",")}]::text[]` : `'{}'::text[]`;
const num = (n: number | undefined | null) => (n == null ? "null" : String(n));

const sliceKeys = NODES.map((n) => `'${n.key}'`).join(",");
const out: string[] = [
  "-- Generated by scripts/seed-generated-items.mts — do not edit by hand.",
  "begin;",
  `delete from competency_items where generation_type = 'ai'
   and primary_node_id in (select id from competency_nodes where key in (${sliceKeys}));`,
];

for (const it of items) {
  const cols = `(primary_node_id, strand, modality, learner_mode, response_type,
   prompt_fr, instructions_fr, correct_answer, acceptable_answers, validator_type,
   validator_config, cefr_level, difficulty, generation_type, generation_model, review_status)`;
  const sel = `select n.id, ${q(it.strand)}, ${q(it.modality)}, ${q(it.learnerMode)},
   ${q(it.responseType)}, ${q(it.promptFr)}, ${q(it.instructionsFr)}, ${q(it.correctAnswer)},
   ${textArr(it.acceptableAnswers)}, ${q(it.validatorType)}, ${jsonb(it.validatorConfig)},
   ${q(it.cefrLevel)}, ${num(it.difficulty)}, 'ai', 'glm-5.2', 'auto_approved'
   from competency_nodes n where n.key = ${q(it.nodeKey)}`;

  if (it.choices?.length) {
    const choiceRows = it.choices
      .map((c, i) => `(${q(c.text)}, ${c.correct}, ${q(c.misconceptionKey)}, ${i}, ${q(c.feedbackFr)})`)
      .join(",\n      ");
    out.push(`with ni as (
  insert into competency_items ${cols}
  ${sel}
  returning id
)
insert into competency_item_choices (item_id, choice_text, is_correct, misconception_id, position, feedback_fr)
select ni.id, c.choice_text, c.is_correct, m.id, c.position, c.feedback_fr
from ni
cross join (values
      ${choiceRows}
) as c(choice_text, is_correct, mk, position, feedback_fr)
left join misconceptions m on m.key = c.mk;`);
  } else {
    out.push(`insert into competency_items ${cols}\n${sel};`);
  }
}

out.push("commit;");
out.push(`-- Seeded ${items.length} generated items across the slice.`);
console.log(out.join("\n\n"));
