-- Generated by scripts/seed-past-narration.mts — do not edit by hand.
begin;

insert into competency_nodes
  (key, strand, label_fr, description_fr, atomicity_level,
   native_grade_min, native_grade_max, cefr_min, cefr_max,
   requires_reading, requires_writing, requires_listening, requires_speaking,
   generation_type, review_status)
values
  ('classes_de_mots', 'grammaire_syntaxe', 'Les classes de mots', 'Distinguer nom, verbe, adjectif, déterminant.', 2, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('groupe_nominal', 'grammaire_syntaxe', 'Le groupe nominal', 'Repérer le noyau du groupe nominal et ses expansions.', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('notion_verbe', 'grammaire_syntaxe', 'La notion de verbe', 'Identifier le verbe conjugué dans la phrase.', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('fonction_sujet', 'grammaire_syntaxe', 'La fonction sujet', 'Trouver le sujet du verbe (qui fait l''action ?).', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('cod_identification', 'grammaire_syntaxe', 'Le complément d''objet direct (COD)', 'Identifier le COD (le verbe + quoi ? qui ?).', 4, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('coi_identification', 'grammaire_syntaxe', 'Le complément d''objet indirect (COI)', 'Identifier le COI (verbe + à/de qui ? à/de quoi ?).', 4, 7, 8, 'B1', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('cod_coi_distinction', 'grammaire_syntaxe', 'Distinguer COD et COI', 'Choisir entre COD et COI selon la construction du verbe.', 4, 8, 9, 'B1', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('pronom_personnel_cod', 'grammaire_syntaxe', 'Les pronoms COD (le, la, les)', 'Remplacer un COD par le pronom qui convient.', 4, 8, 9, 'B1', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('pronom_relatif_que', 'grammaire_syntaxe', 'Le pronom relatif « que »', '« que » reprend un nom et occupe la fonction COD.', 4, 8, 9, 'B1', 'B2', false, false, false, false, 'human', 'human_approved'),
  ('radical_terminaison', 'conjugaison', 'Radical et terminaison', 'Découper un verbe en radical + terminaison.', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('groupes_verbes', 'conjugaison', 'Les groupes de verbes', 'Classer un verbe (1er, 2e, 3e groupe).', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('present_indicatif', 'conjugaison', 'Le présent de l''indicatif', 'Conjuguer au présent (base des autres temps).', 3, 6, 7, 'A1', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('imparfait_formation', 'conjugaison', 'L''imparfait', 'Former l''imparfait à partir du radical du « nous » au présent.', 3, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('participe_passe_formation', 'conjugaison', 'Le participe passé', 'Former le participe passé (é, i, irréguliers).', 3, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('auxiliaire_choix', 'conjugaison', 'Choisir l''auxiliaire (avoir / être)', 'Décider entre avoir et être au passé composé.', 4, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('passe_compose_avoir', 'conjugaison', 'Le passé composé avec « avoir »', 'Conjuguer au passé composé avec l''auxiliaire avoir.', 4, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('passe_compose_etre', 'conjugaison', 'Le passé composé avec « être »', 'Conjuguer au passé composé avec l''auxiliaire être.', 4, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('pc_vs_imparfait', 'conjugaison', 'Passé composé vs imparfait', 'Choisir le temps selon l''aspect (action vs arrière-plan).', 5, 8, 9, 'B1', 'B2', false, false, false, false, 'human', 'human_approved'),
  ('plus_que_parfait', 'conjugaison', 'Le plus-que-parfait', 'Exprimer l''antériorité dans le récit au passé.', 4, 8, 10, 'B1', 'B2', false, false, false, false, 'human', 'human_approved'),
  ('concordance_temps_recit', 'conjugaison', 'La concordance des temps au passé', 'Articuler PC, imparfait et plus-que-parfait dans un récit.', 5, 9, 11, 'B2', 'B2', false, false, false, false, 'human', 'human_approved'),
  ('accord_genre_nombre', 'orthographe_grammaticale', 'L''accord en genre et en nombre', 'Accorder déterminant, nom, adjectif dans le groupe nominal.', 3, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('accord_sujet_verbe', 'orthographe_grammaticale', 'L''accord sujet-verbe', 'Accorder le verbe avec son sujet.', 3, 7, 8, 'A2', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('accord_pp_etre', 'orthographe_grammaticale', 'Accord du participe passé avec « être »', 'Accorder le participe passé avec le sujet (auxiliaire être).', 5, 8, 9, 'B1', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('accord_pp_avoir_cod', 'orthographe_grammaticale', 'Accord du participe passé avec « avoir »', 'Accorder le participe passé avec le COD placé avant l''auxiliaire avoir.', 5, 9, 11, 'B2', 'B2', false, false, false, false, 'human', 'human_approved'),
  ('terminaison_er_e_ez', 'orthographe_grammaticale', 'Les terminaisons -er / -é / -ez', 'Distinguer infinitif, participe passé et 2e personne du pluriel.', 4, 8, 9, 'B1', 'B1', false, false, false, false, 'human', 'human_approved'),
  ('homophone_a_a', 'orthographe_grammaticale', 'Homophones a / à', 'Distinguer « a » (verbe avoir) et « à » (préposition).', 4, 7, 8, 'A2', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('homophone_et_est', 'orthographe_grammaticale', 'Homophones et / est', 'Distinguer « et » (conjonction) et « est » (verbe être).', 4, 7, 8, 'A2', 'A2', false, false, false, false, 'human', 'human_approved'),
  ('narration_passe', 'expression_ecrite', 'Écrire un récit au passé', 'Rédiger un court récit cohérent au passé.', 5, 8, 10, 'B1', 'B2', false, true, false, false, 'human', 'human_approved'),
  ('recit_oral_passe', 'production_orale', 'Raconter à l''oral au passé', 'Raconter spontanément un événement passé.', 4, 7, 9, 'A2', 'B1', false, false, false, true, 'human', 'human_approved'),
  ('comprehension_recit_passe', 'comprehension_ecrite', 'Comprendre un récit au passé', 'Repérer la chronologie et les temps dans un texte au passé.', 4, 7, 9, 'A2', 'B1', true, false, false, false, 'human', 'human_approved'),
  ('ecoute_recit_passe', 'comprehension_orale', 'Écouter un récit au passé', 'Comprendre un court récit oral au passé.', 4, 7, 9, 'A2', 'B1', false, false, true, false, 'human', 'human_approved')
on conflict (key) do update set
  strand = excluded.strand, label_fr = excluded.label_fr,
  description_fr = excluded.description_fr, atomicity_level = excluded.atomicity_level,
  native_grade_min = excluded.native_grade_min, native_grade_max = excluded.native_grade_max,
  cefr_min = excluded.cefr_min, cefr_max = excluded.cefr_max,
  requires_reading = excluded.requires_reading, requires_writing = excluded.requires_writing,
  requires_listening = excluded.requires_listening, requires_speaking = excluded.requires_speaking,
  review_status = 'human_approved', updated_at = now();

insert into competency_edges (source_node_id, target_node_id, edge_type, generation_type)
select s.id, t.id, e.edge_type, 'human'
from (values
    ('classes_de_mots', 'notion_verbe', 'prerequisite'),
    ('classes_de_mots', 'groupe_nominal', 'prerequisite'),
    ('classes_de_mots', 'fonction_sujet', 'prerequisite'),
    ('notion_verbe', 'fonction_sujet', 'prerequisite'),
    ('groupe_nominal', 'accord_genre_nombre', 'prerequisite'),
    ('fonction_sujet', 'accord_sujet_verbe', 'prerequisite'),
    ('notion_verbe', 'accord_sujet_verbe', 'prerequisite'),
    ('fonction_sujet', 'cod_identification', 'prerequisite'),
    ('cod_identification', 'coi_identification', 'prerequisite'),
    ('cod_identification', 'cod_coi_distinction', 'prerequisite'),
    ('coi_identification', 'cod_coi_distinction', 'prerequisite'),
    ('cod_identification', 'pronom_personnel_cod', 'prerequisite'),
    ('cod_identification', 'pronom_relatif_que', 'prerequisite'),
    ('notion_verbe', 'radical_terminaison', 'prerequisite'),
    ('radical_terminaison', 'groupes_verbes', 'prerequisite'),
    ('groupes_verbes', 'present_indicatif', 'prerequisite'),
    ('present_indicatif', 'imparfait_formation', 'prerequisite'),
    ('present_indicatif', 'participe_passe_formation', 'prerequisite'),
    ('participe_passe_formation', 'auxiliaire_choix', 'prerequisite'),
    ('present_indicatif', 'passe_compose_avoir', 'prerequisite'),
    ('auxiliaire_choix', 'passe_compose_avoir', 'prerequisite'),
    ('auxiliaire_choix', 'passe_compose_etre', 'prerequisite'),
    ('participe_passe_formation', 'passe_compose_avoir', 'prerequisite'),
    ('participe_passe_formation', 'passe_compose_etre', 'prerequisite'),
    ('passe_compose_avoir', 'pc_vs_imparfait', 'prerequisite'),
    ('passe_compose_etre', 'pc_vs_imparfait', 'prerequisite'),
    ('imparfait_formation', 'pc_vs_imparfait', 'prerequisite'),
    ('passe_compose_avoir', 'plus_que_parfait', 'prerequisite'),
    ('imparfait_formation', 'plus_que_parfait', 'prerequisite'),
    ('pc_vs_imparfait', 'concordance_temps_recit', 'prerequisite'),
    ('plus_que_parfait', 'concordance_temps_recit', 'prerequisite'),
    ('passe_compose_etre', 'accord_pp_etre', 'prerequisite'),
    ('accord_genre_nombre', 'accord_pp_etre', 'prerequisite'),
    ('fonction_sujet', 'accord_pp_etre', 'prerequisite'),
    ('passe_compose_avoir', 'accord_pp_avoir_cod', 'prerequisite'),
    ('accord_genre_nombre', 'accord_pp_avoir_cod', 'prerequisite'),
    ('cod_identification', 'accord_pp_avoir_cod', 'prerequisite'),
    ('pronom_personnel_cod', 'accord_pp_avoir_cod', 'prerequisite'),
    ('pronom_relatif_que', 'accord_pp_avoir_cod', 'prerequisite'),
    ('present_indicatif', 'homophone_a_a', 'prerequisite'),
    ('present_indicatif', 'homophone_et_est', 'prerequisite'),
    ('present_indicatif', 'terminaison_er_e_ez', 'prerequisite'),
    ('participe_passe_formation', 'terminaison_er_e_ez', 'prerequisite'),
    ('pc_vs_imparfait', 'narration_passe', 'prerequisite'),
    ('accord_pp_etre', 'narration_passe', 'prerequisite'),
    ('accord_sujet_verbe', 'narration_passe', 'prerequisite'),
    ('passe_compose_avoir', 'recit_oral_passe', 'prerequisite'),
    ('passe_compose_etre', 'recit_oral_passe', 'prerequisite'),
    ('passe_compose_avoir', 'comprehension_recit_passe', 'prerequisite'),
    ('imparfait_formation', 'comprehension_recit_passe', 'prerequisite'),
    ('passe_compose_avoir', 'ecoute_recit_passe', 'prerequisite'),
    ('imparfait_formation', 'ecoute_recit_passe', 'prerequisite')
) as e(src, tgt, edge_type)
join competency_nodes s on s.key = e.src
join competency_nodes t on t.key = e.tgt
on conflict (source_node_id, target_node_id, edge_type) do nothing;

insert into misconceptions (key, label_fr, description_fr, strand, primary_node_id, diagnostic_signature)
select m.key, m.label_fr, m.description_fr, m.strand, n.id, m.sig::jsonb
from (values
  ('present_for_past', 'Présent à la place du passé', 'Emploie le présent là où le passé est attendu (« Hier je vais »).', 'conjugaison', 'passe_compose_avoir', '{"pattern":"present_instead_of_past","example":"Hier, je vais au cinéma."}'),
  ('wrong_auxiliary', 'Mauvais auxiliaire', 'Utilise avoir au lieu d''être (ou l''inverse) au passé composé.', 'conjugaison', 'auxiliaire_choix', '{"pattern":"avoir_for_etre","example":"J''ai allé à l''école."}'),
  ('no_pp_agreement_etre', 'Participe passé non accordé (être)', 'N''accorde pas le participe avec le sujet (auxiliaire être).', 'orthographe_grammaticale', 'accord_pp_etre', '{"pattern":"missing_etre_agreement","example":"Elle est allé au marché."}'),
  ('overgen_pp_agreement_avoir', 'Accord abusif avec avoir', 'Accorde le participe avec un COD placé après l''auxiliaire avoir.', 'orthographe_grammaticale', 'accord_pp_avoir_cod', '{"pattern":"agreement_without_preceding_cod","example":"J''ai mangée une pomme."}'),
  ('pc_imparfait_confusion', 'Confusion passé composé / imparfait', 'Choisit le mauvais temps pour l''aspect visé.', 'conjugaison', 'pc_vs_imparfait', '{"pattern":"aspect_confusion","example":"Quand je suis petit, j''ai joué dehors."}'),
  ('er_e_confusion', 'Confusion -er / -é', 'Confond infinitif et participe passé (« j''ai manger »).', 'orthographe_grammaticale', 'terminaison_er_e_ez', '{"pattern":"infinitive_for_participle","example":"J''ai manger une pomme."}')
) as m(key, label_fr, description_fr, strand, node_key, sig)
join competency_nodes n on n.key = m.node_key
on conflict (key) do nothing;
commit;

-- Seeded: 31 nodes, 52 edges, 6 misconceptions.
