-- Sprint 20: second human-anchored competency slice (present + GN agreement).

do $migration$
begin

with seed(key,label,strand,grade,cefr) as (values
('gn_determinant','Reconnaître le déterminant','grammaire_syntaxe',6,'A1'),('gn_nom_noyau','Trouver le nom noyau','grammaire_syntaxe',6,'A1'),('gn_adjectif','Reconnaître l’adjectif','grammaire_syntaxe',6,'A1'),('genre_nom','Identifier le genre du nom','orthographe_grammaticale',6,'A1'),('nombre_nom','Identifier le nombre du nom','orthographe_grammaticale',6,'A1'),('pluriel_noms_reguliers','Former le pluriel régulier','orthographe_grammaticale',6,'A1'),('pluriel_noms_speciaux','Pluriels en -al, -au, -eu','orthographe_grammaticale',7,'A2'),('accord_determinant_nom','Accorder déterminant et nom','orthographe_grammaticale',6,'A1'),('accord_adjectif_genre','Accorder l’adjectif en genre','orthographe_grammaticale',7,'A2'),('accord_adjectif_nombre','Accorder l’adjectif en nombre','orthographe_grammaticale',7,'A2'),('accord_gn_complet','Accorder le groupe nominal','orthographe_grammaticale',7,'A2'),('sujet_simple','Repérer un sujet simple','grammaire_syntaxe',6,'A1'),('sujet_groupe_nominal','Repérer le groupe sujet','grammaire_syntaxe',7,'A2'),('sujet_inverse','Repérer un sujet inversé','grammaire_syntaxe',8,'B1'),('present_er','Présent des verbes en -er','conjugaison',6,'A1'),('present_ir_2g','Présent des verbes du 2e groupe','conjugaison',7,'A2'),('present_etre_avoir','Présent de être et avoir','conjugaison',6,'A1'),('present_aller_faire','Présent de aller et faire','conjugaison',6,'A2'),('present_3g_frequents','Présent des verbes fréquents du 3e groupe','conjugaison',8,'B1'),('accord_sv_sujet_simple','Accord sujet-verbe au présent','orthographe_grammaticale',7,'A2'),('accord_sv_sujet_eloigne','Accord avec sujet éloigné','orthographe_grammaticale',8,'B1'),('accord_sv_sujets_coord','Accord avec plusieurs sujets','orthographe_grammaticale',8,'B1'),('homophone_son_sont','Homophones son / sont','orthographe_grammaticale',7,'A2'),('homophone_on_ont','Homophones on / ont','orthographe_grammaticale',7,'A2'),('homophone_ce_se','Homophones ce / se','orthographe_grammaticale',8,'B1'),('homophone_ces_ses','Homophones ces / ses','orthographe_grammaticale',8,'B1'),('homophone_ou_ou','Homophones ou / où','orthographe_lexicale',7,'A2'),('chaine_accords_phrase','Contrôler les chaînes d’accords','expression_ecrite',8,'B1'),('revision_present_gn','Réviser un paragraphe au présent','expression_ecrite',8,'B1'),('comprendre_description_present','Comprendre une description au présent','comprehension_ecrite',7,'A2'))
insert into public.competency_nodes(key,strand,label_fr,description_fr,atomicity_level,native_grade_min,native_grade_max,cefr_min,cefr_max,generation_type,review_status)
select key,strand,label,label,4,grade,least(12,grade+2),cefr,cefr,'human','human_approved' from seed
on conflict(key) do update set label_fr=excluded.label_fr,description_fr=excluded.description_fr,review_status='human_approved',updated_at=now();

with seed(source_key,target_key) as (values
('gn_nom_noyau','genre_nom'),('gn_nom_noyau','nombre_nom'),('nombre_nom','pluriel_noms_reguliers'),('pluriel_noms_reguliers','pluriel_noms_speciaux'),('gn_determinant','accord_determinant_nom'),('genre_nom','accord_determinant_nom'),('nombre_nom','accord_determinant_nom'),('gn_adjectif','accord_adjectif_genre'),('genre_nom','accord_adjectif_genre'),('gn_adjectif','accord_adjectif_nombre'),('nombre_nom','accord_adjectif_nombre'),('accord_determinant_nom','accord_gn_complet'),('accord_adjectif_genre','accord_gn_complet'),('accord_adjectif_nombre','accord_gn_complet'),('sujet_simple','sujet_groupe_nominal'),('sujet_groupe_nominal','sujet_inverse'),('present_er','accord_sv_sujet_simple'),('present_ir_2g','accord_sv_sujet_simple'),('present_etre_avoir','homophone_son_sont'),('present_etre_avoir','homophone_on_ont'),('sujet_simple','accord_sv_sujet_simple'),('sujet_groupe_nominal','accord_sv_sujet_eloigne'),('accord_sv_sujet_simple','accord_sv_sujet_eloigne'),('accord_sv_sujet_simple','accord_sv_sujets_coord'),('accord_gn_complet','chaine_accords_phrase'),('accord_sv_sujet_eloigne','chaine_accords_phrase'),('homophone_ce_se','revision_present_gn'),('homophone_ces_ses','revision_present_gn'),('chaine_accords_phrase','revision_present_gn'),('revision_present_gn','comprendre_description_present'))
insert into public.competency_edges(source_node_id,target_node_id,edge_type,strength,generation_type)
select s.id,t.id,'prerequisite',1,'human' from seed join public.competency_nodes s on s.key=source_key join public.competency_nodes t on t.key=target_key
where not exists(select 1 from public.competency_edges e where e.source_node_id=s.id and e.target_node_id=t.id and e.edge_type='prerequisite');

with seed(key,label,node_key,pattern) as (values
('missing_plural_gn','Pluriel incomplet dans le GN','accord_gn_complet','partial_plural'),('verb_agrees_nearest_noun','Accord avec le nom le plus proche','accord_sv_sujet_eloigne','nearest_noun'),('ont_on_confusion','Confusion on / ont','homophone_on_ont','on_ont'))
insert into public.misconceptions(key,label_fr,description_fr,strand,primary_node_id,diagnostic_signature,active)
select seed.key,seed.label,seed.label,n.strand,n.id,jsonb_build_object('pattern',seed.pattern),true from seed join public.competency_nodes n on n.key=seed.node_key
on conflict(key) do update set label_fr=excluded.label_fr,primary_node_id=excluded.primary_node_id,active=true;

end
$migration$;
