-- G15: unified direct/indirect spaced retrieval over graph and package state.
create table public.learning_retrieval_schedules(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,target_type text not null check(target_type in('competency_node','competency_item','lexical_sense','conjugation_form','construction','content_concept')),target_id uuid not null,retrieval_mode text not null check(retrieval_mode in('recognition','production')),source_package_version_id uuid references public.learning_package_versions(id) on delete set null,due_at timestamptz not null,interval_days integer not null default 1 check(interval_days>0),ease_factor numeric not null default 2.5 check(ease_factor between 1.3 and 3),repetitions integer not null default 0 check(repetitions>=0),lapse_count integer not null default 0 check(lapse_count>=0),exposure_count integer not null default 0 check(exposure_count>=0),last_reviewed_at timestamptz,status text not null default 'due' check(status in('due','scheduled','paused','retired')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(student_id,target_type,target_id,retrieval_mode));
create index learning_retrieval_due_idx on public.learning_retrieval_schedules(student_id,due_at) where status in('due','scheduled');
create table public.indirect_retrieval_requests(id uuid primary key default gen_random_uuid(),schedule_id uuid not null references public.learning_retrieval_schedules(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,generation_contract_id uuid,request_payload jsonb not null,status text not null default 'pending' check(status in('pending','reserved','fulfilled','expired','cancelled')),not_before timestamptz not null,expires_at timestamptz,fulfilled_at timestamptz,created_at timestamptz not null default now());
create table public.retrieval_evidence_occurrences(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,schedule_id uuid not null references public.learning_retrieval_schedules(id) on delete restrict,occurrence_key text not null,evidence_channel text not null check(evidence_channel in('direct','indirect')),competency_attempt_id uuid references public.competency_attempts(id) on delete set null,score numeric not null check(score between 0 and 1),result text not null check(result in('forgot','hard','good','easy')),occurred_at timestamptz not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),unique(student_id,schedule_id,occurrence_key));
create table public.package_retrieval_policies(package_version_id uuid primary key references public.learning_package_versions(id) on delete cascade,recognition_enabled boolean not null default true,production_enabled boolean not null default true,initial_recognition_days integer not null default 1 check(initial_recognition_days>0),initial_production_days integer not null default 3 check(initial_production_days>0),minimum_spacing_hours integer not null default 18 check(minimum_spacing_hours>0),maximum_indirect_exposures integer not null default 3 check(maximum_indirect_exposures>0));
create or replace function public.schedule_package_retrieval(p_student_id uuid,p_package_version_id uuid,p_completed_at timestamptz default now()) returns integer language plpgsql security definer set search_path=public as $$declare n integer;begin if auth.role()<>'service_role' and not public.owns_student(p_student_id) then raise exception 'forbidden';end if;insert into public.learning_retrieval_schedules(student_id,target_type,target_id,retrieval_mode,source_package_version_id,due_at,status) select p_student_id,'competency_node',m.node_id,mode.mode,p_package_version_id,p_completed_at+make_interval(days=>case when mode.mode='recognition' then coalesce(policy.initial_recognition_days,1) else coalesce(policy.initial_production_days,3) end),'scheduled' from public.learning_package_node_memberships m left join public.package_retrieval_policies policy on policy.package_version_id=m.package_version_id cross join lateral unnest(case when coalesce(policy.production_enabled,true) then array['recognition','production'] else array['recognition'] end) mode(mode) where m.package_version_id=p_package_version_id and m.membership_type='required' and coalesce(policy.recognition_enabled,true) on conflict(student_id,target_type,target_id,retrieval_mode) do update set due_at=least(learning_retrieval_schedules.due_at,excluded.due_at),source_package_version_id=excluded.source_package_version_id,status='scheduled',updated_at=now();get diagnostics n=row_count;return n;end$$;
revoke all on function public.schedule_package_retrieval(uuid,uuid,timestamptz) from public;grant execute on function public.schedule_package_retrieval(uuid,uuid,timestamptz) to authenticated,service_role;
alter table public.learning_retrieval_schedules enable row level security;alter table public.indirect_retrieval_requests enable row level security;alter table public.retrieval_evidence_occurrences enable row level security;alter table public.package_retrieval_policies enable row level security;
create policy learning_retrieval_read on public.learning_retrieval_schedules for select using(public.can_view_student(student_id));create policy learning_retrieval_student_write on public.learning_retrieval_schedules for all using(public.owns_student(student_id)) with check(public.owns_student(student_id));create policy indirect_retrieval_read on public.indirect_retrieval_requests for select using(public.can_view_student(student_id));create policy retrieval_evidence_read on public.retrieval_evidence_occurrences for select using(public.can_view_student(student_id));create policy package_retrieval_policy_read on public.package_retrieval_policies for select using(true);
grant select on public.learning_retrieval_schedules,public.indirect_retrieval_requests,public.retrieval_evidence_occurrences,public.package_retrieval_policies to authenticated;
comment on table public.retrieval_evidence_occurrences is 'Shared direct/indirect evidence ledger; occurrence uniqueness prevents double counting.';
