-- G16: resumable, auditable, mixed-purpose embedded quizzes.
alter table public.competency_items add column quiz_purposes text[] not null default '{}' check(quiz_purposes<@array['retrieval','course_evidence','calibration']::text[]),add column prompt_family text,add column evidence_weight numeric not null default 1 check(evidence_weight between 0 and 1);
create table public.quiz_policies(id uuid primary key default gen_random_uuid(),policy_key text unique not null,version integer not null check(version>0),maximum_items integer not null check(maximum_items between 1 and 20),minimum_minutes_between integer not null check(minimum_minutes_between>0),maximum_quizzes_per_day integer not null check(maximum_quizzes_per_day between 1 and 10),lesson_interval_steps integer not null check(lesson_interval_steps>0),minimum_prompt_families_for_mastery integer not null default 2 check(minimum_prompt_families_for_mastery>1),active boolean not null default false,created_at timestamptz not null default now(),unique(policy_key,version));
insert into public.quiz_policies(policy_key,version,maximum_items,minimum_minutes_between,maximum_quizzes_per_day,lesson_interval_steps,active) values('balanced',1,5,45,3,3,true);
create table public.quiz_sessions(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,package_version_id uuid references public.learning_package_versions(id) on delete set null,policy_id uuid not null references public.quiz_policies(id) on delete restrict,placement text not null check(placement in('lesson_interval','module_boundary','ongoing','remediation_reassessment')),purposes text[] not null check(cardinality(purposes)>0 and purposes<@array['retrieval','course_evidence','calibration']::text[]),status text not null default 'running' check(status in('running','completed','abandoned')),current_position integer not null default 0,assembly_snapshot jsonb not null,audit_context jsonb not null default '{}'::jsonb,started_at timestamptz not null default now(),updated_at timestamptz not null default now(),completed_at timestamptz);
create table public.quiz_session_items(quiz_session_id uuid not null references public.quiz_sessions(id) on delete cascade,item_id uuid not null references public.competency_items(id) on delete restrict,position integer not null,purposes text[] not null,primary_node_id uuid not null references public.competency_nodes(id) on delete restrict,misconception_ids uuid[] not null default '{}',modality text not null,prompt_family text not null,primary key(quiz_session_id,item_id),unique(quiz_session_id,position));
create table public.quiz_responses(id uuid primary key default gen_random_uuid(),quiz_session_id uuid not null references public.quiz_sessions(id) on delete cascade,item_id uuid not null references public.competency_items(id) on delete restrict,student_id uuid not null references public.students(id) on delete cascade,score numeric not null check(score between 0 and 1),is_correct boolean not null,selected_misconception_id uuid references public.misconceptions(id) on delete set null,evidence_occurrence_key text not null,answered_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb,unique(student_id,evidence_occurrence_key));
create table public.quiz_remediation_triggers(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,source_quiz_session_id uuid not null references public.quiz_sessions(id) on delete restrict,node_id uuid not null references public.competency_nodes(id) on delete restrict,remediation_package_version_id uuid references public.learning_package_versions(id) on delete restrict,status text not null default 'pending' check(status in('pending','inserted','evidence_ready','reassessed','resolved')),trigger_snapshot jsonb not null,reassess_after_evidence integer not null default 2 check(reassess_after_evidence>0),created_at timestamptz not null default now());
alter table public.quiz_policies enable row level security;alter table public.quiz_sessions enable row level security;alter table public.quiz_session_items enable row level security;alter table public.quiz_responses enable row level security;alter table public.quiz_remediation_triggers enable row level security;
create policy quiz_policy_read on public.quiz_policies for select using(true);create policy quiz_session_read on public.quiz_sessions for select using(public.can_view_student(student_id));create policy quiz_session_write on public.quiz_sessions for all using(public.owns_student(student_id)) with check(public.owns_student(student_id));create policy quiz_item_read on public.quiz_session_items for select using(exists(select 1 from public.quiz_sessions q where q.id=quiz_session_id and public.can_view_student(q.student_id)));create policy quiz_response_read on public.quiz_responses for select using(public.can_view_student(student_id));create policy quiz_response_write on public.quiz_responses for insert with check(public.owns_student(student_id));create policy quiz_remediation_read on public.quiz_remediation_triggers for select using(public.can_view_student(student_id));
grant select on public.quiz_policies,public.quiz_sessions,public.quiz_session_items,public.quiz_responses,public.quiz_remediation_triggers to authenticated;
