-- G24: sole auditable decision point after passage, question, and risk QA.
create table public.qa_decision_policy_versions(id uuid primary key default gen_random_uuid(),version text unique not null,policy jsonb not null,status text not null check(status in('draft','active','retired')),activated_at timestamptz,created_at timestamptz not null default now(),check((status='active')=(activated_at is not null)));
insert into public.qa_decision_policy_versions(version,policy,status,activated_at) values('1.0.0','{"maximum_repairs":1,"maximum_generation_attempts":3,"maximum_cost_usd":0.25,"minimum_eligible_score":0.72,"hard_failure_policy":"override"}','active',now());
create table public.candidate_decisions(id uuid primary key default gen_random_uuid(),candidate_id uuid not null references public.contract_generation_candidates(id) on delete restrict,policy_version_id uuid not null references public.qa_decision_policy_versions(id) on delete restrict,passage_qa_result_id uuid not null references public.passage_qa_results(id) on delete restrict,risk_result_id uuid not null references public.candidate_risk_results(id) on delete restrict,question_qa_result_ids uuid[] not null,decision text not null check(decision in('eligible','not_selected','repair_once','regenerate','quarantine','escalate')),quality_score numeric not null check(quality_score between 0 and 1),hard_failures jsonb not null,reasons jsonb not null,evidence_snapshot jsonb not null,cost_snapshot jsonb not null,created_at timestamptz not null default now(),unique(candidate_id,policy_version_id));
create table public.candidate_repairs(id uuid primary key default gen_random_uuid(),original_candidate_id uuid not null references public.contract_generation_candidates(id) on delete restrict,repaired_candidate_id uuid not null unique references public.contract_generation_candidates(id) on delete restrict,repair_number integer not null check(repair_number=1),original_snapshot jsonb not null,repaired_snapshot jsonb not null,diff jsonb not null,created_at timestamptz not null default now(),unique(original_candidate_id,repair_number));
create table public.candidate_quarantines(id uuid primary key default gen_random_uuid(),candidate_id uuid not null unique references public.contract_generation_candidates(id) on delete restrict,decision_id uuid not null references public.candidate_decisions(id) on delete restrict,reasons jsonb not null,evidence_snapshot jsonb not null,created_at timestamptz not null default now(),released_at timestamptz,released_by uuid references public.profiles(id) on delete set null);
create table public.candidate_escalations(id uuid primary key default gen_random_uuid(),candidate_id uuid not null references public.contract_generation_candidates(id) on delete restrict,decision_id uuid not null references public.candidate_decisions(id) on delete restrict,reason_keys text[] not null,status text not null default 'open' check(status in('open','resolved','rejected')),created_at timestamptz not null default now(),resolved_at timestamptz);
create table public.candidate_set_decisions(id uuid primary key default gen_random_uuid(),generation_run_id uuid not null unique references public.contract_generation_runs(id) on delete restrict,policy_version_id uuid not null references public.qa_decision_policy_versions(id) on delete restrict,decision text not null check(decision in('accept_provisionally','repair_once','regenerate','quarantine','escalate')),selected_candidate_id uuid references public.contract_generation_candidates(id) on delete restrict,ranking jsonb not null,candidate_decision_ids uuid[] not null,policy_snapshot jsonb not null,created_at timestamptz not null default now(),check((decision='accept_provisionally')=(selected_candidate_id is not null)));
alter table public.qa_decision_policy_versions enable row level security;alter table public.candidate_decisions enable row level security;alter table public.candidate_repairs enable row level security;alter table public.candidate_quarantines enable row level security;alter table public.candidate_escalations enable row level security;alter table public.candidate_set_decisions enable row level security;
create policy decision_policy_read on public.qa_decision_policy_versions for select using(status='active' or public.is_platform_admin());create policy candidate_decisions_staff_read on public.candidate_decisions for select using(public.is_staff());create policy candidate_repairs_staff_read on public.candidate_repairs for select using(public.is_staff());create policy candidate_quarantines_staff_read on public.candidate_quarantines for select using(public.is_staff());create policy candidate_escalations_staff_read on public.candidate_escalations for select using(public.is_staff());create policy candidate_set_decisions_staff_read on public.candidate_set_decisions for select using(public.is_staff());grant select on public.qa_decision_policy_versions,public.candidate_decisions,public.candidate_repairs,public.candidate_quarantines,public.candidate_escalations,public.candidate_set_decisions to authenticated;
