-- G27: sparse calibration, exception, audit campaign, and benchmark review.
create table public.sparse_review_policies(id uuid primary key default gen_random_uuid(),policy_key text not null,version integer not null check(version>0),low_risk_sample_percent integer not null check(low_risk_sample_percent between 0 and 100),medium_risk_sample_percent integer not null check(medium_risk_sample_percent between 0 and 100),always_review_high_risk boolean not null default true,active boolean not null default false,created_at timestamptz not null default now(),unique(policy_key,version));
insert into public.sparse_review_policies(policy_key,version,low_risk_sample_percent,medium_risk_sample_percent,active) values('production_calibration',1,5,20,true);
create table public.pipeline_audit_campaigns(id uuid primary key default gen_random_uuid(),campaign_key text unique not null,pipeline_version text not null,reason text not null,sample_percent integer not null check(sample_percent between 1 and 100),status text not null check(status in('draft','active','completed','cancelled')),started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table public.sparse_review_cases(id uuid primary key default gen_random_uuid(),candidate_id uuid references public.contract_generation_candidates(id) on delete restrict,serving_version_id uuid references public.generated_content_serving_versions(id) on delete restrict,policy_id uuid not null references public.sparse_review_policies(id) on delete restrict,audit_campaign_id uuid references public.pipeline_audit_campaigns(id) on delete set null,primary_reason text not null check(primary_reason in('risk_escalation','empirical_anomaly','qa_disagreement','benchmark_failure','pipeline_audit','random_sample','explicit_request')),reason_keys text[] not null,selection_explanation text not null,queue_key text not null,status text not null default 'open' check(status in('open','assigned','resolved','rejected','retired')),pipeline_version text not null,qa_version_ids uuid[] not null default '{}',created_at timestamptz not null default now(),resolved_at timestamptz,check(candidate_id is not null or serving_version_id is not null));
create table public.sparse_review_evidence(id uuid primary key default gen_random_uuid(),review_case_id uuid not null references public.sparse_review_cases(id) on delete cascade,evidence_type text not null check(evidence_type in('automated_qa','risk','usage_metric','benchmark','pipeline_diff','contract')),automated_claims jsonb not null,observed_evidence jsonb not null,evidence_status text not null,source_version text not null,created_at timestamptz not null default now());
create table public.sparse_review_actions(id uuid primary key default gen_random_uuid(),review_case_id uuid not null references public.sparse_review_cases(id) on delete restrict,reviewer_profile_id uuid not null references public.profiles(id) on delete restrict,action text not null check(action in('confirm','override_accept','override_reject','retire','request_repair')),reason text not null,evidence_snapshot jsonb not null,automated_decision_snapshot jsonb not null,qa_calibration_feedback jsonb not null,created_at timestamptz not null default now());
create or replace function public.prevent_sparse_review_action_mutation()returns trigger language plpgsql as $$begin raise exception 'review_action_is_immutable';end$$;create trigger immutable_sparse_review_action before update or delete on public.sparse_review_actions for each row execute function public.prevent_sparse_review_action_mutation();
alter table public.sparse_review_policies enable row level security;alter table public.pipeline_audit_campaigns enable row level security;alter table public.sparse_review_cases enable row level security;alter table public.sparse_review_evidence enable row level security;alter table public.sparse_review_actions enable row level security;
create policy sparse_policy_staff_read on public.sparse_review_policies for select using(public.is_staff());create policy audit_campaign_staff_read on public.pipeline_audit_campaigns for select using(public.is_staff());create policy sparse_cases_reviewer_read on public.sparse_review_cases for select using(public.is_staff() or public.is_active_content_reviewer());create policy sparse_evidence_reviewer_read on public.sparse_review_evidence for select using(public.is_staff() or public.is_active_content_reviewer());create policy sparse_actions_reviewer_read on public.sparse_review_actions for select using(public.is_staff() or public.is_active_content_reviewer());grant select on public.sparse_review_policies,public.pipeline_audit_campaigns,public.sparse_review_cases,public.sparse_review_evidence,public.sparse_review_actions to authenticated;
