import {chromium} from "@playwright/test";
import {strict as assert} from "node:assert";
const browser=await chromium.launch({channel:"chrome",headless:true});
try{
 const page=await browser.newPage({viewport:{width:1200,height:900}});const errors:string[]=[];
 page.on("pageerror",error=>errors.push(error.message));
 await page.goto("http://127.0.0.1:4179");
 await page.getByRole("button",{name:"Commencer",exact:true}).click();
 await page.getByLabel("Ta réponse",{exact:true}).fill("finissons");
 await page.evaluate(()=>{Object.defineProperty(document,"visibilityState",{configurable:true,value:"hidden"});document.dispatchEvent(new Event("visibilitychange"));});
 await page.getByRole("button",{name:"Reprendre",exact:true}).waitFor();
 await page.evaluate(()=>Object.defineProperty(document,"visibilityState",{configurable:true,value:"visible"}));
 await page.getByRole("button",{name:"Reprendre",exact:true}).click();
 assert.equal(await page.getByLabel("Ta réponse",{exact:true}).inputValue(),"finissons");
 await page.getByRole("button",{name:"Valider",exact:true}).click();
 await page.getByRole("alert").filter({hasText:"conservée"}).waitFor();
 assert.equal(await page.getByLabel("Ta réponse",{exact:true}).inputValue(),"finissons");
 await page.getByRole("button",{name:"Valider",exact:true}).click();
 await page.getByRole("heading",{name:"Tes acquis et tes prochaines étapes"}).waitFor();
 // The first result follows the diagnostic, before any independent learning check.
 await page.getByText("Conjugaison",{exact:true}).click();
 await page.getByText(/À confirmer · 1 réponse/).waitFor();
 await page.screenshot({path:"/tmp/granular-ui-results-desktop.png",fullPage:true});
 await page.reload();await page.getByRole("heading",{name:"Tes acquis et tes prochaines étapes"}).waitFor();
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.screenshot({path:"/tmp/granular-ui-results-mobile.png",fullPage:true});
 await page.getByRole("button",{name:"Vérifier ce point",exact:true}).click();
 await page.getByRole("heading",{name:"Vérifions ce que tu sais",exact:true}).waitFor();
 assert.equal(await page.getByLabel("Ta réponse",{exact:true}).inputValue(),"");
 await page.reload();
 await page.getByRole("heading",{name:"Vérifions ce que tu sais",exact:true}).waitFor();
 await page.getByLabel("Ta réponse",{exact:true}).fill("finissent");
 await page.getByRole("button",{name:"Valider",exact:true}).click();
 await page.getByRole("alert").filter({hasText:"conservée"}).waitFor();
 assert.equal(await page.getByLabel("Ta réponse",{exact:true}).inputValue(),"finissent");
 await page.getByRole("button",{name:"Valider",exact:true}).click();
 await page.getByRole("alert").filter({hasText:"connexion"}).waitFor();
 assert.equal(await page.getByLabel("Ta réponse",{exact:true}).inputValue(),"finissent");
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
 await page.screenshot({path:"/tmp/granular-learning-check-mobile.png",fullPage:true});
 await page.getByRole("button",{name:"Valider",exact:true}).click();
 await page.getByRole("heading",{name:"Tes acquis et tes prochaines étapes"}).waitFor();
 await page.getByText("Conjugaison",{exact:true}).click();
 await page.getByText(/À confirmer · 2 réponse/).waitFor();
 await page.getByRole("status").filter({hasText:"ton bilan a été mis à jour"}).waitFor();
 await page.reload();
 await page.getByText("Conjugaison",{exact:true}).click();
 await page.getByText(/À confirmer · 2 réponse/).waitFor();
 assert.deepEqual(errors,[]);
 console.log("Browser fixture passed: diagnostic pause/resume and results; learning check start, reload, conflict/network retries, saved evidence count, mobile width, no page errors. Backend actions are fixture implementations.");
}finally{await browser.close();}
