import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/page";
import { requireRole } from "@/lib/auth";
import { getAdminReviewReport, getAdminReviewVersions, getReviewNotifications } from "@/lib/db/reviews";
import { difficultyBandLabel } from "@/lib/scoring/band";
import { createClient } from "@/lib/supabase/server";
import { ReviewAdminNav } from "./review-nav";

export default async function AdminReviewsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  await requireRole(["platform_admin"]);
  const db=await createClient();
  const [versions, notifications, report, {data:benchmarks}, params] = await Promise.all([
    getAdminReviewVersions(db), getReviewNotifications(db), getAdminReviewReport(db),
    db.from("content_benchmarks").select("review_version_id").eq("locked",true), searchParams,
  ]);
  const value=(key:string)=>typeof params[key]==="string"?params[key] as string:"";
  const status=value("status"),agreement=value("agreement"),topic=value("topic"),band=value("band"),competency=value("competency"),reviewer=value("reviewer"),from=value("from"),to=value("to"),benchmark=value("benchmark");
  const lockedIds=new Set((benchmarks??[]).map(row=>row.review_version_id as string));
  const visible=versions.filter(item=>(!status||item.workflowStatus===status)&&(!agreement||item.agreement===agreement)&&(!topic||item.candidate.input.topic===topic)&&(!band||item.candidate.input.targetReadingBand===band)&&(!competency||item.candidate.input.targetSkills.includes(competency))&&(!reviewer||item.assignments.some(a=>a.reviewerProfileId===reviewer))&&(!from||new Date(item.createdAt)>=new Date(from))&&(!to||new Date(item.createdAt)<=new Date(`${to}T23:59:59`))&&(!benchmark||(benchmark==="locked"?lockedIds.has(item.id):!lockedIds.has(item.id))));
  const count=(predicate:(item:(typeof versions)[number])=>boolean)=>versions.filter(predicate).length;
  const stats=[["Total",versions.length],["Sans attribution",count(v=>v.assignments.length===0)],["En cours",count(v=>v.workflowStatus==="in_review")],["Évalués",count(v=>v.workflowStatus==="review_complete")],["Unanimes",count(v=>v.agreement==="unanimous")],["Désaccords",count(v=>["mixed","high_disagreement"].includes(v.agreement??""))],["À réviser",count(v=>v.workflowStatus==="needs_revision")],["Rejetés",count(v=>v.workflowStatus==="rejected")],["Approuvés",count(v=>["approved","published"].includes(v.workflowStatus))],["Références",lockedIds.size]];
  const submitted=report.filter(row=>row.assignmentStatus==="submitted");
  const averageSeconds=submitted.flatMap(row=>row.durationSeconds==null?[]:[row.durationSeconds]);
  const issueCounts=new Map<string,number>();submitted.flatMap(row=>row.issueTags).forEach(tag=>issueCounts.set(tag,(issueCounts.get(tag)??0)+1));
  const topIssues=[...issueCounts].sort((a,b)=>b[1]-a[1]).slice(0,5);
  const scoreValues=submitted.flatMap(row=>row.scores);
  const completedVersions=versions.filter(v=>v.agreement);
  const summary=[
    ["Temps moyen",averageSeconds.length?`${Math.round(averageSeconds.reduce((a,b)=>a+b,0)/averageSeconds.length/60)} min`:"—"],
    ["Taux de complétion",report.length?`${Math.round(submitted.length/report.length*100)} %`:"0 %"],
    ["Taux d’accord",completedVersions.length?`${Math.round(completedVersions.filter(v=>["unanimous","strong_agreement"].includes(v.agreement??"")).length/completedVersions.length*100)} %`:"—"],
    ["Taux d’approbation",completedVersions.length?`${Math.round(versions.filter(v=>["approved","published"].includes(v.workflowStatus)).length/completedVersions.length*100)} %`:"—"],
    ["Score moyen",scoreValues.length?(scoreValues.reduce((a,b)=>a+b,0)/scoreValues.length).toFixed(2):"—"],
  ];
  const unique=(values:string[])=>[...new Set(values)].sort();
  const reviewers=unique(report.map(row=>`${row.reviewerProfileId}|${row.reviewerName}`)).map(item=>{const [id,...name]=item.split("|");return{id,name:name.join("|")};});

  return <>
    <PageHeader eyebrow="Qualité éditoriale" title="Évaluations humaines" description="Suivez les attributions, les validations indépendantes et les décisions éditoriales." />
    <ReviewAdminNav />
    {notifications.length>0&&<aside aria-label="Notifications administratives" className="mb-8 grid gap-3 sm:grid-cols-2">{notifications.map((notification,index)=><div key={notification.id} className={`rounded-md border px-4 py-3 ${index%2?"border-secondary/30 bg-secondary/10":"border-primary/30 bg-accent"}`}><p className="font-display text-xs font-semibold uppercase tracking-[.08em]">{notification.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{notification.body}</p></div>)}</aside>}
    <section aria-label="Indicateurs" className="grid grid-cols-2 border-y border-border sm:grid-cols-5">{stats.map(([label,stat],index)=><div key={label} className="border-b border-r border-border px-4 py-5 last:border-r-0 sm:border-b-0"><p className={`font-display text-3xl font-bold tabular-nums ${index===3?"text-success":index===5?"text-secondary":""}`}>{stat}</p><p className="mt-1 font-mono text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p></div>)}</section>
    <form className="my-8 grid gap-3 rounded-lg border border-border bg-card p-4 sm:grid-cols-3 lg:grid-cols-5"><select name="status" defaultValue={status} aria-label="Statut" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les statuts</option>{unique(versions.map(v=>v.workflowStatus)).map(option=><option key={option}>{option}</option>)}</select><select name="agreement" defaultValue={agreement} aria-label="Accord" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les accords</option>{["unanimous","strong_agreement","mixed","high_disagreement"].map(option=><option key={option}>{option}</option>)}</select><select name="reviewer" defaultValue={reviewer} aria-label="Évaluateur" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les évaluateurs</option>{reviewers.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><select name="topic" defaultValue={topic} aria-label="Sujet" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les sujets</option>{unique(versions.map(v=>v.candidate.input.topic)).map(option=><option key={option}>{option}</option>)}</select><select name="band" defaultValue={band} aria-label="Niveau" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les niveaux</option>{unique(versions.map(v=>v.candidate.input.targetReadingBand)).map(option=><option key={option} value={option}>{difficultyBandLabel(option)}</option>)}</select><select name="competency" defaultValue={competency} aria-label="Compétence" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Toutes les compétences</option>{unique(versions.flatMap(v=>v.candidate.input.targetSkills)).map(option=><option key={option}>{option}</option>)}</select><select name="benchmark" defaultValue={benchmark} aria-label="Référence" className="h-11 rounded-md border border-input bg-background px-3 text-sm"><option value="">Tous les états référence</option><option value="locked">Verrouillée</option><option value="unlocked">Non verrouillée</option></select><label className="text-xs text-muted-foreground">Du<input type="date" name="from" defaultValue={from} className="mt-1 h-11 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground"/></label><label className="text-xs text-muted-foreground">Au<input type="date" name="to" defaultValue={to} className="mt-1 h-11 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground"/></label><Button type="submit" className="self-end">Appliquer les filtres</Button></form>
    <div className="overflow-x-auto rounded-lg border border-border bg-card"><table className="w-full min-w-[780px] text-left text-sm"><thead className="border-b border-border bg-muted/50 font-mono text-[10px] uppercase tracking-wider text-muted-foreground"><tr><th className="px-5 py-4">Passage</th><th className="px-3 py-4">Niveau</th><th className="px-3 py-4">Progression</th><th className="px-3 py-4">Accord</th><th className="px-3 py-4">Score</th><th className="py-4 pl-3 pr-4"><span className="sr-only">Action</span></th></tr></thead><tbody className="divide-y divide-border">{visible.map(item=>{const done=item.assignments.filter(a=>a.status==="submitted").length;return <tr key={item.id} className="transition-colors hover:bg-muted/30"><td className="px-5 py-4"><p className="font-medium">{item.candidate.generated.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.candidate.input.topic} · v{item.versionNumber}</p></td><td className="px-3 py-4">{difficultyBandLabel(item.candidate.input.targetReadingBand)}</td><td className="px-3 py-4"><Badge variant={done===item.requiredReviewers?"success":"outline"}>{done}/{item.requiredReviewers}</Badge><p className="mt-1 text-xs text-muted-foreground">{item.workflowStatus}</p></td><td className="px-3 py-4">{item.agreement??"—"}</td><td className="px-3 py-4 font-display font-semibold tabular-nums">{item.averageScore?.toFixed(2)??"—"}</td><td className="py-4 pl-3 pr-4"><Button asChild size="sm" variant="ghost"><Link href={`/admin/reviews/${item.id}`}>Ouvrir<ArrowRight /></Link></Button></td></tr>})}</tbody></table></div>
    <section className="mt-10"><h2 className="text-lg font-semibold">Rapport synthétique</h2><div className="mt-4 grid grid-cols-2 gap-5 border-y border-border py-5 sm:grid-cols-5">{summary.map(([label,stat])=><div key={label}><p className="text-xl font-semibold">{stat}</p><p className="text-xs text-muted-foreground">{label}</p></div>)}</div><div className="mt-5 grid gap-6 sm:grid-cols-3"><div><h3 className="text-sm font-medium">Problèmes fréquents</h3><ol className="mt-2 space-y-1 text-sm text-muted-foreground">{topIssues.length?topIssues.map(([tag,total])=><li key={tag}>{tag} · {total}</li>):<li>Aucun signalement</li>}</ol></div><div><h3 className="text-sm font-medium">Résultats par niveau</h3>{unique(submitted.map(row=>row.band)).map(level=><p key={level} className="mt-1 text-sm text-muted-foreground">{difficultyBandLabel(level)} · {submitted.filter(row=>row.band===level).length} avis</p>)}</div><div><h3 className="text-sm font-medium">Résultats par sujet</h3>{unique(submitted.map(row=>row.topic)).slice(0,8).map(subject=><p key={subject} className="mt-1 text-sm text-muted-foreground">{subject} · {submitted.filter(row=>row.topic===subject).length} avis</p>)}</div></div></section>
  </>;
}
